dns/dnsperf/Dockerfile, dns/dnsperf/Makefile, dns/dnsperf/README.md, dns/dnsperf/queryfile-local-services, dns/dnsperf/runjob.sh
Moving dnsperf changes from contrib repository here.
https://github.com/kubernetes/contrib/pull/1189
=> DNSPerf container build and Job yaml

network/benchmarks/netperf/.gitignore, network/benchmarks/netperf/Dockerfile, network/benchmarks/netperf/Makefile, network/benchmarks/netperf/README.md, network/benchmarks/netperf/launch.go, network/benchmarks/netperf/nptest/Makefile, network/benchmarks/netperf/nptest/nptest.go, network/benchmarks/netperf/plotperf/Makefile
Moved changes from PR https://github.com/kubernetes/kubernetes/pull/28136 here.
=> Network Performance Benchmarks

CONTRIBUTING.md, LICENSE, OWNERS, README.md, RELEASE.md, code-of-conduct.md
=> First version of boilerplate files

network/benchmarks/netperf/launch.go, network/benchmarks/netperf/nptest/nptest.go, verify/boilerplate/boilerplate.go.txt, verify/boilerplate/boilerplate.py.txt, verify/boilerplate/boilerplate.sh.txt, verify/verify-boilerplate.py, verify/verify-flags-underscore.py, verify/verify-gofmt.sh, verify/verify-golint.sh
Copied scripts from `test-infra` and `contrib`
cc @timothysc @apelisse
=> Add basic verify scripts

.travis.yml, network/benchmarks/netperf/launch.go
=> Add travis config to perf-tests

dns/cluster/dnsperf.yaml
Looks like this was somehow missed
=> Fix image path

clusterloader/config/logger.yaml, clusterloader/content/pod-logger.json, clusterloader/doc/README_logging.md
=> base logger config and template

clusterloader/cluster_loader.go, clusterloader/e2e_test.go
@sjug 
Seems to fix the problem.
=> Fix clusterloader compile error

benchmark/Dockerfile, benchmark/Makefile
First step towards adding a CI job for the tool.
cc @kubernetes/sig-scalability-misc @wojtek-t @gmarek
=> Adding dockerization for benchmark tool

clusterloader/run-e2e.sh
=> Fix run-e2e.sh clusterloader script

clusterloader/README.md, clusterloader/cluster_loader.go, clusterloader/e2e/e2e_test.go, clusterloader/framework/context.go, clusterloader/run-e2e.sh
=> Fix run-e2e.sh script in clusterloader

clusterloader/framework/util.go
@sjug FYI: I'm fixing it for the second time.
=> Fix perf-tests

benchmark/cmd/benchmark.go
Fixes https://github.com/kubernetes/test-infra/issues/5053
/cc @gmarek
=> Fix gce job-name for benchmark tool

dns/image/Makefile
Context: https://github.com/kubernetes/kubernetes/pull/57824
xref kubernetes/release#281
=> Pushes go to staging-k8s.gcr.io

benchmark/cmd/benchmark.go
=> Increase benchmark comparison threshold for more variance

benchmark/README.md
=> Update benchmark tool's design doc link

network/benchmarks/netperf/launch.go
For this issue https://github.com/kubernetes/perf-tests/issues/21 . The docker image published by  @jcsirot [https://github.com/jcsirot]
works fine. Made changes in code to adopt this image. Thanks at @jcsirot
=> Updating Docker Image

slo-monitor/Makefile
Also remove usage of "sudo" for building.
=> Makefile: separate building from pushing

slo-monitor/src/main/slo-monitor.go
=> fix misspelling of Kubernetes

.travis.yml, verify/verify-gofmt.sh
=> Updating go version.

perfdash/Makefile, perfdash/deployment.yaml, perfdash/www/script.js
Refresh shouldn't change selected test name (if possible).
=> Keeping selected test name

perfdash/Makefile, perfdash/deployment.yaml, perfdash/www/script.js
Workaround for undefined values.
Allows test phase plots to be displayed.
=> undefined values workaround

perfdash/www/Chart.js
=> Typo fix: seperate->separate

perfdash/README.md
Line 19: kuberntes->kubernetes
=> [perfdash/README.md] Typo fix kuberntes->kubernetes

perfdash/Makefile, perfdash/deployment.yaml, perfdash/www/script.js
This change will prevent from changing selected label values due to data refresh.
Labels will be reset only if needed.
=> Perfdash label refresh

perfdash/perfdash.go
Line 70: formating->formatting
=> Typo fix in returned message: formating->formatting

perfdash/Makefile, perfdash/config.go, perfdash/deployment.yaml, perfdash/parser.go
=> Adding scheduler throughput and scheduling latency to perfdash

perfdash/Makefile, perfdash/deployment.yaml, perfdash/parser.go
Updating scheduler latency metrics due to changes in kubernetes repository:
https://github.com/kubernetes/kubernetes/pull/65318
=> Scheduler latency update

perfdash/Makefile, perfdash/deployment.yaml, perfdash/downloader.go, perfdash/google-gcs-downloader.go, perfdash/perfdash.go, perfdash/www/index.html, perfdash/www/script.js
Splitting test name combo box into two separate ones - one for job name and other for test name.
ref #137
=> Perfdash: splitting test name selector

perfdash/Makefile, perfdash/deployment.yaml, perfdash/www/script.js
Re-enables units being displayed on y-axis on every chart.
ref #137
=> Perfdash units fix

clusterloader2/api/types.go
New version for cluster loader.
=> Cluster loader - API structures

network/benchmarks/netperf/launch.go
- create a new output directory per job
- create an output file with timestamp in this directory per iteration
Fixes #130
=> Create output report per iteration

network/benchmarks/netperf/nptest/nptest.go
Run iperf3 in verbose mode, parse output and report CPU usage for
sender and receiver in orchestrator log output for each job.
Fixes #127
=> Add reporting of CPU usage for iperf to orchestrator

clusterloader2/api/types.go, clusterloader2/config/codec.go
Adding function that can unmarshal json or yaml file into go structure
=> ClusterLoader - File unmarshaling

clusterloader2/api/types.go
=> ClusterLoader - removing ObjectType

perfdash/Makefile, perfdash/deployment.yaml, perfdash/www/index.html
=> Perfdash: adding x-axis label

clusterloader2/framework/client/objects.go, clusterloader2/framework/config/clientconfig.go, clusterloader2/framework/framework.go
Adding cluster managing framework.
=> ClusterLoader - Adding framework

clusterloader2/pkg/state/state.go
Adding structure that represents state of a running test.
=> ClusterLoader - Adding test state

perfdash/Makefile, perfdash/deployment.yaml, perfdash/www/script.js
Graph animation will be removed, due to the performance issues.
=> Perfdash: desabling animation

clusterloader2/pkg/test/interface.go, clusterloader2/pkg/test/test.go
This PR is an alternative to PR #157
=> ClusterLoader - adding test executor interface

clusterloader2/pkg/test/simplecontext.go, clusterloader2/pkg/test/simpletestexecutor.go, clusterloader2/pkg/test/test.go
Implementation for interfaces provided by `test/`.
Test execution logic will be implemented in the next PR.
=> ClusterLoader - simple test implementation

perfdash/Makefile, perfdash/config.go, perfdash/deployment.yaml, perfdash/downloader.go, perfdash/google-gcs-downloader.go, perfdash/perfdash.go, perfdash/www/index.html, perfdash/www/script.js
Adding category level selector.
=> Perfdash: category level

perfdash/Makefile, perfdash/deployment.yaml, perfdash/www/Chart.js
To avoid highlighting multiple points on mouse hovering - as it's a bit annoying.
/cc @krzysied 
/hold
(for https://github.com/kubernetes/perf-tests/pull/161 to merge first and increment version to 1.4)
=> Change hit radius for perfdash click

perfdash/Makefile, perfdash/deployment.yaml, perfdash/parser.go
Cosmetic change for etcd metrics charts.
=> Perfdash: changing le to <=

benchmark/docs/design.md
update the testgrid link for kubemark-100-benchmark perf-tests
=> update the testgrid link for kubemark-100-benchmark perf-tests

clusterloader2/pkg/test/interface.go, clusterloader2/pkg/test/simpletestexecutor.go
Adding handling for create and delete operations. Update operation is not a part of this PR.
=> ClusterLoader - Adding execute object logic

clusterloader2/pkg/framework/client/objects.go, clusterloader2/pkg/test/simpletestexecutor.go
Updating object by creating patch based on already existing object and new object template.
=> ClusterLoader - Object update

clusterloader/docs/design.md
Based on my thoughts from https://github.com/kubernetes/perf-tests/pull/177#issuecomment-409530554
/cc @wojtek-t @krzysied
=> Improving clusterloader's Measurement API

clusterloader/docs/design.md
=> Minor fixes in cluster-loader doc

clusterloader2/api/types.go, clusterloader2/pkg/config/codec.go, clusterloader2/pkg/config/templateprovider.go, clusterloader2/pkg/test/simpletestexecutor.go
Replacing object names + index template.
=> ClusterLoader - Adding templating

clusterloader2/pkg/measurement/factory.go, clusterloader2/pkg/measurement/interface.go, clusterloader2/pkg/measurement/manager.go
Implementation of measurement factory and measurement manager.
CloudProvider will be add in future PR.
=> ClusterLoader - Adding measurement manager

clusterloader2/pkg/ticker/simpletickerfactory.go, clusterloader2/pkg/ticker/ticker.go, clusterloader2/pkg/ticker/timer.go
=> ClusterLoader - Implementing different timers

perfdash/Makefile, perfdash/config.go, perfdash/deployment.yaml
Updating config url in config.go.
ref https://github.com/kubernetes/test-infra/pull/8953
=> Perfdash - config location

clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/config/templateprovider.go, clusterloader2/pkg/framework/framework.go, clusterloader2/pkg/test/simplecontext.go
Object templates will use relative path (from test config directory).
=> ClusterLoader - Adding basepath template provider

run-e2e.sh
=> Adding echo to run-e2e script

clusterloader2/pkg/config/templatefunctions.go, clusterloader2/pkg/config/templateprovider.go, clusterloader2/pkg/test/simpletestexecutor.go
Adding generating random int functions.
=> ClusterLoader - Adding template functions

clusterloader2/pkg/config/template_provider.go, clusterloader2/pkg/measurement/common/wait_for_controlled_pods.go, clusterloader2/pkg/measurement/common/wait_for_pods.go, clusterloader2/pkg/test/simple_test_executor.go, clusterloader2/testing/load/config.yaml, clusterloader2/testing/load/rc.yaml, clusterloader2/testing/load/service.yaml
Adding 3-node load test.
New measurement `WaitForRunningRCs` added.
=> ClusterLoader - Load test

clusterloader2/pkg/test/simple_test_executor.go
Executing object operations (namespace x replicaIndex) in parallel.
=> ClusterLoader - Adding parallelism

clusterloader2/pkg/test/simple_test_executor.go, clusterloader2/pkg/util/util.go
=> ClusterLoader - Fixing mapping creation

clusterloader2/pkg/test/simple_test_executor.go
Making ticker to be blocking object bundle instead of object operation.
=> ClusterLoader - Changing to bundle ticker

perfdash/Makefile, perfdash/deployment.yaml, perfdash/parser.go
Fixing etcd metrics - structure of etcd metrics changed.
=> Perfdash - etcd metrics fix

clusterloader2/pkg/measurement/common/test_phase_timer.go
Adding test phase timer. This timer can create measurement summary.
=> ClusterLoader - Adding test phase timer

clusterloader2/pkg/util/util.go
Adding support for bool values.
\+ Fixing typos.
=> ClusterLoader - Adding bool parsing from config

slo-monitor/Dockerfile
Pick up RCE vulnerability fix for apk: https://alpinelinux.org/posts/Alpine-3.8.1-released.html
=> Update Alpine version for slo-monitor image

clusterloader2/pkg/measurement/common/wait_for_controlled_pods.go, clusterloader2/pkg/measurement/common/wait_for_pods.go
Making  wait_for_controlled_pods measurement be executed in parallel.
=> ClusterLoader - Adding parallelism to wait_for_controlled_pods measurement

clusterloader2/pkg/test/simple_test_executor.go
Adding handling for cluster level objects (when namespace range is not specified).
=> ClusterLoader - Handling cluster level objects

clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/util/cluster.go
Adding computing number of nodes if flag is not provided.
=> ClusterLoader - Adding node number computing

compare/src/compare-logs.go
=> Fix typo in the warning message

clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/config/cluster.go, clusterloader2/pkg/measurement/common/api_responsiveness.go, clusterloader2/pkg/measurement/common/etcd_metrics.go, clusterloader2/pkg/measurement/common/metrics_for_e2e.go, clusterloader2/pkg/measurement/common/profile.go, clusterloader2/pkg/measurement/common/scheduler_latency.go, clusterloader2/pkg/measurement/manager.go, clusterloader2/pkg/test/simple_test_executor.go, clusterloader2/testing/density/config.yaml, clusterloader2/testing/load/config.yaml
=> ClusterLoader - Adding additional cluster config flags

clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/util/cluster.go, clusterloader2/testing/density/config.yaml
Getting master name and master ip based on registered master node.
=> ClusterLoader - Master IP and master name completing

clusterloader2/docs/design.md, clusterloader2/pkg/config/template_functions.go, clusterloader2/pkg/framework/client/objects.go, clusterloader2/pkg/measurement/common/wait_for_pods.go
- Removing dependents during object deletion
- Adding Min and Max to template functions
=> ClusterLoader - Deleting dependents

clusterloader2/pkg/framework/framework.go, clusterloader2/pkg/test/simple_test_executor.go, clusterloader2/pkg/util/util.go
This is the fix for requests latency problem. Each test will use separate namespaces.
=> ClusterLoader - Random automanaged namespace name

clusterloader2/pkg/measurement/common/wait_for_controlled_pods.go
=> ClusterLoader - Removing duplicated functions

clusterloader2/testing/density/config.yaml, clusterloader2/testing/density/rc.yaml
Adding multiple iterations of latency pods creation.
=> ClusterLoader - density test update

clusterloader2/pkg/measurement/common/api_responsiveness.go, clusterloader2/pkg/measurement/common/etcd_metrics.go, clusterloader2/pkg/measurement/common/metrics_for_e2e.go, clusterloader2/pkg/measurement/common/pod_startup_latency.go, clusterloader2/pkg/measurement/common/profile.go, clusterloader2/pkg/measurement/common/resource_usage.go, clusterloader2/pkg/measurement/common/scheduler_latency.go, clusterloader2/pkg/measurement/common/timer.go, clusterloader2/pkg/measurement/common/wait_for_controlled_pods.go, clusterloader2/pkg/measurement/common/wait_for_pods.go, clusterloader2/pkg/measurement/interface.go, clusterloader2/pkg/measurement/manager.go, clusterloader2/pkg/measurement/util/gatherers/container_resource_gatherer.go, clusterloader2/pkg/test/simple_test_executor.go
Adds `Dispose` method to all measurements to ensure disposing allocated resources.
=> ClusterLoader - Adding measurement dispose

clusterloader2/api/extensions.go, clusterloader2/testing/load/config.yaml, clusterloader2/testing/load/rc.yaml
- Creating all services and then all RCs.
- Fixing tuning sets.
=> ClusterLoader - Updating load test

clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/config/cluster.go, clusterloader2/pkg/config/codec.go, clusterloader2/pkg/config/template_functions.go, clusterloader2/pkg/config/template_provider.go, clusterloader2/pkg/test/test.go
=> ClusterLoader - Adding mapping overrides

clusterloader2/testing/load/config.yaml
Applying #278 changes to load test config.
=> ClusterLoader - Removing stop action from load config

clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/measurement/common/api_responsiveness.go, clusterloader2/pkg/measurement/common/etcd_metrics.go, clusterloader2/pkg/measurement/common/metrics_for_e2e.go, clusterloader2/pkg/measurement/common/profile.go, clusterloader2/pkg/measurement/common/scheduler_latency.go, clusterloader2/pkg/measurement/interface.go, clusterloader2/pkg/measurement/manager.go, clusterloader2/pkg/test/simple_context.go
=> ClusterLoader - Moving ClusterConfig global to MeasurementManager structure

clusterloader2/testing/density/config.yaml, clusterloader2/testing/load/config.yaml
=> ClusterLoader - Applying default params to test configs

clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go
=> ClusterLoader - Updating pod startup measurement error text

clusterloader2/pkg/measurement/common/bundle/test_metrics.go, clusterloader2/pkg/measurement/common/simple/etcd_metrics.go, clusterloader2/pkg/measurement/common/simple/metrics_for_e2e.go, clusterloader2/pkg/measurement/common/simple/profile.go, clusterloader2/pkg/measurement/common/simple/resource_usage.go, clusterloader2/pkg/measurement/common/simple/scheduler_latency.go, clusterloader2/pkg/measurement/common/simple/timer.go, clusterloader2/pkg/measurement/common/simple/wait_for_pods.go, clusterloader2/pkg/measurement/common/slos/api_responsiveness.go, clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go, clusterloader2/pkg/measurement/interface.go
Adding `String()` method to measurement interface.
ref #275
=> ClusterLoader - Adding measurement String() method

clusterloader2/pkg/config/template_provider.go, clusterloader2/pkg/measurement/common/bundle/test_metrics.go, clusterloader2/pkg/measurement/common/simple/resource_usage.go, clusterloader2/pkg/measurement/interface.go, clusterloader2/pkg/measurement/manager.go, clusterloader2/pkg/measurement/util/gatherers/container_resource_gatherer.go, clusterloader2/pkg/measurement/util/resource.go, clusterloader2/pkg/test/simple_context.go
Changes:
- Adding template provider to measurement config
- Resource usage constrains validation
Resource constrains can be specified with yaml file. Resource validation was moved to resource usage measurement. If constraint is violated, metric violation error will be returned.
=> ClusterLoader - Resource usage constrains

clusterloader2/testing/density/config.yaml
Temporally changing test to make 5x  create latency pods iterations. Required to compare different latency pods creation approaches.
=> ClusterLoader - 5x100 density test update

clusterloader2/testing/density/config.yaml
Reverts kubernetes/perf-tests#309
fixes #310
=> Revert "ClusterLoader - 5x100 density test update"

clusterloader2/pkg/test/simple_test_executor.go
Adding restriction on bundle. It's now required that all bundle objects have the some replica count.
ref #261
=> ClusterLoader - Adding bundle restriction

clusterloader2/testing/density/config.yaml, clusterloader2/testing/density/rc.yaml
Bumping up latency pods resources to reduce pod assignment variance.
ref #312
=> ClusterLoader - Adding resource requests to latency pods

clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/test/test.go, clusterloader2/vendor/github.com/onsi/ginkgo/LICENSE, clusterloader2/vendor/github.com/onsi/ginkgo/config/config.go, clusterloader2/vendor/github.com/onsi/ginkgo/reporters/default_reporter.go, clusterloader2/vendor/github.com/onsi/ginkgo/reporters/fake_reporter.go, clusterloader2/vendor/github.com/onsi/ginkgo/reporters/junit_reporter.go, clusterloader2/vendor/github.com/onsi/ginkgo/reporters/reporter.go, clusterloader2/vendor/github.com/onsi/ginkgo/reporters/stenographer/console_logging.go, clusterloader2/vendor/github.com/onsi/ginkgo/reporters/stenographer/fake_stenographer.go, clusterloader2/vendor/github.com/onsi/ginkgo/reporters/stenographer/stenographer.go, clusterloader2/vendor/github.com/onsi/ginkgo/reporters/teamcity_reporter.go, clusterloader2/vendor/github.com/onsi/ginkgo/types/code_location.go, clusterloader2/vendor/github.com/onsi/ginkgo/types/synchronization.go, clusterloader2/vendor/github.com/onsi/ginkgo/types/types.go, clusterloader2/vendor/vendor.json
Adds junit.xml file that is used by the testgrid to add additional rows for tests.
ref #317
=> Cluster loader junit log

dns/jsonify/main.go, dns/jsonify/vendor/github.com/golang/glog/LICENSE, dns/jsonify/vendor/github.com/golang/glog/README, dns/jsonify/vendor/github.com/golang/glog/glog.go, dns/jsonify/vendor/github.com/golang/glog/glog_file.go, dns/jsonify/vendor/gopkg.in/yaml.v2/LICENSE, dns/jsonify/vendor/gopkg.in/yaml.v2/LICENSE.libyaml, dns/jsonify/vendor/gopkg.in/yaml.v2/NOTICE, dns/jsonify/vendor/gopkg.in/yaml.v2/README.md, dns/jsonify/vendor/gopkg.in/yaml.v2/apic.go, dns/jsonify/vendor/gopkg.in/yaml.v2/decode.go, dns/jsonify/vendor/gopkg.in/yaml.v2/emitterc.go, dns/jsonify/vendor/gopkg.in/yaml.v2/encode.go, dns/jsonify/vendor/gopkg.in/yaml.v2/go.mod, dns/jsonify/vendor/gopkg.in/yaml.v2/parserc.go, dns/jsonify/vendor/gopkg.in/yaml.v2/readerc.go, dns/jsonify/vendor/gopkg.in/yaml.v2/resolve.go, dns/jsonify/vendor/gopkg.in/yaml.v2/scannerc.go, dns/jsonify/vendor/gopkg.in/yaml.v2/sorter.go, dns/jsonify/vendor/gopkg.in/yaml.v2/writerc.go, dns/jsonify/vendor/gopkg.in/yaml.v2/yaml.go, dns/jsonify/vendor/gopkg.in/yaml.v2/yamlh.go, dns/jsonify/vendor/gopkg.in/yaml.v2/yamlprivateh.go, dns/jsonify/vendor/k8s.io/kubernetes/LICENSE, dns/jsonify/vendor/k8s.io/kubernetes/test/e2e/perftype/BUILD, dns/jsonify/vendor/k8s.io/kubernetes/test/e2e/perftype/perftype.go, dns/jsonify/vendor/vendor.json
Converting dns benchmark result files to metric files.
This will create 4 metrics:
- Latency:
- max_latency
- avg_latency
- min_latency
- LatencyPerc:
- Perc50
- Perc90
- Perc99
- Queries:
- queries_completed
- queries_lost
- queries_send
- Qps:
- qps
=> Dns -  Adding jsonify

clusterloader2/cmd/clusterloader.go
=> ClusterLoader: Pretty printing test summary

clusterloader2/README.md, clusterloader2/cmd/clusterloader.go
When trying to run the benchmark locally this was helpful
=> Allow to set masternode / masterip through CLI

perfdash/Makefile, perfdash/deployment.yaml, perfdash/www/script.js
Removing empty label set. There is on point in having selectable label list when there are no value in it.
=> Perfdash - Removing empty labels

clusterloader2/pkg/measurement/common/simple/scheduling_throughput.go
=> ClusterLoader - Minor logging fix

clusterloader2/pkg/measurement/common/simple/scheduler_latency.go, clusterloader2/pkg/measurement/util/kubemark/kubemark.go
=> Clusterloader - Measurement fixes

clusterloader2/pkg/test/simple_test_executor.go
=> Don't ignore error returned by ctx.GetChaosMonkey().Init.

clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go
Events are best effort and it can happen that some of them are missing, especially when we schedule a lot of events together.
=> Modify pod_startup_latency not to fail in case of missing schedule event.

SECURITY_CONTACTS
Fix https://github.com/kubernetes/perf-tests/issues/357
=> Add Security contacts

clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/flags/flags.go, clusterloader2/pkg/flags/types.go, clusterloader2/run-e2e.sh
Adding env flags that can read env variable if flag is not provided.
=> ClusterLoader - Adding env flags

clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/framework/framework.go, clusterloader2/pkg/framework/multiclient.go, clusterloader2/pkg/measurement/common/bundle/test_metrics.go, clusterloader2/pkg/measurement/common/simple/metrics_for_e2e.go, clusterloader2/pkg/measurement/common/simple/resource_usage.go, clusterloader2/pkg/measurement/common/simple/scheduler_latency.go, clusterloader2/pkg/measurement/common/simple/scheduling_throughput.go, clusterloader2/pkg/measurement/common/simple/wait_for_controlled_pods.go, clusterloader2/pkg/measurement/common/simple/wait_for_pods.go, clusterloader2/pkg/measurement/common/slos/api_responsiveness.go, clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go, clusterloader2/pkg/measurement/interface.go, clusterloader2/pkg/measurement/manager.go, clusterloader2/pkg/test/simple_context.go
Changing client to multiclients. Multiclients are sets of clients with additional logic for providing single client instance.
=> ClusterLoader - Adding multiple clients

clusterloader2/api/types.go, clusterloader2/pkg/tuningset/parallelism_limited.go, clusterloader2/pkg/tuningset/simple_tuning_set_factory.go
Adding new tuning set to execute operations with limited parallelism.
=> ClusterLoader - Adding ParallelismLimitedLoad tuning set

clusterloader2/testing/load/config.yaml
Adding and deleting services 1 by 1.
=> ClusterLoader - Executing load test service operation in a sequence.

perfdash/OWNERS
=> Add mborsz to perfdash/OWNERS

clusterloader2/testing/density/config.yaml, clusterloader2/testing/load/config.yaml
Making separate variables for density test throughput and load test throughput.
=> ClusterLoader - Separating test throughput

clusterloader2/pkg/measurement/common/simple/profile.go
Profiles will only log master sshing error instead of propagating it to caller.
Gathering profiles from apiserver is not a standard thing in gke.
=> ClusterLoader - Logging profile error for gke

clusterloader2/pkg/measurement/common/simple/wait_for_controlled_pods.go
Adding different handling for controlling object check timeout.
WaitForControlledPodsRunningMeasurement will print number of time-outed checks.
=> ClusterLoader - Adding timeout status for controlling objects checkers

clusterloader2/testing/density/600_nodes/high_density_override.yaml
Adding override for high density test.
=> ClusterLoader - Adding high density override

clusterloader2/pkg/measurement/common/simple/wait_for_controlled_pods.go
Fixing bug introduced in #386 . It caused setting timeout status even if there was no timeout.
=> ClusterLoader - Fixing wait for controlling objects timeout

clusterloader2/pkg/measurement/common/simple/wait_for_controlled_pods.go
This will help us debug issues like https://github.com/kubernetes/kubernetes/issues/73461
=> ClusterLoader - log which ReplicationControllers have timed-out.

clusterloader2/README.md
Adding info about:
- overrides
- metrics: APIResponsiveness, PodStartupLatency, ResourceUsageSummary, SchedulingThroughput
=> ClusterLoader - Updating README

clusterloader2/pkg/measurement/common/simple/resource_usage.go, clusterloader2/pkg/measurement/common/simple/wait_for_controlled_pods.go, clusterloader2/pkg/measurement/common/slos/api_responsiveness.go
The goal is to have errors that doesn't require to check build-log to see what exact object/metric is incorrect.
=> Add more descriptive error messages.

clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/chaos/nodes.go, clusterloader2/pkg/flags/flags.go, clusterloader2/pkg/measurement/common/bundle/test_metrics.go, clusterloader2/pkg/measurement/common/simple/etcd_metrics.go, clusterloader2/pkg/measurement/common/simple/metrics_for_e2e.go, clusterloader2/pkg/measurement/common/simple/profile.go, clusterloader2/pkg/measurement/common/simple/resource_usage.go, clusterloader2/pkg/measurement/common/simple/scheduler_latency.go, clusterloader2/pkg/measurement/common/simple/scheduling_throughput.go, clusterloader2/pkg/measurement/common/simple/timer.go, clusterloader2/pkg/measurement/common/simple/wait_for_controlled_pods.go, clusterloader2/pkg/measurement/common/simple/wait_for_pods.go, clusterloader2/pkg/measurement/common/slos/api_responsiveness.go, clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go, clusterloader2/pkg/measurement/util/gatherers/container_resource_gatherer.go, clusterloader2/pkg/measurement/util/gatherers/resource_gather_worker.go, clusterloader2/pkg/measurement/util/kubemark/kubemark.go, clusterloader2/pkg/test/simple_test_executor.go, clusterloader2/pkg/util/cluster.go
Replacing glog with klog.
fixes #402
=> ClusterLoader - Replacing glog with klog

clusterloader2/pkg/chaos/nodes.go
This is to address flakiness described in https://github.com/kubernetes/kubernetes/issues/73461#issuecomment-462754083
=> Don't kill the same node twice in NodeKiller.

clusterloader2/pkg/measurement/common/simple/wait_for_controlled_pods.go
Fix https://github.com/kubernetes/perf-tests/issues/411
=> Handle tombstones in clusterloader2

benchmark/Godeps/Godeps.json, benchmark/vendor/k8s.io/contrib/test-utils/utils/utils.go
Updating vendor with https://github.com/kubernetes/contrib/pull/2995 changes.
fixes #404
=> Benchmark - Vendor update

clusterloader2/pkg/chaos/nodes.go
Adding "NodeKiller: " prefix to logs.
Will make grepping logs easier.
=> ClusterLoader- Adding node killer log prefix

clusterloader2/pkg/framework/framework.go, clusterloader2/pkg/measurement/interface.go, clusterloader2/pkg/measurement/manager.go, clusterloader2/pkg/test/simple_context.go
https://github.com/kubernetes/perf-tests/issues/414
=> ClusterLoader - Add dynamic clients for measurement manager

clusterloader2/testing/density/config.yaml
https://github.com/kubernetes/kubernetes/issues/73461#issuecomment-467338711 and https://github.com/kubernetes/kubernetes/issues/73461#issuecomment-467353255
=> Increase saturationRCHardTimeout to 20min

clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/flags/flags.go, clusterloader2/pkg/flags/types.go
It will simplify enabling the prometheus stack in all tests.
https://github.com/kubernetes/kubernetes/issues/74213
=> Change prometheus flags to be env flags.

clusterloader2/pkg/measurement/util/runtimeobjects/runtimeobjects.go, clusterloader2/pkg/measurement/util/runtimeobjects/runtimeobjects_test.go
https://github.com/kubernetes/perf-tests/issues/414
=> ClusterLoader - Add unstructured support for runtimeobjects.go

clusterloader2/cmd/clusterloader.go
https://github.com/kubernetes/kubernetes/issues/74213
=> Tear down prometheus stack also on failed tests.

clusterloader2/pkg/prometheus/prometheus.go
We shouldn't run tests until the prometheus server is healthy and collects metrics from all targets.
https://github.com/kubernetes/kubernetes/issues/74213
=> Wait for prometheus to become healthy.

clusterloader2/pkg/prometheus/prometheus.go
* Increase timeout to 15min - it takes about 6min in scale tests for the
prometheus stack to become ready. Changing the deadline from 10min to
15min should prevent flakinesss
* Change the progress logging - it's more informative to log how many
targets are ready instead of one target that is not ready.
=> Change how CL2 waits for prometheus to be ready

perfdash/google-gcs-downloader.go, perfdash/parser.go
=> Add missing \n to some log messages

perfdash/Makefile, perfdash/deployment.yaml, perfdash/parser.go
Fixing empty histogram handling (`bucket["inf+"] == 0`).
fixes #442
=> Perfdash - etcd nan fix

clusterloader2/pkg/framework/client/objects.go
Example error is:
```
Post https://34.73.197.67/apis/rbac.authorization.k8s.io/v1/clusterrolebindings: net/http: TLS handshake timeout
```
Ref. https://github.com/kubernetes/kubernetes/issues/75284
=> ClusterLoader2 should retry retriable net errors.

clusterloader2/pkg/measurement/common/simple/etcd_metrics.go
When provider is GCE, etcd metrics port will be set to 2382 in https://github.com/kubernetes/kubernetes/pull/74690. Now etcd_metrics.go is always checking on 2379 for metrics, pull-kubernetes-e2e-gce-100-performance fails. 
It's the first I make any change to perf-tests repo, I have some questions:
1. This PR only makes sense when https://github.com/kubernetes/kubernetes/pull/74690 is merged. But if this pull-kubernetes-e2e-gce-100-performance fails, I cannot check in https://github.com/kubernetes/kubernetes/pull/74690. In this case, what shall I do? Should I make change to the perf-tests locally to test it first, get #74690 merged, and then push this PR?
2. Even after https://github.com/kubernetes/kubernetes/pull/74690 is merged, this change to perf-tests PR should only work with k8s …
=> Fix etcd metrics port for GCE

clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/framework/framework.go, clusterloader2/pkg/measurement/common/bundle/test_metrics.go, clusterloader2/pkg/measurement/common/simple/etcd_metrics.go, clusterloader2/pkg/measurement/common/simple/metrics_for_e2e.go, clusterloader2/pkg/measurement/common/simple/profile.go, clusterloader2/pkg/measurement/common/simple/resource_usage.go, clusterloader2/pkg/measurement/common/simple/scheduler_latency.go, clusterloader2/pkg/measurement/common/simple/scheduling_throughput.go, clusterloader2/pkg/measurement/common/simple/wait_for_controlled_pods.go, clusterloader2/pkg/measurement/common/simple/wait_for_pods.go, clusterloader2/pkg/measurement/common/slos/api_responsiveness.go, clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go, clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go, clusterloader2/pkg/measurement/interface.go, clusterloader2/pkg/measurement/manager.go, clusterloader2/pkg/measurement/util/prometheus.go, clusterloader2/pkg/prometheus/manifests/prometheus-rules.yaml, clusterloader2/pkg/prometheus/prometheus.go, clusterloader2/pkg/test/interface.go, clusterloader2/pkg/test/simple_context.go, clusterloader2/pkg/test/simple_test_executor.go, clusterloader2/pkg/test/test.go
- Adding new method for parsing method samples.
- Adding new api responsiveness measurement based on prometheus server data.
=> ClusterLoader - ApiResponsiveness measurement

clusterloader2/pkg/framework/client/objects.go, clusterloader2/pkg/prometheus/prometheus.go
Ref. https://github.com/kubernetes/kubernetes/issues/76182
=> Log prometheus-k8s events on stack set up failures

clusterloader2/pkg/framework/framework.go, clusterloader2/pkg/prometheus/prometheus.go
The method is needed by both Prometheus and soon-to-be introduced Probes frameworks.
Because of that it deserves to be moved to a commonly available place.
=> Extract ApplyTemplatedManifests method.

clusterloader2/pkg/framework/framework.go, clusterloader2/pkg/prometheus/prometheus.go
I missed that in the previous refactoring.
=> Make ApplyTemplatedManifests accept ApiCallOptions.

clusterloader2/pkg/measurement/common/simple/profile.go
Adding profile name. This name will be used in logs instead of printing whole measurement structure.
=> ClusterLoader - Adding profile name

clusterloader2/pkg/config/template_functions.go, clusterloader2/testing/load/service.yaml
Ref https://github.com/kubernetes/perf-tests/issues/413
=> Prepare for adding service-proxy-name label for half of the services

clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go, clusterloader2/pkg/prometheus/manifests/prometheus-rules.yaml
ref https://github.com/kubernetes/kubernetes/pull/74418
=> ClusterLoader - Fixing api calls metric name

clusterloader2/cmd/clusterloader.go
Ref. https://github.com/kubernetes/kubernetes/issues/76490
=> Fail ClusterLoader2 if there are no schedulable nodes.

clusterloader2/pkg/measurement/common/simple/etcd_metrics.go, clusterloader2/pkg/measurement/common/simple/metrics_for_e2e.go, clusterloader2/pkg/measurement/common/simple/profile.go, clusterloader2/pkg/measurement/common/simple/resource_usage.go, clusterloader2/pkg/measurement/common/simple/scheduler_latency.go, clusterloader2/pkg/measurement/common/simple/scheduling_throughput.go, clusterloader2/pkg/measurement/common/simple/timer.go, clusterloader2/pkg/measurement/common/slos/api_responsiveness.go, clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go, clusterloader2/pkg/measurement/interface.go, clusterloader2/pkg/test/simple_test_executor.go
Ref https://github.com/kubernetes/perf-tests/issues/489
=> Allow for differentiating different summaries from the same measurement

benchmark/Godeps/Godeps.json, benchmark/pkg/metricsfetcher/runselector/schemes/last_n_hours.go, benchmark/pkg/metricsfetcher/runselector/schemes/last_n_runs.go, benchmark/pkg/metricsfetcher/util/mock_util.go, benchmark/pkg/metricsfetcher/util/util.go, benchmark/vendor/k8s.io/contrib/test-utils/utils/bucket.go, benchmark/vendor/k8s.io/contrib/test-utils/utils/utils.go, benchmark/vendor/k8s.io/kubernetes/test/e2e/perftype/perftype.go
Fixing run id issue. Same as in https://github.com/kubernetes/perf-tests/issues/469
=> Benchmark - Run id fix

clusterloader2/pkg/measurement/common/bundle/test_metrics.go, clusterloader2/pkg/measurement/interface.go, clusterloader2/pkg/measurement/manager.go, clusterloader2/pkg/test/simple_context.go
It will be needed to disable Probes measurement in kubemark, see https://github.com/kubernetes/perf-tests/pull/475#discussion_r274874178
=> Add CloudProvider to the MeasurementConfig.

clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/measurement/common/probes/manifests/ping-client-deployment.yaml, clusterloader2/pkg/measurement/common/probes/manifests/ping-client-service.yaml, clusterloader2/pkg/measurement/common/probes/manifests/ping-client-serviceMonitor.yaml, clusterloader2/pkg/measurement/common/probes/manifests/ping-server-deployment.yaml, clusterloader2/pkg/measurement/common/probes/manifests/ping-server-service.yaml, clusterloader2/pkg/measurement/common/probes/manifests/ping-server-serviceMonitor.yaml, clusterloader2/pkg/measurement/common/probes/manifests/prometheus-role.yaml, clusterloader2/pkg/measurement/common/probes/manifests/prometheus-roleBinding.yaml, clusterloader2/pkg/measurement/common/probes/probes.go, clusterloader2/pkg/prometheus/manifests/prometheus-rules.yaml
Probes definition can be found in https://github.com/kubernetes/perf-tests/pull/474
The measurement is currently disabled, will be enabling it gradually.
Ref. https://github.com/kubernetes/kubernetes/issues/76012
=> Framework for running Probes in ClusterLoader2

clusterloader2/pkg/prometheus/manifests/default/master-kubelet-endpoints.yaml, clusterloader2/pkg/prometheus/manifests/default/master-kubelet-service.yaml, clusterloader2/pkg/prometheus/manifests/default/prometheus-serviceMonitorMasterKubelet.yaml
=> Start monitoring master's kubelet (non-kubemark)

clusterloader2/pkg/measurement/common/probes/probes.go, clusterloader2/pkg/measurement/common/simple/etcd_metrics.go, clusterloader2/pkg/measurement/common/simple/metrics_for_e2e.go, clusterloader2/pkg/measurement/common/simple/profile.go, clusterloader2/pkg/measurement/common/simple/resource_usage.go, clusterloader2/pkg/measurement/common/simple/scheduler_latency.go, clusterloader2/pkg/measurement/common/simple/scheduling_throughput.go, clusterloader2/pkg/measurement/common/simple/timer.go, clusterloader2/pkg/measurement/common/simple/wait_for_controlled_pods.go, clusterloader2/pkg/measurement/common/simple/wait_for_pods.go, clusterloader2/pkg/measurement/common/slos/api_responsiveness.go, clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go, clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go, clusterloader2/pkg/measurement/interface.go, clusterloader2/pkg/measurement/summary.go, clusterloader2/pkg/test/simple_test_executor.go
- adding generic summary
- adding extension to summary
=> ClusterLoader - Adding generic summary

clusterloader2/pkg/measurement/common/simple/profile.go, clusterloader2/pkg/measurement/common/slos/api_responsiveness.go, clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go
- Fixing error handling in api responsiveness metrics.
- Handling nil summary in profile measurement.
fixes #519
=> ClusterLoader - Fixing measurements

clusterloader2/pkg/prometheus/manifests/kubemark/kubemark-master-endpoints.yaml, clusterloader2/pkg/prometheus/manifests/kubemark/kubemark-master-service.yaml, clusterloader2/pkg/prometheus/manifests/kubemark/kubemark-master-serviceMonitor.yaml
=> Gather etcd metrics to prometheus

slo-monitor/Makefile, slo-monitor/slo-monitor-deployment.yaml, slo-monitor/slo-monitor-pod.yaml
* New images are pushed to both staging and prod gcr.io.
* Bump the version in sample yaml file and Makfile.
=> Release new slo-monitor image to gcr.io.

clusterloader2/README.md, clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go
Adding missing argument (measurement name) to log.
=> ClusterLoader - Fixing api responsiveness prometheus log

perfdash/Makefile, perfdash/deployment.yaml, perfdash/parser.go
Correctly merging result of e2e metric with different "contentType" label.
=> Perfdash - e2e metric fix

clusterloader2/pkg/prometheus/manifests/0prometheus-operator-deployment.yaml
Ref. https://github.com/kubernetes/kubernetes/pull/70672
=> Update prometheus operator to v0.30.0

perfdash/Makefile, perfdash/deployment.yaml, perfdash/www/script.js
Perfdash plot labels should be set based on last run configuration.
=> Perfdash - Label fix

perfdash/config.go, perfdash/deployment.yaml, perfdash/google-gcs-downloader.go, perfdash/perfdash.go
- Adding support for multi flags
- Extracting hardcoded config paths to deployment params.
ref #546
=> Perfdash - Extracting config paths to flags

perfdash/config.go
Adding config providing using file system paths.
ref #546
=> Perfdash - Reading config from file system

clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go
API responsiveness SLO: move filtering to Prometheus. 
=> API responsiveness SLO: move filtering to Prometheus

perfdash/google-gcs-downloader.go, perfdash/perfdash.go, perfdash/www/script.js
Adding flags for:
- gcs bucket name
- path to logs within the bucket
- path to gcs credentials
- storage url
ref #546
=> Perfdash - Making gcs configurable

clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go, clusterloader2/pkg/measurement/common/slos/prometheus_measurement.go
By no means this is the final form of how the library for Prometheus-based measurements should look like. I've simply extracted common code, that I am using to create measurements for networking programming latency. I'd rather have an iterative approach here. 
Also changed small bits here and there.
=> Extract common code for Prometheus-based measurements.

perfdash/Makefile, perfdash/deployment.yaml
New gcs-configurable version of Perfdash!
ref #564
=> Perdash - version 2.0

clusterloader2/pkg/flags/flags.go, clusterloader2/pkg/flags/types.go
It will be needed to support multiple masters in cl2.
=> Add support for StringSliceEnvVar flag.

clusterloader2/pkg/measurement/common/probes/probes.go, clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go, clusterloader2/pkg/measurement/common/slos/prometheus_measurement.go, clusterloader2/pkg/measurement/util/prometheus.go
This refactoring simplifies unit testing of Prometheus-based measurements.
/assign @mborsz @krzysied 
/kind cleanup
=> Create an interface for querying Prometheus from measurements.

clusterloader2/pkg/measurement/common/bundle/test_metrics.go, clusterloader2/pkg/measurement/common/simple/etcd_metrics.go, clusterloader2/pkg/measurement/common/simple/metrics_for_e2e.go, clusterloader2/pkg/measurement/common/simple/profile.go, clusterloader2/pkg/measurement/common/simple/resource_usage.go, clusterloader2/pkg/measurement/common/simple/scheduler_latency.go, clusterloader2/pkg/measurement/common/simple/scheduling_throughput.go, clusterloader2/pkg/measurement/common/simple/timer.go, clusterloader2/pkg/measurement/common/simple/wait_for_controlled_pods.go, clusterloader2/pkg/measurement/common/simple/wait_for_pods.go, clusterloader2/pkg/measurement/common/slos/api_responsiveness.go, clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go, clusterloader2/pkg/measurement/util/runtimeobjects/runtimeobjects.go
Those were caught by errcheck.
=> Fix unchecked errors in clusterloader2 code.

clusterloader2/pkg/measurement/common/slos/network_programming.go
=> Fix typo in measurement name.

clusterloader2/pkg/measurement/common/slos/network_programming.go, clusterloader2/pkg/measurement/common/slos/network_programming_test.go
refs https://github.com/kubernetes/perf-tests/issues/575
/label do-not-merge/work-in-progress
=> Report 50th, 90th and 99th percentailes of network programming latency.

perfdash/config.go
ref https://github.com/kubernetes/perf-tests/issues/498
=> Display prometheus-based API responsiveness SLI.

perfdash/Makefile, perfdash/deployment.yaml
Include changes from https://github.com/kubernetes/perf-tests/pull/607
/assign @mm4tt
=> Upgrade perf-dash to 2.4

clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.dashboard.py, clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.json
=> Modify prometheus dashboard to work for multiple masters

clusterloader2/pkg/measurement/common/probes/probes.go, clusterloader2/testing/density/config.yaml, clusterloader2/testing/experiments/probes.yaml, clusterloader2/testing/load/config.yaml
Add couple of minor improvements to the probes framework. 
/assign @mm4tt
=> Conditionally enable probes measuring in-cluster network latency

clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.dashboard.py, clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.json
=> Add few updates to master dashboard.

clusterloader2/pkg/prometheus/manifests/default/master-ip/master-endpoints.yaml, clusterloader2/pkg/prometheus/manifests/kubemark/kubemark-master-endpoints.yaml, clusterloader2/pkg/prometheus/prometheus.go
=> Add support for multiple masters to prometheus

clusterloader2/pkg/measurement/common/simple/wait_for_controlled_pods.go, clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go, clusterloader2/pkg/measurement/util/informer/informer.go
Extracting informer and dynamic informer.
=> ClusterLoader - Informers

clusterloader2/testing/density/config.yaml, clusterloader2/testing/load/config.yaml
Follow practices stated in https://github.com/kubernetes/perf-tests/tree/master/clusterloader2/docs
/assign @mm4tt
=> Actually do not enable anything with ENABLE_PROBES.

clusterloader2/OWNERS, perfdash/OWNERS, probes/OWNERS
=> Add oxddr as a reviewer to clusterloader2, perfdash and probes.

clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.dashboard.py, clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.json, clusterloader2/pkg/prometheus/manifests/default/master-ip/master-serviceMonitor.yaml, clusterloader2/pkg/prometheus/manifests/kubemark/kubemark-master-serviceMonitor.yaml
Also changes scrape interval for node-exporter, as node-exporter takes usually ~10s to scrape.
/assign @mm4tt
=> Add few graphs to master dashboard.

clusterloader2/pkg/measurement/common/simple/wait_for_controlled_pods.go, clusterloader2/pkg/measurement/common/simple/wait_for_pods.go, clusterloader2/pkg/measurement/util/wait_for_pods.go
Moving waitForPods method to measurement/util.
=> ClusterLoader - Extracting wait for pods method

clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/measurement/common/etcd_metrics.go, clusterloader2/pkg/measurement/common/metrics_for_e2e.go, clusterloader2/pkg/measurement/common/profile.go, clusterloader2/pkg/measurement/common/resource_usage.go, clusterloader2/pkg/measurement/common/scheduler_latency.go, clusterloader2/pkg/measurement/common/scheduling_throughput.go, clusterloader2/pkg/measurement/common/timer.go, clusterloader2/pkg/measurement/common/wait_for_controlled_pods.go, clusterloader2/pkg/measurement/common/wait_for_pods.go
=> ClusterLoader - Moving common/simple/ content to common/

probes/Dockerfile, probes/cmd/main.go, probes/pkg/common/consts.go, probes/pkg/dns/probe.go, probes/pkg/metrics/metrics.go, verify/verify-flags/known-flags.txt
ref #612
/assign @wojtek-t @mm4tt
=> Add probe periodically performing DNS lookups to probes binary

clusterloader2/pkg/measurement/common/probes/probes.go, clusterloader2/pkg/measurement/common/slos/network_programming.go, clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go, clusterloader2/pkg/measurement/util/latency_metric.go
=> Name functions creating LatencyMetric more coherently.

clusterloader2/pkg/measurement/util/phase_latency.go
The log prints in the wrong order. This simple Pr fixes that.
=> fix X worst latency log

perfdash/Makefile, perfdash/config.go, perfdash/deployment.yaml
ref https://github.com/kubernetes/perf-tests/issues/669
=> Perfdash - experimental jobs

clusterloader2/pkg/measurement/util/phase_latency.go
ref https://github.com/kubernetes/perf-tests/issues/663
=> ClusterLoader - Phase latency logs

clusterloader2/pkg/measurement/util/object_store.go
=> Generalize PodStore

clusterloader2/pkg/measurement/util/object_store.go
=> Create PVCStore and fix typos from #675

clusterloader2/pkg/measurement/common/probes/probes.go, clusterloader2/pkg/prometheus/manifests/default/master-ip/master-endpoints.yaml, clusterloader2/pkg/prometheus/manifests/default/master-ip/master-service.yaml, clusterloader2/pkg/prometheus/manifests/default/master-ip/master-serviceMonitor.yaml, clusterloader2/pkg/prometheus/prometheus.go, clusterloader2/pkg/prometheus/util.go
Ref. https://github.com/kubernetes/kubernetes/pull/77561
=> Make prometheus monitor etcd on 2379 or 2382 port.

clusterloader2/pkg/prometheus/manifests/kubemark/kubemark-master-endpoints.yaml, clusterloader2/pkg/prometheus/manifests/kubemark/kubemark-master-service.yaml, clusterloader2/pkg/prometheus/manifests/kubemark/kubemark-master-serviceMonitor.yaml, clusterloader2/pkg/prometheus/prometheus.go
Ref. https://github.com/kubernetes/kubernetes/pull/77561
=> Make prometheuse monitor etcd on 2379 or 2382 in kubemark

clusterloader2/pkg/measurement/util/pvcs.go, clusterloader2/pkg/measurement/util/wait_for_pods.go, clusterloader2/pkg/measurement/util/wait_for_pvcs.go
=> Unify and cleanup wait_for_pods and wait_for_pvc

clusterloader2/pkg/measurement/common/service_creation_latency.go
Adding measurement that measures service creation latency.
=> ClusterLoader - Adding service_creation_latency measurement

clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.dashboard.py, clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.json
Few changes:
1. irate to etcd network client bytes to show more spiky graph
2. few etcd compaction-related metrics
3. Fix 'Watch events traffic' format
4. Add format to 'Network tcp segments' graph.
=> Improve master dashboard

clusterloader2/pkg/measurement/util/kubemark/kubemark.go
With kubemark script changes the run etcd  command changed.
/fixes #700
=> ClusterLoader - Gathering kubemark etcd resource usage fix

clusterloader2/docs/test_suite_design.md
ref https://github.com/kubernetes/perf-tests/issues/641
=> ClusterLoader - Test suite design

clusterloader2/pkg/measurement/util/runtimeobjects/runtimeobjects.go
=> Support StatefulSets in runtimeobjects.go

perfdash/Makefile, perfdash/config.go, perfdash/deployment.yaml
Adding config for new test names and new measurement identifiers.
=> Perfdash - Storage test config fix

clusterloader2/testing/experimental/storage/pod-startup/config.yaml
=> Create pods slower in storage tests

clusterloader2/pkg/prometheus/experimental.go
=> Improve logging around Prometheus snapshoting

clusterloader2/api/types.go
=> ClusterLoader - Adding TestSuite api

clusterloader2/pkg/measurement/common/wait_for_pvs.go, clusterloader2/pkg/measurement/util/object_store.go, clusterloader2/pkg/measurement/util/pvs.go, clusterloader2/pkg/measurement/util/wait_for_pvs.go
Per #722, this adds a function that waits until all PVs are deleted. 
@msau42 @davidz627 @jingxu97 @verult
=> add function to wait for available PVs

clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/config/template_provider.go
=> ClusterLoader - Test suite

clusterloader2/testing/density/config.yaml, clusterloader2/testing/load/config.yaml, clusterloader2/testing/load/experimental/bundled_services_and_deployments.yaml, clusterloader2/testing/load/experimental/extended_config.yaml
=> Remove ENABLE_PROBES experiment.

clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go, clusterloader2/pkg/measurement/common/slos/network_programming.go, clusterloader2/pkg/measurement/common/slos/prometheus_measurement.go
=> Disable "NetworkProgrammingLatency" measurement in kubemark

clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/config/cluster.go, clusterloader2/pkg/prometheus/prometheus.go, verify/verify-flags/known-flags.txt
- Moving overrides parameters to prometheus flags.
=> ClusterLoader - Adding prometheus flags

probes/pkg/ping/client/metrics.go
=> Fix buckets in ping-client probe.

clusterloader2/pkg/measurement/common/probes/manifests/ping-client-deployment.yaml, clusterloader2/pkg/measurement/common/probes/manifests/ping-server-deployment.yaml
=> Bump version of probes in ping-{client,server} to 0.0.3

clusterloader2/pkg/prometheus/manifests/dashboards/Makefile, clusterloader2/pkg/prometheus/manifests/dashboards/README.md, clusterloader2/pkg/prometheus/manifests/dashboards/__init__.py, clusterloader2/pkg/prometheus/manifests/dashboards/defaults.py, clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.dashboard.py, clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.json, clusterloader2/pkg/prometheus/manifests/dashboards/requirements.txt, verify/boilerplate/boilerplate.py.txt
This PR is a preparation for adding more dashboards using grafanalib.
/assign @mborsz @wojtek-t
=> Refactoring of Granafa dashboard setup.

clusterloader2/pkg/prometheus/manifests/dashboards/defaults.py, clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.dashboard.py, clusterloader2/pkg/prometheus/manifests/dashboards/slo.dashboard.py, clusterloader2/pkg/prometheus/manifests/dashboards/slo.json, clusterloader2/pkg/prometheus/manifests/grafana-dashboardDefinitions.yaml, clusterloader2/pkg/prometheus/manifests/grafana-deployment.yaml
Experimental panels shows SLO but using different window size (30s and 1m).
/hold
=> Grafana: create SLO dashboard with experimental panels

clusterloader2/pkg/measurement/common/probes/probes.go
=> Do not run probes if Prometheus is disabled.

clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/config/cluster.go, clusterloader2/pkg/config/template_provider.go, clusterloader2/pkg/test/simple_context.go, clusterloader2/pkg/test/simple_test_executor.go, clusterloader2/pkg/test/test.go
=> ClusterLoader - Adding test scenario to config

clusterloader2/pkg/prometheus/manifests/dashboards/OWNERS
=> Create a separate OWNERS file for Grafana dashboards.

clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.dashboard.py, clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.json
They should use container instead of container_name
=> Fix container_* metrics

clusterloader2/pkg/measurement/common/probes/manifests/dnsLookup/dns-prober-deployment.yaml, clusterloader2/pkg/measurement/common/probes/manifests/ping-client-deployment.yaml, clusterloader2/pkg/measurement/common/probes/manifests/ping-server-deployment.yaml
/hold
ref https://github.com/kubernetes/perf-tests/issues/755
=> Bump probes to v0.0.4.

clusterloader2/pkg/config/cluster.go, clusterloader2/pkg/prometheus/manifests/0prometheus-operator-deployment.yaml, clusterloader2/pkg/prometheus/manifests/default/prometheus-serviceMonitorKubelet.yaml, clusterloader2/pkg/prometheus/manifests/prometheus-prometheus.yaml, clusterloader2/pkg/prometheus/prometheus.go, verify/verify-flags/known-flags.txt
=> Optionally scrape kubelets in tests. Skip test pods.

clusterloader2/pkg/config/template_functions.go
In addition sort entries in FuncMap
=> Implement IfThenElse template func

clusterloader2/pkg/prometheus/manifests/dashboards/network.dashboard.py, clusterloader2/pkg/prometheus/manifests/dashboards/network.json
fixes: https://github.com/kubernetes/perf-tests/issues/755
/hold
=> Grafana: plot ping rate, ping error rate and probes memory usage

clusterloader2/testing/load/config.yaml, clusterloader2/testing/load/statefulset.yaml, clusterloader2/testing/load/statefulset_service.yaml
=> Create StatefulSets in load test

clusterloader2/pkg/prometheus/experimental.go, clusterloader2/pkg/prometheus/prometheus.go
=> Cache Prometheus persistent disk name before running tests

clusterloader2/testing/load/experimental/overrides/enable_daemonsets.yaml
=> Add override for enabling DaemonSets

clusterloader2/testing/load/statefulset.yaml
=> Fix group label in statefulset.yaml

clusterloader2/pkg/prometheus/manifests/dashboards/network.dashboard.py, clusterloader2/pkg/prometheus/manifests/dashboards/network.json
=> Grafana: improve dashboard for network-latency probes.

clusterloader2/testing/load/config.yaml, clusterloader2/testing/load/job.yaml
=> Extend load test to cover Jobs

clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.dashboard.py, clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.json
Grafana: add etcd wal fsync duration panel
Helps with debugging recent issues - Persistent Disks unhealthiness or COS regression
/cc mm4tt
=> Grafana: add etcd wal fsync duration panel

clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.dashboard.py, clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.json
=> Grafana: collapse panels on master dashboard

clusterloader2/testing/load/daemonset.yaml
Ref https://github.com/kubernetes/perf-tests/issues/704
=> Bump daemonset parallelism in load test

dns/README.md, dns/run
This will enable setting up ci to trigger nodelocaldns tests.
=> Update run command to support nodelocaldns tests.

dns/run
Fixing output dir for coredns and nodelocaldns tests.
=> Dns - fixing script out dir

README.md, _hook/pre-push
To be use as a git pre-push hook. Hopefully this will minimize back and forth due to linter or boilerplate problems. 
/assign @mm4tt
=> Add script running verify* scripts.

clusterloader2/pkg/measurement/util/pods.go, clusterloader2/pkg/measurement/util/wait_for_pods.go
Logging pods status (name, phase, node) when waitForPods times out.
=> ClusterLoader - waitForPods timeout log

clusterloader2/OWNERS, perfdash/OWNERS, probes/OWNERS
=> Make oxddr approver in CL2, perfdash and probes.

clusterloader2/pkg/chaos/nodes.go, clusterloader2/pkg/framework/client/objects.go
=> Node-killer avoid killing nodes where prometheus is running

dns/README.md, dns/py/runner.py, dns/run
=> fix "./run  core-dns out" failed

clusterloader2/pkg/measurement/util/runtimeobjects/runtimeobjects.go
Take into account nodeAffinity when calculating num replicas for DaemonSets
Ref #790 
/assign @mm4tt
=> Calculating num replicas for DaemonSets take into account affinity

clusterloader2/testing/density/legacy/config.yaml
ref https://github.com/kubernetes/perf-tests/pull/823
=> ClusterLoader - Legacy latency pod memory update

clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/imagepreload/imagepreload.go, clusterloader2/pkg/imagepreload/manifests/daemonset.yaml, verify/verify-flags/known-flags.txt
Please let me know if more documentation should be added, either here or in the code.
=> Add an option to CL2 to preload given list of images.

clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.dashboard.py, clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.json
Also, refactor excluded verbs in apiserver_request_latency graph
=> Exclude CONNECT calls from Cl2 requests panel

clusterloader2/pkg/measurement/common/slos/api_responsiveness.go, clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go
Actually move common code to a dedicated function and use it in both measurements.
/assign @mm4tt
=> Format errors from APIResponsiveness* measurements uniformly

clusterloader2/pkg/execservice/exec_service.go, clusterloader2/pkg/measurement/common/service_creation_latency.go
ServiceCreationLatency handle ClusterIP and NodePort type of service
Ref #679 
/assign  @wojtek-t @krzysied @mm4tt
=> ServiceCreationLatency handle ClusterIP and NodePort type of service

clusterloader2/pkg/config/template_functions.go, clusterloader2/pkg/measurement/common/service_creation_latency.go, clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go, clusterloader2/pkg/measurement/util/kubelet/kubelet.go, clusterloader2/pkg/measurement/util/runtimeobjects/runtimeobjects.go, clusterloader2/pkg/util/util.go
Fix some err check and remove some unused values
=> Fix some err check and remove some unused values 

clusterloader2/pkg/measurement/common/bundle/test_metrics.go, clusterloader2/pkg/measurement/common/scheduler_latency.go
Fix typo and add some debug logs.
=> Minor change: add some debug log and fix a typo

clusterloader2/pkg/measurement/util/wait_for_pods.go, clusterloader2/pkg/measurement/util/wait_for_pvcs.go, clusterloader2/pkg/measurement/util/wait_for_pvs.go
Fix several spelling mistakes in clusterloader2/pkg/measurement/util
=> Fix a few spelling mistakes.

clusterloader2/README.md, clusterloader2/pkg/measurement/common/sleep.go
=> Add Sleep measurement

clusterloader2/testing/experiments/ignore_known_gce_container_restarts.yaml
fixes: https://github.com/kubernetes/kubernetes/issues/85682
/assign @pierewoj
=> Allow a single restart of master components 

run-e2e-with-prometheus-fw-rule.sh
Remove additional firewall rule to pass check-leaked-resources test
/cc wojtek-t
=> Clean up Prometheus firewall rule after test

benchmark/docs/design.md
The link to Kubemark Guide has changed.I update it.
=> Update a Website link

clusterloader2/pkg/measurement/util/prometheus.go
ref https://github.com/kubernetes/kubernetes/issues/86082
=> Log response body when there is an error from Prometheus

perfdash/config.go, perfdash/downloader.go, perfdash/github-configs-fetcher.go, perfdash/google-gcs-downloader.go, perfdash/parser.go, perfdash/perfdash.go
Fix [Issue929](https://github.com/kubernetes/perf-tests/issues/929).
Change all ocurrances of fmt.Printf to klog in perfdash.
Using go-errors for handling errors will be a separate PR
=> Perfdash: Improve perfdash logging

clusterloader2/OWNERS
=> Make mborsz approver in CL2

clusterloader2/OWNERS
=> Make mborsz approver in CL2 (1.17)

clusterloader2/OWNERS
=> Make oxddr and mborsz approvers in CL2 (1.16)

clusterloader2/OWNERS
=> Make oxddr and mborsz approvers in CL2 (1.13)

clusterloader2/OWNERS
=> Make oxddr and mborsz approvers in CL2 (1.12)

clusterloader2/OWNERS
=> Make oxddr and mborsz approvers in CL2 (1.14)

clusterloader2/OWNERS
=> Make oxddr and mborsz approvers in CL2 (1.15)

clusterloader2/pkg/measurement/common/profile.go
Profile measurements should warn instead of fail on lack of master IPs
Currently it fails tests with:
```
[measurement call TestMetrics - TestMetrics error: [
Profile measurements will be disabled due to no MasterIps 
Profile measurements will be disabled due to no MasterIps 
Profile measurements will be disabled due to no MasterIps 
Profile measurements will be disabled due to no MasterIps 
Profile measurements will be disabled due to no MasterIps 
Profile measurements will be disabled due to no MasterIps 
Profile measurements will be disabled due to no MasterIps 
Profile measurements will be disabled due to no MasterIps 
Profile measurements will be disabled due to no MasterIps
]]
```
/assign @mm4tt
=> Profile measurements should warn instead of fail on lack of master IPs

clusterloader2/testing/density/legacy/config.yaml
Cherry-pick: https://github.com/kubernetes/perf-tests/pull/823
/cc mborsz
=> ClusterLoader - Legacy latency pod memory update (1.13)

clusterloader2/testing/density/config.yaml, clusterloader2/testing/density/legacy/config.yaml
Cherry-picks:
https://github.com/kubernetes/perf-tests/pull/823
https://github.com/kubernetes/perf-tests/pull/873
=> ClusterLoader - latency pod memory update (1.14)

clusterloader2/testing/density/config.yaml, clusterloader2/testing/density/legacy/config.yaml
Cherry-picks: #823 #873
/cc mborsz
=> ClusterLoader - Legacy latency pod memory update (1.15)

clusterloader2/testing/density/legacy/config.yaml
=> ClusterLoader - Legacy latency pod memory update (1.12)

clusterloader2/pkg/prometheus/experimental.go, verify/verify-flags/known-flags.txt
=> Add flag to override the prometheus snapshot name (1.15)

clusterloader2/pkg/prometheus/experimental.go, verify/verify-flags/known-flags.txt
=> Add flag to override the prometheus snapshot name (1.13)

clusterloader2/pkg/prometheus/experimental.go, verify/verify-flags/known-flags.txt
=> Add flag to override the prometheus snapshot name (1.14)

run-e2e-with-prometheus-fw-rule.sh
Cherry-pick #907 (with subsequent fixes) into release-1.16
/cc mm4tt
=> Ability to add Prometheus port firewall rule

perfdash/Makefile, perfdash/config.go, perfdash/deployment.yaml
Ref: https://github.com/kubernetes/perf-tests/issues/963
=> Expose node-throughput tests in perfdash

clusterloader2/pkg/util/cluster.go
It's an anti-pattern to control level of logging via method arguments, a logging framework features should be used for that.
Changing the log level to V(4) so it can be turned on/off by setting the --v flag appropriately.
A justification for making this change is the CA tests where nodes appear and disappear, in the current for this logging spams the CL2 output.
=> Simplify logging in the isNodeConditionSetAsExpected

clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.dashboard.py, clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.json
Two nice graphs that can be used to see what kind of load is generated in the cluster.
=> Add pod binding and pod creations graphs.

.travis.yml, verify/go-build.sh
=> [Travis] Add support to skip some go build targets

clusterloader2/pkg/measurement/common/profile.go
Fixes https://github.com/kubernetes/perf-tests/issues/985
=> Fix gathering apiserver profiles

clusterloader2/pkg/prometheus/util.go
=> Log response' body from a call to Prometheus (proxied by apiserver).

clusterloader2/pkg/prometheus/manifests/dashboards/Makefile, clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.dashboard.py, clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.json
Related issue: https://github.com/kubernetes/perf-tests/issues/1002
=> dashboards: remove apiserver_request_total client label

clusterloader2/pkg/measurement/common/etcd_metrics.go
We should use HTTPS to reach the ETCD metrics API outside of GCE.
=> Add curl https config.

clusterloader2/pkg/framework/client/objects.go
The goal is to:
* reflect reality: before this change, we were using jsonmergepatch
object as an argument to strategic patch which works fine, as we always
provide entire slices which makes 'merge' patchStrategy noop
* make it work for CRDs: strategic patch is not supported for CRDs
=> Change patch strategy to MergePatchType

clusterloader2/pkg/measurement/util/wait_for_pods.go
=> Fix a typo in wait_for_pods.go

clusterloader2/pkg/measurement/common/profile.go
In k8s cluster built by aks-engine, for some reason it's hard to curl api server. Hence I add a config to let it reach api server through k8s client.
=> Add a config for reaching apiserver through k8s client.

clusterloader2/pkg/config/template_functions.go
Required to add access-tokens test to branch 1.17
Related to https://github.com/kubernetes/kubernetes/issues/83375
=> [ClusterLoader2] change slice related Go template functions

clusterloader2/pkg/framework/framework.go
This change fixs the race condition that's happened around
the `wait.Group` and some code refactoring as well.
fix: https://github.com/kubernetes/perf-tests/issues/1072
=> Stale namespaces should be cleaned all at once

clusterloader2/pkg/measurement/common/scheduler_latency.go, clusterloader2/pkg/measurement/util/histogram.go, clusterloader2/pkg/measurement/util/histogram_test.go, clusterloader2/vendor/github.com/prometheus/client_golang/prometheus/testutil/testutil.go, clusterloader2/vendor/k8s.io/component-base/metrics/OWNERS, clusterloader2/vendor/k8s.io/component-base/metrics/collector.go, clusterloader2/vendor/k8s.io/component-base/metrics/counter.go, clusterloader2/vendor/k8s.io/component-base/metrics/desc.go, clusterloader2/vendor/k8s.io/component-base/metrics/gauge.go, clusterloader2/vendor/k8s.io/component-base/metrics/histogram.go, clusterloader2/vendor/k8s.io/component-base/metrics/legacyregistry/registry.go, clusterloader2/vendor/k8s.io/component-base/metrics/metric.go, clusterloader2/vendor/k8s.io/component-base/metrics/processstarttime.go, clusterloader2/vendor/k8s.io/component-base/metrics/registry.go, clusterloader2/vendor/k8s.io/component-base/metrics/summary.go, clusterloader2/vendor/k8s.io/component-base/metrics/testutil/metrics.go, clusterloader2/vendor/k8s.io/component-base/metrics/testutil/testutil.go, clusterloader2/vendor/vendor.json, perfdash/parser.go
On top of https://github.com/kubernetes/perf-tests/pull/978
- importing `k8s.io/component-base/metrics/testutil.Histogram` to compute quantile
- adding unit test to validate the quantile of `k8s.io/perf-tests/clusterloader2/pkg/measurement/util.Histogram` is computed correctly
=> clusterloader2: import k8s.io/component-base/metrics/testutil.Histogram to compute quantile

perfdash/Makefile, perfdash/deployment.yaml
=> [Remove density] New version of perf-dash

clusterloader2/pkg/measurement/interface.go, clusterloader2/pkg/measurement/manager.go, clusterloader2/pkg/test/interface.go, clusterloader2/pkg/test/simple_context.go
As requested here:
[https://github.com/kubernetes/perf-tests/pull/1075/files#r383722052](url) , creating a separate PR for creating a measurementmanager interface which would and adding Measurementmanager to measurementConfig.
=> Create Measurementmanager interface

clusterloader2/pkg/config/template_functions.go, clusterloader2/pkg/measurement/common/sleep.go, clusterloader2/testing/access-tokens/config.yaml, clusterloader2/testing/access-tokens/deployment.yaml, clusterloader2/testing/access-tokens/role.yaml, clusterloader2/testing/access-tokens/roleBinding.yaml, clusterloader2/testing/access-tokens/serviceAccount.yaml, clusterloader2/testing/access-tokens/token.yaml
Backport:
* Access-tokens test
* Template function 'Loop'
* 'Sleep' measurement
=> [Access-tokens] Backport test and dependencies from 'master'

perfdash/Makefile, perfdash/deployment.yaml
=> Update perfdash to 2.20.

perfdash/Makefile, perfdash/deploy.sh
Also make deploy.sh to use temp directory, which is removed by the script fully.
/assign @mm4tt
=> perfdash: add deploy target to Makefile.

_hook/pre-push, verify/test.sh, verify/verify-golint.sh
=> Disable Go Modules in scripts used by travis (and pre-push hook)

clusterloader2/pkg/measurement/common/service_creation_latency.go
This PR fixes https://github.com/kubernetes/perf-tests/issues/1101. It adds checks to handle errors thrown by exec_service and also, to not start service_creation_latency when --enable-exec-service flag is disabled.
=> Fix to handle exec_service error + not starting service creation latency measurment when --enable-exec-service flag is disabled

perfdash/Makefile, perfdash/deployment.yaml
Also fix dependencies in perfdash Makefile.
/assign @mm4tt
=> Bump perfdash to 2.21

clusterloader2/testing/chaosmonkey/ignore_node_killer_container_restarts_100.yaml
Ref. #1005
Backporting to 1.18
=> [NodeKiller] Add override to ignore expected crashes

clusterloader2/pkg/chaos/monkey.go, clusterloader2/pkg/chaos/nodes.go, clusterloader2/pkg/test/simple_test_executor.go
=> [NodeKiller] Add summary

clusterloader2/pkg/chaos/monkey.go, clusterloader2/pkg/chaos/nodes.go, clusterloader2/pkg/test/simple_test_executor.go, clusterloader2/testing/load/config.yaml
- [NodeKiller] Schedule reboot and disconnect from node
- [NodeKiller] Change rounding of a number of selected nodes
- [NodeKiller] Add summary
=> Cherry-pick NodeKiller changes

clusterloader2/README.md
Super simple change of README.md as a part of my onboarding process.
Please trigger the tests using /ok-to-test so I could see which scalability tests are run as presubmits.
CC @mm4tt
=> Fix a typo

clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/config/cluster.go, clusterloader2/pkg/measurement/common/profile.go
This PR is to resolve issue #948 as seen with @mm4tt
=> CL2: fix etcd profiles gathering

perfdash/Dockerfile, perfdash/Makefile
This PR is to resolve issue #604 as seen with @oxddr
=> Improve perfdash container build

clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/config/cluster.go, clusterloader2/pkg/measurement/common/etcd_metrics.go, clusterloader2/pkg/measurement/common/profile.go, clusterloader2/pkg/measurement/common/scheduler_latency.go
Addresses @mm4tt  post-submit comments in #1056 (which was much easier given recent refactorings).
=> Follow up from 1056

clusterloader2/pkg/measurement/common/slos/windows_node_resource_usage.go
1. Add memory usage measurement, query is from discussion: https://github.com/martinlindhe/wmi_exporter/issues/496
2. Rename cpu usage measurement methods
3. Bumped the default pause image version
=> Add windows memory usage measurement

perfdash/Makefile, perfdash/deployment.yaml
=> Bump perfdash to 2.22

clusterloader2/api/types.go, clusterloader2/pkg/measurement/manager.go, clusterloader2/pkg/measurement/measurement_executor.go, clusterloader2/pkg/test/simple_test_executor.go
This PR is for [https://github.com/kubernetes/perf-tests/issues/794](url) which attempts to create a new measurement as a wrapper measurement to reduce boiler plate code.
=> Perf tests 794- Create Wrapper measurement.

clusterloader2/pkg/measurement/common/probes/probes.go
Allow probes measurement to use custom timeout for pod readiness. Required to adapt containerd for tests
Ref. #1110 
=> [ClusterLoader2] Enable custom timeouts for probes

clusterloader2/README.md
=> ClusterLoader: update README

clusterloader2/README.md
ref https://github.com/kubernetes/perf-tests/pull/915
=> update Readme.md for clusterloader2 to replace APIResponsiveness with APIResponsivenessPrometheusSimple

clusterloader2/pkg/config/cluster.go, clusterloader2/pkg/framework/client/objects.go, clusterloader2/pkg/prometheus/experimental.go, clusterloader2/pkg/prometheus/manifests/0ssd-storage-class.yaml, clusterloader2/pkg/prometheus/prometheus.go
Fix: #1020
/cc mm4tt tosi3k mborsz
=> Snapshot Prometheus disk after tearing Prometheus down (1.18)

clusterloader2/pkg/config/cluster.go, clusterloader2/pkg/framework/client/objects.go, clusterloader2/pkg/prometheus/experimental.go, clusterloader2/pkg/prometheus/manifests/0ssd-storage-class.yaml, clusterloader2/pkg/prometheus/prometheus.go
=> Snapshot Prometheus disk after tearing Prometheus down (1.17)

clusterloader2/pkg/config/cluster.go, clusterloader2/pkg/framework/client/objects.go, clusterloader2/pkg/prometheus/experimental.go, clusterloader2/pkg/prometheus/manifests/0ssd-storage-class.yaml, clusterloader2/pkg/prometheus/prometheus.go
=> Snapshot Prometheus disk after tearing Prometheus down (1.16)

clusterloader2/pkg/config/cluster.go, clusterloader2/pkg/framework/client/objects.go, clusterloader2/pkg/prometheus/experimental.go, clusterloader2/pkg/prometheus/manifests/0ssd-storage-class.yaml, clusterloader2/pkg/prometheus/prometheus.go
=> Snapshot Prometheus disk after tearing Prometheus down (1.15)

clusterloader2/pkg/config/cluster.go, clusterloader2/pkg/framework/client/objects.go, clusterloader2/pkg/prometheus/experimental.go, clusterloader2/pkg/prometheus/manifests/0ssd-storage-class.yaml, clusterloader2/pkg/prometheus/prometheus.go
=> Snapshot Prometheus disk after tearing Prometheus down (1.14)

clusterloader2/cmd/clusterloader.go
Moving overrides parameters to prometheus flags.
Needed as we backported whole prometheus pkg.
Cherry-pick: #741
/cc wojtek-t
=> Backport: ClusterLoader - Adding prometheus flags (1.15)

clusterloader2/cmd/clusterloader.go
Moving overrides parameters to prometheus flags.
Needed as we backported whole prometheus pkg.
Cherry-pick: #741
/cc wojtek-t
=> Backport: ClusterLoader - Adding prometheus flags (1.14)

clusterloader2/pkg/prometheus/experimental.go
Currently some error messages are silently ignored.
/cc wojtek-t
=> Print errors handling Prometheus disk and snapshot

clusterloader2/pkg/prometheus/manifests/dashboards/gcp-api.json
=> Add dashboard showing num of request to GCP.

clusterloader2/pkg/prometheus/manifests/dashboards/dns.dashboard.py, clusterloader2/pkg/prometheus/manifests/dashboards/dns.json, clusterloader2/pkg/prometheus/manifests/default/prometheus-serviceMonitorLegacyKubeDNS.yaml
=> Add support for kube-dns dns

clusterloader2/pkg/prometheus/manifests/dashboards/dns.dashboard.py, clusterloader2/pkg/prometheus/manifests/dashboards/dns.json, clusterloader2/pkg/prometheus/manifests/default/prometheus-serviceMonitorLegacyKubeDNS.yaml
=> Add support for kube-dns dns (1.15)

clusterloader2/pkg/prometheus/manifests/dashboards/dns.dashboard.py, clusterloader2/pkg/prometheus/manifests/dashboards/dns.json, clusterloader2/pkg/prometheus/manifests/default/prometheus-serviceMonitorLegacyKubeDNS.yaml
=> Add support for kube-dns dns (1.18)

clusterloader2/pkg/prometheus/manifests/dashboards/dns.dashboard.py, clusterloader2/pkg/prometheus/manifests/dashboards/dns.json, clusterloader2/pkg/prometheus/manifests/default/prometheus-serviceMonitorLegacyKubeDNS.yaml
=> Add support for kube-dns dns (1.16)

clusterloader2/pkg/prometheus/manifests/dashboards/dns.dashboard.py, clusterloader2/pkg/prometheus/manifests/dashboards/dns.json, clusterloader2/pkg/prometheus/manifests/default/prometheus-serviceMonitorLegacyKubeDNS.yaml
Cherry pick of #1197 to 1.17 release branch.
Should be merged after main commit
=> Add support for kube-dns dns (1.17)

clusterloader2/pkg/prometheus/manifests/dashboards/dns.dashboard.py, clusterloader2/pkg/prometheus/manifests/dashboards/dns.json, clusterloader2/pkg/prometheus/manifests/default/prometheus-serviceMonitorLegacyKubeDNS.yaml
=> Add support for kube-dns dns (1.14)

clusterloader2/pkg/measurement/common/system_pod_metrics.go, clusterloader2/pkg/measurement/common/system_pod_metrics_test.go
=> Backport: Allow changing default allowed restart count (1.17)

clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go, clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus_test.go
This requires changes done in: https://github.com/kubernetes/perf-tests/pull/1209
/hold
=> Do not fail API call latency SLO if there is less than X slow calls

clusterloader2/testing/density/config.yaml, clusterloader2/testing/load/config.yaml
Ref. https://github.com/kubernetes/perf-tests/issues/986
=> Enable allowedSlowCalls feature in density and load

clusterloader2/pkg/measurement/common/wait_for_controlled_pods.go
=> Solve the problem with faulty WaitForControllerPods

clusterloader2/pkg/measurement/common/wait_for_controlled_pods.go
This reverts commit 8f86e8eed3ee494ecacde5788b47bf91cb41447c, reversing
changes made to a01992fde748dc03235fa164ed9b981dda9c76ea.
Explanation at https://github.com/kubernetes/perf-tests/pull/1260#issuecomment-629239878
=> Revert "Merge pull request #1260 from wojtek-t/faulty_deletions"

clusterloader2/testing/density/config.yaml, clusterloader2/testing/load/config.yaml
Yesterday, I put it in the wrong place. It should be set in the gather action.
=> Enable slow-api-calls feature for real

clusterloader2/pkg/measurement/common/wait_for_controlled_pods.go
Fix #1259
/assign @mm4tt
/hold
=> attempt2: Solve the problem with faulty WaitForControlledPods

clusterloader2/pkg/measurement/common/wait_for_controlled_pods.go
=> Fix sequencing issue

clusterloader2/pkg/measurement/util/phase_latency.go, clusterloader2/pkg/measurement/util/wait_for_nodes.go, clusterloader2/pkg/measurement/util/wait_for_pods.go, clusterloader2/pkg/measurement/util/wait_for_pvcs.go, clusterloader2/pkg/measurement/util/wait_for_pvs.go, clusterloader2/pkg/util/cluster.go
This reverts commit bf383bc8887d16206bef698f04eb443c35859c33.
=> Revert "Clusterloader: change the detailed measurement logs to V(2)"

clusterloader2/pkg/measurement/common/resource_usage.go, clusterloader2/pkg/measurement/util/gatherers/container_resource_gatherer.go
=> MasterAndNonDaemons mode for resource gatherer

clusterloader2/pkg/measurement/util/gatherers/container_resource_gatherer.go
=> Fix MasterAndNonDaemons mode

clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/config/cluster.go, clusterloader2/pkg/test/simple_test_executor.go
Cherry pick of c9eee3f7e1dd11098a31b1ac2e6bca5eaa97e7f9
/cc @yuanchen8911
=> [1.18] Cherry-pick of 'Add an option delete-automanaged-namespaces to clusterloader'

perfdash/Makefile, perfdash/deployment.yaml
To release https://github.com/kubernetes/perf-tests/pull/1287
Ref https://github.com/kubernetes/perf-tests/issues/1285
=> Bump perfdash to 2.24

perfdash/Makefile, perfdash/deployment.yaml
To release https://github.com/kubernetes/perf-tests/pull/1291
Ref https://github.com/kubernetes/perf-tests/issues/1290
=> Bump perfdash version to 2.25

clusterloader2/testing/load/config.yaml
Self-explanatory PR title. Needed for Golang CI test job.
/cc mm4tt
=> Add enableViolations customization in APIResponsivenessPrometheus measurement

clusterloader2/testing/chaosmonkey/ignore_node_killer_container_restarts_100.yaml
=> a misspelling

clusterloader2/pkg/modifier/modifier.go, clusterloader2/pkg/modifier/modifier_test.go
Follow up to post-submit comments in #1308.
=> [CL2][Modifier][Overwrite] Fix 'int setting' and style issues

clusterloader2/pkg/measurement/common/scheduler_latency.go
@wojtek-t ( Re-submit the PR due to CLA issue)
=> Fix wrong condition check

clusterloader2/pkg/measurement/util/phase_latency.go
fix: https://github.com/kubernetes/perf-tests/issues/1307
Signed-off-by: Dave Chen <dave.chen@arm.com>
=> clusterloader2: Make sure the latency is not a negtive value

clusterloader2/pkg/measurement/common/resource_usage.go, clusterloader2/pkg/measurement/util/gatherers/container_resource_gatherer.go
Cherry-pick: #1277, #1281
Ref #1275
/cc @wojtek-t
=> MasterAndNonDaemons mode for resource gatherer (1.18)

clusterloader2/testing/density/2000_nodes/override.yaml, clusterloader2/testing/density/5000_nodes/override.yaml, clusterloader2/testing/density/legacy/2000_nodes/override.yaml, clusterloader2/testing/density/legacy/5000_nodes/override.yaml
Cherry-pick: #1279
Ref #1275
/cc @wojtek-t, @mborsz
=> Migrate to master and non-daemons mode (1.18)

clusterloader2/pkg/measurement/common/resource_usage.go, clusterloader2/pkg/measurement/util/gatherers/container_resource_gatherer.go
Cherry-pick: #1277, #1281
Ref #1275
/cc @wojtek-t
=> MasterAndNonDaemons mode for resource gatherer (1.16)

clusterloader2/pkg/measurement/common/resource_usage.go, clusterloader2/pkg/measurement/util/gatherers/container_resource_gatherer.go
Cherry-pick: #1277, #1281
Ref #1275
/cc @wojtek-t, @mborsz
=> MasterAndNonDaemons mode for resource gatherer (1.17)

clusterloader2/docs/oom_detection.md, clusterloader2/pkg/measurement/common/bundle/test_metrics.go, clusterloader2/pkg/measurement/common/ooms_tracker.go, clusterloader2/testing/density/config.yaml, clusterloader2/testing/load/config.yaml
Backports PR #1309.
/cc jkaniuk
/cc wojtek-t
=> Backport #1309: Add cluster OOMs tracking in clusterloader2 (1.18)

clusterloader2/testing/density/2000_nodes/override.yaml, clusterloader2/testing/density/5000_nodes/override.yaml, clusterloader2/testing/density/legacy/2000_nodes/override.yaml, clusterloader2/testing/density/legacy/5000_nodes/override.yaml
Cherry-pick: #1279
Ref #1275
/cc @wojtek-t
=> Migrate to master and non-daemons mode (1.17)

clusterloader2/testing/density/2000_nodes/override.yaml, clusterloader2/testing/density/5000_nodes/override.yaml, clusterloader2/testing/density/legacy/2000_nodes/override.yaml, clusterloader2/testing/density/legacy/5000_nodes/override.yaml
Cherry-pick: #1279
Ref #1275
/cc @wojtek-t
=> Migrate to master and non-daemons mode (1.16)

clusterloader2/docs/oom_detection.md
Documents how OOMs tracking works in Kubemark tests.
/cc jkaniuk
/cc wojtek-t
=> Add a note about Kubemark in OOMs detection doc

clusterloader2/cmd/clusterloader.go, clusterloader2/testing/load/daemonset.yaml, clusterloader2/testing/load/deployment.yaml, clusterloader2/testing/load/job.yaml, clusterloader2/testing/load/simple-deployment.yaml, clusterloader2/testing/load/statefulset.yaml
To allow load tests to bypass CNI plugin.
/cc @wojtek-t @mm4tt
=> Allow load tests to run with hostNetwork pods

clusterloader2/pkg/measurement/common/ooms_tracker.go
Current OOMs tracker's informer picks up OOMs that are not relevant during performance testing.
/cc jkaniuk
/cc wojtek-t
=> Do not track OOMs happening before test start in clusterloader2

clusterloader2/docs/oom_detection.md, clusterloader2/pkg/measurement/common/ooms_tracker.go, clusterloader2/testing/density/config.yaml, clusterloader2/testing/load/config.yaml
Backports #1348, #1346 and #1340.
/cc jkaniuk
/cc wojtek-t
=> OOM tracking: backport #1348, #1346 and #1340 (release-1.15)

clusterloader2/pkg/measurement/common/probes/manifests/dnsLookup/dns-prober-deployment.yaml, clusterloader2/pkg/measurement/common/probes/manifests/ping-client-deployment.yaml, clusterloader2/pkg/measurement/common/probes/manifests/ping-server-deployment.yaml
Backport into release-1.18 - #981
ref kubernetes/kubernetes#87143
/assign @mm4tt
/cc @tosi3k
=> Backport: probers: log to file

clusterloader2/pkg/measurement/common/simple/resource_usage.go, clusterloader2/pkg/measurement/util/gatherers/container_resource_gatherer.go
Cherry-pick: #1277, #1281
Ref #1275
/cc @wojtek-t
/cc @mm4tt
=> MasterAndNonDaemons mode for resource gatherer (1.15)

clusterloader2/testing/density/2000_nodes/override.yaml, clusterloader2/testing/density/5000_nodes/override.yaml, clusterloader2/testing/density/legacy/2000_nodes/override.yaml, clusterloader2/testing/density/legacy/5000_nodes/override.yaml
Cherry-pick: #1279
Ref #1275
/cc @wojtek-t
Wait for #1359 to be merged
/hold
=> Migrate to master and non-daemons mode (1.15)

clusterloader2/pkg/measurement/common/bundle/test_metrics.go
Fix wrong type in Errorf format
/cc @mm4tt
=> Fix wrong type in Errorf format (1.18)

clusterloader2/pkg/measurement/common/bundle/test_metrics.go
Fix wrong type in Errorf format
/cc @mm4tt
=> Fix wrong type in Errorf format (1.17)

clusterloader2/pkg/measurement/common/bundle/test_metrics.go
Fix wrong type in Errorf format
/cc @mm4tt
=> Fix wrong type in Errorf format (1.16)

clusterloader2/pkg/measurement/common/resource_usage.go, clusterloader2/pkg/measurement/util/gatherers/container_resource_gatherer.go
Adds a parameter for namespace to be used for ResourceUsageSummary measurement
=> Specify namespace in ResourceUsageSummary measurement

clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.dashboard.py, clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.json
/cc @mm4tt 
/cc @wojtek-t 
/cc @jprzychodzen
=> Add webhook addmission duration panel to Grafana

clusterloader2/pkg/measurement/common/ooms_tracker.go
Backport of #1368 to release-1.17 branch.
/cc mm4tt
=> Remove duplicate OOM event reports in OOM tracker (1.17)

clusterloader2/pkg/measurement/common/ooms_tracker.go
Backport of #1368 to release-1.15 branch.
/cc mm4tt
=> Remove duplicate OOM event reports in OOM tracker (1.15)

clusterloader2/pkg/measurement/common/ooms_tracker.go
Backport of #1368 to release-1.18 branch.
/cc mm4tt
=> Remove duplicate OOM event reports in OOM tracker (1.18)

clusterloader2/pkg/measurement/common/ooms_tracker.go
Backport of #1368 to release-1.16 branch.
/cc mm4tt
=> Remove duplicate OOM event reports in OOM tracker (1.16)

clusterloader2/testing/load/config.yaml
This PR is related to https://github.com/kubernetes/perf-tests/issues/794. The actual code changes for the wrapper measurement are in https://github.com/kubernetes/perf-tests/pull/1075 and have been merged. This PR deals mainly with the config changes.
=> Initial commit - Making wrapper measurement changes for WaitForControlledPodsRunning

clusterloader2/pkg/measurement/common/probes/manifests/dnsLookup/dns-prober-deployment.yaml, clusterloader2/pkg/measurement/common/probes/manifests/ping-client-deployment.yaml, clusterloader2/pkg/measurement/common/probes/manifests/ping-server-deployment.yaml
Backport into release-1.17 - #981
Ref kubernetes/kubernetes#87143
/cc @mm4tt
/cc @jkaniuk
=> Backport into 1.17: probers: log to file

perfdash/go.mod, perfdash/go.sum
=> Update aws-sdk-go to version v1.34.4

clusterloader2/pkg/measurement/common/scheduler_latency.go
=> cl2/scheduler_latency: add PostFilter extension point

clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go, clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus_test.go
Fix: #1406
/cc @mm4tt 
Need to test it first
/hold
=> New method of counting slow queries

clusterloader2/pkg/measurement/common/wait_for_controlled_pods.go, clusterloader2/pkg/measurement/util/wait_for_pods.go
Add countErrorMargin option to WaitForControlledPods
When using preemptibles on large scale, number of nodes do not become stable, so reaching DesiredPodCount could take a very long time.
=> Add countErrorMargin to WaitForControlledPods

clusterloader2/pkg/measurement/common/etcd_metrics.go, go.mod
add etcdHost from env instead hardcoding
Signed-off-by: zackzhangkai <zhangkaiamm@gmail.com>
=> add etcdHost

clusterloader2/testing/density/config.yaml, clusterloader2/testing/density/high-density-config.yaml, clusterloader2/testing/density/scheduler-suite.yaml, clusterloader2/testing/density/scheduler/pod-anti-affinity/deployment.yaml, clusterloader2/testing/density/scheduler/pod-anti-affinity/overrides.yaml
/cc @ahg-g @mm4tt 
/sig scheduling
(Will update with results in a bit.)
=> cl2/density: add pod-pod anti-affinity benchmarks

clusterloader2/pkg/measurement/common/probes/probes.go
Backport changes to 1.18 branch, enabling customization of probes timeout
=> [1.18][ClusterLoader2] Enable custom timeouts for probes

clusterloader2/pkg/measurement/common/probes/probes.go
Backport changes to 1.17 branch, enabling customization of probes timeout
=> [1.17][ClusterLoader2] Enable custom timeouts for probes

clusterloader2/pkg/measurement/common/probes/probes.go
Backport changes to 1.16 branch, enabling customization of probes timeout
=> [1.16][ClusterLoader2] Enable custom timeouts for probes

clusterloader2/testing/density/config.yaml, clusterloader2/testing/load/config.yaml, clusterloader2/testing/load/experimental-config.yaml
Backport commit 038d353a3bfe880fa983879592a8eb3a1eeb6df8 with configuration changes
/cc @mborsz
=> [1.18] Add configurable timeout for probes in configs

README.md
Signed-off-by: Kush Trivedi <kushthedude@gmail.com>
Fixes #1444
=> chore: remove travis ci badge

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/enhancement.md, .github/ISSUE_TEMPLATE/failing-test.md, .github/PULL_REQUEST_TEMPLATE.md
Signed-off-by: Kush Trivedi <kushthedude@gmail.com>
fixes #1455
=> feat: add github issue and pull requests templates

clusterloader2/testing/load/config.yaml
/kind cleanup
As suggested https://github.com/kubernetes/perf-tests/pull/1485#discussion_r493534124
Fixes #
```release-note
```
```docs
```
=> Rename PodStartupLatency to CreatePhasePodStartupLatency in load test

clusterloader2/testing/load/config.yaml
/kind feature
Fixes #
```release-note
```
```docs
```
=> Add density test to load test

perfdash/config.go
/kind feature
Adds SchedulingThroughput and SchedulingLatency to perf-dash for load test
Fixes #
```release-note
```
```docs
```
=> Add SchedulingThroughput and SchedulingLatency in load test to perf-dash

clusterloader2/pkg/measurement/common/slos/slo_measurement.go
Fixes #
```release-note
```
```docs
```
=> Combined SLO measurement- initial commit

perfdash/Makefile, perfdash/deployment.yaml
Fixes #
```release-note
```
```docs
```
=> Bump perfdash version to 2.28

clusterloader2/pkg/measurement/common/prometheus_measurement.go, clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go, clusterloader2/pkg/measurement/common/slos/network_programming.go, clusterloader2/pkg/measurement/common/slos/network_programming_test.go, clusterloader2/pkg/measurement/common/slos/windows_node_resource_usage.go
Currently only slos were able to use prometheusMeasurement. I next PR I want to reimplement SchedulingThroughput measurement to use prometheus metric. 
Fixes #
```release-note
```
```docs
```
=> Move prometheus measurement to common package

clusterloader2/pkg/prometheus/manifests/dashboards/__init__.py, clusterloader2/pkg/prometheus/manifests/dashboards/defaults.py, clusterloader2/pkg/prometheus/manifests/dashboards/dns.dashboard.py, clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.dashboard.py, clusterloader2/pkg/prometheus/manifests/dashboards/network.dashboard.py, clusterloader2/pkg/prometheus/manifests/dashboards/slo.dashboard.py, dns/py/data.py, dns/py/data_test.py, dns/py/ingest.py, dns/py/params.py, dns/py/params_test.py, dns/py/run_perf.py, dns/py/runner.py, dns/run, verify/boilerplate/boilerplate.py, verify/boilerplate/boilerplate.py.txt, verify/verify-flags-underscore.py
Fixes #
```release-note
```
```docs
```
=> Migrate dns benchmarks from python2 to python3 

clusterloader2/pkg/measurement/common/slos/slo_measurement.go
Fixes #
```release-note
```
```docs
```
=> Removing network programming latency from slo measurement

clusterloader2/pkg/measurement/common/scheduling_throughput_prometheus.go
Previous PR got stucked and @jprzychodzen asked me to reopen it: https://github.com/kubernetes/perf-tests/pull/1505
Fixes #
```release-note
```
```docs
```
=> Reimplement scheduling throughput to prometheus metric

clusterloader2/testing/density/config.yaml, clusterloader2/testing/density/high-density-config.yaml, clusterloader2/testing/density/scheduler-suite.yaml, clusterloader2/testing/density/scheduler/pod-affinity/deployment.yaml, clusterloader2/testing/density/scheduler/pod-affinity/overrides.yaml, clusterloader2/testing/density/scheduler/pod-anti-affinity/deployment.yaml, clusterloader2/testing/density/scheduler/pod-anti-affinity/overrides.yaml, clusterloader2/testing/density/scheduler/pod-topology-spread/deployment.yaml, clusterloader2/testing/density/scheduler/pod-topology-spread/overrides.yaml
/kind feature
**What this PR does / why we need it**: This PR cherry picks the recent scheduler-suite additions to 1.19.
Fixes #
```release-note
NONE
```
```docs
```
/cc @tosi3k
=> [cherry pick 1.19] scheduler-suite: pod-affinity, pod-anti-affinity, pod-topology-spread

clusterloader2/testing/density/config.yaml, clusterloader2/testing/density/high-density-config.yaml, clusterloader2/testing/density/scheduler-suite.yaml, clusterloader2/testing/density/scheduler/pod-affinity/deployment.yaml, clusterloader2/testing/density/scheduler/pod-affinity/overrides.yaml, clusterloader2/testing/density/scheduler/pod-anti-affinity/deployment.yaml, clusterloader2/testing/density/scheduler/pod-anti-affinity/overrides.yaml, clusterloader2/testing/density/scheduler/pod-topology-spread/deployment.yaml, clusterloader2/testing/density/scheduler/pod-topology-spread/overrides.yaml
/kind feature
**What this PR does / why we need it**: This PR cherry picks the recent scheduler-suite additions to 1.18.
Fixes #
```release-note
NONE
```
```docs
```
/cc @tosi3k
=> [cherry pick 1.18] scheduler-suite: pod-affinity, pod-anti-affinity, pod-topology-spread

clusterloader2/pkg/measurement/common/slos/slo_measurement.go, clusterloader2/testing/load/config.yaml
Fixes #
```release-note
```
```docs
```
=> Config changes to add SLOMeasurement- initial commit

clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go, clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus_test.go
Fix: #1406
Cherry-pick #1417, #1416 
/cc @wojtek-t
=> New method of counting slow queries [1.19]

clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go, clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus_test.go
Fix: #1406
Cherry-pick #1417, #1416
/cc @wojtek-t
=> New method of counting slow queries [1.18]

clusterloader2/pkg/measurement/common/slos/slo_measurement.go, clusterloader2/pkg/measurement/common/slos/slo_measurement_test.go
/kind feature
Adds support for overrides in SLOMeasurement and includes SchedulingThroughputPrometheus in SLOMeasurement.
Fixes #
```release-note
```
```docs
```
=> Add overrides and SchedulingThroughputPrometheus to SLOMeasurement

clusterloader2/testing/experimental/storage/pod-startup/config.yaml
/kind bug
Otherwise the junit.xml is not very readable.
```release-note
NONE
```
=> storage/pod-startup: name all steps

clusterloader2/pkg/measurement/common/wait_for_controlled_pods.go
Fixes #
```release-note
```
```docs
```
=> Force Delete Pods on Timeout Initial Commit

clusterloader2/testing/load/config.yaml
/kind feature
Cherry-pick: #1485 #1490 #1508 
Fixes #
```release-note
```
```docs
```
=> Density in load test backport to 1.19

clusterloader2/testing/load/config.yaml
Cherry-pick: #1485 #1490 #1508
/assign Maciej Borsz
Please review carefully, there were quite many merge conflicts
Fixes #
```release-note
```
```docs
```
=> Density in load test backport to 1.18

clusterloader2/testing/load/config.yaml
Fixing typos in density in load test
Fixes #
```release-note
```
```docs
```
=> Fix density in load

perfdash/Makefile, perfdash/config.go, perfdash/deployment.yaml
/kind feature
Adds SchedulingThroughputPrometheus measurement to perfdash
Fixes #
```release-note
```
```docs
```
=> Add SchedulingThroughputPrometheus to perfdash

clusterloader2/testing/load/configmap.yaml
Ref https://github.com/kubernetes/perf-tests/pull/1526/files#r511885934
=> Update configmap in load test for preparation to DNS tests

clusterloader2/testing/density/config.yaml, clusterloader2/testing/density/scheduler-suite.yaml, clusterloader2/testing/density/scheduler/pod-affinity/deployment.yaml, clusterloader2/testing/density/scheduler/pod-affinity/overrides.yaml, clusterloader2/testing/density/scheduler/pod-anti-affinity/deployment.yaml, clusterloader2/testing/density/scheduler/pod-anti-affinity/overrides.yaml, clusterloader2/testing/density/scheduler/pod-topology-spread/deployment.yaml, clusterloader2/testing/density/scheduler/pod-topology-spread/overrides.yaml
/kind feature
**What this PR does / why we need it**: This PR cherry picks the recent scheduler-suite additions to 1.17.
Fixes #
```release-note
NONE
```
```docs
```
/cc @tosi3k
=> [cherry pick 1.17] scheduler-suite: pod-affinity, pod-anti-affinity, pod-topology-spread

perfdash/Makefile, perfdash/config.go, perfdash/deployment.yaml
/kind bug
**What this PR does / why we need it**: `density_vanilla` items were incorrectly parsed as density.
Fixes #
```release-note
NONE
```
```docs
```
/cc @marseel who is sig/scalability oncall AFAICT
=> perfdash: parse vanilla results correctly

clusterloader2/testing/density/config.yaml, clusterloader2/testing/density/scheduler-suite.yaml, clusterloader2/testing/density/scheduler/pod-affinity/deployment.yaml, clusterloader2/testing/density/scheduler/pod-affinity/overrides.yaml, clusterloader2/testing/density/scheduler/pod-anti-affinity/deployment.yaml, clusterloader2/testing/density/scheduler/pod-anti-affinity/overrides.yaml, clusterloader2/testing/density/scheduler/pod-topology-spread/deployment.yaml, clusterloader2/testing/density/scheduler/pod-topology-spread/overrides.yaml
/kind feature
**What this PR does / why we need it**: This PR cherry picks the recent scheduler-suite additions to 1.16.
Fixes #
```release-note
NONE
```
```docs
```
/cc @tosi3k
=> [cherry pick 1.16] scheduler-suite: pod-affinity, pod-anti-affinity, pod-topology-spread

clusterloader2/testing/load/config.yaml, clusterloader2/testing/load/deployment.yaml
This will run parallel DNS lookups via 'git' commands that do not retry.
So, a DNS error will result in a 'git clone' error.
The image has been built from some prototype code in https://github.com/prameshj/dns-stress-test, specifically the simple script - https://github.com/prameshj/dns-stress-test/blob/master/git-fetch.sh
This can be enhanced to send queries at a desired QPS and also expose latency metrics.
Fixes #
```release-note
```
```docs
```
=> Run a DNS workload as part of load tests.

clusterloader2/testing/load/config.yaml
/kind feature
This PR allows us to stop test after execution of command.
Fixes #
```release-note
```
```docs
```
=> Allow to wait and exit after command execution

clusterloader2/testing/load/config.yaml
/kind cleanup
Rename variable: https://github.com/kubernetes/perf-tests/pull/1553#discussion_r516652801
Fixes #
```release-note
```
```docs
```
=> Rename WAIT_AFTER_EXEC_DURATION to SLEEP_AFTER_EXEC_DURATION in load test

clusterloader2/testing/load/config.yaml
/kind feature
Cherry-pick: #1553 #1557 to 1.18
Fixes #
```release-note
```
```docs
```
=> Backport exit after exec to 1 18

clusterloader2/testing/load/config.yaml
/kind feature
Cherry-pick: #1553  #1557 to 1.19
Fixes #
```release-note
```
```docs
```
=> Backport exit after exec to 1 19

golang/OWNERS
=> Add OWNERS file to golang subdirectory

clusterloader2/testing/load/config.yaml
/kind feature
Allows to change requests for latency pods in load test
Fixes #
```release-note
```
```docs
```
=> Parametrize latency pod cpu and memory requests in load test

clusterloader2/testing/load/config.yaml
/kind feature
Cherry-pick: #1565
Fixes #
```release-note
```
```docs
```
=> Backport cpu memory templating to 1.18

clusterloader2/testing/load/config.yaml
/kind feature
Cherry-pick: #1565 
Fixes #
```release-note
```
```docs
```
=> Backport cpu memory templating to 1.19

clusterloader2/pkg/measurement/common/resource_usage.go, clusterloader2/pkg/measurement/util/gatherers/container_resource_gatherer.go, clusterloader2/testing/access-tokens/config.yaml, clusterloader2/testing/density/config.yaml, clusterloader2/testing/density/high-density-config.yaml, clusterloader2/testing/experimental/storage/pod-startup/config.yaml, clusterloader2/testing/load/config.yaml
This will allow us to remove some overrides and thanks that simplify our test job definitions.
/assign @mborsz @jkaniuk
=> Define resource tracking mode based on cluster size

clusterloader2/testing/load/config.yaml
/kind feature
Fixes #
```release-note
```
```docs
```
=> Allow to disable APIResponsivenessPrometheusSimple violations

clusterloader2/testing/load/config.yaml
/kind feature
Cherry-picks: #1569 
Fixes #
```release-note
```
```docs
```
=> Backport to 1.18: Allow to disable APIResponsivenessPrometheusSimple violations

clusterloader2/testing/load/config.yaml
/kind feature
Cherry-picks: #1569 
Fixes #
```release-note
```
```docs
```
=> Backport to 1.19: Allow to disable APIResponsivenessPrometheusSimple violations

clusterloader2/testing/load/config.yaml
/kind cleanup
Fixes #
```release-note
```
```docs
```
=> Remove density flags in load test

clusterloader2/pkg/prometheus/manifests/0prometheus-operator-0alertmanagerCustomResourceDefinition.yaml, clusterloader2/pkg/prometheus/manifests/0prometheus-operator-0podmonitorCustomResourceDefinition.yaml, clusterloader2/pkg/prometheus/manifests/0prometheus-operator-0prometheusCustomResourceDefinition.yaml, clusterloader2/pkg/prometheus/manifests/0prometheus-operator-0prometheusruleCustomResourceDefinition.yaml, clusterloader2/pkg/prometheus/manifests/0prometheus-operator-clusterRole.yaml, clusterloader2/pkg/prometheus/manifests/0prometheus-operator-deployment.yaml, clusterloader2/pkg/prometheus/manifests/prometheus-clusterRole.yaml, clusterloader2/pkg/prometheus/manifests/prometheus-prometheus.yaml
/kind feature
Upgrades prometheus-operator to 0.31.0.
This allows us to use PodMonitor instead of ServiceMonitor.
Fixes #
```release-note
```
```docs
```
=> Upgrade prometheus-operator to 0.31.0 and improve requests/limits

clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go, clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus_test.go, clusterloader2/testing/load/config.yaml, clusterloader2/testing/load/golang/custom_api_call_thresholds.yaml
/kind feature
/kind bug
Cherry-pick: #1524 #1525 #1602
Fixes #
```release-note
```
```docs
```
=> Backport slow count improvements and fixes to 1.17

clusterloader2/OWNERS
Add jkaniuk to clusterloader2 release-1.16 OWNERS
/cc  @wojtek-t
=> Add jkaniuk to clusterloader2 release-1.16 OWNERS

clusterloader2/OWNERS
Add jkaniuk to clusterloader2 release-1.18 OWNERS
/cc @wojtek-t
=> Add jkaniuk to clusterloader2 release-1.18 OWNERS

clusterloader2/OWNERS
Add jkaniuk to clusterloader2 release-1.17 OWNERS
/cc @wojtek-t
=> Add jkaniuk to clusterloader2 release-1.17 OWNERS

clusterloader2/OWNERS
Add jkaniuk to clusterloader2 release-1.19 OWNERS
/cc @wojtek-t
=> Add jkaniuk to clusterloader2 release-1.19 OWNERS

clusterloader2/OWNERS
Add jkaniuk to clusterloader2 OWNERS
/cc @wojtek-t
=> Add jkaniuk to clusterloader2 OWNERS

clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go
/kind bug
Cherry-pick #1600 
Also, fixes slow count for events in api responsiveness prometheus
Fixes #
```release-note
```
```docs
```
=> Backport slow count fix to 1.18

clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go
/kind bug
Cherry-pick: #1600
Fixes #
```release-note
```
```docs
```
=> Backport slow count fix to 1.19

dns/py/runner.py
/kind bug
When run perf test, i faced some exception, it's likely to get kubectl stdout and parse:
```python
Traceback (most recent call last):
File "py/run_perf.py", line 119, in <module>
sys.exit(runner.go())
File "/root/yida/offical-perf/perf-tests-master/dns/py/runner.py", line 102, in go
client_pods=self._reset_client()
File "/root/yida/offical-perf/perf-tests-master/dns/py/runner.py", line 367, in _reset_client
self._create(self.dnsperf_yaml)
File "/root/yida/offical-perf/perf-tests-master/dns/py/runner.py", line 181, in _create
ret, out, err = self._kubectl(yaml.dump(yaml_obj), 'create', '-f', '-')
File "/root/yida/offical-perf/perf-tests-master/dns/py/runner.py", line 170, in _kubectl
out, err = …
```
=> Fix exception when get kube stdout

dns/py/runner.py
/kind bug
when kubectl exec dig, the dns perf client selector podname is not  correct
Fixes #
```release-note
NONE
```
```docs
```
=> When kubectl exec dig, the dns perf client selector podname is not  correct

clusterloader2/pkg/config/cluster.go, clusterloader2/pkg/prometheus/manifests/default/prometheus-podMonitorNodeLocalDNS.yaml, clusterloader2/pkg/prometheus/prometheus.go
/kind feature
Allows us to scrape metrics from NodeLocalDNS pods.
Fixes #
```release-note
```
```docs
```
=> Allow to scrape node local dns pods

clusterloader2/README.md
Adds documentation for scraping prometheus metrics
Fixes #
```release-note
```
```docs
```
=> Add documentation for scraping prometheus metrics

clusterloader2/pkg/test/simple_test_executor.go
=> CLEANUP: move preparing test namespaces to a separate method

clusterloader2/pkg/prometheus/prometheus.go
It's not clear what would be a value of the disk in case when we do not stop prometheus cleanly before taking snapshot, but hopefully this will give us at least partial data.
Without this change, we do not take snapshot of the disk when kube-apiserver is down, e.g. in https://github.com/kubernetes/kubernetes/issues/97801#issuecomment-756080299
=> Snapshot prometheus disk even if we failed to tear down prometheus

clusterloader2/pkg/measurement/common/nodelocaldns_latency_prometheus.go
This PR adds a new measurement for NodeLocalDNS latency which can be used in clusterloader tests to set the outcome correctly.
Fixes #
```release-note
None
```
```docs
```
=> Add a new prometheus measurement for dns latency

clusterloader2/pkg/measurement/common/nodelocaldns_latency_prometheus.go, clusterloader2/testing/load/config.yaml
/kind feature
/kind bug
Adds measuring of NodeLocalDNSLatency to load test.
Fixes metric name used in NodeLocalDNSLatency.
Fixes #
```release-note
```
```docs
```
=> Add node local dns latency to load test

util-images/containerd/Dockerfile, util-images/containerd/Makefile, util-images/containerd/README.md
/kind bug
Refer to https://github.com/kubernetes/perf-tests/pull/1654
Part of https://github.com/kubernetes/perf-tests/issues/1619
```release-note
NONE
```
```docs
```
=> Add containerd util image

clusterloader2/pkg/measurement/common/nodelocaldns_latency_prometheus.go
/kind bug
Fixes #
```release-note
```
```docs
```
=> Fix measuring latency of nodelocaldns

clusterloader2/pkg/imagepreload/manifests/daemonset.yaml
/kind bug
Details in https://github.com/kubernetes/perf-tests/issues/1619
Part of https://github.com/kubernetes/perf-tests/issues/1619
Retained the docker volume mount but gating logic to fallback to docker is not implemented yet. Should be doable by updating framework / image preload.
```release-note
NONE
```
```docs
```
=> Use containerd in image preloader

clusterloader2/pkg/measurement/common/nodelocaldns_latency_prometheus.go, clusterloader2/testing/load/config.yaml
/kind feature
Adds option to parametrize node local dns latency threshold in load test.
Fixes #
```release-note
```
```docs
```
=> Add latency threshold to load test for node local dns measurement

clusterloader2/pkg/measurement/util/pods_metadata.go
Signed-off-by: Guangwen Feng <fenggw-fnst@cn.fujitsu.com>
/kind cleanup
Fix golint issue caused by typo
```release-note
NONE
```
=> Fix golint issue caused by typo

clusterloader2/testing/load/config.yaml
=> Add custom thresholds param to simple APIResponsiveness measurement

golang/build-kubernetes.sh
=> Cherry-pick of #97843 and #98141 to golang job

clusterloader2/cmd/clusterloader.go
=> Enable exec service by default in clusterloader2

clusterloader2/pkg/measurement/common/wait_for_pvs.go, clusterloader2/pkg/measurement/util/object_store.go, clusterloader2/pkg/measurement/util/wait_for_pvs.go, clusterloader2/testing/experimental/storage/pod-startup/README.md, clusterloader2/testing/experimental/storage/pod-startup/config.yaml, clusterloader2/testing/experimental/storage/pod-startup/volume-types/persistentvolume/override.yaml, clusterloader2/testing/experimental/storage/pod-startup/volume-types/persistentvolume/pvc.yaml, clusterloader2/testing/experimental/storage/pod-startup/volume_binding/override.yaml, clusterloader2/testing/experimental/storage/pod-startup/volume_creation/override.yaml
/kind feature
I started using the experimental pod-startup test to measure how quickly provisioning of volumes via PVC can be done. Some tweaks to the test were necessary - see individual commit messages for details.
```release-note
NONE
```
=> PVC creation test

clusterloader2/api/types.go, clusterloader2/pkg/modifier/modifier.go, clusterloader2/pkg/modifier/modifier_test.go, clusterloader2/pkg/state/namespaces_state.go, clusterloader2/pkg/test/modules.go, clusterloader2/pkg/test/simple_test_executor.go, clusterloader2/pkg/tuningset/interface.go, clusterloader2/pkg/tuningset/simple_tuning_set_factory.go
/kind cleanup
Refactor the cl2 api to use slice of pointers to structs. See https://github.com/kubernetes/perf-tests/pull/1680#issuecomment-768128821
```release-note
NONE
```
```docs
```
=> Update CL2 api to use slice of pointers

clusterloader2/pkg/measurement/common/ooms_tracker.go
=> Fix OOM tracker in clusters with large number of events

clusterloader2/pkg/prometheus/experimental.go
Ref https://github.com/kubernetes/kubernetes/issues/98757
=> Add support for 'topology.kubernetes.io/zone' label

clusterloader2/testing/load/configmap.yaml, clusterloader2/testing/load/deployment.yaml, clusterloader2/testing/load/secret.yaml
=> Customize enabling of immutable secrets and configmaps in CL2

clusterloader2/README.md, clusterloader2/pkg/provider/constants.go, clusterloader2/pkg/provider/kind.go, clusterloader2/pkg/provider/provider.go
/kind feature
Adds a kind provider for CL2. More details here: https://github.com/kubernetes/perf-tests/issues/1693
Part of https://github.com/kubernetes/perf-tests/issues/1693
SSH to master to be tackled in a separate PR
```release-note
Support kind as a CL2 provider
```
```docs
```
=> Add CL2 kind provider

clusterloader2/pkg/provider/gce.go, clusterloader2/pkg/util/ssh.go
Fixes https://github.com/kubernetes/perf-tests/issues/1554.
Previous attempt in https://github.com/kubernetes/perf-tests/pull/1563.
=> Handle both old and new topology labels in perf-tests

clusterloader2/README.md
=> Add a README entry about the APIAvailabilityMeasurement

clusterloader2/api/types.go, clusterloader2/api/validation.go, clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/config/cluster.go, clusterloader2/pkg/config/template_provider.go, clusterloader2/pkg/config/template_provider_test.go, clusterloader2/pkg/test/interface.go, clusterloader2/pkg/test/simple_context.go, clusterloader2/pkg/test/simple_test_executor.go, clusterloader2/pkg/test/test.go
This reverts commit f2ec68631780e2c8c4ba6e114c03a068e5549af4, reversing changes made to 11eae442ad488ec5bd99ddcbb1a0123f33af43e3.
=> Revert "Merge pull request #1680 from lyzs90/extract-module-compilation"

clusterloader2/testing/load/config.yaml, clusterloader2/testing/load/simple-deployment.yaml
This is to add a way of testing the scalability of EndpointSlice objects.
=> Add huge services to load test

clusterloader2/testing/load/config.yaml, clusterloader2/testing/load/modules/services.yaml
name -> actionName
fixed typo in yaml description
/kind cleanup
/hold
Part of #1659
=> Load test - services.yaml small refactor

clusterloader2/testing/load/config.yaml
/kind feature
Sometimes admission controllers can change pods, which causes load test to wait indefinitely. This change allows us to skip comparison of created pods. 
Fixes #
```release-note
```
```docs
```
=> Add option to change checkIfPodsAreUpdated

clusterloader2/testing/load/config.yaml
/kind feature
Currently, we don't have a way to disable daemonsets in load test. skip-steps does not help in this case, because there is one step that creates all objects. 
Fixes #
```release-note
```
```docs
```
=> Allow to disable daemonsets in load test

clusterloader2/pkg/util/cluster.go
Prior this change, nodes with user-defined taints were not perceived by CL2 as schedulable and were completely excluded from `WaitForNodes` barrier. This change limits that exclusion to built-in K8s taints only.
=> Allow user-defined node taints in CL2

clusterloader2/pkg/prometheus/manifests/dashboards/dns.json, clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.dashboard.py, clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.json, clusterloader2/pkg/prometheus/manifests/dashboards/network.json, clusterloader2/pkg/prometheus/manifests/dashboards/requirements.txt, clusterloader2/pkg/prometheus/manifests/dashboards/slo.json
Also updates grafanalib to use 0.5.8 version, as it includes https://github.com/weaveworks/grafanalib/pull/182/commits/65600cedf41054526384ffe59f4f8aec41406377 as it's not possible to regenerate dashboards without it (bug).
Fixes #
```release-note
```
```docs
```
=> Add resource scope to api call latency to show anything

clusterloader2/pkg/prometheus/manifests/dashboards/dns.json, clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.dashboard.py, clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.json, clusterloader2/pkg/prometheus/manifests/dashboards/network.json, clusterloader2/pkg/prometheus/manifests/dashboards/slo.json
=> Add P&F metrics to dashboard

clusterloader2/pkg/framework/client/objects.go
/kind cleanup
`OrphanDependents` has been deprecated, we should use PropagationPolicy instead.
Fixes #
```release-note
```
```docs
```
=> Use PropagationPolicy instead of OrphanDependents

clusterloader2/pkg/prometheus/manifests/dashboards/dns.json, clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.dashboard.py, clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.json, clusterloader2/pkg/prometheus/manifests/dashboards/network.json, clusterloader2/pkg/prometheus/manifests/dashboards/slo.dashboard.py, clusterloader2/pkg/prometheus/manifests/dashboards/slo.json
/kind bug
Two graphs with "scope=resource" had actually scope set to "namespace"
Fixes #
```release-note
```
```docs
```
=> Fix resource graphs in grafana dashboards

clusterloader2/pkg/measurement/common/wait_for_controlled_pods.go
/kind bug
Right now we are dropping condition errors, however we should return them to log them properly.
=> Return error message from condition if it failed

clusterloader2/pkg/prometheus/gce_windows_util.go
/kind bug
From our Windows load tests, the prometheus wmi exporter failed sometimes due to poor ssh connection, so add retry for it.
```release-note
NONE
```
=> Add retry to install wmi exporter in case of bad ssh connection

clusterloader2/pkg/measurement/common/network/worker_pod_info.go
What type of PR is this?
/kind feature
What this PR does / why we need it:
This review is one of the changeset done as part of the enhancement/feature (Reference #1498)
This changeset contains following changes:
a) All required type definitions in separate file types.go
b) Other utility method required to choose unique pod pairs . It implemented using heap technique .
=> Adding network performance measurement testcases(Data types and utility methods)

adhoc/run-e2e-test.sh
=> Fix adhoc test job stub

clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/measurement/common/network/network_performance_measurement.go, clusterloader2/pkg/measurement/common/network/performance-measurement-helper.go, clusterloader2/pkg/measurement/common/network/types.go
/kind feature
**What this PR does / why we need it:**
This review is one of the changeset done as part of the enhancement/feature (Reference #1498)
This changeset contains following changes:
a) A new measurement for network metric performance using CRD based design approach .
b) A new custom resource "NetworkTestRequest" is introduced to store unique pod pair data and metric result
=> Adding network performance measurement testcases. (Clusterloader changes) 

clusterloader2/pkg/prometheus/manifests/0prometheus-operator-0alertmanagerConfigCustomResourceDefinition.yaml, clusterloader2/pkg/prometheus/manifests/0prometheus-operator-0podmonitorCustomResourceDefinition.yaml, clusterloader2/pkg/prometheus/manifests/0prometheus-operator-0probeCustomResourceDefinition.yaml, clusterloader2/pkg/prometheus/manifests/0prometheus-operator-0prometheusCustomResourceDefinition.yaml, clusterloader2/pkg/prometheus/manifests/0prometheus-operator-0prometheusruleCustomResourceDefinition.yaml, clusterloader2/pkg/prometheus/manifests/0prometheus-operator-0servicemonitorCustomResourceDefinition.yaml, clusterloader2/pkg/prometheus/manifests/0prometheus-operator-0thanosrulerCustomResourceDefinition.yaml, clusterloader2/pkg/prometheus/manifests/0prometheus-operator-clusterRole.yaml, clusterloader2/pkg/prometheus/manifests/0prometheus-operator-clusterRoleBinding.yaml, clusterloader2/pkg/prometheus/manifests/0prometheus-operator-deployment.yaml, clusterloader2/pkg/prometheus/manifests/0prometheus-operator-service.yaml, clusterloader2/pkg/prometheus/manifests/0prometheus-operator-serviceAccount.yaml, clusterloader2/pkg/prometheus/manifests/prometheus-prometheus.yaml
/kind cleanup
This bumps prometheus-operator to its newest version v0.46.0 and is a simplified version of #1661
=> Bump prometheus operator and prometheus

clusterloader2/pkg/measurement/common/network/network_performance_measurement.go, clusterloader2/testing/network/config.yaml, perfdash/config.go
What type of PR is this?
/kind feature
What this PR does / why we need it:
This review is one of the changeset done as part of the enhancement/feature (Reference #1498)
This changeset has PerfDash changes for displaying the results in dashboard.
=> Perfdash changes to display network performance benchmark results

clusterloader2/pkg/measurement/common/network/manifests/networktestrequests-CustomResourceDefinition.yaml, clusterloader2/pkg/measurement/common/network/manifests/networktestrequests.yaml, clusterloader2/pkg/measurement/common/network/manifests/roleBinding.yaml, clusterloader2/pkg/measurement/common/network/manifests/worker-deployment.yaml
It includes:
* CRD yaml
* Role binding yaml
* NetworkTestRequest CR template yaml
* Worker Pod deployment yaml
=> Manifest files for network performance measurement

clusterloader2/pkg/measurement/common/network/manifests/worker-deployment.yaml
/kind cleanup
Earlier the worker image was taken from a private account, the change is to pick it from gcr.io/k8s-testimages.This also contain changes for reducing the cpu utilisation limit and request from 1 to 500m.
Fixes #
```release-note
NONE
```
```docs
```
=> Update image name and cpu resources for network performance test worker image

clusterloader2/pkg/prometheus/manifests/0prometheus-operator-deployment.yaml
- Make requests = limits
- Increase memory request/limit for 500+ node clusters
=> Update prometheus-operator mem/cpu request/limits

clusterloader2/testing/load/config.yaml, clusterloader2/testing/load/modules/measurements.yaml
/kind cleanup
Move measurements config to another module.
N/A
```release-note
NONE
```
```docs
NONE
```
=> Add measurements module

clusterloader2/pkg/measurement/common/loadbalancer_nodesync_latency.go, clusterloader2/testing/l4lb/config.yaml, clusterloader2/testing/l4lb/dep.yaml, clusterloader2/testing/l4lb/service.yaml
/kind feature
Add a generic load test for L4 LBs
Fixes #
```release-note
NONE
```
```docs
```
=> add load test for L4 LB nodesync

clusterloader2/pkg/measurement/common/network/manifests/worker-deployment.yaml, util-images/network/netperfbenchmark/Makefile
/kind feature
Continuation  of #1803
I've already build image and push to repository. 
Fixes #
```release-note
```
```docs
```
=> Bump netperfbenchmark to 0.2

clusterloader2/cmd/clusterloader.go
Dump generated test config to artifacts folder.
Allows easier debugging of test configs.
/cc @wojtek-t 
/cc @mborsz
=> Dump generated test config to artifacts folder

clusterloader2/testing/load/config.yaml, clusterloader2/testing/load/modules/scheduler-throughput.yaml
/kind cleanup
Move scheduler throughput config to another module.
See #1659 for details. This change produces 0 difference in the config steps.
/assign marseel
```release-note
N/A
```
```docs
N/A
```
=> Add scheduler-throughput module

clusterloader2/testing/load/config.yaml, clusterloader2/testing/load/modules/reconcile-objects.yaml
/kind cleanup
Move reconcile config to another module.
See https://github.com/kubernetes/perf-tests/issues/1659 for details.  
This PR is originally split into 3 commits, each moving another part of `config.yaml` to `modules/reconcile-objects.yaml`. Currently there is an additional layer of control flow implemented with the use of `$is_creating`, `$is_scaling` and `$is_deleting` variables but it should be reconsidered if it's needed.
```release-note
N/A
```
```docs
N/A
```
=> Add reconcile-objects module

clusterloader2/testing/l4ilb/config.yaml
This PR makes ILB wait timeout configurable. When large number of ILBs are created, the test should wait longer for them to be processed.
Fixes #
```release-note
NONE
```
```docs
```
=> Make L4 latency measurement timeout configurable.

clusterloader2/testing/load/config.yaml, clusterloader2/testing/load/modules/huge-services.yaml, clusterloader2/testing/load/modules/scheduler-throughput.yaml
/kind cleanup
A cleanup for https://github.com/kubernetes/perf-tests/pull/1794. Moves huge services config outside of `scheduler-throughput.yaml`.
/assign mborsz
Fixes #
```release-note
NONE
```
```docs
```
=> Add huge-services module

clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go
/kind bug
Fixes https://github.com/kubernetes/perf-tests/pull/1809#discussion_r637880857
/assign mborsz
/assign tosi3k
=> Fix api responsiveness filter

clusterloader2/api/validation.go, clusterloader2/api/validation_test.go
/kind feature
This PR adds more validation to cl2 config
Part of #1746 
```release-note
NONE
```
```docs
```
=> added empty step validation

clusterloader2/testing/node-throughput/config.yaml, clusterloader2/testing/windows-tests/config.yaml
/kind bug
/kind failing-test
This PR removes deprecated automanagedNamespaces
Part Of #1696 
```release-note
NONE
```
```docs
```
=> Migrated automanaged namespaces in node-throughput and windows-test tests

clusterloader2/testing/l4ilb/config.yaml
Without this step there is non-failling error
Additionally, fix missing names.
Tested manually.
/cc @prameshj
/assing @jkaniuk
=> Add step to wait for deployments deletions

clusterloader2/OWNERS, clusterloader2/pkg/prometheus/manifests/dashboards/OWNERS, util-images/probes/OWNERS
oxddr is no longer an active contributor.
/kind cleanup
```release-note
n/a
```
=> Move oxddr under emeritus_approvers

clusterloader2/cmd/clusterloader.go
/kind cleanup
Fixes #
```release-note
"NONE"
```
```docs
```
=> spelling mistake

clusterloader2/pkg/prometheus/prometheus.go, clusterloader2/pkg/provider/aks.go, clusterloader2/pkg/provider/aws.go, clusterloader2/pkg/provider/eks.go, clusterloader2/pkg/provider/gce.go, clusterloader2/pkg/provider/gke.go, clusterloader2/pkg/provider/kind.go, clusterloader2/pkg/provider/kubemark.go, clusterloader2/pkg/provider/local.go, clusterloader2/pkg/provider/provider.go, clusterloader2/pkg/provider/skeleton.go, clusterloader2/pkg/provider/vsphere.go
Signed-off-by: JunYang <yang.jun22@zte.com.cn>
/kind feature
Migrate not-scrape-kube-proxy.yaml to provider specific config
Fixes [#1831](https://github.com/kubernetes/perf-tests/issues/1831)
```release-note
Migrate not-scrape-kube-proxy.yaml to provider specific config
```
```docs
"NONE"
```
=> Migrate not-scrape-kube-proxy.yaml to provider specific config

clusterloader2/pkg/measurement/util/kubelet/kubelet.go
/kind feature
Fixes #1789
```release-note
ClusterLoader2: Tracks kubelet and global pod resource usage
```
Track kubelet and global pod resource usage.
We had a major regression on kubelet that went unnoticed and caused a lot of disruption in the CI, with major flakes and multiple teams trying to find the root cause without success.
It seems reasonable that, each time we get the container information in one node, we obtain the kubelet and global pod resources usage, so we can compare against them, and also track the overall resource usage independently.
Current code was process the /stats/summary output to obtain the resource usage of containers. 
This structure also reports the usage of kubelet and all the pods in the `systemContainers` field, with the same type, making it very easy to …
=> get kubelet systemContainer resource metrics

clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.dashboard.py, clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.json
=> Add apiserver_request_filter_duration_seconds_bucket graph to Grafana

clusterloader2/OWNERS
Add marseel to clusterloader2 approvers
/assign @mm4tt
=> Add marseel to cl2 approvers

clusterloader2/testing/network/config.yaml
/kind cleanup
Migrates clusterloader2/testing/network/config.yaml to use namespace
Part of  #1696 
Ref PR #1825 
```release-note
NONE
```
```docs
```
=> migrated clusterloader2/testing/network/config.yaml to use namespace

clusterloader2/testing/load/modules/huge-services.yaml
/kind bug
While introducing multiple deployments for huge service, we've accidentally removed sleep measurement. This PR fixes it. Related to #1840 
Fixes #
```release-note
```
```docs
```
=> Fix sleeping after deleting huge service

perfdash/README.md
Signed-off-by: RinkiyaKeDad <arshsharma461@gmail.com>
Needed for kubernetes/k8s.io#1597
Needed for kubernetes/k8s.io#1597
```release-note
NONE
```
```docs
```
=> replacing master with main for k/k8s.io links

clusterloader2/pkg/config/cluster.go, clusterloader2/pkg/measurement/common/metrics_server_prometheus.go, clusterloader2/pkg/prometheus/manifests/exporters/metrics-server/serviceMonitor.yaml, clusterloader2/pkg/prometheus/prometheus.go, clusterloader2/testing/load/modules/measurements.yaml
Signed-off-by: JunYang <yang.jun22@zte.com.cn>
/kind feature
implement of issue: [#710](https://github.com/kubernetes-sigs/metrics-server/issues/710)
Fixes #1839
part of issue: [#710](https://github.com/kubernetes-sigs/metrics-server/issues/710)
```release-note
Add metrics-server latency measurement, Controlled by flag --prometheus-scrape-metrics-server
```
```docs
```
=> Supplementary  metrics-server latency measurement

util-images/network/netperfbenchmark/Makefile, util-images/network/netperfbenchmark/cmd/main.go, util-images/network/netperfbenchmark/pkg/worker/worker.go
/kind feature
This PR is for tuning the command parameters for TCP and UDP measurements(so that the metrics makes sense in k8s CI/CD clusters). This PR also contains changes
for making the tuning easier in future by controlling it from the workers deployment yaml file.
Fixes #
```release-note
NONE
```
```docs
```
=> Network Performance Measurement: Make parameters tunable from outside

clusterloader2/pkg/measurement/common/network/manifests/worker-deployment.yaml
/kind feature
This PR is for tuning the command parameters for UDP measurements.
Fixes #
```release-note
NONE
```
```docs
```
=> Network Performance Measurement: Tuning parameters

clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go
/kind feature
Currently, timestamp of received event was created when event was processed. Now, we add channel and before processing event with create timestamp to have better information when CL2 received event.
```release-note
```
```docs
```
=> Add channel for events to PodStartupLatency

clusterloader2/README.md, clusterloader2/docs/GETTING_STARTED.md
Added getting started section. 
Fixes #1759
```release-note
```
```docs
```
=> Add getting started tutorial

clusterloader2/pkg/measurement/util/kubelet/kubelet.go
Backport #1815 to 1.21
```release-note
NONE
```
ref https://github.com/kubernetes/perf-tests/issues/1789
=> cherrypick 1.21 "get kubelet systemContainer resource metrics"

clusterloader2/pkg/measurement/util/kubelet/kubelet.go
Backport #1815 to 1.20
```release-note
NONE
```
ref https://github.com/kubernetes/perf-tests/issues/1789
=> cherrypick to 1.20 "get kubelet systemContainer resource metrics"

clusterloader2/testing/load/config.yaml, clusterloader2/testing/load/modules/huge-services.yaml, clusterloader2/testing/load/modules/scheduler-throughput.yaml
/kind cleanup
As the tests using huge services have the flag set to `true` I believe we can use this value as default and reduce the boilerplate.
N/A
```release-note
N/A
```
```docs
N/A
```
=> Remove huge services multiple deployments flag

perfdash/Dockerfile, perfdash/Makefile, perfdash/deployment.yaml
Migrate to Docker image of perfdash to distroless base image.
Signed-off-by: Arnaud Meukam <ameukam@gmail.com>
Fixes https://github.com/kubernetes/perf-tests/issues/604
I'll advise local test before push the image.
```release-note
NONE
```
```docs
https://github.com/GoogleContainerTools/distroless
```
=> [perfdash]: Migrate Docker image to distrolesss

clusterloader2/testing/node-throughput/config.yaml
Signed-off-by: Ruquan Zhao <ruquan.zhao@arm.com>
Add one of the following kinds:
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> Add name to a test steps

clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go
/assign @mborsz @marseel @jupblb
=> Update API responsiveness SLO to exclude long-running calls

clusterloader2/testing/l4ilb/config.yaml, clusterloader2/testing/l4ilb/modules/measurements.yaml, clusterloader2/testing/l4ilb/modules/services.yaml, clusterloader2/testing/l4ilb/service.yaml
/kind feature
- Adds modules for measurements and services for L4 ILB tests.
- Modifies the existing service creation latency config.yaml test to use the added modules.
- Modifies service.yaml to receive the value for ExternalTrafficPolicy.
Fixes #
```release-note
```
```docs
```
=> Add modules for L4 ILB creation latency tests

clusterloader2/pkg/measurement/common/service_creation_latency.go
Missing lock when manipulating pingCheckers in service_creation_latency.go
What type of PR is this?
/kind bug
Add lock when manipulating pingCheckers. Without the fix, there is high possibility to hit fatal error as below
`fatal error: concurrent map writes
goroutine 18304 [running]:
runtime.throw(0x199dc53, 0x15)
/usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc00172ed48 sp=0xc00172ed18 pc=0x438bb2
runtime.mapdelete_faststr(0x18102c0, 0xc004bdc3f0, 0xc002320260, 0x1d)
/usr/local/go/src/runtime/map_faststr.go:306 +0x3de fp=0xc00172edb0 sp=0xc00172ed48 pc=0x41667e
k8s.io/perf-tests/clusterloader2/pkg/measurement/util/checker.Map.DeleteAndStop(...)
/src/k8s.io/perf-tests-1c-100w/clusterloader2/pkg/measurement/util/checker/checker_map.go:52 …
=> Add lock when calling pingCheckers's functions to guarantee consistency

clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go, clusterloader2/pkg/measurement/util/pods_metadata.go, perfdash/config.go
=> Expose stateful pod startup in perfdash

clusterloader2/pkg/execservice/manifest/exec_deployment.yaml, clusterloader2/pkg/prometheus/manifests/exporters/metrics-server/resourceConsumer.yaml
/kind cleanup
/sig testing
We're moving away from google.com gcp projects. These images are now on community-owned infra.
Related: https://github.com/kubernetes/k8s.io/issues/1522
```release-note
NONE
```
```docs
```
=> Updates E2E test images registry

clusterloader2/pkg/provider/autopilot.go, clusterloader2/pkg/provider/constants.go, clusterloader2/pkg/provider/provider.go
/kind feature
Adds support for Autopilot clusters.
Fixes #
```release-note
```
```docs
```
=> Added provider for Autopilot

clusterloader2/pkg/prometheus/manifests/dashboards/defaults.py, clusterloader2/pkg/prometheus/manifests/dashboards/dns.dashboard.py, clusterloader2/pkg/prometheus/manifests/dashboards/dns.json, clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.dashboard.py, clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.json, clusterloader2/pkg/prometheus/manifests/dashboards/network.dashboard.py, clusterloader2/pkg/prometheus/manifests/dashboards/network.json, clusterloader2/pkg/prometheus/manifests/dashboards/slo.dashboard.py, clusterloader2/pkg/prometheus/manifests/dashboards/slo.json
/kind bug
This PR fixes issues with editing Grafana targets when reviewing dashboards.
Fixes #
```release-note
N/A
```
```docs
N/A
```
=> Set datasource for Grafana targets

clusterloader2/run-e2e.sh
Allow changing clusterloader2 verbosity in `run-e2e.sh` by `CL2_VERBOSITY` flag
/cc @marseel
=> Allow changing clusterloader2 verbosity in run-e2e.sh

clusterloader2/pkg/prometheus/manifests/master-ip/master-serviceMonitor.yaml
/kind bug
This PR updates the template for the ServiceMonitor for the `master` service, to make it exclude kubelets when that is configured.
Fixes #1922
```release-note
NONE
```
```docs
```
=> Make master ServiceMonitor respect PROMETHEUS_SCRAPE_KUBELETS

clusterloader2/pkg/prometheus/experimental.go, clusterloader2/pkg/prometheus/experimental_test.go
See https://github.com/kubernetes/test-infra/pull/24352 for context
=> Implement prometheus snapshot for CSI

clusterloader2/run-e2e.sh
/kind bug
See https://github.com/kubernetes/test-infra/pull/24357#issuecomment-969060521
/cc @leiyiz
/assign @tosi3k @wojtek-t
=> Fix CSI driver for kubemark

clusterloader2/run-e2e.sh
cleanup for https://github.com/kubernetes/perf-tests/pull/1940 and installation is successful in test run of that pr.
=> fix kubemark test install pdcsi driver

clusterloader2/testing/load/modules/huge-services.yaml, clusterloader2/testing/load/service.yaml
/kind feature
Fixes #
```release-note
```
```docs
```
=> Add a CL2 parameter for creating headless huge services.

clusterloader2/go.mod, clusterloader2/pkg/measurement/common/wait_for_controlled_pods.go, clusterloader2/pkg/measurement/util/pods.go, clusterloader2/pkg/measurement/util/runtimeobjects/runtimeobjects.go, clusterloader2/pkg/measurement/util/runtimeobjects/runtimeobjects_test.go, clusterloader2/pkg/measurement/util/wait_for_pods.go
Add information why sample Pod is not considered as updated
/kind feature
=> Extend log entry for in progress WaitForControlledPodsRunning

clusterloader2/pkg/config/cluster.go, clusterloader2/pkg/prometheus/manifests/pushgateway/deployment.yaml, clusterloader2/pkg/prometheus/manifests/pushgateway/service.yaml, clusterloader2/pkg/prometheus/manifests/pushgateway/serviceMonitor.yaml, clusterloader2/pkg/prometheus/prometheus.go
With '--enable-pushgateway' ClusterLoader2 will setup Pushgateway
instance and setup Prometheus to scrape metrics from that instance.
=> Add implementaion of Pushgateway feature

clusterloader2/testing/load/modules/measurements.yaml
=> Add enableViolations parameter to ContainerRestarts measurement params

clusterloader2/testing/load/configmap.yaml, clusterloader2/testing/load/deployment.yaml
/kind feature
Use the new dnsperfgo client in dns load tests.
Fixes #
```release-note
Use a new dns client(dnsperfgo) in DNS load tests. This client does searchpath expansion, sends A/AAAA queries in parallel and exports prometheus metrics.
```
```docs
```
=> Use the new dnsperfgo client in dns load tests.

dns/dnsperfgo/README.md, dns/dnsperfgo/deployment.yaml, dns/dnsperfgo/main.go, dns/dnsperfgo/queries-cm.yaml
Clarified help text/comments, updated README.
**What this PR does / why we need it**: 
This PR adds sample yamls for deploying dnsperfgo - a DNS client for scale testing DNS server, while triggering parallel A/AAAA queries.
Fixes #
```release-note
NONE
```
```docs
```
=> Added sample yamls for deploying dnsperfgo.

clusterloader2/testing/huge-service/modules/service.yaml
/kind bug
Fix huge-service pod deletion
N/A
```release-note
NONE
```
```docs
```
=> Fix huge-service pod deletion

clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.dashboard.py, clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.json
/kind feature
This PR adds new panels to P&F grafana dashboard, extending observability of apf 
Fixes #
All 3 metrics are of type Gauge. https://kubernetes.io/docs/concepts/cluster-administration/flow-control/#metrics
no
```release-note
NONE
```
```docs
```
=> Extend P&F dashboard with additional metrics

util-images/sleep/Makefile
Bumped sleep image. Related PR: https://github.com/kubernetes/perf-tests/pull/1986
I've already pushed 0.0.2 image to gcr.
Fixes #
```release-note
NONE
```
```docs
```
=> Update sleep image to 0.0.2

golang/Makefile
=> Use community-owned GCS bucket for Golang scripts

perfdash/Makefile, perfdash/deployment.yaml
/kind cleanup
Incremented prefdash version since new changes to it where made here: https://github.com/kubernetes/perf-tests/pull/1992.
=> Incremented perfdash version

dns/dnsperfgo/main.go
nslookup does very different behavior depending on whether or not bind-tools is installed.
nslookup performs parallel A, AAAA lookups only if bind-tools is
NOT installed. Once bind-tools is installed, it sends AAAA queries only
after all A queries have been sent and unanswered.
/kind bug
Fixes #
```release-note
NONE
```
```docs
```
=> Use net.LookupHost since it is more consistent.

dns/dnsperfgo/Makefile
Cleanup of Makefile for dnsperfgo.
/kind cleanup
Fixes #
```release-note
```
```docs
```
=> Update Makefile for dnsperfgo

clusterloader2/pkg/measurement/common/resource_usage.go, clusterloader2/pkg/prometheus/prometheus.go, clusterloader2/pkg/provider/constants.go, clusterloader2/pkg/provider/gke_kubemark.go, clusterloader2/pkg/provider/provider.go
/kind feature
Adds support for GKE kubemark.
Fixes #
```release-note
```
```docs
```
=> Add gkekubemark provider

dns/dnsperfgo/Dockerfile, dns/dnsperfgo/Makefile
Dnsperfgo image should be build in isolated environment
Fixes #2001
```release-note
```
```docs
```
=> Dnsperfgo image should be build in isolated environment

clusterloader2/pkg/measurement/common/generic_query_measurement.go, clusterloader2/pkg/measurement/common/generic_query_measurement_test.go
Use case:
* I want to get container usage, breakdown by container name
Usage:
```
- Identifier: gq
Method: GenericPrometheusQuery
Params:
action: start
metricName: API request latency
metricVersion: v1
unit: ms
dimensions:
- verb
- resource
- subresource
queries:
- name: Perc99
query: histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket[%v])) by (verb, resource, subresource, le))
threshold: 60
- name: Perc90
query: histogram_quantile(0.9, sum(rate(apiserver_request_duration_seconds_bucket[%v])) by (verb, resource, subresource, le))
- name: Perc50
query: histogram_quantile(0.5, sum(rate(apiserver_request_duration_seconds_bucket[%v])) by (verb, resource, subresource, le))
threshold: 5
```
See tests for more examples.
Semantics:
* Still no more than a single value for …
=> Extend GenericPrometheusQuery to support multiple streams for single query

OWNERS
@marseel has a long history of contributions/reviews in this repository.
I support giving him a full ownership in this repo.
=> Add marseel to OWNERS

perfdash/Makefile, perfdash/test/jobs.yaml
/kind feature
Make it easier and faster to test perfdash locally.
Fixes #
```release-note
```
```docs
```
=> Add prow config with one job for faster testing of perfdash

clusterloader2/api/validation.go, clusterloader2/api/validation_test.go, clusterloader2/pkg/measurement/measurement_executor.go, clusterloader2/pkg/test/simple_test_executor.go
/kind cleanup
Removes unnecessary checks, adds validation for Measurements and unifies Measurement execute with Phase execute.
Fixes #
```release-note
```
```docs
```
=> Cleanup validation and unify execute Measurement/Phase

clusterloader2/pkg/test/interface.go, clusterloader2/pkg/test/simple_reporter.go, clusterloader2/pkg/test/simple_test_executor.go, clusterloader2/pkg/test/step_summary.go
Adds measurements/phases as separate steps for reporting - Each measurement/phase will have separate row in junit.xml, which will result in separate row in testgrid.
Depends on PR https://github.com/kubernetes/perf-tests/pull/2012
/kind feature
Fixes #
```release-note
```
```docs
```
=> Shows substeps in junit

clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.dashboard.py, clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.json
/kind feature
This PR adds apiserver_terminated_watchers_total metric to grafana.
NONE
=> Added apiserver_terminated_watchers_total metric to grafana

clusterloader2/testing/load/modules/pod-startup-latency.yaml
=> Adjust latency pods requirements

clusterloader2/pkg/test/step_summary.go
/kind bug
Fixes #
```release-note
```
```docs
```
=> Fix reporting phases in junit

clusterloader2/pkg/measurement/common/etcd_metrics.go
/kind bug
This change fixes etcd metrics collection with v3.5, where `etcd_debugging_mvcc_db_total_size_in_bytes` is replaced by
`etcd_mvcc_db_total_size_in_bytes`. See: https://etcd.io/docs/v3.4/upgrades/upgrade_3_5/#deprecated-etcd_debugging_mvcc_db_total_size_in_bytes-prometheus-metrics
Fixes #
```release-note
```
```docs
```
=> Add support for etcd mvcc metric introduced in v3.5

clusterloader2/api/types.go, clusterloader2/examples/chaos_monkey_example.yaml, clusterloader2/pkg/chaos/monkey.go, clusterloader2/pkg/chaos/nodes.go, clusterloader2/pkg/measurement/common/chaos_monkey_measurement.go, clusterloader2/pkg/test/simple_test_executor.go
Allows enabling chaos monkey only for part of the test.
=> Add chaos monkey measurement

clusterloader2/pkg/prometheus/manifests/0ssd-storage-class.yaml, clusterloader2/run-e2e.sh
/kind feature
* Adds support for Azure-Disk storageClass
part of https://github.com/kubernetes/perf-tests/issues/2035
```release-note
```
```docs
```
=> Add support for Azure Disk storageClass

clusterloader2/pkg/measurement/common/etcd_metrics.go
Right now it can fail due to sshResult.Code !=0 and we won't even know why it failed (or what sshResult.Code value was).
=> Improve logging in EtcdMetrics

clusterloader2/testing/load/daemonset.yaml, clusterloader2/testing/load/job.yaml, clusterloader2/testing/load/statefulset.yaml
=> Unify resource requests for load test

clusterloader2/testing/huge-service/modules/measurements.yaml
=> Add container restarts and OOMs measurements to huge service test

clusterloader2/pkg/provider/kind.go, clusterloader2/pkg/provider/local.go
/kind feature
The current test for metrics-server only supports gce provider, for kubernetes-sigs/metrics-server, it is tested on local or kind, so
need to add support for local and kind providers
Fixes #
```release-note
```
```docs
```
=> metrics-server test support kind and local provider

clusterloader2/pkg/prometheus/manifests/prometheus-prometheus.yaml
Reverts kubernetes/perf-tests#2076
=> Revert "Add 'do not evict' annotation to Prometheus"

clusterloader2/pkg/config/template_functions.go
/kind feature
When the project is not located in the gopath, the file path will be incorrect, causing the manifests file to fail to load.
We should not use gopath to configure the path of the files
Fixes #2058
```release-note
```
```docs
```
=> clusterloader2: Remove the file's dependency on gopath

clusterloader2/docs/DEVELOPING_MEASUREMENT.md
Tutorial about developing measurements in CL2.
Fixes #
```release-note
```
```docs
```
=> Added developing measurement tutorial

clusterloader2/docs/DEVELOPING_MEASUREMENT.md
Document the way how one can unit test their Prometheus-based measurement in Clusterloader2.
=> Add information about measurement unit testing to docs

perfdash/Makefile, perfdash/config.go, perfdash/deployment.yaml
/kind feature
Collect Windows metrics from Soak test jobs and expose them in perfdash
part of https://github.com/kubernetes/kubernetes/issues/108621
depends on https://github.com/kubernetes/perf-tests/pull/2034
Collect Windows metrics and expose them in perfdash
```release-note
```
```docs
```
=> Expose Windows metrics in perfdash

clusterloader2/pkg/measurement/common/slos/windows_node_resource_usage.go
/kind feature
Add Windows measurements for
- node storage
- open file handles
- Windows processes
- Windows network traffic
Part of https://github.com/kubernetes/kubernetes/issues/108621
=> Add Windows measurements for soak tests

perfdash/Makefile, perfdash/deployment.yaml, perfdash/gcs_metrics_bucket.go
=> [Perfdash] Add support for ADC

clusterloader2/pkg/measurement/common/generic_query_measurement.go, clusterloader2/pkg/measurement/common/generic_query_measurement_test.go, perfdash/Makefile, perfdash/config.go, perfdash/deployment.yaml, perfdash/metrics-downloader.go
=> Fix perfdash for generic Prometheus measurements

perfdash/deployment.yaml, perfdash/perfdash-service.yaml
=> Change perfdash deployment's namespace

golang/Makefile
=> Update Go compiler version in golang job scripts

clusterloader2/pkg/measurement/util/controlled_pods_indexer.go, clusterloader2/pkg/measurement/util/controlled_pods_indexer_test.go
Cherry-pick of https://github.com/kubernetes/perf-tests/pull/2117 to release-1.25 branch.
=> Fix WaitForControlledPodsRunning for deletion of deployments - release-1.25

clusterloader2/testing/access-tokens/config.yaml
/kind feature
Aligns measurement configuration for access token config with load config
NONE
=> Propagate ALLOWED_SLOW_API_CALLS to access tokens config

clusterloader2/pkg/measurement/util/controlled_pods_indexer.go, clusterloader2/pkg/measurement/util/controlled_pods_indexer_test.go
The goal is to simplify the code by reusing existing blocks: there already exists a rsIndexer that allows us to store objects along with some indexes for them (this is what is used by informers).
We can use here to avoid manual map operations.
=> Use rsIndexer instead of indexing manually

clusterloader2/pkg/measurement/util/wait_for_pods.go
/kind feature
Most of the logs dumped by CL2 are now WaitForControlledPodsRunning logs which are in many cases quite redundant.
While I'm planning to make more WaitForControlledPodsRunning instances running concurrently, the size of output will grow even more.
The point is: those logs aren't that useful as we thought: in the early days of CL2 we used the fact that they are dumped every 5s to debug some CL2/watch-related issues, but now we don't need them that much:
* We log when WaitForControlledPodsRunning starts and ends
* We log when object changes
Anyone can easily interpolate to understand the state and timeline.
Ref https://github.com/kubernetes/perf-tests/pull/2016 where this problem has been mentioned
=> WaitForPods: log only if state changes

clusterloader2/pkg/measurement/common/wait_for_controlled_pods.go
/kind cleanup
Two changes:
* Adds a comment explaining a meaning of all statuses in WaitForPods (in the next PR I would like to simplify it)
* Adds failed which means that WaitForPods has finished with some error (before it was using unknown).
=> Document WaitForPods statuses

clusterloader2/testing/huge-service/modules/service.yaml, clusterloader2/testing/load/simple-deployment.yaml
/kind bug
Upgrade huge-service after creating it (change some env var)
N/A
```release-note
NONE
```
```docs
```
=> Add huge-service upgrade

clusterloader2/pkg/measurement/common/wait_for_controlled_pods.go
/kind feature
This can be used to estimate impact of enabling CL2_WAIT_FOR_CONTROLLED_PODS_USE_EXACT_OPERATION_TIMEOUT introduced in https://github.com/kubernetes/perf-tests/pull/2128 without actually enabling it.
=> WaitForControlledPodsRunning: Print maxDuration

clusterloader2/pkg/measurement/common/api_availability_measurement.go
/kind feature
Optimizes the polling of hosts for APIAvailability metrics.
Fixes #1683
```release-note
NONE
```
```docs
```
=> Parallelize APIAvailability measurement polling

clusterloader2/pkg/measurement/util/controlled_pods_indexer.go, clusterloader2/pkg/measurement/util/controlled_pods_indexer_test.go
We don't have to count pods manually, we can try to use podIndexer for this purpose.
=> Simplify ControlledPodsIndexer

clusterloader2/testing/load/modules/pod-startup-latency.yaml
=> Pod startup: delete pods faster

clusterloader2/run-e2e.sh
So far, it wasn't possible to set up GCE PD CSI driver in CL2 without providing service account credentials to the driver's controller.
This PR adds an option to reuse Application Default Credentials if `GOOGLE_APPLICATION_CREDENTIALS` env var is not set during CL2 execution.
=> Fall back to using ADC when setting up GCE PD CSI driver in CL2

clusterloader2/pkg/prometheus/manifests/dashboards/master-comparison.json, clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.json, clusterloader2/pkg/prometheus/manifests/dashboards/master_panels.py
/kind feature
This adds two new dashboards, the number of calls made by apiserver that resulted in response code different from 200 and 99th percentile of latency of those calls. They exclude calls made to itself, with the main purpose to find calls to external apis that might have caused overall latency increase
Fixes #
```release-note
```
```docs
```
=> Add dashboards for calls made from apiserver

clusterloader2/run-e2e.sh
/kind feature
/sig windows
Add support for custom azuredisk install url. 
`AZUREDISK_CSI_DRIVER_VERSION` and `AZUREDISK_CSI_DRIVER_INSTALL_URL` are hardcored in `clusterloader2/run-e2e.sh` script
Fixes #
Changed default for AZUREDISK_CSI_DRIVER_VERSION to master.
```release-note
AZUREDISK_CSI_DRIVER_VERSION and AZUREDISK_CSI_DRIVER_INSTALL_URL environment variables can be used to override default AzureDisk Driver install URL
```
```docs
```
=> Support custom azuredisk driver install url

clusterloader2/testing/load/config.yaml
/kind feature
Allow to override default timeout for exec command in load test.
Fixes #
```release-note
NONE
```
```docs
```
=> Add option to specify timeout for exec command

clusterloader2/pkg/measurement/common/wait_for_controlled_pods.go
/kind cleanup
Follow up to https://github.com/kubernetes/perf-tests/pull/2134
After running CL2_WAIT_FOR_CONTROLLED_PODS_USE_EXACT_OPERATION_TIMEOUT experiment in oss tests and internal ones for few weeks now, it looks like it's OK to remove this completely.
=> Cleanup exact operation timeout experiment

clusterloader2/pkg/measurement/common/profile.go
This reverts commit 7457cbea0a37f01692f72321134e002d41241063.
Fixes #
```release-note
```
```docs
```
=> Revert "Update profile.go"

clusterloader2/pkg/measurement/common/profile.go
This time as a regular PR. Sorry for the misclick before.
=> Change profile frequency to 5m

clusterloader2/pkg/measurement/util/prometheus.go, clusterloader2/pkg/prometheus/clients/gcp_managed.go
=> Add more robust error handling for GMP-based Prometheus client

clusterloader2/testing/request-benchmark/cluster-role-binding.yaml, clusterloader2/testing/request-benchmark/cluster-role.yaml, clusterloader2/testing/request-benchmark/config.yaml, clusterloader2/testing/request-benchmark/configmap.yaml, clusterloader2/testing/request-benchmark/deployment.yaml, clusterloader2/testing/request-benchmark/modules/benchmark-deployment.yaml, clusterloader2/testing/request-benchmark/modules/measurements.yaml
/kind feature
Followup to https://github.com/kubernetes/perf-tests/pull/2156
N/A
In a single run the benchmark may create a number of config maps and perform GET/LIST operations on them.
=> Add request-benchmark CL2 scenario

clusterloader2/pkg/measurement/common/bundle/test_metrics.go
/kind cleanup
This PR enables mutex profiles for components other than etcd.
Fixes #
=> bundle: Add mutex profile for components other than etcd

clusterloader2/OWNERS, perfdash/OWNERS
=> Remove krzysied from OWNERS

clusterloader2/go.mod, clusterloader2/pkg/execservice/exec_service.go, clusterloader2/pkg/measurement/common/network/network_performance_measurement.go, clusterloader2/pkg/measurement/common/wait_for_controlled_pods.go, clusterloader2/pkg/measurement/common/wait_for_pods.go, clusterloader2/pkg/measurement/util/pods.go, clusterloader2/pkg/measurement/util/wait_for_pods.go
/kind feature
This PR adds summary for WaitForControlledPodsRunning with a list of failed pods to ease the debugging. 
Fixes #
=> Return summary with failed pods in WaitForControlledPodsRunning

clusterloader2/go.mod
/kind cleanup
I've added unnecessary dependency on klog in last pr
Fixes #
=> Remove unnecessary dependency on klog

perfdash/deployment.yaml
/kind cleanup
I've manually bumped perfdash memory to 20GB. This change reflects it in deployment.
Fixes #
=> Reflect manually changed memory in deployment for perfdash

clusterloader2/pkg/measurement/common/service_creation_latency.go, clusterloader2/testing/l4lb/config.yaml
/kind feature
It adds a step `waitForDeletion` in ServiceCreationLatency to wait for services to be deleted, and it can also get the time duration of deletion.
Fixes #2111
=> wait for services to be deleted

OWNERS, OWNERS_ALIASES, benchmark/OWNERS, clusterloader2/OWNERS, dns/OWNERS, perfdash/OWNERS, slo-monitor/OWNERS, util-images/probes/OWNERS
Update all OWNERS files and add tosi3k as root reviewer. 
/kind cleanup
Fixes #
=> Update all OWNERS files and add tosi3k as reviewer

clusterloader2/pkg/prometheus/manifests/dashboards/dns.json, clusterloader2/pkg/prometheus/manifests/dashboards/master-comparison.dashboard.py, clusterloader2/pkg/prometheus/manifests/dashboards/master-comparison.json, clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.dashboard.py, clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.json, clusterloader2/pkg/prometheus/manifests/dashboards/master_panels.py, clusterloader2/pkg/prometheus/manifests/dashboards/network.json, clusterloader2/pkg/prometheus/manifests/dashboards/requirements.txt, clusterloader2/pkg/prometheus/manifests/dashboards/slo.json
/kind feature
Add borrowing-related graphs. 
Fixes #
=> Add borrowing graphs to dashboard

clusterloader2/pkg/config/template_functions.go, clusterloader2/pkg/config/template_functions_test.go
/kind feature
Add RandData to template functions. This can be used for example to populate ConfigMap with random data of specified length. 
Fixes #
=> Add RandData template function

perfdash/Makefile, perfdash/config.go, perfdash/deployment.yaml
/kind feature
Adds measurements done during huge-service tests to perf-dash
=> Added parsing of huge-service messurements to pref dash

slo-monitor/Makefile, slo-monitor/go.mod, slo-monitor/go.sum
/kind cleanup
Update to go 1.19 
Fixes #
=> Update to go 1.19

clusterloader2/pkg/measurement/util/runtimeobjects/replicaswatcher.go, clusterloader2/pkg/measurement/util/runtimeobjects/runtimeobjects.go, clusterloader2/pkg/measurement/util/runtimeobjects/runtimeobjects_test.go
daemonset in load test count node error when exist taints
/kind bug
Fixes #
=> fix(clusterloader2): fix daemonset node counter

slo-monitor/Makefile, slo-monitor/go.mod
Requested from security team for golang version bump
/kind cleanup
Security fix 
The following images were discovered with go binaries.
gke.gcr.io/slo-monitor:0.15.3-gke.0@sha256:a6566735491187c15c4e5d53e638a3e7cad98629df4e2650c48ee77cf74d0d39:
slo-monitor: go1.19.6
migrate the binaries to the following patched versions: [go1.19.9 go1.20.4]
Fixes #
=> Update to go 1.20

clusterloader2/testing/watch-list/job.yaml
/kind feature
16GB = 400MB (secrets) * 16 (informers) * 2 (store: old, new) + some headroom to accommodate future growth
Fixes #
=> watch-list: define resources request and limit (mem, cpu) for the test pod

clusterloader2/testing/watch-list/config.yaml, clusterloader2/testing/watch-list/job.yaml
/kind feature
The flag controls whether to set` ENABLE_CLIENT_GO_WATCH_LIST_ALPHA` env var. 
It will allow to have two separate CI jobs (https://github.com/kubernetes/test-infra/pull/29464) for comparing results with the WatchList feature on/off.
xref: https://github.com/kubernetes/enhancements/issues/3157
Fixes #
=> API Streaming test: allow for overwrite enableWatchListFeature flag

clusterloader2/pkg/prometheus/manifests/prometheus-prometheus.yaml
/kind feature
Add an option to disable Prometheus's PVC.
=> Add option to disable pvc for prometheus

clusterloader2/pkg/measurement/common/cilium_endpoint_propagation_delay.go
Two fixes for the `CiliumEndpointPropagationDelay` measurement:
1. Query all intervals between startTime and endTime (right now it's possible to have 0 samples if `endTime.Sub(startTime) < queryInterval`
2. Check ranges independently instead of accumulating everything over time
/kind bug
=> Fix CEP propagation delay measurement

clusterloader2/testing/overrides/watch_list_off.yaml, clusterloader2/testing/watch-list/config.yaml
for watch-list-off scenario
a higher latency is expected
due to the size of the total payload
one this PR merges i'm going to open 
a new PR with an overwrite
Fixes #
=> watch-list: allow for specifying custom api latency thresholds

perfdash/Makefile, perfdash/deployment.yaml
/kind cleanup
Release new perfdash with updated config
=> Release perfdash 2.47

clusterloader2/pkg/measurement/util/runtimeobjects/runtimeobjects.go
[`gocmp.Diff`](https://godoc.corp.google.com/pkg/google3/third_party/golang/cmp/cmp#Diff) is computationally expensive which can be especially seen in CL2 when one profiles it during execution on a large scale performance test:
Fortunately, we only need its value when we fail the [WaitForControlledPodsRunning](https://github.com/kubernetes/perf-tests/blob/c356da9de198fc14e62b4a18116162d018bc29f4/clusterloader2/pkg/measurement/util/wait_for_pods.go#L82) measurement, so we can defer the error message computation until we really need.
=> Compute gocmp.Diff lazily in ClusterLoader2

clusterloader2/testing/request-benchmark/config.yaml, clusterloader2/testing/request-benchmark/configmap.yaml, clusterloader2/testing/request-benchmark/deployment.yaml, clusterloader2/testing/request-benchmark/modules/benchmark-deployment.yaml, clusterloader2/testing/request-benchmark/modules/measurements.yaml, util-images/request-benchmark/Makefile, util-images/request-benchmark/client.go, util-images/request-benchmark/main.go
/kind feature
Fixes required to test ConsistentListFromCache
=> Improve request benchmark test

clusterloader2/testing/watch-list/config.yaml, clusterloader2/testing/watch-list/job.yaml
https://github.com/kubernetes/perf-tests/issues/2287 reports unexpectedly high LIST latency for watchlist-off.
It looks like the main suspect is egress throughput. This PR reduces the amount of informers/workers to just `2`, which, in turn, reduces the amount of downloaded data, resulting in improved latency.
Fixes #
=> issue:2287: decrease the number of informers to see impact on latency

benchmark/docs/design.md
fixed broken link of testgrid dashboard in  design.md
The domain name of the testgrid dashboard was updated from k8s-testgrid.appspot.com to testgrid.k8s.io. After the update old domain now throws a 'page not found error'. So fixed the broken link of testgrid dashboard in  design.md.
This is related to an umbrella issue and fixes a task of the same:
https://github.com/kubernetes/test-infra/issues/30370
=> fixed broken link of testgrid dashboard in  design.md

clusterloader2/pkg/measurement/util/object_store_dynamic.go, clusterloader2/pkg/measurement/util/wait_for_conditions.go
The logging added lists failed objects whenever it fails.
Fixes #
=> Add more logging to the WaitForGenericK8sObjects meassurment

slo-monitor/Makefile
Update the version to reflect the latest changes, mostly https://github.com/kubernetes/perf-tests/pull/2317
Fixes #
=> Bump up version for slo-monitor

clusterloader2/pkg/provider/eks.go, clusterloader2/testing/list/README.md, clusterloader2/testing/list/clusterrole.yaml, clusterloader2/testing/list/clusterrolebinding.yaml, clusterloader2/testing/list/config.yaml, clusterloader2/testing/list/configmap.yaml, clusterloader2/testing/list/deployment.yaml, clusterloader2/testing/list/modules/list-benchmark-deployment.yaml, clusterloader2/testing/list/modules/list-benchmark.yaml, clusterloader2/testing/list/namespace.yaml, clusterloader2/testing/list/rolebinding.yaml, clusterloader2/testing/list/secret.yaml
/kind feature
/kind api-change
Provide a load test coverage to exercise list calls.
Fixes https://github.com/kubernetes/perf-tests/issues/2275
This PR requires https://github.com/kubernetes/perf-tests/pull/2258.
=> support list objects in load tests

clusterloader2/pkg/provider/aws.go, clusterloader2/pkg/provider/eks.go
Enable KubeState metrics for EKS and AWS providers. 
This is required to gather prom metrics dataset about state changes of k8s objects during the tests.
Enabling with just `PROMETHEUS_SCRAPE_KUBE_STATE_METRICS` flag doesn't work for EKS and AWS providers due to this explicit check with `AND` operation [here](https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/pkg/prometheus/prometheus.go#L266)
Fixes #
=> Enable KubeState metrics for EKS and AWS providers

clusterloader2/pkg/config/template_functions.go
/kind feature
This is necessary for generating templates that iterate over values from a dynamically provided variable.
Fixes #
=> Add a template helper function for string slices

clusterloader2/run-e2e.sh
* Allows re-runs by checking if K8s objects exist before creating them
* We only mutate temporary config, which prevents breakages for a local workflow
/kind bug
After #2258 `run-e2e` failed on re-runs on the same cluster, and was messing with local KUBECONFIG. This change ensures that we only create service account and appropriate K8s configuration if it's missing. Additionally, we are creating a temporary configuration for CL2 usage. 
=> [ClusterLoader2] run-e2e.sh improvements

slo-monitor/go.mod, slo-monitor/go.sum
/kind cleanup
Update k8s.io/kubernetes to fix CVE
Fixes #
=> Update k8s.io/kubernetes to fix CVE

slo-monitor/Makefile
/kind cleanup
Mostly for https://github.com/kubernetes/perf-tests/pull/2453
=> Bump up slo-monitor to 0.15.6

util-images/sleep/main.go
/kind feature
Supply an exit code to be used when SIGTERM is received.
This allows the image to be used for more complex scenarios such as Job retry policies.
Fixes #
=> Supply an exit code for SIGTERM

util-images/sleep/Makefile
/kind feature
Preparation for release
Fixes #
=> Increment sleep version

util-images/watch-list/main.go
/kind cleanup
The previous environment variable is being replaced in https://github.com/kubernetes/kubernetes/pull/122791
Fixes #
=> util-images/watch-list: replace `ENABLE_CLIENT_GO_WATCH_LIST_ALPHA` env var with `KUBE_FEATURE_WatchListClient`

clusterloader2/pkg/measurement/common/api_availability_measurement.go
Enable API Availability measurement for public IPs, also add a flag to enable/disable private/public IPs
/kind feature
=> [ClusterLoader2] Enable measuring API availability for public and/or private IPs

clusterloader2/pkg/measurement/common/neg_latency_measurement.go, clusterloader2/pkg/measurement/common/service_creation_latency.go, clusterloader2/testing/neg/config.yaml, clusterloader2/testing/neg/dep.yaml, clusterloader2/testing/neg/ing.yaml, clusterloader2/testing/neg/modules/ingress-measurements.yaml, clusterloader2/testing/neg/modules/measurements.yaml, clusterloader2/testing/neg/modules/services.yaml, clusterloader2/testing/neg/service.yaml
Add NEG Latency test
/kind feature
=> Add NEG Latency test

network/OWNERS
I plan to work more on scalability tests and being approver will speed up the work
=> Add aojea to network folder

clusterloader2/pkg/measurement/common/exec.go
Add support for configuring number of retries and interval between retries to exec measurement.
/kind feature
=> Add retry to exec measurement

clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/provider/constants.go, clusterloader2/pkg/provider/ks.go, clusterloader2/pkg/provider/provider.go
/kind feature
This PR adds a provider for KubeStellar (https://github.com/kubestellar/kubestellar) - a CNCF sandbox project.
Fixes #
=> New Provider: Adding a KubeStellar provider

clusterloader2/api/types.go, clusterloader2/api/validation.go, clusterloader2/api/validation_test.go, clusterloader2/pkg/tuningset/poisson_load.go, clusterloader2/pkg/tuningset/simple_tuning_set_factory.go
/kind feature
This PR adds a Poisson tuningSet - it will allow to generate load using a Poisson distribution 
Fixes #
=> New Tuning Set: Adding a Poisson tuning set

clusterloader2/README.md
Cleans up some grammar and inconsistencies in `clusterloader2/README.md` to make it easier for new contributors to understand.
Fixes #
=> Grammar fixes for the CL2 README.md

perfdash/Dockerfile, perfdash/Makefile, perfdash/deployment.yaml, perfdash/perfdash.go
/kind feature
/kind bug
Add an option to change the synchronization interval.
Also, fixes build regressions from #2734
=> Add option to tune sync interval

clusterloader2/testing/watch-list/config.yaml, clusterloader2/testing/watch-list/job.yaml
Doesn't resolve the latency issue from https://github.com/kubernetes/perf-tests/issues/2287 but will give me data I need for the blog post.
Fixes #
=> watchlist: bring the initial informers count back

perfdash/Makefile, perfdash/deployment.yaml
=> Release new version of perfdash

dns/jsonify/go.mod, dns/jsonify/go.sum
Ref https://github.com/kubernetes/perf-tests/pull/2973
/cc @mboersma
=> Bump kubernetes dependency in jsonify

perfdash/Makefile, perfdash/config.go, perfdash/deployment.yaml
/kind feature
Let's add request count to watchlist tests as well. 
Additionally switch local testing of perfdash from using githubConfig to local config.
=> Add request count to watchlist tests

clusterloader2/pkg/measurement/common/metrics/metrics_grabber.go, clusterloader2/pkg/provider/autopilot.go, clusterloader2/pkg/provider/aws.go, clusterloader2/pkg/provider/eks.go, clusterloader2/pkg/provider/gce.go, clusterloader2/pkg/provider/gke.go, clusterloader2/pkg/provider/gke_kubemark.go, clusterloader2/pkg/provider/kubemark.go, clusterloader2/pkg/provider/local.go, clusterloader2/pkg/provider/skeleton.go, clusterloader2/pkg/provider/util.go, clusterloader2/pkg/provider/vsphere.go, clusterloader2/pkg/util/ssh_core.go
Ref https://github.com/kubernetes/perf-tests/pull/3050#discussion_r1884019995
=> Remove dependency on kubernetes test/e2e in clusterloader2

verify/test.sh
=> Remove test exclusions

perfdash/config.go
=> Add support for DNSPropagation measurement to perfdash

clusterloader2/testing/list/README.md
Note the provided resource requirements assume improvements from https://github.com/kubernetes/perf-tests/pull/3162
=> Add instructions to run list benchmark locally

clusterloader2/testing/list/config.yaml, clusterloader2/testing/list/deployment.yaml, clusterloader2/testing/list/modules/list-benchmark.yaml
=> Implement passing content-type in list benchmark

util-images/request-benchmark/main.go
/kind bug
/assign @mborsz @jprzychodzen
=> Fix passing accept header

util-images/request-benchmark/Makefile
/kind feature
To rollout changes
=> Increase request-benchmark version to 0.0.9

clusterloader2/pkg/prometheus/manifests/default/prometheus-serviceMonitorCoreDNS.yaml, clusterloader2/pkg/prometheus/manifests/default/prometheus-serviceMonitorKubelet.yaml, clusterloader2/pkg/prometheus/manifests/default/prometheus-serviceMonitorLegacyKubeDNS.yaml, clusterloader2/pkg/prometheus/manifests/master-ip/master-serviceMonitor.yaml, clusterloader2/pkg/prometheus/prometheus.go
Reverts kubernetes/perf-tests#3214
Reverting: merging this PR broke https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-scalability-100
=> Revert "Remove usage of system:anonymous from ClusterRoleBinding used to scra…"

benchmark/go.mod, clusterloader2/go.mod, dns/dnsperfgo/go.mod, dns/jsonify/go.mod, network/benchmarks/netperf/go.mod, network/tools/network-policy-enforcement-latency/go.mod, perfdash/go.mod, slo-monitor/go.mod, util-images/access-tokens/go.mod, util-images/network/netperfbenchmark/go.mod, util-images/probes/go.mod, util-images/request-benchmark/go.mod, util-images/watch-list/go.mod
=> Bump golang version to 1.24.1

clusterloader2/pkg/prometheus/prometheus.go
Make Prometheus secret creation idempotent. Currently it causes tests fail when run multiple times against same cluster.. https://github.com/kubernetes/perf-tests/issues/3301
Recent changes in https://github.com/kubernetes/perf-tests/pull/3240 have made Prometheus stack creation non-idempotent. This results in failures for tests rerun against the same cluster.
The changes introduced in this PR verify the existence of the Prometheus secret and, depending on whether it exists, take the appropriate action of updating or creating it.
Fixes #3301
=> Make Prometheus secret creation idempotent

clusterloader2/testing/neg/config.yaml
fixes: https://github.com/kubernetes/perf-tests/pull/2981
/kind bug
Fix for compilation error message:
```
Test compilation failed: [config reading error: parsing error: template: :5: unrecognized character in action: U+201C '“']
```
=> fix: neg-latency quotes typo on waitAfterDelete

golang/build-kubernetes.sh
In https://github.com/kubernetes/kubernetes/pull/132197 we added support for `gimme` to pick up the tip of golang master to build things in the kubernetes harness. Let's reuse that instead of trying to build kube-cross from scratch!
Trying to fix https://github.com/kubernetes/test-infra/issues/34918
/kind cleanup
Fixes #
=> Avoid building kube-cross (inject `.go-version` instead)

golang/build-kubernetes.sh
The previous change to build golang tip worked fine
```
+++ [0610 18:20:41] Running build command...
go version go1.25-devel_fb0c27c514 Tue Jun 10 11:18:22 2025 -0700 linux/amd64
```
But the job failed with [log](https://storage.googleapis.com/kubernetes-ci-logs/logs/ci-build-and-push-k8s-at-golang-tip/1932502415790051328/build-log.txt)
```
push-build.sh: BEGIN main on ecc4b375-9f2c-439f-9862-a772b7ed8124 Tue Jun 10 18:26:34 UTC 2025
Refusing to push dirty build with --ci flag given.
CI builds should always be performed from clean commits.
version output:
v1.34.0-alpha.0.984+447efd4c0f45f1-dirty
push-build.sh: DONE main on ecc4b375-9f2c-439f-9862-a772b7ed8124 Tue Jun 10 18:26:34 UTC 2025 in 0s
```
So let's create a dummy commit with the edited `.go-version` file
/kind cleanup
Fixes #
=> Create a temp commit for the .go-version edit

OWNERS_ALIASES
Add @mengqiy to perf-tests OWNERS per https://github.com/kubernetes/community/pull/8343
=> add mengqiy to OWNERS

clusterloader2/testing/dra/config.yaml
Based on the job run here: https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-e2e-azure-dra-with-workload-scalability/1935231328828002304, with the 100 node cluster, the time taken for pods to start in churn phase seems to be longer.
This PR is needed to test run to completion
Fixes #
=> update thresholds for dra test Churn phase

clusterloader2/pkg/measurement/common/prometheus_scheduler_latency.go, clusterloader2/testing/dra/README.md, clusterloader2/testing/dra/config.yaml
This PR implements a PrometheusSchedulingMetrics measurement that collects the
scheduling numbers using prometheus rather then querying scheduler pod via apiserver
This is needed for getting numbers from the DRA job
Part of fixes for: #https://github.com/kubernetes/kubernetes/issues/131198
=> implement a PrometheusSchedulingMetrics Measurement and Gatherer

clusterloader2/pkg/dependency/dra/dra.go
/kind cleanup
1. gke-100-node test has run into a test failure where pods were created before resource slices were available in the scheduler.
1. This led to scheduler publishing logs where it could not find node for the pod for 3 seconds
1. With this PR, the test waits for the setup to assert resource slices are available before declaring the dependency ready
Fixes #
=> dra dependency: wait for resourceslice to be published

util-images/Makefile, util-images/access-tokens/Makefile, util-images/cloudbuild.yaml, util-images/containerd/Makefile, util-images/probes/Makefile, util-images/request-benchmark/Makefile, util-images/scratch/Makefile, util-images/sleep/Makefile, util-images/watch-list/Makefile
/kind cleanup
Fixes https://github.com/kubernetes/perf-tests/issues/3376
=> Add cloud build
