kubernetes/perf-tests

network/benchmarks/netperf/nptest/nptest.go
=> netperf: MSS is not passed to iperf3

.travis.yml
Ref #49 #50 
Following instruction here: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received.
This should make travis print something to stdout once every minute to ensure longer run.
cc @gmarek @wojtek-t
=> Add travis wait to 'go build' command for avoiding timeout

clusterloader/run-e2e.sh
Matches the CI filename, just build and run cluster loader.
The `/config/test.yaml` is not very useful. I will either edit this PR with the new config or have another one that follows shortly.
The run command assumes that k8s has the unencrypted port open (8080) as well as the kubeconfig at the default location of `~/.kube/config`
Nothing is parameterized at this point.
=> Basic compile & run script

benchmark/Makefile, benchmark/runner.sh
Seems like docker image for running the tool is not needed. All we need is a runner for dockerized compilation and then running the binary with the right args.
This seems to be the pattern for running simple binaries in CI jobs, where anyway the running of bootstrap.py is dockerized. (Eg: Job ci-cadvisor-node-kubelet (https://github.com/kubernetes/test-infra/blob/master/jobs/config.json#L10) simply calls the runner script in the cadvisor repo (https://github.com/google/cadvisor/blob/master/build/jenkins_e2e.sh))
cc @wojtek-t @gmarek
=> Replace dockerization logic for benchmark with a runner script instead

clusterloader/cluster_loader.go, clusterloader/config/logger.yaml, clusterloader/config/rctest.yaml, clusterloader/config/test.yaml, clusterloader/framework/context.go, clusterloader/framework/pod_utils.go, clusterloader/framework/rc_utils.go, clusterloader/framework/tuning_utils.go, clusterloader/framework/util.go
PR to add some of the functionality as per our design discussions a few weeks ago.
First of all, there is now a tuningset to support a delay between creation of each new defined project.
We also support creation of RCs and modification of RCs. To do this we had to be able to recognize existing namespaces, as well as existing RCs, so there's less blind creation going on now. The generic side effect is that we can now define different "projects" with the same name and then have different objects deployed in each.
The RC makes use of the image field which was not utilized for pod definitions. 
Labels have also been exposed to the config so the user can now set their own.
=> RCs added, resize working, labels exposed

benchmark/cmd/benchmark.go, benchmark/pkg/comparer/schemes/avgtest.go, benchmark/pkg/util/util.go
The results printed by the tool would now be split by latency percentiles (50, 90, 99), and sorted by the avg ratio within each of those individual tables.
cc @wojtek-t
=> Benchmark tool prints results in a classified and sorted way

benchmark/cmd/benchmark.go, benchmark/pkg/comparer/comparer.go, benchmark/pkg/comparer/schemes/avgtest.go, benchmark/pkg/comparer/schemes/avgtest_test.go, benchmark/pkg/comparer/schemes/kstest.go, benchmark/pkg/comparer/schemes/kstest_test.go, benchmark/pkg/util/util.go, verify/verify-flags/known-flags.txt
And also NaN avg ratios are marked as matched.
/cc @gmarek
=> Benchmark marks metrics with too low avg values as matched & prints some more useful info

slo-monitor/Dockerfile, slo-monitor/Makefile
I believe this fixes CVE-2016-9841 and CVE-2016-9843 present in the existing slo-monitor images (0.9.1 and 0.9.2).
Images have not yet been pushed anywhere.
@gmarek
=> Create slo-monitor:0.9.3 based on alpine:3.6

benchmark/cmd/benchmark.go
We're catching too much noise with 20ms.
IMO 50ms should be good enough to spot 'real' differences.
=> Increase benchmark metric consideration threshold to 50ms

slo-monitor/src/monitors/util.go, slo-monitor/src/monitors/watcher.go
I was looking at the [Go Report Card](https://goreportcard.com/report/github.com/kubernetes/perf-tests) for the project and noticed it caught two misspellings. This PR just fixes those spelling errors so the Report Card will be 100% free of misspellings… nothing fancy.
=> Fix misspell warnings in Go Report Card

network/benchmarks/netperf/Dockerfile
Fixes #73 
Updated Dockerfile to reflect new location and added the rename command because they new archive untar's to netperf-netperf-2.7.0 in order to maintain further logic.
=> PR: Network test cannot resolve host ftp.netperf.org

benchmark/Godeps/Godeps.json, benchmark/pkg/util/util.go, benchmark/pkg/util/util_test.go, benchmark/vendor/k8s.io/kubernetes/test/e2e/perftype/BUILD
Following up changes in https://github.com/kubernetes/kubernetes/pull/52237
cc @kubernetes/sig-scalability-misc @porridge
=> Update benchmark tool with new 'Scope' field in API call metric

network/benchmarks/netperf/README.md, network/benchmarks/netperf/launch.go
Currently the `netperfImage` is hardcoded into the code. This PR allows to use a different Docker image (e.g. self build with the provided Docker image). Otherwise you can't run the network perf-test if you only have a private registry with a different Docker image name.
=> Allow to set different docker image

dns/image/Dockerfile.build, dns/image/Dockerfile.image
There was a missing library, the `libxml2-dev` on the build and `libcrypto1.0` on the final image. I have also changed a little bit the apk command.
How to replicate the issue ?
```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty
$ git clone git@github.com:kubernetes/perf-tests.git
$ cd dns/image/
$ make
[some lines omitted]
docker run --rm -v `pwd`/build/src:/src kube-dns-perf-client-build \
/bin/sh -c "cd /src && ./configure && make -j"
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we …
```
=> Fixing dnsperf build

run-e2e.sh
Similar to cluster loader, this allows netperf and DNS tests as well to run from kubetest e2e framework.
Once this PR gets merged, we will create a PR in test-infra repo as well.
=> Allowing ClusterLoader,Network and DNS Tests to run from kubetest 

perfdash/Makefile, perfdash/deployment.yaml, perfdash/www/script.js
Adding empty objects  as a placeholders to data series. Due to this change, perfdash will match values to corresponding builds correctly.
=> Perfdash empty entries

network/benchmarks/netperf/Makefile
nptest needs to be build for Linux (and potentially cross-compiled).
Fixes #105
=> Adapt netperf Makefile to support MacOS

verify/boilerplate/boilerplate.py
Changing the way of handling years by the boilerplate script. Script will accept years from 2014 till now.
=> Updating boilerplate script

verify/verify-golint.sh
Removing go version check - everyone uses 1.5+ version as default.
=> Fixing verify_golint.sh for go1.10+ versions

perfdash/Makefile, perfdash/deployment.yaml, perfdash/downloader.go, perfdash/perfdash.go, perfdash/www/script.js
Instead of getting all available data for every possible <job x test>, only requested data (for one selected <job x test>) will be retrieved.
ref #137
=> Perfdash: requesting builds data on demand

perfdash/OWNERS
To avoid mis-assignment of reviewers for PRs.
/cc @krzysied
=> Update OWNERS for perf-dash

clusterloader2/api/types.go
Adding new fields to Measurement API:
- Identifier - is a identifier within method scope.
Pair <Method, Identifier> makes measurement unique at global scope. The new field is needed due to possible having multiple measurements  instances that uses the same measurement method.
- Params - map of <name, value>. Optional additional method parameters. Allows measurements to be more generic.
=> ClusterLoader - Updating measurement api

clusterloader2/pkg/util/util.go
Adding functions for retrieving variables from map[string]interface{} that is used for measurement params.
This will be commonly used by measurement implementation due to map[string]interface{}  being  part of measurement interface.
=> ClusterLoader - Adding measurement util

run-e2e.sh
Added flags to invoke clusterloader, netperf and DNS separately from Kubetest (e2e framework).
=> Adding Flags to run ClusterLoader, Netperf and DNS

clusterloader2/api/types.go, clusterloader2/cmd/clusterloader.go, clusterloader2/testing/density/config.yaml
In future there will be added option to run multiple tests in single clusterloader execution. Cause files will be created (for example: measurement summaries) for every test, there is a need to include test name in file name to prevent name collisions.
=> ClusterLoader - Adding test name to config

clusterloader2/pkg/measurement/common/api_responsiveness.go, clusterloader2/testing/density/config.yaml, clusterloader2/testing/load/config.yaml
Changing metric to have exactly the same name and the same layout as original one.
Needed due to backward compatibility.
=> ClusterLoader - Api responsiveness fix

clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/config/codec.go, clusterloader2/pkg/framework/client/objects.go, clusterloader2/pkg/framework/framework.go, clusterloader2/pkg/test/simple_test_executor.go
Allowing `--testconfig` flag to be used multiple times.
Test will wait until resources are cleaned up.
=> ClusterLoader - Allowing multiple tests

clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/config/cluster.go, clusterloader2/pkg/config/codec.go, clusterloader2/pkg/config/template_provider.go, clusterloader2/pkg/test/test.go
Test configs will support templating. Nodes placeholder and template functions will available for test configs.
`nodes` must be provided!
=> ClusterLoader - Adding templating to test configs

verify/install-verify-tools.sh
Changing github.com/golang/lint/golint to golang.org/x/lint/golint.
That's the proper way of installation according to https://github.com/golang/lint
Removing version check - we always use 1.5+ version.
=> Updating golint

clusterloader2/pkg/measurement/util/resource.go
Copied from:
- k8s.io/kubernetes/test/e2e/framework/kubelet_stats.go
- ContainerResourceUsage
- ResourceUsagePerContainer
- UsageDataPerContainer
- k8s.io/kubernetes/test/e2e/framework/resource_usage_gatherer.go
- all other structs and funcs.
=> ClusterLoader - Adding resource data types

verify/verify-gofmt.sh
Removing go version check from verify-gofmt.sh. Go version checks have been already removed from all other verify scripts.
=> Verify gofmt fix

clusterloader2/api/types.go, clusterloader2/pkg/tuningset/randomized_time_limited.go, clusterloader2/pkg/tuningset/simple_tuning_set_factory.go, clusterloader2/pkg/tuningset/time_limited.go
Two new tuning sets added:
- TimeLimitedLoad
Spreads action evenly over given time.
- RandomizedTimeLimitedLoad
Runs each action at random point of time (within given time limit).
=> ClusterLoader - Adding time limited tuning sets

clusterloader2/pkg/state/namespaces_state.go, clusterloader2/pkg/state/resource_state.go, clusterloader2/pkg/state/state.go, clusterloader2/pkg/test/interface.go, clusterloader2/pkg/test/simple_context.go, clusterloader2/pkg/test/simple_test_executor.go, clusterloader2/pkg/test/test.go
- Adding resources versions state
This is a map {apiVersion, Kind} -> {resourceVersion}
File `pkg/state/resource_state.go`.
- Adding state that contains both namespaces state (previous state) and resources versions state
Files: `pkg/state/state.go`, `pkg/state/namespaces_state.go`.
- Applying changes
Files: all not listed above.
=> ClusterLoader - Adding resources versions state

perfdash/Makefile, perfdash/deployment.yaml, perfdash/www/script.js
This is a handling for:
1. Requesting metric X
2. Requesting metric Y
3. Getting response Y. Drawing chart for Y.
4. Getting response X (due to X taking longer than Y). Drawing chart for X.
Point 4. is wrong. It should just omit the stale response.
=> Perfdash - Dropping old callbacks

clusterloader2/pkg/measurement/common/wait_for_controlled_pods.go, clusterloader2/pkg/measurement/util/runtimeobjects/runtimeobjects.go, clusterloader2/testing/load/config.yaml
Reimplementing wait for controlled pods measurement. Now it support two actions:
- start - starts to observe the controlling objects.
- gather - waits for objects to have all pods running.
- stop - stops the observation.
Minor changes:
- parallel group that limits number of routines running in parallel added.
- `waitForPods` has stop channel. Timeouts should be handled by the caller.
=> ClusterLoader - Reimplementing wait for controlled pods measurement

clusterloader/framework/util.go, clusterloader2/pkg/measurement/util/perftype.go, clusterloader2/pkg/state/namespaces_state.go, slo-monitor/src/monitors/pod_monitor.go
Fix some typos in the below files:
1. clusterloader/framework/util.go
2. clusterloader2/pkg/measurement/util/perftype.go
3. clusterloader2/pkg/state/namespaces_state.go
4. slo-monitor/src/monitors/pod_monitor.go
=> Fix some typos

clusterloader2/pkg/measurement/common/api_responsiveness.go, clusterloader2/pkg/measurement/errors.go
Failing tests when api responsiveness metric is not satisfy.
=> ClusterLoader - Adding metric violation error

clusterloader2/pkg/measurement/common/bundle/test_metrics.go
Setting `ClusterConfig` in test metric bundle, which is required by the metrics.
=> ClusterLoader - Fixing test metrics bundle

clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go, clusterloader2/pkg/measurement/util/latency_metric.go
Added:
- failing when podStartupLatencyThreshold(5s) is not satisfied.
- logging pod latencies.
ref #293
=> ClusterLoader - Updating pod startup measurement logs

slo-monitor/Makefile, slo-monitor/slo-monitor-deployment.yaml, slo-monitor/slo-monitor-pod.yaml
Changes in this version: new distribution bucket boundaries for the pod startup metrics.
=> Increment version number for slo-monitor.

clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/errors/error_list.go, clusterloader2/pkg/errors/metric_violation_error.go, clusterloader2/pkg/framework/framework.go, clusterloader2/pkg/measurement/common/bundle/test_metrics.go, clusterloader2/pkg/measurement/common/slos/api_responsiveness.go, clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go, clusterloader2/pkg/test/interface.go, clusterloader2/pkg/test/simple_test_executor.go, clusterloader2/pkg/test/test.go
Moving:
- `pkg/util/error_list.go` → `pkg/errors/error_list.go`
- `pkg/measurement/errors.go` → `pkg/errors/metric_violation_error.go`
=> ClusterLoader - Moving errors to pkg/errors

clusterloader2/cmd/clusterloader.go
Tests will continue if there are only metric violation errors.
=> ClusterLoader - handling SLOs fails

dns/README.md, dns/run, run-e2e.sh
- dns/run takes care of running benchmark. It runs tests, creates required directories and creates metrics.
- run-e2e.sh only calls dns/run
=> Updating dns benchmark run script

dns/run
Adding numpy installation to run script, due to numpy being required by `py/run_perf.py`. This command installs numpy or does nothing is numpy s already available.
=> Dns benchmark - Adding numpy installation to run script

clusterloader2/testing/density/2000_nodes/override.yaml, clusterloader2/testing/density/config.yaml, clusterloader2/testing/load/config.yaml
Resource usage will be gather from master and dns only.
=> ClusterLoader - Overriding resource usage gathering for 2000 nodes test

clusterloader2/testing/density/100_nodes/constraints.yaml
- apiserver cpu: 1.7 -> 1.9
- scheduler cpu: 0.25 -> 0.35
ref https://github.com/kubernetes/kubernetes/issues/72016
=> ClusterLoader - Updating 100 nodes density constraints

clusterloader2/testing/density/rc.yaml, clusterloader2/testing/load/rc.yaml
This way, if node goes down (e.g. due to hostError), the test won't fail.
=> Add not-ready/unreachable node tolerations ot density/load rcs.

clusterloader2/api/types.go
The idea is to add clusterloader-level feature to simulate node failures (NodeKiller in old framework). In future we may want to extend this to master component failures, pod failures and other.
=> Add API to configure node killing in clusterloader2.

clusterloader2/pkg/measurement/common/simple/wait_for_controlled_pods.go, clusterloader2/pkg/measurement/common/simple/wait_for_pods.go
- Waiting for pods.
Measurement will wait until desired pods are running and there are no others pods that match given labels and namespace (regardless their statuses).
- Waiting for controlled pod.
Handling of object deletion changed to waiting for pods with desired replicas equaling 0.
=> ClusterLoader - Fixing RC deletion handling

clusterloader2/pkg/chaos/monkey.go, clusterloader2/pkg/chaos/nodes.go, clusterloader2/pkg/test/interface.go, clusterloader2/pkg/test/simple_context.go, clusterloader2/pkg/test/simple_test_executor.go, clusterloader2/pkg/util/cluster.go
This is basically copy-paste of https://github.com/kubernetes/kubernetes/pull/71320.
In the next step, once we migrate -killer job to clusterloader2, I will remove NodeKiller from kubernetes/kubernetes repo to remove code duplication.
=> Migrate NodeKiller to clusterloader2.

clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/config/cluster.go, clusterloader2/pkg/config/template_provider.go, clusterloader2/testing/chaosmonkey/override.yaml, clusterloader2/testing/density/config.yaml, clusterloader2/testing/load/config.yaml
Chaos monkey is disabled by default, but can be enabled by adding --testoverrides=testing/chaosmonkey/override.yaml.
=> Add a way to optionally enable chaos monkey in tests.

clusterloader2/pkg/chaos/monkey.go
Right now it blocks the main goroutine :|
=> Bug in chaos.Monkey: add missing go in m.nodeKiller.Run() call.

clusterloader2/pkg/measurement/common/simple/wait_for_controlled_pods.go
Those are redundant with what is already written from wait_for_pods.
=> Reduce amount of unuseful logs

perfdash/Makefile, perfdash/config.go, perfdash/deployment.yaml
The path changes in #353 from PodStartupLatency to PodStartupLatency_PodStartupLatency and a new metric PodStartupLatency_SaturationPodStartupLatency is added.
=> Change perfdash to look for PodStartupLatency metrics in new place.

clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go, clusterloader2/pkg/measurement/interface.go, clusterloader2/pkg/measurement/manager.go, clusterloader2/pkg/measurement/util/latency_metric.go, clusterloader2/testing/density/config.yaml, clusterloader2/testing/load/config.yaml
As operationTimeout for WaitForRunningSaturationRCs was dynamically computed, I changed hard deadline to 15m and moved logic to compare perc99 in SaturationPodStartupLatency.
=> Change operationTimeout to 15m in scalability tests

clusterloader2/testing/density/100_nodes/constraints.yaml
Bumping up density test resources:
- apiserver cpu 1.9 -> 2.0
- scheduler memory 100MB -> 110MB
=> ClusterLoader - Bumping up test resources

dns/run, perfdash/Makefile, perfdash/config.go, perfdash/deployment.yaml
Renaming benchmark files to be more generic.
Will allow easier job creation + perfdash setup.
=> Dns benchmark files rename

clusterloader2/testing/density/100_nodes/constraints.yaml
Right now the test is using approx. ~980M so we are way too close to the limit (and we are hitting the limit in -killer job).
=> Change apiserver's memory limit to 1200M.

clusterloader2/testing/load/config.yaml, clusterloader2/testing/load/rc.yaml, clusterloader2/testing/load/service.yaml
Changing logic of the test to:
1. Create 1 SVC per every 2 RCs (that will be created).
2. Create RCs. 
3. Scale RCs
4. Delete RCs
5. Delete SVCs
=> ClusterLoader - Changing to 1 svc per 2 rcs

clusterloader2/testing/density/100_nodes/constraints.yaml
- apiserver cpu 2.0 -> 2.2
- controller manager cpu 0.9 -> 1.1
=> ClusterLoader - Updating density 100 nodes constraints

clusterloader2/testing/load/config.yaml
Changing replicas random range to match original tests: https://github.com/kubernetes/kubernetes/blob/49891cc270019245a3d4796e84b33bf36d0bae08/test/e2e/scalability/load.go#L674
ref #371 
Should reduce pod post calls.
=> ClusterLoader - Changing to original load RC randimized range

clusterloader2/cmd/clusterloader.go
MkDirAll is an equivalent of mkdir -p command, it creates all necessary parent directories if needed.
=> Use os.MkdirAll instead of os.MkDir when creating report dir

clusterloader2/testing/load/rc.yaml
This change will make only half of pods to use SVCs. Same as in original load test.
ref #371
=> ClusterLoader - Making every second RC use svc

clusterloader2/testing/load/config.yaml
The last run of ci-kubernetes-e2e-gce-scale-performance-cl was successful.
#372 shouldn't have a big impact on test execution -  this change is being reverted. 
Reverts kubernetes/perf-tests#372
=> Revert "ClusterLoader - Changing to original load RC randimized range"

clusterloader2/testing/density/100_nodes/constraints.yaml
Controller manger memory constraint 250MB -> 300MB.
=> ClusterLoader - Bumping up controller manager memory

clusterloader2/testing/density/100_nodes/constraints.yaml
Scheduler avg memory usage (gce 100) has increased ~5MB. Bumping up constraint to prevent flakes.
Memory has increased between run 21637 and 21640, possible due to https://github.com/kubernetes/kubernetes/pull/71731 PR.
=> Clusterloader - Bumping up scheduler memory constraint

clusterloader2/pkg/measurement/common/simple/wait_for_controlled_pods.go, clusterloader2/pkg/measurement/util/runtimeobjects/runtimeobjects.go
Increasing timeout for operation related to the pod deletion.
This change is required due to the garbage collector requiring twice as much time to remove the pods as it was needed for pods creation.
=> ClusterLoader - Increasing timeout for waiting for deletion operations

clusterloader2/pkg/measurement/util/ssh.go
This PR is a cherry pick from kubernetes/kubernetes
https://github.com/kubernetes/kubernetes/blob/9fd23b217800a312a45dbaedb70f4ffa65ec661b/test/e2e/framework/ssh.go#L36
**Additional**, this PR adds an environment variable `KUBEMARK_SSH_KEY` for provider `kubemark` SSH.
=> add kubemark ssh key env variable

clusterloader2/testing/density/100_nodes/constraints.yaml
This is to prevent flakes like https://github.com/kubernetes/kubernetes/issues/73461#issuecomment-464619155:
```
[measurement call TestMetrics - TestMetrics error: [resource constraints: 1 constraints violated: [container kube-proxy-e2e-big-minion-group-m4xc/kube-proxy is using 0.051962892/0.05 CPU]]]
```
=> Bump up kube-proxy cpu constraint

clusterloader2/pkg/measurement/common/simple/scheduling_throughput.go, clusterloader2/pkg/measurement/common/simple/wait_for_pods.go, clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go, clusterloader2/pkg/measurement/util/selector.go
- Extracting `createSelectorsString` to `mesurement/util`.
- Adding selectors string and threshold logging to `PodStartupLatency` measurement. The logging format will be consistent with `SchedulingThroughput` and `WaitForControlledPodsRunning`.
ref https://github.com/kubernetes/kubernetes/issues/74088
=> ClusterLoader - Pod startup log

clusterloader2/pkg/measurement/common/simple/wait_for_controlled_pods.go
https://github.com/kubernetes/perf-tests/issues/414
=> ClusterLoader - refine wait_for_controlled_pods.go clients data structure

clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/config/cluster.go, clusterloader2/pkg/prometheus/prometheus.go, verify/verify-flags/known-flags.txt
I cofirmed that deleting the namespace deletes the PV which in turns deletes disks in GCE.
This should help us fix the "leaked resources" errors, e.g. https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability-killer/1964
Putting this behind a flag, so one can disable it and leave prometheus stack for further analysis when running tests manually.
=> Add ability to tear down prometheus stack.

clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go
Limiting pod startup latencies listing to only 100 worst instead of 10% of all.
Ref discussion: https://github.com/kubernetes/kubernetes/issues/74088#issuecomment-464680872
=> ClusterLoader - Limiting pod startup logs to worst 100 pods

clusterloader2/vendor/k8s.io/client-go/dynamic/dynamicinformer/informer.go, clusterloader2/vendor/k8s.io/client-go/dynamic/dynamicinformer/interface.go, clusterloader2/vendor/k8s.io/client-go/dynamic/dynamiclister/interface.go, clusterloader2/vendor/k8s.io/client-go/dynamic/dynamiclister/lister.go, clusterloader2/vendor/k8s.io/client-go/dynamic/dynamiclister/shim.go, clusterloader2/vendor/vendor.json
https://github.com/kubernetes/perf-tests/issues/414
This PR only update packages `k8s.io/client-go/dynamic/dynamicinformer` and `k8s.io/client-go/dynamic/dynamiclister`, so that their revisions are different from package `k8s.io/client-go/dynamic`. However, it's compatible.
**What not update `k8s.io/client-go/dynamic`**:
This commit update `k8s.io/apimachinery/pkg/apis/meta/v1`, https://github.com/kubernetes/kubernetes/commit/0e1d50e70fdc9ed838d75a7a1abbe5fa607d22a1, but i think i should not update it.
=> Clusterloader - update vendor client-go dynamic package

clusterloader2/pkg/measurement/common/simple/wait_for_controlled_pods.go, clusterloader2/testing/density/config.yaml, clusterloader2/testing/load/config.yaml, clusterloader2/testing/node-throughput/config.yaml
This is the final PR for fixing https://github.com/kubernetes/perf-tests/issues/414
1. Replace clientset by dynamic client.
2. Update clusterloader2 testing configs
**What is not sure for me**:
I don't know whether it handles tombstone correctly.
=> ClusterLoader - Replace clientset by dynamic client

clusterloader2/testing/density/100_nodes/constraints.yaml
This is to address the following test failure (flakiness): https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability-killer/2153
=> Bump l7-lb-controller cpu constraint to 0.20

perfdash/Makefile, perfdash/deployment.yaml, perfdash/www/index.html, perfdash/www/script.js
This change adds two-way binding between the drop-down menus of PerfDash
and the set of URL query parameters. The result is that changing the
drop-downs will change the URL, and changing the URL will update the UI.
More importantly, these URLs can be shared, causing PerfDash to load a
specific graph.
=> Add deep links to PerfDash. 

clusterloader2/cmd/clusterloader.go
As the Prometheus Server is going to become a standard way of measuring SLIs in scale-tests we should make the ClusterLoader2 fail if it's not able to set up the Prometheus stack. 
It doesn't make sense to run tests if we're not able to measure SLIs.
Ref. https://github.com/kubernetes/kubernetes/issues/75284
=> CL2 should fail on Prometheus set-up errors.

clusterloader2/pkg/prometheus/manifests/0prometheus-operator-deployment.yaml
We don't monitor kubelets via Prometheus in scale tests, thus we can disable creation of the Endpoints object for kubelets.
An alternative would be to wait for the Kubelet Endpoints object to be created before running tests. 
But, for now, disabling the Kubelet Endpoints object creation is simply a better solution.
Ref. https://github.com/kubernetes/kubernetes/issues/75284
=> Prometheus - disable creating Kublet Endpoints

clusterloader2/cmd/clusterloader.go, clusterloader2/run-e2e.sh
The KUBEMARK_ROOT_KUBECONFIG variable is replacing DEFAULT_KUBECONFIG that turned out to be not propagated to clusterloader2.
=> Introduce KUBEMARK_ROOT_KUBECONFIG env variable.

clusterloader2/pkg/measurement/util/pod_store.go
Adding reflector name that will allow easy pod store identification.
ref https://github.com/kubernetes/perf-tests/issues/464
=> ClusterLoader - Adding name to pod store reflector

clusterloader2/pkg/prometheus/manifests/kubemark/kube-apiserver-endpoints.yaml, clusterloader2/pkg/prometheus/prometheus.go
Previously we've used kubemark master's cluster ip, but I don't think there is any gain in doing that.
What's more the way we implemented getting the master's cluster ip turned out to be not safe when there are multiple clusters running in the same gcp project, see https://github.com/kubernetes/perf-tests/issues/459
Below a proof that the kubemark master can be successfully scraped over public ip
=> Use $MASTER_IP to scrape kubemark's apiserver metrics

clusterloader2/pkg/framework/client/objects.go, clusterloader2/pkg/framework/framework.go, clusterloader2/pkg/measurement/util/runtimeobjects/runtimeobjects.go, clusterloader2/pkg/prometheus/prometheus.go
Options will allow stating how particular errors should be treated, e.g. which additional errors should be allowed (ignored), which should be retried.
This change is almost transparent to the existing code, e.g. the old code like
```
framework.CreateObject(item.GetNamespace(), item.GetName(), &item)
```
will be still valid and will behave as it used to, but it will be also possible to do something like
```
framework.CreateObject(item.GetNamespace(), item.GetName(), &item, client.Allow(apierrs.IsUnauthorized), client.Retry(apierrs.IsNotFound))
```
which in addition will allow IsUnauthorized errors and will retry IsNotFound.
This PR is to address https://github.com/kubernetes/perf-tests/pull/466#discussion_r268795519
=> Change objects API to allow specifying options

clusterloader2/pkg/prometheus/prometheus.go
The 404 errors during object creations may be caused by races.
E.g. when a ServiceAccount is created the associated token is created asynchronously, when creating an object that needs the token we may get a retryable 404 error if the token has not been created yet.
This should fix the issue described in https://github.com/kubernetes/kubernetes/issues/74213#issuecomment-476247400
=> Retry 404 errors when creating prometheus objects

clusterloader2/pkg/framework/client/objects.go
The bug was introduced by https://github.com/kubernetes/perf-tests/pull/467
These are two places I missed to update.
=> Don't call RetryFunction with nil.

clusterloader2/pkg/prometheus/prometheus.go, clusterloader2/pkg/prometheus/util.go
Checking if prometheus targets are ready will be used in other places, e.g. when setting up probes.
=> Extract CheckTargetsReady method.

clusterloader2/pkg/prometheus/manifests/0prometheus-operator-deployment.yaml, clusterloader2/pkg/prometheus/manifests/grafana-deployment.yaml, clusterloader2/pkg/prometheus/manifests/prometheus-prometheus.yaml
This is to stop using external registries in our scalability tests.
I copied all the images used by prometheus to gcr.io/k8s-testimages
=> Pull prometheus images from gcr.io.

slo-monitor/slo-monitor-deployment.yaml, slo-monitor/slo-monitor-pod.yaml
In https://github.com/kubernetes/perf-tests/pull/481 I updated the slo-monitor version in the Makefile but not in the yaml files. I noticed that the previous time the version number was incremented in https://github.com/kubernetes/perf-tests/pull/305 the yaml files were updated, so updating them for consistency.
cc @wojtek-t @listx
=> Increment version number for slo-monitor to 0.11.1

clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go, clusterloader2/testing/density/config.yaml, clusterloader2/testing/load/config.yaml
- Making api responsiveness measurement non-failable.
- Addinf api responsiveness measurement to density and load test.
=> ClusterLoader - Adding api reposiveness prometheus to tests

clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go, clusterloader2/pkg/measurement/util/prometheus.go
Extracting prometheus query execution from api_responsiveness_proemtheus.go to pkg/measurement/util.
=> ClusterLoader - extracting prometheus query execution to util

clusterloader2/pkg/prometheus/manifests/prometheus-prometheus.yaml
The default is 24h which may be not enough for long running / multiple runs of scalability tests.
=> Set the prometheus data retention to 7d

clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/config/cluster.go, clusterloader2/pkg/prometheus/prometheus.go, verify/verify-flags/known-flags.txt
=> Pre-work to monitoring kubemark via internal IP.

slo-monitor/Dockerfile
This is part of the effort described in kep kubernetes/enhancements#900
Compariing to alpine, distroless can mitigate the influence due to CVE issues.
=> Rebase slo-monitor to distroless

clusterloader2/pkg/prometheus/manifests/default/kube-controller-manager-service.yaml, clusterloader2/pkg/prometheus/manifests/default/kube-scheduler-service.yaml
This will fix scraping metrics from kube-scheduler and kube-controller-manager in non-kubemark clusters.
=> Add missing prometheus services.

clusterloader2/pkg/prometheus/manifests/default/prometheus-serviceMonitorApiserver.yaml, clusterloader2/pkg/prometheus/manifests/kubemark/prometheus-serviceMonitorApiserver.yaml
There isn't that much difference in number of metrics with/without dropping:
```
curl -k https://10.40.0.13:443/metrics 2>/dev/null | wc -l
13635
curl -k https://10.40.0.13:443/metrics 2>/dev/null  | grep -v apiserver_admission_controller_admission_latencies_seconds_ | grep -v etcd_ | grep -v apiserver_admission_step_admission_latencies_seconds_ | wc -l
11527
```
Some of them might be useful when debugging, let's stop dropping them.
We may reconisder dropping if we ever run into performance / storage issues.
=> Don't drop any kube-apiserver metrics.

clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/util/cluster.go
This is to allow monitoring master's kubelet in non-kubemark clusters.
For kubemark clusters the MasterInternalIp will be always set via env variable, see https://github.com/kubernetes/test-infra/pull/12251
=> Set MasterInternalIp in completeConfig if not set.

clusterloader2/pkg/prometheus/manifests/kubemark/kube-apiserver-endpoints.yaml, clusterloader2/pkg/prometheus/prometheus.go
Currently we have KubemarkMasterIp used in kubemark clusters, but we will need the same variable to monitor master's kubemark in non-kubemark cluster.
=> Unify MasterIp variable used in prometheus templates.

clusterloader2/pkg/prometheus/manifests/default/prometheus-serviceMonitorApiserver.yaml, clusterloader2/pkg/prometheus/manifests/default/prometheus-serviceMonitorKubeControllerManager.yaml, clusterloader2/pkg/prometheus/manifests/default/prometheus-serviceMonitorKubeScheduler.yaml
Scraping O(few) master components is relatively cheap (e.g. comparing to scraping 5K kube-proxy instances) and there is no reason for doing that every 30s.
=> Scrape master's components every 5s.

clusterloader2/pkg/measurement/util/runtimeobjects/runtimeobjects.go, clusterloader2/pkg/measurement/util/runtimeobjects/runtimeobjects_test.go, clusterloader2/pkg/prometheus/manifests/0prometheus-operator-deployment.yaml, clusterloader2/pkg/prometheus/manifests/grafana-deployment.yaml, dns/cluster/coredns-deployment.yaml, dns/cluster/kube-dns-deployment.yaml, perfdash/deployment.yaml, slo-monitor/slo-monitor-deployment.yaml
Required to get CI green in advance of disabling deprecated apps and extensions APIs
xref https://github.com/kubernetes/kubernetes/issues/43214 https://github.com/kubernetes/kubernetes/pull/70672
=> Switch to apps/v1

clusterloader2/pkg/prometheus/prometheus.go
https://github.com/kubernetes/perf-tests/pull/528 temporarily removed kube-proxy monitoring, forgot to update this place.
=> Fix expected targets after #528

clusterloader2/pkg/prometheus/manifests/grafana-dashboardDefinitions.yaml, clusterloader2/pkg/prometheus/manifests/grafana-deployment.yaml
It's quite hard to update the dashboards when it's inlined in yaml and we need to escape "{{" etc.
I will try to migrate this dashboard to a separate file in the next PR.
=> Dashboard for watching master metrics.

clusterloader2/pkg/prometheus/experimental.go, clusterloader2/pkg/prometheus/prometheus.go, verify/verify-flags/known-flags.txt
Automatic snapshot of the prometheus disk after the tests might be extremely helpful in our large scale tests. Especially with the new debug dashboard that @mborsz is working on.
Two main use-cases are:
1. Manual testing, by setting this flag you can start your manual scale tests and analyze the prometheus graphs later, without worrying that it would be wiped by the next run
2. CI testing, we could start storing snapshots for few recent runs of scale tests for comparison / debugging purposes. Last time I checked these snapshots are only a few hundred MBs per run so they basically cost nothing comparing to the gcs storage we use per run. We'd have to come up with some automatic clean-up mechanism eventually, but we could start with manual clean-up every month or so. This scenarion might …
=> Experimental snapshotting of Prometheus's PD (GCP only).

clusterloader2/pkg/prometheus/manifests/kubemark/kubemark-master-endpoints.yaml, clusterloader2/pkg/prometheus/manifests/kubemark/kubemark-master-service.yaml, clusterloader2/pkg/prometheus/manifests/kubemark/kubemark-master-serviceMonitor.yaml
duplicate `ServicePort` names make `Service` object fail validation during e2e test. The other two APIs (`Endpoints` and `ServiceMonitor`) might tolerate duplication, but de-duped here for clarity.
ref: https://github.com/kubernetes/kubernetes/issues/78401, https://github.com/kubernetes/perf-tests/pull/538#discussion_r287891512
/cc @mm4tt @wojtek-t
=> failing-test: remove duplicate ports and endpoints

clusterloader2/cmd/clusterloader.go
Given that some config parts are based on env, some on flags, some autoguessed I think it's better to log all of them to make debugging easier.
=> Print config on startup

.travis.yml
This should fix cl2 build broken by https://github.com/kubernetes/perf-tests/pull/534
=> Update travis go version to 1.12.

.travis.yml, clusterloader2/pkg/config/template_functions.go
ReplaceAll function has been added in go1.12. We still compile clusterloader2 against go1.11 to run tests against stable Kubernetes versions.
Until we figure out how to compile clusterloader2 with newer version of go and Kubernetes with the older one, we should test against go1.11.
/fixes #554
=> Use strings.Replace instead strings.ReplaceAll to keep compatibility with go1.11.5

clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.json
Values on any of those dashboard won't go below that value. Plus it makes some dashboards more readable and accurate (e.g by showing accurate proportions between series).
/kind cleanup
=> Master dashboard: set min value on Y axis to 0.

.travis.yml, clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.json, clusterloader2/pkg/prometheus/manifests/dashboards/network-programming-latency.json, verify/verify-dashboard-format.sh
Also add make target to simplify usage for other contributors.
/kind cleanup
/assign @mm4tt
=> Use jq to format Grafana dashboards in json files

verify/test.sh
It's using bazel setup, so 'go test' won't work on it.
=> Exclude _logviewer from tests

perfdash/Makefile, perfdash/config.go, perfdash/deployment.yaml, perfdash/parser.go, perfdash/www/script.js
- DensityRequestCountByClient and LoadRequestCountByClient will have separate plot for each component (instead of component + version). Each version will be displayed as separate plot line.
- Removing parser for phase time. We aren't collecting this data anymore.
- Preventing triple calls during the initialization (one for each label).
=> Perfdash - Merging component versions

.gitignore, clusterloader2/pkg/prometheus/manifests/dashboards/README.md, clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.dashboard.py, clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.json, clusterloader2/pkg/prometheus/manifests/dashboards/regenerate.sh
The changes:
* dashboard is stored in readable, modifiable file
* grafanalib has reasonable defaults (e.g. minY=0)
* it's possible to reuse the same code (e.g. simple_graph).
/cc @oxddr
=> Migrate master dashboard to grafanalib

perfdash/config.go, perfdash/parser.go
Rename parsing function more clearly (it's actually not specific to responsiveness data).
fixes: https://github.com/kubernetes/perf-tests/issues/575
Tested locally: ![b9a2U3ZYNEd](https://user-images.githubusercontent.com/30298753/60447793-7e1b8800-9c24-11e9-9f75-4f1dc94d7fcd.png)
/assign @mm4tt
=> Show Network programming latency in perf-dash

clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/config/cluster.go, clusterloader2/pkg/measurement/common/simple/etcd_metrics.go, clusterloader2/pkg/measurement/common/simple/profile.go, clusterloader2/pkg/measurement/common/simple/resource_usage.go, clusterloader2/pkg/measurement/common/simple/scheduler_latency.go, clusterloader2/pkg/prometheus/prometheus.go, clusterloader2/pkg/util/cluster.go
This change should be no-op, it only changes the CL2 api (flags/envs) to accept multiple values as the `master ip` - both internal and external. 
The api change should be backward compatible, i.e. if flag/env was set to a single master-ip it will continue to work in exactly the same way.
Actual changes supporting multi-master clusters will come in separate PRs.
=> Make CL2 accept multiple master ips.

clusterloader2/pkg/measurement/common/slos/network_programming.go, clusterloader2/pkg/measurement/common/slos/network_programming_test.go
Clarify documentation of query used to measure network programming latency. 
Also remove redundant method.
ref https://github.com/kubernetes/perf-tests/issues/575
/assign @mm4tt
=> Clarify documentation of query used to measure network programming latency

perfdash/Dockerfile, perfdash/Makefile, perfdash/deployment.yaml
Also switch perfdash to use debian images (not Google ones).
ref https://github.com/kubernetes/perf-tests/issues/575
=> Update perfdash to 2.2

clusterloader2/testing/density/config.yaml, clusterloader2/testing/density/deployment.yaml, clusterloader2/testing/load/config.yaml, clusterloader2/testing/load/deployment.yaml
Experimental change to switch deprecated ReplicationControllers to Deployments. 
We'll see if the today's CI/CD scale test passes with this change. If no we'll revert, if yes we'll cleanup and continue using Deployments.
=> ClusterLoader2: switch RCs to Deployments

clusterloader2/testing/density/100_nodes/constraints.yaml
This is to deflake the test for the time of investigation.
Ref. https://github.com/kubernetes/kubernetes/issues/79898
=> Temporarily increase the controller-manager CPU constraint

clusterloader2/testing/load/deployment.yaml, clusterloader2/testing/load/rc.yaml
Adding group label to pods, so they can be observed by pod startup latency measurement.
=> ClusterLaoder - Adding group label to load test pods

clusterloader2/docs/experiments.md
Let's have a discussion about how to rollout experiments to clusterloader2. By no means I insist this is the final form of this document (and practices it describes). 
fixes https://github.com/kubernetes/perf-tests/issues/588
/assign @mm4tt @wojtek-t 
/cc @mborsz @krzysied
=> Document process for rolling out clusterloader2 experiments.

clusterloader2/pkg/chaos/nodes.go, clusterloader2/pkg/prometheus/manifests/default/master-ip/master-endpoints.yaml, clusterloader2/pkg/prometheus/manifests/default/master-ip/master-service.yaml, clusterloader2/pkg/prometheus/manifests/default/master-ip/master-serviceMonitor.yaml, clusterloader2/pkg/prometheus/manifests/exporters/node-exporter.yaml, clusterloader2/pkg/prometheus/manifests/kubemark/kubemark-master-endpoints.yaml, clusterloader2/pkg/prometheus/manifests/kubemark/kubemark-master-service.yaml, clusterloader2/pkg/prometheus/manifests/kubemark/kubemark-master-serviceMonitor.yaml, clusterloader2/pkg/prometheus/prometheus.go, clusterloader2/pkg/util/ssh.go, clusterloader2/vendor/golang.org/x/sync/errgroup/errgroup.go, clusterloader2/vendor/vendor.json
Add support for node-exporter in our tests.
It will run only on registered nodes with kubernetes.io/node-exporter=true label (none right now, it will be possible to add this when https://github.com/kubernetes/kubernetes/pull/79703 is merged.
* It does work for both kubemark and regular tests *
/assign @mm4tt
=> Add node-exporter to our tests

clusterloader2/testing/density/config.yaml, clusterloader2/testing/load/config.yaml
=> Enable probes measuring in-cluster network latency.

perfdash/Makefile, perfdash/config.go, perfdash/deployment.yaml
ref https://github.com/kubernetes/perf-tests/issues/579
Also rename "KubeProxy" section to "Network".
/hold 
wait until metrics is enable in gce100 and we have some results to display and test this upon
=> Display in-cluster network latency in perf-dash.

clusterloader2/pkg/measurement/common/probes/probes.go, clusterloader2/pkg/measurement/common/slos/network_programming.go, clusterloader2/pkg/measurement/common/slos/network_programming_test.go, clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go, clusterloader2/pkg/measurement/util/latency_metric.go
Refactor exsiting measurements to make use of shared utilities.
ref https://github.com/kubernetes/perf-tests/issues/640
/hold
=> Improve logging of network programming latency measurement

clusterloader2/testing/density/100_nodes/constraints.yaml
Fixing https://github.com/kubernetes/kubernetes/issues/77492#issuecomment-511785738
This should deflake the test, the increase was most likely caused by fluentd version upgrade.
The 260MB seems as a reasonable limit currently:
=> Increase fluentd memoryConstraint to 260 MB

clusterloader2/testing/density/100_nodes/constraints.yaml
This is to deflake presubmit until we figure out what has changed.
Ref. https://github.com/kubernetes/kubernetes/issues/80212
=> Temporarily increase scheduler cpu constraint.

clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go
Using `EventTime` as a default when checking scheduling time.
=> ClusterLoader - Pod startup fix

clusterloader2/testing/experiments/enable_dns_probes.yaml
ref https://github.com/kubernetes/perf-tests/issues/612
/assing @mborsz
=> Add knob to enable DNS probe in clusterloader2.

clusterloader2/pkg/prometheus/experimental.go, verify/verify-flags/known-flags.txt
This will be useful when running multiple similar tests locally to better organize the snaphots.
E.g. when running golang1.13 test we've already tried over 5 custom k8s versions, it'd be easier if I can give a snapshot a meaningful name (e.g. golang1.12.6-basline) rather than using the auto-generated pd name (e.g. golang-kubemark-dynami-pvc-1a775eaa-22bb-405a-81a5-eb2dd545168c)
=> Add flag to override the prometheus snapshot name

clusterloader2/testing/density/100_nodes/constraints.yaml
The test still flakes and the only reason is this cpuConstraint being violated.
This is strictly related to the other symptoms we see in https://github.com/kubernetes/kubernetes/issues/80212
=> Temporarily increase kube-apiserver cpuConstraint to 2.5 in gce-100

clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go
This basically means that our tests could never failing in pod-startup-latency SLO. !!!
Fix: https://github.com/kubernetes/perf-tests/issues/667
@kubernetes/sig-scalability-bugs 
@mm4tt @mborsz @oxddr @krzysied
=> Fix error handling in pod startup time metric

clusterloader2/pkg/test/simple_test_executor.go, clusterloader2/testing/density/config.yaml, clusterloader2/testing/load/config.yaml
The change adds name for each steps describing what it does. I believe this will make the test configs easier to understand to people not familiar with clusterloader2.
In addition we'll be logging when step starts and ends, so it's easier to identify particular steps in the log.
=> Clean up steps in CL2 test configs.

clusterloader2/pkg/measurement/common/slos/api_responsiveness.go, clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go
Also remove logic for special handling of  big clusters in api_responsiveness measurement. 
=> Use 30s as the threshold for cluster-scoped list calls.

clusterloader2/pkg/measurement/common/wait_for_pvcs.go, clusterloader2/pkg/measurement/util/pvcs.go, clusterloader2/pkg/measurement/util/wait_for_pvcs.go
Adds a function `WaitForBoundPVCs` that works very similarly to `WaitForRunningPods` and waits until the desired number of PVCs becomes "Bound". 
The code is very similar to the code for `WaitForRunningPods` - I played with experimenting on a way to generalize the similar parts into a generic `WaitForResource` but I am not sure how easy or feasible it will be to actually complete it. In the mean time, this does it with just some repeated code and logic.
=> add function to wait for bound PVCs

clusterloader2/testing/load/experimental_config.yaml, clusterloader2/testing/load/service.yaml
Ref. https://github.com/kubernetes/perf-tests/issues/413
This change is no-op for CI/CD tests.
The simplified load test is is added in a new file `experimental_config.yaml` that will eventually replace the old `config.yaml` once the new config is tested properly.
I run the tests on 100 node cluster and the results look promising:
=> Simplified load test - deployments and services bundled together

clusterloader2/pkg/measurement/common/bundle/test_metrics.go, clusterloader2/pkg/measurement/common/profile.go
Refactoring in profile.go allows adding new profile types much easier, it also removes duplicated and unnecessary code.
=> Gather etcd mutex profile and refactor profile.go

clusterloader2/pkg/measurement/common/resource_usage.go, clusterloader2/pkg/measurement/util/gatherers/container_resource_gatherer.go, clusterloader2/pkg/measurement/util/gatherers/resource_gather_worker.go, clusterloader2/pkg/measurement/util/kubelet/kubelet.go
It's not used anywhere other than to check that it's within some limits.
Also update the method doc, as it doesn't make sense comparing to what the method actually does and how cadvisor works.
From the tests I've run, the cadvisor endpoint gets updated every ~15s and scraping it takes on average ~110ms. It seems to be exactly the same data that we scrape via prometheus. 
Given that, we should be able to scrape it more often (in prometheus we scrape master every 5s) which should allow us to fix https://github.com/kubernetes/perf-tests/issues/694. 
This is a prework to that.
=> Remove cpuInterval param from GetOneTimeResourceUsageOnNode()

clusterloader2/pkg/measurement/common/resource_usage.go, clusterloader2/pkg/measurement/util/gatherers/container_resource_gatherer.go
This is to address https://github.com/kubernetes/perf-tests/issues/694.
It's enough to scrape more often only on master as when it comes to nodes'components we scrape them much more often on average, e.g. for 100 node cluster we have 100 times more data for nodes components as each node is scrape separately every 60s.
In addition it should be safe to hit cadvisor every 10s on master due to two reasons:
1. We do it already via prometheus every 5s (and it doesn't seem to be impacting master's performance at all)
2. From the tests I run looks like cadvisor updates every ~10-16s and request are fast (~100ms), so it implements caching and requests are cheap and in addition there is no gain in scraping it often than 10s
=> Gather resource usage on master every 10s

clusterloader2/testing/load/experimental/bundled_services_and_deployments.yaml, clusterloader2/testing/load/experimental/deployment.yaml, clusterloader2/testing/load/experimental/extended_config.yaml, clusterloader2/testing/load/experimental/service.yaml
1. Move and rename experimental_load to bundled_services_and_deployments and add a comment in it that it's currently frozen
2. Create extended_config.yaml which is an exact copy of load/config at this point. This will make reviewing future changes easier.
=> Clean up load test experiments

probes/Makefile
ref https://github.com/kubernetes/perf-tests/issues/612
/assign @mm4tt
=> Bump probes to v0.0.2, so the image includes dns probe.

clusterloader2/pkg/config/template_functions.go, clusterloader2/pkg/test/simple_test_executor.go, clusterloader2/testing/load/deployment.yaml, clusterloader2/testing/load/experimental/configmap.yaml, clusterloader2/testing/load/experimental/extended_config.yaml, clusterloader2/testing/load/experimental/overrides/enable_configmaps.yaml, clusterloader2/testing/load/experimental/overrides/enable_secrets.yaml, clusterloader2/testing/load/experimental/secret.yaml
https://github.com/kubernetes/perf-tests/issues/704
=> Create configmaps and secrets in extended load test

clusterloader2/pkg/prometheus/manifests/prometheus-rules.yaml
They should be rather cheap, so I don't think we need to be cautious about enabling them.
ref https://github.com/kubernetes/perf-tests/issues/498
/assign @mm4tt
=> Add more precomputation rules for apiserver latencies.

clusterloader2/pkg/config/template_functions.go, clusterloader2/pkg/test/interface.go, clusterloader2/pkg/test/simple_context.go, clusterloader2/pkg/test/simple_test_executor.go, clusterloader2/pkg/test/test.go, clusterloader2/pkg/util/util.go, clusterloader2/testing/load/deployment.yaml, clusterloader2/testing/load/experimental/extended_config.yaml, clusterloader2/testing/load/service.yaml
*  Remove IsEven / IsOdd template functions: replaced with eq (Mod a 2) 0/1
* Make overrides available in object templates - we don't have to pipe overrides to object templates anymore
* Don't apply empty object template files - this adds ability to easily create an object (e.g. NetworkPolicy) only for X% of deployments
=> ClusterLoader2 cleanups and improvements

clusterloader2/testing/experimental/storage/pod-startup/config.yaml, clusterloader2/testing/experimental/storage/pod-startup/volume-types/configmap/pod_with_configmap.yaml, clusterloader2/testing/experimental/storage/pod-startup/volume-types/downwardapi/pod_with_downwardapi.yaml, clusterloader2/testing/experimental/storage/pod-startup/volume-types/emptydir/pod_with_emptydir.yaml, clusterloader2/testing/experimental/storage/pod-startup/volume-types/persistentvolume/pod_with_pvc.yaml, clusterloader2/testing/experimental/storage/pod-startup/volume-types/secret/pod_with_secret.yaml
remove app name parameter from pod and volume object template
Fix: https://github.com/kubernetes/perf-tests/issues/710
/sig storage
cc @hantaowang @msau42
=> Storage tests: Remove app name from pod and volume object template

clusterloader2/testing/density/100_nodes/constraints.yaml
Now, the https://github.com/kubernetes/perf-tests/pull/697 has merged, the CPU usage is much less flaky. On the other hand it went up which is expected as now we more accurately measure the actual 99th percentile (see https://github.com/kubernetes/kubernetes/issues/80212#issuecomment-515010726 as an example of how bad we used to did it).
Given that we should increase some constraints and remove the old TODOs.
Justification for the values of cpuConstraints used in this PR:
* **scheduler** - since https://github.com/kubernetes/perf-tests/pull/697 the max observed value was 0.61 CPU, setting the limit to ~20% more which is ~0.75 
* **api-server** - since https://github.com/kubernetes/perf-tests/pull/697 the max observed value was 2.3 CPU, setting the limit to ~20% more which is ~2.8
Fixes …
=> Update cpuConstraints for scheduler and apiserver

clusterloader2/pkg/prometheus/experimental.go, clusterloader2/pkg/prometheus/util.go, clusterloader2/pkg/prometheus/util_test.go
This change prevents losing prometheus disk snapshot when snapshot name is invalid.
=> ClusterLoader - Disk snapshot name verify

dns/py/data.py, dns/py/runner.py, verify/verify-flags-underscore.py
Old style exceptions are syntax errors in Python 3 but new style exceptions work as expected in both Python 2 and Python 3.
Also fix __reduce()__ and __printf()__ ;-)
=> Old style exceptions -> new style for Python 3

clusterloader2/testing/experimental/storage/pod-startup/config.yaml, clusterloader2/testing/experimental/storage/pod-startup/volume-types/persistentvolume/override.yaml
Per #722, this turns on waiting for PVs to be deleted for storage tests. I tested this locally with #723 merged.
Because PVs are created on demand by PVCs, I have not found a way to add a label to the created PVs. Thus this config currently waits for all global PVs to be deleted.
@msau42 @davidz627 @jingxu97 @verult
=> wait for PV to be deleted in storage tests

clusterloader2/drivers/gcp-csi-driver-stable.yaml, clusterloader2/run-e2e.sh, clusterloader2/testing/experimental/storage/pod-startup/config.yaml, clusterloader2/testing/experimental/storage/pod-startup/volume-types/persistentvolume/pvc.yaml, clusterloader2/testing/experimental/storage/pod-startup/volume-types/persistentvolume/usecsi.yaml
@davidz627 @wojtek-t @jingxu97 @verult 
This PR adds the ability to test PVs provisioned and managed by the CSI GCP PD Driver. Included is a change to cl2's run-e2e.sh that deploys a secret (if it exists) and a yaml that deploys the driver and all its associates rbacs and SAs (one of which uses this secret).
I will rebase this after https://github.com/kubernetes/perf-tests/pull/657 is merged so that the ability to deploy the driver yaml (if necessary) is build into the storage test config. It will be turned off by default and an additional override file in volume-types/persistentvolume will turn it on.
=> add functionality to deploy cloud-sa secret and driver

clusterloader2/pkg/prometheus/manifests/default/kube-proxy-service.yaml, clusterloader2/pkg/prometheus/manifests/default/prometheus-serviceMonitorKubeProxy.yaml, clusterloader2/testing/load/config.yaml, clusterloader2/testing/load/experimental/bundled_services_and_deployments.yaml, clusterloader2/testing/load/experimental/extended_config.yaml
It has been enabled in all tests and no negative impact has been observed.
ref https://github.com/kubernetes/perf-tests/issues/615
=> Remove PROMETHEUS_SCRAPE_KUBE_PROXY experiment.

clusterloader2/pkg/measurement/common/probes/probes.go, clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go, clusterloader2/pkg/measurement/util/latency_metric.go, clusterloader2/testing/density/config.yaml, clusterloader2/testing/load/config.yaml, clusterloader2/testing/load/experimental/bundled_services_and_deployments.yaml, clusterloader2/testing/load/experimental/extended_config.yaml
This allows to enable probes using overrides, so they can be rolled out gradually or rolled back if needed. The previous version was optimized for minimizing code changes needed to enable a new prober. However in light of https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/docs/experiments.md this make gradual rollout impossible without changes to probes.go.
=> Refactor probes.go so that there is a single prober enabled per instance

perfdash/config.go, perfdash/parser.go
Removing parsers for unused metric naming conventions.
=> Perfdash - old metrics cleanup

clusterloader2/pkg/measurement/common/probes/manifests/dnsLookup/dns-prober-deployment.yaml, clusterloader2/pkg/measurement/common/probes/manifests/dnsLookup/dns-prober-service.yaml, clusterloader2/pkg/measurement/common/probes/manifests/dnsLookup/dns-prober-serviceMonitor.yaml, clusterloader2/pkg/measurement/common/probes/probes.go, clusterloader2/pkg/prometheus/manifests/prometheus-rules.yaml, clusterloader2/testing/density/config.yaml, clusterloader2/testing/load/config.yaml, clusterloader2/testing/load/experimental/bundled_services_and_deployments.yaml, clusterloader2/testing/load/experimental/extended_config.yaml
ref https://github.com/kubernetes/perf-tests/issues/612
This PR also adds parsed overrides as an argument to Measurements. This is needed, so the probes can be started from inside measurement and still benefit from knobs passed via testoverrides to clusterloader2. I think the approach is not ideal, but I am struggling to come up with something better. I am open to other ideas. 
/assign @wojtek-t @mm4tt
=> Run DNS probes in tests

perfdash/Makefile, perfdash/config.go, perfdash/deployment.yaml
Also reintroduce Network latency as the metric format has changed.
ref https://github.com/kubernetes/perf-tests/issues/612
/hold
=> Show DNS lookup latency in PerfDash.

clusterloader2/testing/l4ilb/config.yaml, clusterloader2/testing/l4ilb/dep.yaml, clusterloader2/testing/l4ilb/service.yaml
The test creates 3 ILBs - 1 with 300 backends, 1 with 150 and the third one with 10 backends.
The time taken for an ip address to be assigned to the ILB and the time taken for the IP to serve traffic is also measured.
=> Added a simple scale test for L4ILB.

probes/Makefile, probes/cmd/main.go, probes/pkg/ping/client/client.go
Close response body to fix memory leak in ping-client.
Also:
* bump probes to v0.0.4
* add pprof handlers to probes binary for ease of debugging
ref https://github.com/kubernetes/perf-tests/issues/755
/assign @mm4tt
=> Fix memory leaks in probes.

clusterloader2/testing/load/deployment.yaml
This is to fix presubmits. It will be switched back in https://github.com/kubernetes/perf-tests/pull/767
=> Make deployment.yaml ignore .ENABLE_CONFIGMAPS|SECRETS vars

clusterloader2/testing/density/config.yaml, clusterloader2/testing/load/config.yaml
Change number of probes to 2 + #nodes / 100. 
This gives more data points and decreases chances that of single restarted pod to burn SLO (which IMO is unintended).
/assign @mm4tt
=> Increase number of probes running in tests

clusterloader2/pkg/prometheus/prometheus.go
This will fail until https://github.com/kubernetes/kubernetes/pull/82579 gets in.
Ref. https://github.com/kubernetes/perf-tests/issues/786
=> Fix logic for checking if at least one etcd target is available

clusterloader2/pkg/test/simple_test_executor.go
Our load config recently exceeded 500 lines. If you modify a few places in the config and you get an error is super hard to find it in the yaml as errors are only logged after the whole test, without information where it occurred. This logging will let user know if there were any errors for a given step, which in most cases is enough to easily locate the error it in the yaml file.
=> ClusterLoader: Log step's errors

clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go, clusterloader2/pkg/measurement/common/slos/network_programming.go, clusterloader2/pkg/measurement/common/slos/network_programming_test.go, clusterloader2/pkg/measurement/common/slos/prometheus_measurement.go, clusterloader2/pkg/measurement/util/prometheus.go, clusterloader2/testing/density/config.yaml, clusterloader2/testing/load/config.yaml
Simple query is intended to be used in short tests, where there is not enough windows to compute two-level SLO. 
Also fix naming as advised by golint (Api -> API)
ref https://github.com/kubernetes/perf-tests/issues/498
/assign @wojtek-t @mm4tt
=> Add option to use simple latency query for API latency.

clusterloader2/api/types.go, clusterloader2/pkg/measurement/util/runtimeobjects/runtimeobjects.go, clusterloader2/pkg/test/simple_test_executor.go, clusterloader2/testing/load/config.yaml, clusterloader2/testing/load/pvc.yaml, clusterloader2/testing/load/statefulset.yaml
The only tricky part here is deleting PVs that are created via StatefulSets. Theses PVs are not automatically deleted when StatefulSets are deleted. 
Because of that I extended the ClusterLoader2 Phase api to allow deleting objects that weren't created directly via CL2. 
The way it works is that once we detect a new object, and if certain option is set, we issue a List request to find number of replicas for that object.
=> Extend load test to cover PersistentVolumes

clusterloader2/pkg/prometheus/util.go
This will help debugging prometheus setup errors. Currently we know that some targets didn't go up, but we have no idea which ones.
=> Prometheus: log example not ready target

clusterloader2/pkg/measurement/util/runtimeobjects/runtimeobjects.go
Filtering deamonset schedulable nodes only by node unschedulable spec.
ref https://github.com/kubernetes/kubernetes/issues/82875
=> ClusterLoader - Using unschedulable spec

perfdash/README.md
This updates the readme with specific commands on how to start perfdash
locally. Commit also includes minor style changes to the readme code (line
wrapping, extra newlines etc).
Testing:
* ran perfdash according to the readme
fixes #585
=> Add local dev instructions to perfdash readme

clusterloader2/testing/experimental/storage/pod-startup/config.yaml, clusterloader2/testing/experimental/storage/pod-startup/empty_test_name/override.yaml, clusterloader2/testing/experimental/storage/pod-startup/suite.yaml
This adds a test suite for running storage tests. In the next commit (to
test-infra), a prow job that runs this suite will be defined in
sig-scalability-experimental-periodic-jobs.
The goal of running a suite instead of duplicated jobs is to minimize
config duplication.
There is some redundancy in the suite definition. To be investigated if
it can be reduced using go templates. If it is feasible, it will be done
as a follow-up change once the suite job is working.
Tesing:
* ran clusterloader with
testsuite=testing/experimental/storage/pod-startup/suite.yaml and
verified that tests passed
=> Add storage experimental test suite

perfdash/config.go
Commit https://github.com/kubernetes/test-infra/commit/50615e resulted
in breaking perfdash. This was due to lack of support for
"storage-suite" job type in perfdash.
To prevent such changes from breaking perfdash again, jobs with bad config will
be ignored.
Testing:
* ran perfdash locally with bad config for storage jobs, verified that
other job data is fetched correctly
=> Skip fetching metrics by perfdash for misconfigured jobs

perfdash/config.go, perfdash/google-gcs-downloader.go, perfdash/www/index.html
This commit enables perfdash to view metrics recorded by clusterloader
test suite runs.
Before this change, it was not possible to do so, because test suite run
puts measurement results in separate files, for example:
-  APIResponsiveness_storage_configmap-vol-per-node_2019-10-01T06:08:05Z.json
-  APIResponsiveness_storage_downwardapi-vol-per-node_2019-10-01T06:10:00Z.json
In such case, perfdash read metrics data from the first file that
matched the prefix APIResponsiveness_storage (prefix is specified in
config.go file), meaning that other results were ignored.
To solve this issue, support for handling multiple files that match
given prefix is added. For each of the matched files, perfdash extracts
the "suiteId" from the file name and appends it to the result category.
This means that …
=> Add support for displaying test suite results in perfdash

perfdash/config.go
As a followup from previous PR, this fixes minor style issues in the
config validation logic:
- use of named return values
- comment was not formatted properly
- typo in comment
=> Apply minor style changes to perfdash config validation

clusterloader2/testing/density/config.yaml
Using better memory estimation for latency pods in gce 100 test. This will save ~200MB for potential probe pods.
Scheduler uses allocatable memory to evaluate node score. Nodes have < 3500MB memory available. Therefore 350MB should be a good choice.
=> ClusterLoader - Latency pod memory update - 100 nodes

clusterloader2/pkg/config/template_provider.go, clusterloader2/pkg/config/template_provider_test.go
This is because underscores are used as separators in test run
artifacts. Allowing underscores will make filename parsing harder for
tools like perfdash.
Testing:
* ran the new unit test
=> Do not allow undersores in clusterloader suite scenario ids

clusterloader2/testing/load/config.yaml, clusterloader2/testing/load/networkpolicy.yaml
Copy of: https://github.com/kubernetes/perf-tests/pull/719 with fixed paths
This is most likely no-op until we turn on some Network Policy Provider that will start enfocring these network policies.
It should be pretty straightforward to turn on Calico both in GKE and in GCE.
This should be done separately to isolate any potential performance
impact of tuning it just on.
/cc oxddr
/cc mm4tt
=> Extended Load: NetworkPolicies

clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go, clusterloader2/pkg/prometheus/manifests/prometheus-rules.yaml
Default so far was 5m as in SLI definition. We're changing this to 1m, so we
have we calculate the the SLI over more data points. In the past, we were
suffering from having not enough of them, which was causing 99th percentaile to
be actually max over the series.
Minor: remove recording rules with 30s window.
/ref https://github.com/kubernetes/perf-tests/issues/498
/assign @mm4tt
=> Switch Prometheus API responsiveness to use 1m windows.

clusterloader2/pkg/measurement/common/bundle/test_metrics.go, clusterloader2/pkg/measurement/common/system_pod_metrics.go
In this commit, "system pod metrics" measurement is added. Its purpose
is to gather data about system pod restarts. This measurement will be
invoked on every test run, but it's logic is no-op by default.
It will be enabled by setting "systemPodMetricsEnabled: true" in
TestMetrics measurement. This is to be done in follow-up commits.
Testing:
* ran storage suite against existing cluster
* verified that SystemPodMetrics artifact is being created
with proper content if flag is set to true
* verified that no such artifact is created when this flag is absent
=> Add system pod metrics measurement in clusterloader

run-e2e.sh
The previous PR https://github.com/kubernetes/perf-tests/pull/824 added support in run command, but not in e2e script.
/assign @krzysied @wojtek-t
=> Add node-local-dns flag in e2e script.

clusterloader2/pkg/measurement/common/bundle/test_metrics.go, clusterloader2/pkg/measurement/common/system_pod_metrics.go, clusterloader2/pkg/measurement/common/system_pod_metrics_test.go
Before this change, system pod measurement gathered metrics only at the
end of each test. This means that the restart count in the present in
the summary was equal to the restart count since each given container
was created (this is usually during cluster creation). This means that
we could have high restart count metric for some test even though no
restart happened during that test, which could be misleading.
To fix this, in this commit we add listing system pods before the test
(in measurement "start" action). Then in "gather" action, initial
restart counts are subtracted from the actual restart counts. In effect,
restart count present in the summary is the number of restarts that
occured during execution of this test.
Testing:
* ran storage suite locally
* verified SystemPodMetrics …
=> Subtract initial restart counts when calculating system pod metrics

clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go, clusterloader2/testing/density/config.yaml, clusterloader2/testing/load/config.yaml
Measure APIResponsivenessPrometheus twice (gather action):
1. First call mimics old APIResponsiveness, but uses new metric instead of the old summary. 
2. Second call uses the new two-level query. 
/ref https://github.com/kubernetes/perf-tests/issues/498
=> Enable simple Promethues API responsiveness measurement.

clusterloader2/testing/density/config.yaml, clusterloader2/testing/load/config.yaml
Flag is already enabled by enable_system_pod_metrics.yaml override in
several tests (perf-tests presubmits for example, see test-infra).
In this commit, system pod metrics measurement is being enabled if
$ENABLE_SYSTEM_POD_METRICS flag is set.
This will result in all system pods being listed twice (first in start
action, then in gather action) for all tests that use this override.
=> Enable collection of system pod metrics if flag is set

clusterloader2/pkg/measurement/common/slos/network_programming.go, clusterloader2/pkg/measurement/interface.go, clusterloader2/pkg/measurement/manager.go
Fix for 
https://github.com/kubernetes/perf-tests/issues/807
=> ClusterLoader2:  NetworkProgrammingLatency disable on scraping kube-proxy disabled

perfdash/Makefile, perfdash/config.go, perfdash/deployment.yaml, perfdash/parser.go, perfdash/parser_test.go
For each build, perfdash will display maximum restart count per each
container name (for example metadata-proxy, kube-apiserver,
etcd-container etc).
In addition a test was added and makefile was changed to run tests
before run.
Testing:
- started perfdash locally
=> Add support for viewing system pod metrics in perfdash

perfdash/Makefile, perfdash/config.go, perfdash/deployment.yaml
New prometheus summary naming was introduces in pull #837. It resulted
in metrics not being visible for new runs in perfdash. This commit adds
handling of these summaries.
Testing:
- ran perfdash locally
=> Add parsing for Prometheus_simple summaries

clusterloader2/pkg/measurement/common/system_pod_metrics.go, clusterloader2/pkg/measurement/common/system_pod_metrics_test.go, clusterloader2/testing/density/config.yaml, clusterloader2/testing/experiments/ignore_known_gce_container_restarts.yaml, clusterloader2/testing/experiments/ignore_known_kubemark_container_restarts.yaml, clusterloader2/testing/load/config.yaml
In this change, restart count validation is implemented. Note that it
will only affect tests, which have this feature enabled (by using
enable_restart_count_check.yaml override).
Testing:
* ran kubemark test locally using clusterloader, cluster running on GCE
/hold 
need to finish testing locally
=> Enable restart count validation in clusterloader

clusterloader2/pkg/measurement/common/etcd_metrics.go, clusterloader2/pkg/measurement/util/histogram.go, clusterloader2/pkg/measurement/util/histogram_test.go
This patch enables clusterloaderv2 etcd measurements for multiple master
nodes.
ref: https://github.com/kubernetes/perf-tests/issues/246
Signed-off-by: alejandrox1 <alarcj137@gmail.com>
=> Enabled HA support for ETCD measurements

clusterloader2/pkg/config/template_functions.go
Adds an explicit check on division by zero for template functions. This way we get more precise errors like:
```
config reading error: replacing placeholders error: template: :34:23: executing "" at <DivideInt $totalPods $namespaces>: error calling DivideInt: division by zero
```
instead of weird ones like:
```
config reading error: decoding failed: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal number -4611686018427388 into Go struct field Phase.ReplicasPerNamespace of type int32
```
Part of #887
=> Check division by zero in template func

clusterloader2/testing/experiments/ignore_known_gce_container_restarts.yaml
/assign @pierewoj 
/assign @mm4tt
=> Allow for 2 restarts of CoreDNS in tests.

clusterloader2/testing/density/config.yaml, clusterloader2/testing/load/config.yaml
Without it the `startTime` is set to `time.Zero` which results in querying metrics for the whole lifetime of a cluster while we should query only for the time of the test.
=> Add missing start for APIResponsivenessPrometheusSimple

clusterloader2/pkg/test/simple_test_executor.go
This is useful in some cases, e.g. when creating ClusterRoleBinding for ServiceAccount the namespace is required to be passed explicitly in the subject object.
=> Make .Namespace variable to be available in test specs

clusterloader2/pkg/measurement/common/system_pod_metrics.go
This is a change in clusterloader system pod metrics measurement. To
speed up rootcausing, in this change restart reason field is added to
the measurement output.
Testing:
- set up cluster with 1 node
- ran density test with enabled system_pod_metrics
- restarted one container manually
- verified that SystemPodMetrics artifact is generated properly
=> Add last restart reason to system pod metrics

clusterloader2/testing/density/config.yaml
This reverts commit #904 
Caused:
Error: scheduler throughput: actual throughput 23 lower than threshold 90
https://gke-scalability-prow.corp.goog/view/gcs/gke-scalability-prow/logs/ci-kubernetes-e2e-gke-1.16-100-performance/1197481369819680772
/cc mm4tt oxddr
=> Revert "Start enforcing scheduler throughput to be 90+ in density test"

run-e2e-with-prometheus-fw-rule.sh
Prometheus monitoring does not work on private GKE clusters.
There was https://github.com/kubernetes/test-infra/pull/15044 to fix that, but it did not propagate to all kubekins images.
This is a temporary hack to overcome that.
=> Ability to add Prometheus port firewall rule

clusterloader2/pkg/measurement/common/system_pod_metrics.go, clusterloader2/pkg/measurement/common/system_pod_metrics_test.go
This feature is mostly used for detecting crashlooping system
components. Single restart of any component may be ok, see discussion in
https://github.com/kubernetes/perf-tests/pull/908.
At this point, tests will fail if any container (which is not present in
overrides) has even one restart. To simplify this, in this change
support for 'default' max allowed restart count was added. Setting it
will be as simple as adding 'default: X' in the overrides map. Note that
this won't be applied for containers that have some threshold specified.
=> Allow changing default allowed restart count

run-e2e-with-prometheus-fw-rule.sh
Decrease verbosity of Prometheus firewall rule checking
Prow log viewer extracts its output as an error
/cc wojtek-t
=> Decrease verbosity of Prometheus firewall rule checking

clusterloader2/testing/density/config.yaml, clusterloader2/testing/load/config.yaml
The latter is based on a deprecated metric. The former mimics the behavior using Prometheus and has been already enable in all tests. 
ref https://github.com/kubernetes/kubernetes/issues/73519
=> Use APIResponsivenessPrometheusSimple instead of APIResponsiveness.

clusterloader2/testing/density/config.yaml
This is to catch regressions like https://github.com/kubernetes/kubernetes/pull/85030.
This will affect only tests for 500+ node clusters as in smaller clusters the scheduler QPS setting may be less than 100 and hence to 100 throughput won't be achievable.
=> Start enforcing scheduler throughput in density test

clusterloader2/pkg/config/template_provider.go, clusterloader2/pkg/config/template_provider_test.go
This will make all env variables starting with CL2_ prefix available in the CL2 template files.
It will allow us to leverage the presets mechanism in cl2 templates and (in some cases) use it instead of relying on cumbersome test override files.
The problem it solves is that sometimes we want to set something for almost all (but not all tests) tests.
Currently, the only way to do that is the create an override file and pass it to many test definitions.
This is arduous for many reasons, e.g. it requires at least 2 PRs (one to perf-test with the override file, second to test-infra) and it requires keeping many places in sync.
=> Cl2: Make CL2_* envs available in templates

clusterloader2/pkg/prometheus/manifests/prometheus-prometheus.yaml
See https://github.com/kubernetes/kubernetes/issues/85683 and https://github.com/kubernetes/kubernetes/pull/85797 for context. 
=> Allow Prometheus to run on a tainted heapster node.

clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go, clusterloader2/pkg/measurement/common/slos/prometheus_measurement.go
This allows to clearly identify logs if we have two, distinct instances of the same measurement.
/assign @mm4tt
=> Use Measurement's indentifier in logging.

clusterloader2/pkg/prometheus/manifests/prometheus-prometheus.yaml
This should mitigate: "query processing would load too many samples into memory in query execution" error in gce5000.
ref https://github.com/kubernetes/kubernetes/issues/86082
/assign @mm4tt
=> Increase maxSamples to 100000000 (from default 50000000).

perfdash/Makefile, perfdash/deployment.yaml, perfdash/github-configs-fetcher.go, perfdash/google-gcs-downloader.go, perfdash/perfdash.go
At this point, we need to specify each prow config file explicitly in
deployment yaml. This will be a problem for adding sig-release jobs to
pefdash, since these configs are autogenerated by config forker.
With this change, we'd be able to just specify "githubConfigDir" to the
sig-release dir and perfdash will ingest all the configs from that dir.
Testing:
* started perfdash locally with
githubConfigDir=path-to-sig-release-configs, verified configs are
fetched
* tested that perfadash still works without providing githubConfigDir
flag
=> Implement fetching prow config from directories

perfdash/Makefile, perfdash/deployment.yaml
Also, bumping version to 2.17 so that new version of perfdash can be
deployed.
Testing:
* ran manually using make run, verified release jobs are present in the
ui
=> Add sig-release GCE-100 jobs to perfdash

clusterloader2/testing/node-throughput/config.yaml, clusterloader2/testing/node-throughput/rc.yaml, clusterloader2/testing/node-throughput/windows_override.yaml
Add support for windows nodes to do node-throughput test.
1. the pod startup latency threshold on windows node is not clear yet, so set 20m for now.
cmd to run on k8s windows cluster:
$GOPATH/src/k8s.io/perf-tests/run-e2e.sh cluster-loader2 --nodes=1 --provider=gce --report-dir=/workspace/_artifacts --testconfig=testing/node-throughput/config.yaml --testoverrides=./testing/node-throughput/windows_override.yaml
=> Support for windows nodes

clusterloader2/pkg/measurement/common/scheduler_latency.go, perfdash/parser.go
add e2e_scheduling_duration_seconds to perf_test
ref  [#86216](https://github.com/kubernetes/kubernetes/issues/86126)
=> add scheduling cycle e2e latency

clusterloader2/testing/experimental/storage/pod-startup/config.yaml, clusterloader2/testing/node-throughput/config.yaml
Some scalability tests are failing after https://github.com/kubernetes/perf-tests/pull/915 was merged
https://k8s-testgrid.appspot.com/sig-scalability-experiments#storage
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-storage-scalability/1205162963401445380
https://k8s-testgrid.appspot.com/sig-scalability-node#node-throughput
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-node-throughput/1205121688543432710
```
[measurement call APIResponsiveness - APIResponsiveness error: unknown measurement method APIResponsiveness
measurement call APIResponsiveness - APIResponsiveness error: unknown measurement method APIResponsiveness]
```
/cc oxddr
=> Use APIResponsivenessPrometheusSimple in legacy test configs.

clusterloader2/api/types.go, clusterloader2/pkg/tuningset/global_qps_load.go, clusterloader2/pkg/tuningset/simple_tuning_set_factory.go
It is essentially the same as QPSLoad, but all phases share the same limiter.
The difference compared to "standard" qpsLoad: if you have n phases running simultaneously, with QPS limit set to x:
* globalQPSLoad will run all of them with max rate of x
* qpsLoad will maintain limiter for each of n phases separately, so this will give total rate of n * x.
=> Implement GlobalQPSLoad tuning set.

clusterloader2/pkg/measurement/common/profile.go
This patch enables clusterloaderv2 profile measurements for multiple master
nodes.
ref: #246
Signed-off-by: alejandrox1 <alarcj137@gmail.com>
=> Enabled HA support for profile measurements

clusterloader2/pkg/tuningset/global_qps_load.go, clusterloader2/pkg/tuningset/simple_tuning_set_factory.go
The previous attempt doesn't work. Cluster loader creates new instance of GlobalQPSLoad for all phases, so fact that they use inner *rate.Limiter doesn't change anything.
=> Fix GlobalQPSLoad to really share rate.Limiter

clusterloader2/pkg/measurement/common/metrics_for_e2e.go
There aren't that many of those, and may appear useful at some point.
=> Don't filter apiserver metrics

clusterloader2/testing/node-throughput/config.yaml
With containerd tests already fixed, let's bump it to compare docker and containerd at higher throughputs.
=> Bump throughput in scalability node tests

clusterloader2/pkg/measurement/common/wait_for_nodes.go, clusterloader2/pkg/measurement/util/object_store.go, clusterloader2/pkg/measurement/util/wait_for_nodes.go
One of the use-cases for this is to allow running simple ClusterAutoscaler tests.
=> Implement WaitForNodes measurement

clusterloader2/testing/node-throughput/config.yaml
Reverts kubernetes/perf-tests#969
=> Revert "Bump node throughput to 10pods/s"

clusterloader2/clean-up-old-snapshots.sh
Periodic scalability tests save snapshots of prometheus disks.
That script helps with automatic removal of old snapshots so that project quota won't be exhausted.
It should be executed by separate periodic prow job.
/cc mm4tt
=> Script to remove old prometheus snapshots

clusterloader2/pkg/framework/client/objects.go
It can happen, that 401 is returned on valid request, when token has expired between client-side validation and server-side validation.
/assign @mm4tt
=> Retry also 401 (Unauthorized) errors

clusterloader2/README.md
Adding an information about already existing feature to ClusterLoader2 README.md.
=> [ClusterLoader2] Add information about environment variables to readme

clusterloader2/pkg/framework/client/objects.go, clusterloader2/pkg/framework/client/objects_test.go
We noticed runs where some calls failed with:
```
measurement call InClusterNetworkLatency - InClusterNetworkLatency error: error while applying (/go/src/k8s.io/perf-tests/clusterloader2/pkg/measurement/common/probes/manifests/ping-client-service.yaml): Operation cannot be fulfilled on resourcequotas "gke-resource-quotas": the object has been modified; please apply your changes to the latest version and try again
```
This seems to be the exactly the situation described in https://github.com/kubernetes/kubernetes/issues/67761
=> Retry 409 resource-quotas errors in CL2

clusterloader2/pkg/prometheus/manifests/prometheus-rules.yaml
Hopefully this should allow to easily find an offending kube-proxy
#experimental
/ref https://github.com/kubernetes/perf-tests/issues/1003
=> Precompute network programming latency percentailes by endpoint

util-images/access-tokens/Makefile, util-images/access-tokens/cmd/main.go, util-images/access-tokens/example/example.yaml.template
Changelog:
* Add layer of parallelization per token
* Make requests cheaper with  ResoruceVersion : 0
=> [Access-tokens] Update access-tokens to version v0.0.6

clusterloader2/pkg/measurement/common/wait_for_controlled_pods.go, clusterloader2/pkg/measurement/util/runtimeobjects/runtimeobjects.go
With this change WaitForControlledPodsRunning should work for CRDs wrapping groups of pods with format like:
```
metadata:
namespace: namespace-1
spec:
replicas: 200
selector:
matchLabels:
name: xx
```
i.e.:
* metadata.namespace must point to the namespace that the object lives in
* spec.replicas must describe desired number of pods
* spec.selector must describe a selector that can be used to find all pods associated with given CRD
WaitForControlledPodsRunning will wait until exactly `spec.replica` pods in given namespace match `spec.selector` and is in running state.
=> Modify ListRuntimeObjectsForKind to work for CRDs as well

clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/config/cluster.go, clusterloader2/pkg/measurement/common/etcd_metrics.go
The port number should be configurable instead of hard-coded,
actually, for the cluster which is setup by kubeadm, the insecure
access number is "2381" by default.
It's hard-coded as "2382", this will make end-users face issues
when etcd metrics is needed, change source code to gather data for
end-user does not make sense, we'd better to provide a option so that
the port number could be specified before the job is started.
=> port number of etcd insecure access should be configurable

clusterloader2/testing/density/high-density-config.yaml
This is to allow deprecating density tests in all other places except high-density. See https://github.com/kubernetes/perf-tests/pull/1008#discussion_r375719348
Once this merges I will update the high-density job def to use this new config.
Ref. https://github.com/kubernetes/perf-tests/issues/1007
=> Copy density test into high-density-config

clusterloader2/testing/access-tokens/config.yaml, clusterloader2/testing/access-tokens/deployment.yaml, clusterloader2/testing/access-tokens/role.yaml, clusterloader2/testing/access-tokens/roleBinding.yaml, clusterloader2/testing/access-tokens/serviceAccount.yaml, clusterloader2/testing/access-tokens/token.yaml
Add standalone test for ClusterLoader2 that allows benchmarking and
testing access tokens thresholds.
This test is based on Mateusz's code from github.com/mm4tt/k8s-util.
=> [Access-tokens][ClusterLoader2] Add standalone test

clusterloader2/pkg/measurement/common/etcd_metrics.go
If the ssh connection to the host is successful but the cmd run failed,
the error message should be more helpful instead of misleading us with
ssh connection error.
`runSSHCommand` method provides us a way to judge this based on the return
`code`.
=> Differentiate different kinds of errors

clusterloader2/testing/load/experimental-config.yaml, clusterloader2/testing/load/simple-deployment.yaml
Ref. https://github.com/kubernetes/perf-tests/issues/1007
=> Experimental config with merged density and load

clusterloader2/pkg/prometheus/manifests/prometheus-rules.yaml
Should be "pod" instead of "endpoint".
ref https://github.com/kubernetes/kubernetes/issues/82378
=> Use correct label in kube-proxy precomputes.

clusterloader2/pkg/measurement/common/scheduling_throughput.go, clusterloader2/pkg/measurement/common/wait_for_controlled_pods.go, clusterloader2/pkg/measurement/util/pods.go, clusterloader2/pkg/measurement/util/runtimeobjects/runtimeobjects.go, clusterloader2/pkg/measurement/util/runtimeobjects/runtimeobjects_test.go, clusterloader2/pkg/measurement/util/wait_for_pods.go
This implements an experimental support for waiting for pod updates in WaitForControlledPodsRunning.
```
- name: Starting measurement for waiting for pods
measurements:
- Identifier: WaitForRunningPods
Method: WaitForControlledPodsRunning
Params:
action: start
apiVersion: apps/v1
kind: Deployment
labelSelector: l1 = v1
checkIfPodsAreUpdated: true
operationTimeout: 1h
- name: Create deployments with envVar set to old
phases:
- namespaceRange:
min: 1
max: 1
replicasPerNamespace: 1
tuningSet: 100qps
objectBundle:
- basename: foo
objectTemplatePath: deployment.yaml
templateFillMap:
envToSet: old
- name: Waiting for objects become created
measurements:
- Identifier: WaitForRunningPods
Method: WaitForControlledPodsRunning
Params:
action: gather
```
The new logic is enabled by setting …
=> Add pod update checking to WaitForControlledPodsRunning

clusterloader2/pkg/measurement/common/wait_for_controlled_pods.go, clusterloader2/pkg/measurement/util/runtimeobjects/runtimeobjects.go
In https://github.com/kubernetes/perf-tests/pull/1023 I implemented using dynamic client as a fallback and we agreed that ultimately we want to migrate all cases to dynamic client how it's done in other places.
=> Migrate ListRuntimeObjectsForKind to use dynamic client

clusterloader2/pkg/prometheus/manifests/dashboards/defaults.py, clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.dashboard.py, clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.json
This should ease querying and allows to remove some dedicated graphs as they can be now easily substituted.
=> Add "etcd_operation" and "etcd_type" variables to Grafana dashboard

application-benchmarks/OWNERS, application-benchmarks/README.md
Replaces PR #974.
Just create initial subdirectory, preparatory to actually starting to put data and benchmarks into it.  Initial owners are jberkus and wojtek-t because other contributors don't have Kubernetes accounts yet.  
If this is accepted, next steps are:
Updating /community/sig-scalability with subproject info
Meeting on slack to discuss first projects/information
I'd also like to potentially have a label added to this repo for kind/appbench so that we can tag issues/PRs for this project.
(Apologies for new PR; renaming the directory isn't compatible with squashing the commit)
=> Initial creation of subdirectory for application-benchmarks subproject.

clusterloader2/pkg/measurement/common/wait_for_controlled_pods.go
We should switch default WaitForControllerPodsRunning behavior to the right one: where we correctly distinguish updated pods from state ones.
The original change (https://github.com/kubernetes/perf-tests/pull/1035) has been merged 4 hours ago so maybe let's wait one more day before submitting this.
/hold
=> Change checkIfPodsAreUpdated default to true

clusterloader2/pkg/measurement/common/probes/manifests/dnsLookup/dns-prober-deployment.yaml, clusterloader2/pkg/measurement/common/probes/manifests/ping-client-deployment.yaml, clusterloader2/pkg/measurement/common/probes/manifests/ping-server-deployment.yaml
ref https://github.com/kubernetes/kubernetes/issues/87143
/assign @mm4tt
=> probers: log to file 

clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/config/cluster.go, clusterloader2/pkg/framework/framework.go, clusterloader2/pkg/test/simple_test_executor.go
It's not likely execution is finished normally everytime, the execution
might be aborted abnormally, this will make the auto managed namespaces
become orphans and no chance to be clean up on the test machine, thus,
impact the data we got from execution.
The change cleans up all those namespaces before the execution, give
the execution a fairly clean environment.
=> clean up stale namespaces before execution

clusterloader2/testing/load/experimental-config.yaml, perfdash/config.go
Add experiment specific metric to Perf-Dash.
Rename experiment specific metric in ClusterLoader2 experiment config.
Ref. #1007
/assign @mm4tt
=> [Remove density] Fix metrics in perf dash

clusterloader2/pkg/measurement/common/slos/api_responsiveness.go, clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go
Also remove logic for special handling of  big clusters in api_responsiveness measurement.
Cherry picks https://github.com/kubernetes/perf-tests/pull/673
/assign @mm4tt
=> Use 30s as the threshold for cluster-scoped list calls (1.15)

clusterloader2/pkg/measurement/common/scheduler_latency.go, clusterloader2/vendor/k8s.io/kubernetes/pkg/scheduler/metrics/metrics.go, clusterloader2/vendor/vendor.json, perfdash/parser.go
Also, update vendored `k8s.io/kubernetes/pkg/scheduler/metrics`.
=> clusterloader2: collect scheduling_algorithm_duration_seconds to see algorithm latency without binding

clusterloader2/pkg/measurement/common/slos/api_responsiveness.go, clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go
Also remove logic for special handling of  big clusters in api_responsiveness measurement.
Cherry picks #673
/assign @mm4tt
=> Use 30s as the threshold for cluster-scoped list calls (1.14)

clusterloader2/pkg/measurement/common/scheduling_throughput.go, clusterloader2/testing/load/experimental-config.yaml
* Add measurmentInterval parameter to SchedulingThroughput
* SchedulingThroughput threshold compares to max value, instead of 99th
percentile
=> [Remove density] Rework SchedulingThroughput

perfdash/Makefile
Go modules need to be explicitly disabled, as in newer Go versions, they are enabled by default. Perfdash won't build with Go modules enabled. 
/assign @mm4tt
=> Disable Go modules in perfdash make targets.

clusterloader2/pkg/prometheus/prometheus.go
This method used to be called only for kubemark clusters, but it's not anymore. When it's called for non-kubemark cluster the log statement is confusing.
=> Fix confusing log line in exposeAPIServerMetrics

clusterloader2/pkg/chaos/nodes.go, clusterloader2/testing/load/config.yaml
=> [NodeKiller] Change rounding of a number of selected nodes

perfdash/config.go
Time to display collected metrics from test/integration/scheduler_perf.
Jenkins Job: https://github.com/kubernetes/test-infra/pull/16421
Fixes: https://github.com/kubernetes/kubernetes/issues/86972
=> perfdash: display metrics from ci-benchmark-scheduler-perf-master

clusterloader2/testing/chaosmonkey/ignore_node_killer_container_restarts_100.yaml
Ref. #1005 
Backporting NodeKiller fixes to 1.16 branch
=> [NodeKiller] Add override to ignore expected crashes

clusterloader2/pkg/chaos/monkey.go, clusterloader2/pkg/chaos/nodes.go, clusterloader2/pkg/framework/client/objects.go, clusterloader2/pkg/test/simple_test_executor.go, clusterloader2/testing/load/config.yaml
- [NodeKiller] Schedule reboot and disconnect from node
- [NodeKiller] Change rounding of a number of selected nodes
- [NodeKiller] Add summary
- Node-killer avoid killing nodes where prometheus is running
Ref. #1005
=> Cherry-pick NodeKiller changes

clusterloader2/pkg/measurement/common/slos/windows_node_resource_usage.go, clusterloader2/pkg/prometheus/gce_windows_util.go, clusterloader2/pkg/prometheus/manifests/prometheus-prometheus.yaml, clusterloader2/pkg/prometheus/manifests/prometheus-windows-scrape-configs.yaml, clusterloader2/pkg/prometheus/prometheus.go, clusterloader2/testing/node-throughput/config.yaml, clusterloader2/testing/node-throughput/windows_override.yaml
1. As windows server container doesn't support privileged containers, so to collect the cpu usage per process, have to install the [wmi_exporter](https://github.com/martinlindhe/wmi_exporter#installation) onto windows node using `gcloud ssh` command. As a result, this feature is only supported for GCE cluster.
2. Use the "[Additional Scrape configs](https://github.com/coreos/prometheus-operator/blob/master/Documentation/additional-scrape-config.md)" in prometheus-operator to scrape windows node.
3. Add a new measurement to collect the metrics once when all pods are running, as we want to find out if there's any noticeable high cpu usage process. Later on, we may change to calculate the percentiles during the test run and put it on perf-dash board.
=> Add measurement to collect windows node cpu usage per process

clusterloader2/pkg/measurement/common/slos/windows_node_resource_usage.go, clusterloader2/pkg/prometheus/manifests/prometheus-windows-scrape-configs.yaml
Found we couldn't get the cpu usage per process data during windows [load test](https://testgrid.k8s.io/google-windows#gce-windows-node-throughput).
So figured out that the scraping is pretty slow for `process` collector in wmi_exporter.
Tried locally, the prometheus server took around 1m30s to scrape windows target data when all 80 pods are running, so expand the scrape_timeout and interval.
Also created an [issue](https://github.com/martinlindhe/wmi_exporter/issues/487) for tracking
=> Expand the scraping timeout

clusterloader2/pkg/chaos/monkey.go, clusterloader2/pkg/chaos/nodes.go, clusterloader2/pkg/test/simple_test_executor.go
With this change I tried to introduce some sort of wait mechanism for the NodeKiller subroutine.
The rationale behind is it avoiding that cluster nodes are left in a broken state by NodeKiller if the test finishes while downtime is being simulated for some nodes.
Now the chaos monkey can return back to its caller a WaitGroup that can be used to wait for the subroutine termination before proceeding to test summary.
/assign @jprzychodzen 
Ref: #1130
=> [NodeKiller] Rebooting broken nodes before exiting the test

clusterloader2/pkg/chaos/nodes.go
This reverts commit f1647f4e3c1f05c29c5d04596a876371893420b7.
Required to make Node Killer work again - with shutdown it silently fails.
/hold
=> Revert "[NodeKiller] Schedule reboot and disconnect from node"

clusterloader2/pkg/config/template_provider.go, clusterloader2/pkg/config/template_provider_test.go
Without doing it, it's impossible to easily override boolean param via env. E.g. if I do
```
--env=ENABLE_MY_FEATURE=false
```
The 'false' will be treated as string, and then in the config file the if statement like this:
```
{{if .ENABLE_MY_FEATURE}}
...
{{end}}
```
Will evaluate to true and will be executed, because "false" is non-empty string that evaluates to true :)
=> Unpack the string values from the CL2_.* envs

clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/config/cluster.go, clusterloader2/pkg/measurement/common/etcd_metrics.go, clusterloader2/pkg/measurement/common/profile.go, clusterloader2/pkg/measurement/common/scheduler_latency.go, clusterloader2/pkg/prometheus/prometheus.go
AKS, much like GKE, does not support SSH to master nodes or similar methods of contacting them. This PR avoids trying to do so as part of cluster loader tests for AKS. Without this, the TestMetrics gather step fails to SSH without a signer for the provider.
I imagine the same patterns would be broadly applicable for managed clusters. Perhaps we could generalize this?
=> clusterloader2: improve experience on aks

clusterloader2/pkg/prometheus/gce_windows_util.go, clusterloader2/pkg/prometheus/manifests/prometheus-windows-scrape-configs.yaml, clusterloader2/testing/node-throughput/windows_override.yaml, clusterloader2/testing/windows-tests/OWNERS, clusterloader2/testing/windows-tests/config.yaml, clusterloader2/testing/windows-tests/rc.yaml, clusterloader2/testing/windows-tests/windows_override.yaml
1. Added a `windows-tests` folder to contain all windows yaml configs, and planning to deprecate the windows test configs in `node-throughput` folder later.
2. Reference to the pre-release fast version of wmi_exporter, so decrease the scrape interval and timeout, also change to `CL2_` variables for easier update in test definitions.
3. Bumped the pause image version
=> Add load test for iis container

.gitignore, clusterloader2/pkg/chaos/nodes.go, clusterloader2/pkg/prometheus/prometheus.go, clusterloader2/pkg/util/ssh.go
Following up with #1137 we are starting to decouple code that depends on real cloud components to allow unit testing, starting with util.SSH. This utility executes commands against a GCloud cluster so it should be abstracted with an interface and replaceable in a go test.
- create interface for command execution in cluster nodes through SSH
- refactor code that is currently using util.SSH to use the new executor interface
=> Decouple SSH command execution in util.SSH to enable unit testing

clusterloader2/testing/chaosmonkey/ignore_node_killer_container_restarts_100.yaml
Node Killer is running under https://testgrid.k8s.io/sig-scalability-experiments#gce-cos-master-scalability-100-nodekiller and sometime there are failing tests.
Some components are missing from [ignore override](../tree/master/clusterloader2/testing/chaosmonkey/ignore_node_killer_container_restarts_100.yaml).
Log 1:
```
[measurement call TestMetrics - TestMetrics error: [restart counts violation: RestartCount(coredns-78ff568f7c-8ddpw, coredns)=1, want <= 0]]
```
Log 2:
```
[measurement call TestMetrics - TestMetrics error: [restart counts violation: RestartCount(volume-snapshot-controller-0, volume-snapshot-controller)=1, want <= 0]]
```
Log 3:
```
[measurement call TestMetrics - TestMetrics error: [restart counts violation: RestartCount(volume-snapshot-controller-0, …
```
=> [NodeKiller][Config] Add known components to node killer expected crashes

clusterloader2/pkg/measurement/common/bundle/test_metrics.go
This PR adds action name + measurement name to the TestMetrics action execute log, to make point of failure more obvious to an end user.
Before the fix:
```
Errors: [measurement call TestMetrics - TestMetrics error: [unexpected error (code: 0) in ssh connection to master: &errors.errorString{s:"error getting signer for provider local: 'error reading SSH key /root/.ssh/id_rsa: 'open /root/.ssh/id_rsa: no such file or directory''"}]
measurement call TestMetrics - TestMetrics error: [unexpected error (code: 0) in ssh connection to master: &errors.errorString{s:"error getting signer for provider local: 'error reading SSH key /root/.ssh/id_rsa: 'open /root/.ssh/id_rsa: no such file or directory''"}
unexpected error (code: 0) in ssh connection to master: &errors.errorString{s:"error getting …
```
=> clusterloader2: more info to TestMetrics action execute error logs

clusterloader2/testing/load/config.yaml, clusterloader2/testing/load/deployment.yaml
As a part of #1125, default value of the variables
ENABLE_CONFIGMAPS, ENABLE_DAEMONSETS, ENABLE_JOBS, ENABLE_SECRETS, and ENABLE_STATEFULSETS are set to true, and these values are not overriden in any of the tests. The config file and deployment yaml can now be be simplified as discussed in https://github.com/kubernetes/perf-tests/issues/1036#issuecomment-607631768 .
=> cleanup the clusterloader2 load testing config file and deployment yaml

clusterloader2/pkg/measurement/common/scheduler_latency.go, clusterloader2/vendor/k8s.io/component-base/metrics/testutil/metrics.go, clusterloader2/vendor/vendor.json, perfdash/parser.go
Collecting the following extension points:
- PreFilter
- PreFilterExtensionAddPod
- PreFilterExtensionRemovePod
- Filter
- PreScore
- Score
- ScoreExtensionNormalize
- PreBind
- Bind
- PostBind
- Reserve
- Unreserve
- Permit
As per https://github.com/kubernetes/perf-tests/issues/1074#issuecomment-589963229
=> clusterloader2: display extension points metrics

clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go, clusterloader2/pkg/measurement/common/slos/network_programming.go, clusterloader2/pkg/measurement/common/slos/network_programming_test.go, clusterloader2/pkg/measurement/common/slos/prometheus_measurement.go, clusterloader2/pkg/measurement/common/slos/windows_node_resource_usage.go
Execute() method in `prometheus_measurement.go` could return multiple summary, but the Gather() method return only one summary, which seems not reasonable.
So modify it to collect multiple summaries in one file for prometheus measurements.
=> Return multiple summaries in Gather method

clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/measurement/common/bundle/test_metrics.go
Golang >=1.12 throws a "suspect or" error
Before the change:
```
% go test ./...
?   	k8s.io/perf-tests/clusterloader2/api	[no test files]
pkg/measurement/common/bundle/test_metrics.go:43:3: Errorf format %s has arg metrics of wrong type k8s.io/perf-tests/clusterloader2/pkg/measurement/common/bundle.testMetrics
pkg/measurement/common/bundle/test_metrics.go:46:3: Errorf format %s has arg metrics of wrong type k8s.io/perf-tests/clusterloader2/pkg/measurement/common/bundle.testMetrics
pkg/measurement/common/bundle/test_metrics.go:49:3: Errorf format %s has arg metrics of wrong type k8s.io/perf-tests/clusterloader2/pkg/measurement/common/bundle.testMetrics
pkg/measurement/common/bundle/test_metrics.go:52:3: Errorf format %s has arg metrics of wrong type …
```
=> ClusterLoader - fix provider check that is always true

clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/config/cluster.go, clusterloader2/pkg/measurement/common/resource_usage.go, clusterloader2/pkg/measurement/util/gatherers/container_resource_gatherer.go, clusterloader2/pkg/measurement/util/gatherers/resource_gather_worker.go, clusterloader2/pkg/measurement/util/kubelet/kubelet.go
This is intended for clusters whose Kubelets
are not configured with the default 10250 port.
=> ClusterLoader - add kubelet port override option

clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/config/cluster.go, clusterloader2/pkg/test/simple_test_executor.go
clusterloader automatically creates namespaces for testing and deletes the namespaces and  all resources in the namespaces after the test exits (successfully or failed).  We propose adding a flag _delete-auto-namespaces_ to specify whether or not delete the namespace after a test.
=> clusterloader: add a new flag delete-automanaged-namespaces

perfdash/deployment.yaml
/cc @mm4tt 
as discussed with Matt I want to remove duplicated manifests from https://github.com/kubernetes/k8s.io/tree/master/perf-dash.k8s.io and instead use the ones from this repository and removing `namespace` gives me possibility to use the manifest from this repository with `-n perfdash` flag
Signed-off-by: Bart Smykla <bsmykla@vmware.com>
=> Remove namespace field from perfdash deployment

clusterloader2/pkg/measurement/common/scheduler_latency.go, clusterloader2/pkg/measurement/util/gatherers/container_resource_gatherer.go, clusterloader2/pkg/prometheus/prometheus.go, clusterloader2/pkg/util/cluster.go
This function was moved to private in k8s >=1.16,
but ClusterLoader still depends on it in a few places.
Copying the function in the meantime unblocks upgrading Go,
upgrading k8s, and moving to Go modules in ClusterLoader.
Suggested in https://github.com/kubernetes/perf-tests/pull/1171#discussion_r409777034 that I do this PR first.
=> ClusterLoader: copy unexported legacy function

clusterloader2/testing/density/config.yaml, clusterloader2/testing/load/config.yaml, clusterloader2/testing/load/experimental-config.yaml
Configure tests to allow custom timeout for starting probes measurements.
Ref. #1110
=> Add configurable timeout for probes in configs

clusterloader2/pkg/measurement/common/scheduler_latency.go, perfdash/parser.go
Both predicate_evaluation and priority_evaluation operation metrics are replaced
with filter, resp. score extension points.
Also, preemption_evaluation, resp. binding operation metrics are replaced with
scheduler_scheduling_algorithm_preemption_evaluation_seconds_bucket, resp.
scheduler_binding_duration_seconds_bucket metrics.
=> clusterloader2: drop metrics deprecated in 1.19

perfdash/Makefile, perfdash/deployment.yaml
This is to include https://github.com/kubernetes/perf-tests/pull/1172
=> Bump perf-dash to 2.23

clusterloader2/api/default.go, clusterloader2/api/types.go, clusterloader2/api/validation.go, clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/config/cluster.go, clusterloader2/pkg/flags/flags.go, clusterloader2/pkg/test/simple_test_executor.go, clusterloader2/pkg/test/test.go, clusterloader2/testing/access-tokens/config.yaml, clusterloader2/testing/density/config.yaml, clusterloader2/testing/density/high-density-config.yaml, clusterloader2/testing/density/legacy/config.yaml, clusterloader2/testing/experimental/storage/pod-startup/config.yaml, clusterloader2/testing/l4ilb/config.yaml, clusterloader2/testing/load/config.yaml, clusterloader2/testing/load/experimental-config.yaml, clusterloader2/testing/load/experimental/bundled_services_and_deployments.yaml, clusterloader2/testing/load/legacy/config.yaml
This PR is to separate namespace specific configurations from cluster level configurations (e.g., kubeconfig, master-ip). The cluster configurations belong to config.ClusterConfig and are specified as the command line options while namespace configuration is a part of api.Config and deigned in the testconfig.yaml file.
1.  A new structure _NamespaceConfig_ is defined for namespace parameters as a part of api.Config and the values are specified in the testconfig yaml file.  If a parameter is not specified, a default value is used.
2. A new parameter "_Prefix_" is added to specify the prefix of auto-created namespaces. Clusterloader uses the specified prefix if set otherwise uses the default "_test-\<random string\>_".
3. Add two files _api.default.go_ and _api.validate.go_  for setting …
=> clusterloader: enhance namespace configurations

clusterloader2/pkg/config/cluster.go, clusterloader2/pkg/prometheus/experimental.go, clusterloader2/pkg/prometheus/prometheus.go
When using pod-utils for SIG scalability test jobs, clusterloader was attempting to snapshot Prometheus' PDs to Prow cluster project. The proposed flag `experimental-snapshot-project` (which defaults to `PROJECT` environment variable value which is set [here](https://github.com/kubernetes/test-infra/blob/5f62df0ca89fd93fdcc3f1a7a76019bb115ffa47/kubetest/main.go#L775)) is added to be utilized by gcloud command that performs snapshotting.
=> Pass proper GCP project with snapshots storage to PrometheusController

perfdash/perfdash-service.yaml
/cc @mm4tt 
As perfdash is currently deployed at the `aaa` cluster
at community owned infrastructure and we don't have to use
services with LoadBalancer types it's good to change it
in the source repository and then removing unnecessary
manual instructions from the k/k8s.io [repository](https://github.com/kubernetes/k8s.io/tree/master/perf-dash.k8s.io)
Signed-off-by: Bart Smykla <bsmykla@vmware.com>
=> Changed perfdash service type to NodePort

clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.dashboard.py, clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.json
`rate` query function better reflects the change in time in case of `etcd_network_client_grpc_sent_bytes_total` metric than `irate`.
=> Change query function to rate for etcd_network_client_grpc_sent_bytes_total metric

clusterloader2/testing/load/experimental-config.yaml
As a part of #1125, default value of the variables
ENABLE_CONFIGMAPS, ENABLE_DAEMONSETS, ENABLE_JOBS, ENABLE_SECRETS, and ENABLE_STATEFULSETS are set to true, and these values are not overriden in any of the tests. The clusterloader2 load testing  [experimental-config.yaml](https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/testing/load/experimental-config.yaml) file can now be be simplified as discussed in https://github.com/kubernetes/perf-tests/issues/1036#issuecomment-617133148
=> Cleanup clusterloader2 load testing experimental config file

golang/Makefile, golang/build-go.sh, golang/build-kubernetes.sh, golang/push.sh
The script will be executed in a container by a Prow Job to automate building Kubernetes with custom Go version. Description of the script's content in short:
* clone the golang repo and build it, set the tag for kube-cross,
* clone the kubernetes/release repo and copy just built Go SDK to `kubernetes/release/images/build/cross`,
* modify Dockerfile of kube-cross to use just built Go SDK & build kube-cross image,
* clone the kubernetes/kubernetes repo and build Kubernetes using just built kube-cross image,
* push the custom Kubernetes build.
=> Create a script for building Kubernetes using golang tip

clusterloader2/testing/load/configmap.yaml, clusterloader2/testing/load/deployment.yaml, clusterloader2/testing/load/secret.yaml
Each deployment in load test has now both secret and configmap mounted. 90% of them are marked as immutable, only 10% is mutable (as it was before).
Scalability test coverage is a requirement for graduating "Immutable Secrets/ConfigMaps" feature to Beta.
This has been scale-tested already and the features was enabled by default in https://github.com/kubernetes/kubernetes/pull/89594
ref https://github.com/kubernetes/enhancements/issues/1412
=> Extend load test to immutable secrets/configmaps

network/benchmarks/netperf/Dockerfile, network/benchmarks/netperf/launch.go, network/benchmarks/netperf/nptest/nptest.go
The SCTP protocol can be tested using the same iperf3 client command line as the TCP protocol with the addition of a single parameter (--sctp).  The test parameters and output are otherwise the same as the TCP protocol.
Changed the Dockerfile definition to pull and rebuild and the latest stable version of [iperf-3.1](https://downloads.es.net/pub/iperf/), because the current iperf-3.0 does not support SCTP.
=> Add sctp support for network performance test

clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.dashboard.py, clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.json
Add a set of new graphs to Graphana dashboard, using `quantile_over_time(0.99,` query.
=> Add aggregated graphs to master dashboard

clusterloader2/pkg/framework/client/objects.go, clusterloader2/pkg/prometheus/experimental.go, clusterloader2/pkg/prometheus/manifests/0ssd-storage-class.yaml, clusterloader2/pkg/prometheus/prometheus.go
=> Snapshot Prometheus disk after tearing Prometheus down

clusterloader2/pkg/measurement/common/scheduler_latency.go, clusterloader2/pkg/measurement/util/gatherers/container_resource_gatherer.go, clusterloader2/pkg/prometheus/prometheus.go, clusterloader2/pkg/util/cluster.go
Some utils like kubeadm will label master node as
"node-role.kubernetes.io/master=''" so it would be better to check
labels as additional signal. If that label is not set, it does not
affect the existing logic.
fix #1191
=> Clusterloader2: check labels additionally to decide master node

dns/README.md, dns/cluster/dnsperf-deploy.yaml, dns/jsonify/main.go, dns/py/data.py, dns/py/params.py, dns/py/run_perf.py, dns/py/runner.py
This change supports running dnsclient as a deployment. The replicas can be configured by editing the cluster/dnsperf-deploy.py, it will be made configurable in a followup change. This will help measure ClusterDNS and NodeLocal DNSCache performance at scale.
=> Run dnsclient as a deployment in DNS performance tests

clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go, clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus_test.go, clusterloader2/pkg/measurement/common/slos/prometheus_measurement.go
Improvements:
1.  Added unit tests to cover all functionality
2. Refactor code, so it's IMO structured better.
One remaining thing is to move each measurement into it's own package. Currently, due to similarity of measurements, I've hit names collision few times while working on this PR.
=> Improve api_responsiveness_prometheus

golang/Makefile, golang/build-kubernetes.sh
`ci-build-and-push-k8s-at-golang-tip` job fails due to the changes in kubernetes/release repo (namely in `k8s.io/release/images/build/cross` directory). The PR enables fixing the commit of kubernetes/release repo to work around this issue.
This is a short-term fix - the script will need further adjustments to its logic in the future to handle new kubernetes/release kube-cross building procedure.
=> Add custom k/release repo commit env var

clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go, clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus_test.go
Add test to verify log statements (they are on of the interfaces for this
measurement). Also take advantage of t.Run method in tests.
=> Fix incorrect order of apiCalls in API latency SLO measurement

clusterloader2/pkg/framework/framework.go
When there is no manifest file matching a provided pattern, Clusterloader does not report any errors or warnings, which makes debugging difficult. For example, the prometheus manifest path is relative to `$GOPATH`. If the path is mis-configured, the matching manifest files will be empty and Clusterloader will fail to create the objects silently. It is very hard to capture such a configuration issue without a warning message. A specific example is that `$GOPATH` will not be expanded properly if a user runs Clusterloader as a sudo user but forgot to set the flag `-E` or` --preserve-env=GOPATH`.
This PR generates a warning message if there is no matching manifest file.
=> Clusterloader2: add a warning message for no matching manifest file

Makefile, verify/test.sh
I've split all packages into ones using Go modules and ones still relying on
vendor/. They are tested separately.
ref https://github.com/kubernetes/perf-tests/issues/552
=> Second attempt to run unit tests on Prow

clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go
=> Do not filter out "events" in API call latency measurement.

Makefile, clusterloader2/pkg/prometheus/manifests/dashboards/Makefile, clusterloader2/pkg/prometheus/manifests/dashboards/dns.json, clusterloader2/pkg/prometheus/manifests/dashboards/gcp-api.json, clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.json, clusterloader2/pkg/prometheus/manifests/dashboards/network.json, clusterloader2/pkg/prometheus/manifests/dashboards/slo.json, verify/verify-dashboard-format.sh
This removes an external dependecy from presubmit (python3 should be included in
golang docker images).
ref https://github.com/kubernetes/perf-tests/issues/552
/assign @mm4tt
=> Use python3 instead of jq to format dashboards.

clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/config/cluster.go, clusterloader2/pkg/prometheus/prometheus.go
In the current implementation, the prometheus manifest file path is relative to` $GOPATH`. This PR enables to configure the path prefix through a new command line flag `--prometheus-manifest-path`. If not specified, the default value `$GOPATH` is used.  The prometheus manifest file path parameters are changed to PrometheusConfig's fields.
=> Clusterloader2: make the prometheus manifest path configurable

clusterloader2/pkg/config/template_functions.go
This PR changes the default` IncludeFile `path prefix from the clusterloader binary location to the clusterloader source path, which logically makes more sense.  It also checks if the `IncludeFile` path in the manifest file is an absolute path or not. If it's an absolute path, the default path prefix will not be joined.
=> Clusterloader2: Change the default IncludeFile path

clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/prometheus/prometheus.go
Without this, we will only know at the end of the test that the project is not configured
=> Add validation for Prometheus config

clusterloader2/pkg/measurement/util/runtimeobjects/runtimeobjects.go
If the List method returns error the list object is nil and accessing list.Items results in segfault.
Ref. https://github.com/kubernetes/perf-tests/issues/1248
=> Fix segfault in GetNumObjectsMatchingSelector

clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/config/cluster.go, clusterloader2/pkg/modifier/modifier.go, clusterloader2/pkg/modifier/modifier_test.go, clusterloader2/pkg/test/test.go
This change enables runetime test config change - skipping any number of
steps without a need to modify config file.
=> Add flag --skip-steps

clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/config/cluster.go, clusterloader2/pkg/modifier/modifier.go, clusterloader2/pkg/modifier/modifier_test.go, clusterloader2/pkg/test/test.go
This change enables runetime test config change - skipping any number of
steps without a need to modify config file.
Cherry-pick from master, commit f4b2903b
=> Add flag --skip-steps (1.18)

golang/build-kubernetes.sh
`build-and-push-k8s-at-golang-tip` builds Kubernetes v1.18 that does not contain k/k [PR](https://github.com/kubernetes/kubernetes/pull/90806) that increases Kubemark nodes objects. The proposed cherry-pick is a quick workaround for that issue.
=> Enable Kubemark nodes objects size increase in golang tests

golang/build-kubernetes.sh
The command was cherry-picking a merge commit and it didn't know relative to which of its parents should the diff be taken against, hence `ci-build-and-push-k8s-at-golang-tip` job was [failing](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-build-and-push-k8s-at-golang-tip/1261187637507526656). `-m 1` is equivalent to taking the first parent of the aforementioned merge commit (the one that is of interest for us - Kubemark cluster nodes objects increase).
/cc mm4tt
=> Fix cherry-picking k8s commit in golang tests

clusterloader2/pkg/config/template_provider.go, clusterloader2/pkg/config/template_provider_test.go
This is to fix issues when `1` is parsed as `true`, e.g. failing presubmit in https://github.com/kubernetes/perf-tests/pull/1262
=> Parse envs first as numbers before parsing them as booleans

golang/build-kubernetes.sh
Follow-up of the fix attempt in #1261. The test job failed because git user identity wasn't set before cherry-picking k/k commit.
I moved out setting the identity to `init` function to prevent such situations happening in the future.
/cc mm4tt
=> Set git user identity before any k8s repository changes

clusterloader2/pkg/measurement/util/phase_latency.go, clusterloader2/pkg/measurement/util/wait_for_nodes.go, clusterloader2/pkg/measurement/util/wait_for_pods.go, clusterloader2/pkg/measurement/util/wait_for_pvcs.go, clusterloader2/pkg/measurement/util/wait_for_pvs.go, clusterloader2/pkg/util/cluster.go
Clusterloader generates a lot of output on the console. The information is helpful but the large amount of very detailed runtime measurement data can be overwhelming and may hide some desired and  important information. This PR changes the detailed runtime measurement logs to V(2).
=> Clusterloader: customize logging levels

clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/config/cluster.go, clusterloader2/pkg/framework/framework.go, clusterloader2/pkg/test/simple_test_executor.go
Cherry-pick 93c4d8aa2ec8178c3735ce772cc4545ab4b0ba0b from master.
/cc @chendave
=> [1.18] Cherry-pick of 'clean up stale namespaces before execution'

perfdash/parser.go
perf-dash by default adds all labels to available selectors and does breakdown by that label. See https://github.com/kubernetes/perf-tests/issues/1285
=> Remove SlowCount from labels

clusterloader2/pkg/prometheus/manifests/exporters/node-exporter.yaml
`quay.io` is down, hence pulling this image is not going to succeed in this pod.
=> Change node-exporter image origin

clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go, clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus_test.go, clusterloader2/testing/load/config.yaml, clusterloader2/testing/load/golang/custom_api_call_thresholds.yaml
To automatize Golang regression detection in our CI jobs it'd be convenient to override the default SLO threshold for certain metrics.
Custom thresholds included in the `custom_api_call_thresholds.yaml` file derive from experiments with running a kubemark load test job with the faulty golang version.
/cc mm4tt
=> Add custom thresholds mechanism in APIResponsivenessPrometheus measurement

perfdash/www/script.js
It got renamed in https://github.com/kubernetes/perf-tests/commit/5d15f0f796e371284b47a1831a5d06b73afb6bc4#diff-824455981b31a867d75ca77e17833a13L43
I think it's the only place, so we should be good to simply rename here instead of revert of that change.
=> Rename storageUrl to storageURL

clusterloader2/pkg/execservice/exec_service.go, clusterloader2/pkg/measurement/common/wait_for_controlled_pods.go, clusterloader2/pkg/measurement/common/wait_for_nodes.go, clusterloader2/pkg/measurement/common/wait_for_pods.go, clusterloader2/pkg/measurement/common/wait_for_pvcs.go, clusterloader2/pkg/measurement/common/wait_for_pvs.go, clusterloader2/pkg/measurement/util/gatherers/resource_gather_worker.go, clusterloader2/pkg/measurement/util/phase_latency.go, clusterloader2/pkg/measurement/util/wait_for_nodes.go, clusterloader2/pkg/measurement/util/wait_for_pods.go, clusterloader2/pkg/measurement/util/wait_for_pvcs.go, clusterloader2/pkg/measurement/util/wait_for_pvs.go, clusterloader2/pkg/util/cluster.go, clusterloader2/run-e2e.sh
1. Remove _EnableLogging_ flag and use the verbosity level to customize the detailed measurement logging instead.  
2. Address the issue of #1270 by setting the default v level v(2) in  _run-e2e.sh_.
=> ClusterLoader2: use verbosity to customize measurement logging

clusterloader2/pkg/measurement/common/resource_usage.go, clusterloader2/pkg/measurement/util/gatherers/container_resource_gatherer.go, clusterloader2/pkg/measurement/util/gatherers/resource_gather_worker.go
Delete two flags printVerboseLogs and PrintVerboseLogs in measurement/util/gathers and use the verbosity level --v to control the logging levels. Please refer to #1298.
=> ClusterLoader: remove PrintVerboseLogs flags and use V levels

clusterloader2/pkg/config/cluster.go, clusterloader2/pkg/modifier/modifier.go, clusterloader2/pkg/modifier/modifier_test.go, clusterloader2/pkg/test/test.go
Flag level allowing configuration of config for ClusterLoader2
It solves problem for #1282 and little more.
It does not support slices on parameter path, but this feature is currently not needed.
/cc @wojtek-t
=> Add modifier to overwrite test configuration by flags

clusterloader2/docs/oom_detection.md, clusterloader2/pkg/measurement/common/bundle/test_metrics.go, clusterloader2/pkg/measurement/common/ooms_tracker.go, clusterloader2/testing/density/config.yaml, clusterloader2/testing/load/config.yaml
This PR adds a measurement tracking OOM events in clusterloader2 emitted by `node-problem-detector` and enables it in density and load tests.
Confirmation that it works: [cl2 presubmit job results](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/perf-tests/1309/pull-perf-tests-clusterloader2/1268900097278611456/) (there was a deployment with an OOMing container in the PR version of this presubmit).
=> Add cluster OOMs tracking in clusterloader2

clusterloader2/pkg/measurement/common/exec.go, clusterloader2/pkg/util/util.go, clusterloader2/testing/load/config.yaml
This can be used to e.g. test cluster-wide operations like rolling update or dumping some debug info.
=> Exec command in the middle of performance test.

clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/config/cluster.go, clusterloader2/pkg/modifier/modifier.go, clusterloader2/pkg/modifier/modifier_test.go, clusterloader2/pkg/test/test.go
Original message
Add flag --skip-steps
This change enables runetime test config change - skipping any number of
steps without a need to modify config file.
=> Cherry-pick --skip-steps from master

clusterloader2/pkg/measurement/common/scheduler_latency.go
Using reset to change scheduler metrics has 2 issues: 
1) Reset scheduler metrics that are shared with prometheus may disrupt time series stored in prometheus. 
2) Reset operation are often forbidden in production cluster.
Use get to retrieve and store initial value instead of reset. At gather stage, subtract the data from the initial data.
=> remove metrics reset. Use get to obtain initial metrics values

clusterloader2/pkg/measurement/common/exec.go, clusterloader2/pkg/util/util.go, clusterloader2/testing/load/config.yaml
Not merged cleanly, some changes required (different type names)
Original message:
Exec command in the middle of performance test.
This can be used to e.g. test cluster-wide operations like rolling
update or dumping some debug info.
/cc @mborsz 
/assign @mm4tt
=> [1.18] Backport Exec measurement from master

clusterloader2/pkg/provider/aks.go, clusterloader2/pkg/provider/aws.go, clusterloader2/pkg/provider/constants.go, clusterloader2/pkg/provider/eks.go, clusterloader2/pkg/provider/gce.go, clusterloader2/pkg/provider/gke.go, clusterloader2/pkg/provider/kubemark.go, clusterloader2/pkg/provider/local.go, clusterloader2/pkg/provider/provider.go, clusterloader2/pkg/provider/skeleton.go, clusterloader2/pkg/provider/util.go, clusterloader2/pkg/provider/vsphere.go
Ref https://github.com/kubernetes/perf-tests/issues/238
Provider specific logic has been scattered around the code. Making it
hard to support a new provider. This change moves provider related code
into provider pacakge. Other packages should depend on provider
interface rather than provider name.
=> consolidate provider related logic into a single place

clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go, clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus_test.go, clusterloader2/pkg/measurement/common/slos/prometheus_measurement.go, clusterloader2/testing/density/config.yaml, clusterloader2/testing/load/config.yaml
Backport #1262, #1258, #1213, #1229 and #1209 to get rid of API call measurement flakes due to single slow API calls breaking the latency SLOs.
/cc jkaniuk
/cc mm4tt
/cc wojtek-t
=> Slow API calls - backport #1262, #1258, #1213, #1229 and #1209 (release-1.18)

clusterloader2/pkg/measurement/common/ooms_tracker.go
Perform deduplication of OOM events with the same `ResourceVersion`.
/cc mm4tt
/cc jkaniuk
/cc wojtek-t
=> Remove duplicate OOM event reports in OOM tracker

perfdash/github-configs-fetcher.go
GitHub's API will rate limit unauthenticated requests from IPs with high request
rates, but will allow requests that include authentication. This adds
support for reading in a `GITHUB_TOKEN` environment variable and adding
it as a bearer token to requests against the GitHub API
I got the message when trying to test this tool on my corporate network.
```json
{
"message": "API rate limit exceeded for xxx.xxx.xxx.xxx. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
"documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```
=> * Added support for GitHub bearer token

network/benchmarks/netperf/nptest/nptest.go
Worker nodes need to add square brackets ([...]) to IPv6 addresses
when connecting to the orchestrator otherwise the call to `rpc.DialHTTP`
fails.
This change has been tested on an ipv6 cluster with two worker nodes.
Co-authored-by: Allain Legacy <allain.legacy@windriver.com>
Signed-off-by: Thomas Gao <thomas.gao@windriver.com>
=> Add ipv6 support for network performance test

perfdash/Makefile, perfdash/metrics-downloader-helper.go, perfdash/metrics-downloader.go, perfdash/perfdash.go
This PR refactors the perfdash codebase for future S3 support. My changes consist of:  
* renaming many of the variables, functions, and files to be more generic/readable
* converting bucketUtil to an interface called MetricsBucket
* moving GCS specific flags to a GCSDownloaderOptions struct
=> Refactor perfdash codebase for future S3 support

clusterloader2/README.md, clusterloader2/pkg/config/template_provider.go, clusterloader2/pkg/config/template_provider_test.go
Backports #1263, #1145, #998 & #921.
This will facilitate leveraging some of the backported features in perf-tests (like in #1379 where we'd need to add an override file and enable it in each 1.17 test job).
/cc mm4tt
=> Cl2 env template params - backport #1263, #1145, #998 & #921 (release-1.17)

clusterloader2/README.md, clusterloader2/pkg/config/template_provider.go, clusterloader2/pkg/config/template_provider_test.go
Backports #1263, #1145, #998 & #921.
This will facilitate leveraging some of the backported features in perf-tests in the future.
/cc mm4tt
=> Cl2 env template params - backport #1263, #1145, #998 & #921 (release-1.16)

clusterloader2/pkg/config/template_provider.go, clusterloader2/pkg/config/template_provider_test.go
Handling `CL2_*` environment variables by cl2 is present in `release-1.18` branch but it's lacking #1263 and #1145 that fix the behavior of parsing those variables when a boolean or a number is expected.
/cc mm4tt
=> Cherry-pick CL2_* env template params fixes to release-1.18

perfdash/README.md, perfdash/metrics-downloader.go, perfdash/perfdash.go
In this PR: 
- I fix the lint issues from PR #1382. My gofmt/golint was not working properly. The PR was merged, but it failed the verify-lint test
- I updated the readme to reflect that perfdash is no longer using godeps since we moved to go modules
=> Use gofmt to fix lint issues and update perfdash README

clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.dashboard.py
Fix https://github.com/kubernetes/perf-tests/issues/1371
update etcd_disk_backend_commit_duration_seconds to etcd_disk_backend_commit_duration_seconds_bucket in master dashboard.
I have a problem that run `make all` always show `make: Nothing to be done for 'all'.`, i don't know why, if someone knows, please tell me. Thanks.
=> Update etcd_disk_backend_commit_duration_seconds histogram to etcd_disk_backend_commit_duration_seconds_bucket

clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.json
Regenerate master-dashboard.json after rename etcd_disk_backend_commit_duration_seconds to etcd_disk_backend_commit_duration_seconds_bucket in master dashboard.
=> Regenerate master dashboard

clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/chaos/monkey.go, clusterloader2/pkg/chaos/nodes.go, clusterloader2/pkg/config/cluster.go, clusterloader2/pkg/framework/framework.go, clusterloader2/pkg/imagepreload/imagepreload.go, clusterloader2/pkg/measurement/common/etcd_metrics.go, clusterloader2/pkg/measurement/common/metrics_for_e2e.go, clusterloader2/pkg/measurement/common/probes/probes.go, clusterloader2/pkg/measurement/common/profile.go, clusterloader2/pkg/measurement/common/resource_usage.go, clusterloader2/pkg/measurement/common/scheduler_latency.go, clusterloader2/pkg/measurement/common/slos/network_programming.go, clusterloader2/pkg/measurement/interface.go, clusterloader2/pkg/measurement/util/gatherers/container_resource_gatherer.go, clusterloader2/pkg/measurement/util/gatherers/resource_gather_worker.go, clusterloader2/pkg/measurement/util/kubemark/kubemark.go, clusterloader2/pkg/measurement/util/ssh.go, clusterloader2/pkg/prometheus/experimental.go, clusterloader2/pkg/prometheus/gce_windows_util.go, clusterloader2/pkg/prometheus/prometheus.go
Provider specific logic has been scattered around the code. Making it
hard to support a new provider. This change moves provider related code
into provider pacakge. Other packages should depend on provider
interface rather than provider name.
=> use provider across clusterloader2.

clusterloader2/pkg/measurement/common/scheduling_throughput.go, clusterloader2/testing/density/config.yaml
Addressing issue https://github.com/kubernetes/kubernetes/issues/93217 where problems with this measurement arose due to master VMs in 100 nodes tests lacking CPU time for kube-scheduler in the density test after changes in https://github.com/kubernetes/kubernetes/pull/92840.
We maintain the default behavior of failing the test when SLO violation occurs but will make 100 nodes tests not fail when the violation happens.
/cc jkaniuk
/cc wojtek-t
=> Make schedulerThroughput measurement SLO violation failing a test customizable

clusterloader2/pkg/measurement/common/scheduling_throughput.go, clusterloader2/testing/density/config.yaml
Backport of https://github.com/kubernetes/perf-tests/pull/1401.
/cc jkaniuk
/cc wojtek-t
=> Make schedulerThroughput measurement SLO violation failing a test customizable (release-1.18)

clusterloader2/pkg/measurement/common/scheduling_throughput.go, clusterloader2/testing/density/config.yaml
Backport of https://github.com/kubernetes/perf-tests/pull/1401.
/cc jkaniuk
/cc wojtek-t
=> Make schedulerThroughput measurement SLO violation failing a test customizable (release-1.19)

perfdash/Makefile, perfdash/gcs_metrics_bucket.go, perfdash/go.mod, perfdash/go.sum, perfdash/metrics-downloader.go, perfdash/perfdash.go, perfdash/s3_metrics_bucket.go
In this PR, I added functionality to get data from AWS S3 by:
- adding s3 specific functions to pull build numbers and files from the specified s3 bucket
- adding s3 specific flags (flag to specify region)
- adding mode flag to specify whether to get data from s3 or gcs (the default is gcs)
I also moved s3 and gcs functions to their own files (s3_metrics_bucket.go and gcs_metrics_bucket.go). I tested the changes on local and on an EKS cluster; metrics were successfully pulled from S3 and displayed on perfdash. 😄
=> Add AWS S3 functionality for perfdash

perfdash/config.go, perfdash/github-configs-fetcher.go
I was running into an auth issue despite setting my Github token properly. Upon investigation, I found that the request header for auth should look like: `Authorization: Bearer <token>`. In the current code, we have a colon after Bearer leading to my auth issues. Once removed, I was authenticated properly. 
Unfortunately, this breaks retrieving the prow config because a bearer token adds some extra auth chars after the [downloadURL](`https://github.com/kubernetes/perf-tests/blob/master/perfdash/github-configs-fetcher.go#L55). (e.g: `https://raw.githubusercontent.com/kubernetes/test-infra/master/config/jobs/kubernetes/sig-scalability/sig-scalability-release-blocking-jobs.yaml?token=AXXXXXXXXXXXXXXXXXXXXZ`). In the code: 
- To ensure that we are only working with strings that end in …
=> Fix typo in Github Bearer Token and remove redundant check for ignoring non-yaml files in config.go

clusterloader2/pkg/measurement/common/api_availability_measurement.go, clusterloader2/pkg/measurement/common/api_availability_metrics.go
This PR is for https://github.com/kubernetes/perf-tests/issues/1096 which created a new measurement to track the availability of api-server by probing the /healthz end point
=> Api availability measurement

clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go, clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus_test.go
Always count slow queries - even when SlowCount threshold is not set
/cc @mm4tt
=> Always count slow queries

clusterloader2/testing/density/config.yaml, clusterloader2/testing/load/config.yaml
Backport commit 038d353a3bfe880fa983879592a8eb3a1eeb6df8 with configuration changes
/cc @mborsz
=> [1.17] Add configurable timeout for probes in configs

clusterloader2/testing/density/config.yaml, clusterloader2/testing/load/config.yaml
Backport commit 038d353a3bfe880fa983879592a8eb3a1eeb6df8 with configuration changes
/cc @mborsz
=> [1.16] Add configurable timeout for probes in configs

clusterloader2/testing/density/config.yaml
Merge two saturation pods steps into one and fix the names of saturation-related steps.
/assign mm4tt
=> Clean up steps in density test config

slo-monitor/Makefile, slo-monitor/src/monitors/pod_monitor.go
Change page size in slo-monitor from 500 to 5000.
kube-apiserver internally uses the page size as a chunk size for a single etcd requests. In cases like this one (a fieldSelector that matches only a tiny fraction of all obects) it needs to scan all objects which takes a lot of time when 500 page size is used.
In my benchmark with 200k events, this change seems to decrease request latency 3x.
=> Increase page size to 5000 in slo-monitor

.golangci.yml, benchmark/pkg/comparer/comparer.go, benchmark/pkg/metricsfetcher/runselector/selector.go, benchmark/pkg/metricsfetcher/util/mock_util.go, benchmark/pkg/metricsfetcher/util/util.go, clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/config/template_provider.go, clusterloader2/pkg/measurement/common/service_creation_latency.go, clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus_test.go, clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go, clusterloader2/pkg/prometheus/prometheus.go, clusterloader2/pkg/provider/util.go, clusterloader2/pkg/tuningset/global_qps_load.go, network/benchmarks/netperf/launch.go, network/benchmarks/netperf/nptest/nptest.go, perfdash/metrics-downloader-helper.go, perfdash/metrics-downloader.go, perfdash/perfdash.go, slo-monitor/src/monitors/store.go, slo-monitor/src/monitors/watcher.go, util-images/access-tokens/cmd/main.go, util-images/probes/pkg/ping/server/server.go
=> feat: Add errcheck linter with golangci-lint

.golangci.yml, compare/src/compare-resources.go, network/benchmarks/netperf/launch.go, perfdash/config.go
Signed-off-by: Kush Trivedi <kushthedude@gmail.com>
=> feat: add deadcode linter in golangci-lint

.golangci.yml, clusterloader2/api/types.go, clusterloader2/pkg/measurement/util/resource.go, clusterloader2/pkg/prometheus/util.go, slo-monitor/src/monitors/store.go
Signed-off-by: Kush Trivedi <kushthedude@gmail.com>
Refers #1244
=> feat: enable govet in golangci-lint

slo-monitor/Makefile, slo-monitor/src/monitors/pod_monitor.go, slo-monitor/src/monitors/watcher.go, slo-monitor/src/third_party/forked/k8s.io/client-go/tools/cache/controller.go
The previous attempt to increase page size was incorrect (was changing a pagination that is noop).
It seems to work now:
```
I0902 09:54:33.023988       1 httplog.go:90] verb="GET" URI="/api/v1/pods?limit=5000&resourceVersion=0" latency=3.396776ms resp=200 UserAgent="slo-monitor/v0.0.0 (linux/amd64) kubernetes/$Format" srcIP="[::1]:49440":
I0902 09:54:34.031390       1 httplog.go:90] verb="GET" URI="/api/v1/events?fieldSelector=involvedObject.kind%3DPod%2Csource%3Dkubelet&limit=5000&resourceVersion=0" latency=34.948446ms resp=200 UserAgent="slo-monitor/v0.0.0 (linux/amd64) kubernetes/$Format" srcIP="[::1]:49440":
```
=> Increase page size in slo-monitor to 5000 (attempt #2).

clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go
Exclude proxy subresource from API responsiveness.
Remove also outdated WATCHILIST, PROXY and CONNECT verbs as they don't seem to used sine 1.11.
Fix: https://github.com/kubernetes/kubernetes/issues/94368
/cc @wojtek-t 
I will run some manual tests first
/hold
=> Exclude proxy subresource from API responsiveness

clusterloader2/pkg/prometheus/manifests/0prometheus-operator-deployment.yaml, clusterloader2/pkg/prometheus/manifests/grafana-deployment.yaml, clusterloader2/pkg/prometheus/manifests/prometheus-prometheus.yaml
Use kubernetes.io/os instead of beta.kubernetes.io/os
/cc @jkaniuk
=> Use kubernetes.io/os after graduation from beta

benchmark/Makefile
Tests: https://k8s-testgrid.appspot.com/sig-scalability-perf-tests#kubemark-100-benchmark
were broken by: https://github.com/kubernetes/perf-tests/pull/1447
```
I0902 22:03:20.536] GOOS=linux GOARCH=amd64 CGO_ENABLED=0 godep go build -a -o build/benchmark cmd/benchmark.go
W0902 22:03:20.637] godep: No Godeps found (or in any parent directory)
W0902 22:03:20.638] make: *** [Makefile:25: benchmark] Error 1
```
/cc @kushthedude
/cc @wojtek-t
=> Fix benchmark Makefile after migration to go modules

dns/run
Fixes https://github.com/kubernetes/kubernetes/issues/94473
=> Pin python and pip to v2 version

perfdash/Makefile, perfdash/config.go, perfdash/deployment.yaml, perfdash/parser.go
This label will be used to view the graphs for data generated by
different tests defined in cl2/testing/density/scheduler.
Related to #1414
=> perfdash: add scheduler throughput/latency labels

clusterloader2/testing/density/config.yaml
/kind cleanup
Even though there exists no such override in-tree or in this PR, making
this overridable makes it easier to test multiple cl2 executions quickly
without having to wait for 3000 saturation pods / 500 latency pods.
Fixes #
```release-note
NONE
```
```docs
```
=> cl2/density: make MIN_LATENCY_PODS configurable

clusterloader2/testing/density/scheduler-suite.yaml, clusterloader2/testing/density/scheduler/pod-affinity/deployment.yaml, clusterloader2/testing/density/scheduler/pod-affinity/overrides.yaml, clusterloader2/testing/density/scheduler/pod-topology-spread/deployment.yaml, clusterloader2/testing/density/scheduler/pod-topology-spread/overrides.yaml
/kind feature
**What this PR does / why we need it**: This PR adds the pod-affinity test to the suite of scheduler benchmark(s) we have.
Related to https://github.com/kubernetes/perf-tests/issues/1414
**Special notes for your reviewer**: No.
```release-note
NONE
```
/sig scheduling
/sig testing
/cc @ahg-g @mm4tt
=> cl2/density: add pod affinty, pod topology spreading workloads to scheduler suite

.golangci.yml, verify/verify-lint.sh
Increase the timeout for the linter job after recent changes to `pull-perf-tests-verify-lint` CPU limits.
Fixes #1469.
=> Bump timeout for the linter test job

clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/test/interface.go, clusterloader2/pkg/test/simple_context.go, clusterloader2/pkg/test/simple_reporter.go, clusterloader2/pkg/test/simple_test_executor.go, clusterloader2/pkg/test/test.go
Introduce a level of granularity in the performance tests reporting that is shown in the Prow job test results. Every step in each of the test configs will be reported separately.
=> Add per step reporting in CL2

slo-monitor/Makefile, slo-monitor/src/monitors/pod_monitor.go, slo-monitor/src/monitors/watcher.go
Limits memory usage after slo-monitor restart
Fixes #
```release-note
```
```docs
```
=> Fix memory usage when listing pods/events

perfdash/Makefile, perfdash/config.go, perfdash/deployment.yaml
/kind feature
**What this PR does / why we need it**: Adds pod-affinity and pod-topology-spread workloads (added in https://github.com/kubernetes/perf-tests/pull/1464) to perf-dash.
Fixes https://github.com/kubernetes/perf-tests/issues/1414
```release-note
NONE
```
```docs
```
/sig scheduling
/cc @mm4tt @ahg-g
=> perfdash: add pod-affinity, pod-topology-spread workloads

clusterloader2/pkg/measurement/common/scheduler_latency.go, clusterloader2/pkg/provider/provider.go
Some providers can support ssh to master, but not expose
scheduler metrics on insecure port.
/kind feature
cc @Catramen
=> Introduce SchedulerInsecurePortDisabled

perfdash/config.go, perfdash/metrics-downloader.go
Some jobs may have layout that is placing results below root artifacts dir.
=> Allow per-job path override for clusterloader2 results dir

Makefile
/kind feature
Optionally add one or more of the following kinds if applicable:
Allow migration to Python3 - we want to split presubmit verify-all to a language dependent presubmits.
Related to #1470
=> Add Python specific test suite to allow migration to Python3

clusterloader2/testing/load/config.yaml
/kind bug
Fixes cpu requests in load test when density test is enabled.
Example failed test: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/1310988110418415616
Fixes #
```release-note
```
```docs
```
=> Fix cpu requests in load test when density test is enabled.

Makefile
/kind cleanup
Ref. #1470 
`verify-all` presubmit is already skipped for master branch. Changing test target to allow passing jobs after rebase if there will be pending presubmit statuses.
/cc @wojtek-t 
Also, fix `verify-all-python` target.
=> Mark 'verify-all' as deprecated, but leave it to make pass existing PRs

clusterloader2/testing/load/config.yaml
This adds CL2_DELETE_TEST_THROUGHPUT, which is purely optional. If not set, it defaults to $LOAD_TEST_THROUGHPUT making this change no-op there.
=> Decouple deletion test throughput from load test throughput.

clusterloader2/testing/load/config.yaml
Cherry pick of https://github.com/kubernetes/perf-tests/pull/1520
=> [Cherrypick 1.19] Decouple deletion test throughput from load test throughput.

clusterloader2/testing/load/config.yaml
Cherry pick of https://github.com/kubernetes/perf-tests/pull/1520
=> [Cherrypick 1.18] Decouple deletion test throughput from load test throughput.

perfdash/Makefile, perfdash/deployment.yaml, perfdash/metrics-downloader.go
/kind bug
**What this PR does / why we need it**: perfdash's metrics-downloader.go oddly seems to break after the first processed testDescription if that testDescription has non-zero number of artificats. This has existed for at least two years (https://github.com/kubernetes/perf-tests/commit/b11dd1efb807a2ffdde4aede0fa269e73301cdaf).
Fixes https://github.com/kubernetes/perf-tests/issues/1488
```release-note
NONE
```
```docs
```
/cc @tosi3k
=> perfdash/metrics-downloader: process all testDescriptions within a category

perfdash/parser.go
These fields should've been removed in https://github.com/kubernetes/perf-tests/pull/743. They were deprecated in https://github.com/kubernetes/perf-tests/pull/330 originally.
=> perfdash/parser.go: remove unused throughput fields

clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go, clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus_test.go, clusterloader2/testing/load/config.yaml, clusterloader2/testing/load/golang/custom_api_call_thresholds.yaml
Cherry-pick #1276 to 1.18
Needed to cherry-pick other improvements of this measurement.
/cc @wojtek-t
/cc @tosi3k
=> [1.18] Add custom thresholds mechanism in APIResponsivenessPrometheus measurement

clusterloader2/testing/load/config.yaml
…ing throughput below 100
/kind feature
We are in a process of merging density test into load test. Based on data gathered in perfdash for 100 and 5k nodes runs, we are comfortable with turning on alerting for SchedulingThroughput and PodStartupLatency.
Metrics:
100 Nodes:
Pod startup latency:
http://perf-dash.k8s.io/#/?jobname=gce-100Nodes-master&metriccategoryname=E2E&metricname=LoadPodStartup&Metric=pod_startup
Scheduling throughput:
http://perf-dash.k8s.io/#/?jobname=gce-100Nodes-master&metriccategoryname=Scheduler&metricname=SchedulingThroughput&TestName=load
5k Nodes:
Pod startup latency:
http://perf-dash.k8s.io/#/?jobname=gce-5000Nodes&metriccategoryname=E2E&metricname=LoadPodStartup&Metric=pod_startup
Scheduling …
=> Turn on alerting in load test for pod latency and scheduling throughput

clusterloader2/README.md
The default is the empty string which raises an error:
```
$ go run cmd/clusterloader.go --kubeconfig=$KUBECONFIG --testconfig=testing/experimental/storage/pod-startup/config.yaml
F1005 11:07:26.997733   67200 clusterloader.go:242] Error init provider: unsupported provider name:
exit status 1
```
```release-note
NONE
```
=> clusterloader2: -provider is required

clusterloader2/pkg/measurement/common/scheduling_throughput.go, clusterloader2/testing/load/experimental-config.yaml
Cherry-pick: #1093 
* Add measurmentInterval parameter to SchedulingThroughput
* SchedulingThroughput threshold compares to max value, instead of 99th
percentile
* Remove broken average value
Fixes #
```release-note
```
```docs
```
=> Backport scheduling throughput to 1.18

golang/run-e2e.sh
Small facilitation utility for debugging Golang-related regressions.
=> Add Golang job script printing Golang repo commit hash

clusterloader2/pkg/prometheus/experimental.go, clusterloader2/pkg/util/ssh.go
Output of grepping `failure-domain.beta.kubernetes.io` at the top-level perf-tests repo directory, `master` branch:
```
./clusterloader2/vendor/k8s.io/api/core/v1/well_known_labels.go:22:	LabelZoneFailureDomain       = "failure-domain.beta.kubernetes.io/zone"
./clusterloader2/vendor/k8s.io/api/core/v1/well_known_labels.go:23:	LabelZoneRegion              = "failure-domain.beta.kubernetes.io/region"
./clusterloader2/pkg/util/ssh.go:39:	zone, ok := node.Labels["failure-domain.beta.kubernetes.io/zone"]
./clusterloader2/pkg/util/ssh.go:41:		return fmt.Errorf("unknown zone for %q node: no failure-domain.beta.kubernetes.io/zone label", node.Name)
./clusterloader2/pkg/prometheus/experimental.go:89:		zone = pv.ObjectMeta.Labels["failure-domain.beta.kubernetes.io/zone"] …
```
=> Replace references to old topology labels with the new ones

clusterloader2/pkg/prometheus/experimental.go, clusterloader2/pkg/util/ssh.go
Reverts kubernetes/perf-tests#1563
This seems to be causing https://github.com/kubernetes/kubernetes/issues/96509
=> Revert "Replace references to old topology labels with the new ones"

clusterloader2/testing/load/config.yaml, clusterloader2/testing/load/configmap.yaml, clusterloader2/testing/load/deployment.yaml
Cherrypick of https://github.com/kubernetes/perf-tests/pull/1526 and https://github.com/kubernetes/perf-tests/pull/1546
This will run dnsperf which will issue 10 queries per second.
The queries are specified via a configmap and include
searchpath-expanded queries to simulate a real application.
Rebased configmap changes that include dns queries.
Simplified config by removing extra template fillup.
Fixes #
```release-note
NONE
```
```docs
```
/assign @wojtek-t @mborsz
=> Cherrypick of #1526 into 1.19 - Adding a new DNS workload in load tests 

clusterloader2/testing/load/config.yaml, clusterloader2/testing/load/configmap.yaml, clusterloader2/testing/load/deployment.yaml
Cherrypick of https://github.com/kubernetes/perf-tests/pull/1526 and https://github.com/kubernetes/perf-tests/pull/1546
This will run dnsperf which will issue 10 queries per second.
The queries are specified via a configmap and include
searchpath-expanded queries to simulate a real application.
Rebased configmap changes that include dns queries.
Simplified config by removing extra template fillup.
Fixes #
```release-note
NONE
```
```docs
```
/assign @wojtek-t @mborsz
=> Cherrypick of #1526 into 1.18 - Adding a new DNS workload in load tests

clusterloader2/testing/load/config.yaml
As measurements in a single step are run in parallel, sleeping needs to be moved out to a separate step.
/cc @marseel
=> Move the sleep command to a separate step

clusterloader2/pkg/measurement/common/ooms_tracker.go
Backports https://github.com/kubernetes/perf-tests/pull/1579.
=> Adapt the event message regex in the OOM tracker (release-1.19)

clusterloader2/pkg/measurement/common/ooms_tracker.go
=> Adapt the event message regex in the OOM tracker (release-1.18)

clusterloader2/pkg/measurement/common/ooms_tracker.go
=> Adapt the event message regex in the OOM tracker (release-1.17)

clusterloader2/pkg/measurement/common/ooms_tracker.go
=> Adapt the event message regex in the OOM tracker (release-1.16)

clusterloader2/pkg/measurement/common/ooms_tracker.go
=> Adapt the event message regex in the OOM tracker

dns/run
This is, among others, to properly propagate error status.
Ref. https://github.com/kubernetes/perf-tests/issues/1586
=> Add missing bash options to dns/run.sh

dns/py/data.py, dns/py/runner.py
Ref. https://github.com/kubernetes/perf-tests/issues/1586
=> Fix dns benchmark failing after python 2->3 migration

clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go
/kind bug
Slow count for cluster scope lists was calculated incorrectly.
Fixes #
```release-note
```
```docs
```
=> Fix slow count for api responsiveness for cluster list

clusterloader2/pkg/imagepreload/imagepreload.go
Fixes a bug in `imagepreload.go`
Fixes #1597
=> bugfix in imagepreload.go

clusterloader2/testing/load/config.yaml
Backport https://github.com/kubernetes/perf-tests/pull/1576 to release-1.18 branch.
=> Move the sleep command to a separate step (release-1.18)

clusterloader2/testing/load/config.yaml
Backport https://github.com/kubernetes/perf-tests/pull/1576 to release-1.19 branch.
=> Move the sleep command to a separate step (release-1.19)

clusterloader2/testing/load/config.yaml
/kind feature
Fixes #
```release-note
```
```docs
```
=> Backport metrics violation for density in load 1.18

clusterloader2/testing/load/config.yaml
…ing throughput below 100
/kind feature
Fixes #
```release-note
```
```docs
```
=> Backport metrics violation for density in load 1.19

clusterloader2/pkg/test/simple_test_executor.go
After https://github.com/kubernetes/perf-tests/pull/1495 was merged, we stopped getting a notice of when a particular step begins/ends in the build logs of 1.16 jobs. This PR will bring it back.
=> Fix lack of printing of steps beginning/end in CL2 (release-1.16)

clusterloader2/pkg/test/simple_test_executor.go
After https://github.com/kubernetes/perf-tests/pull/1493 was merged, we stopped getting a notice of when a particular step begins/ends in the build logs of 1.18 jobs. This PR will bring it back.
=> Fix lack of printing of steps beginning/end in CL2 (release-1.18)

clusterloader2/pkg/test/simple_test_executor.go
After https://github.com/kubernetes/perf-tests/pull/1494 was merged, we stopped getting a notice of when a particular step begins/ends in the build logs of 1.17 jobs. This PR will bring it back.
=> Fix lack of printing of steps beginning/end in CL2 (release-1.17)

clusterloader2/pkg/measurement/common/service_creation_latency.go, clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go, clusterloader2/pkg/measurement/util/phase_latency.go, clusterloader2/pkg/measurement/util/pods_metadata.go
This is a step towards getting rid of latency phase from our test.
Pod startup from "CreatePhasePodStartupLatency":
```
{
"data": {
"Perc50": 2203.834508,
"Perc90": 2990.742296,
"Perc99": 12677.203517
},
"unit": "ms",
"labels": {
"Metric": "pod_startup"
}
},
```
Pod startup from "Stateles CreatePhasePodStartupLatency":
```
{
"data": {
"Perc50": 2199.278227,
"Perc90": 2953.810973,
"Perc99": 4251.361823
},
"unit": "ms",
"labels": {
"Metric": "pod_startup"
}
}
```
=> Measure pod startup for stateless pods

util-images/network/netperfbenchmark/Dockerfile, util-images/network/netperfbenchmark/Makefile, util-images/network/netperfbenchmark/cmd/main.go, util-images/network/netperfbenchmark/go.mod, util-images/network/netperfbenchmark/pkg/worker/util.go, util-images/network/netperfbenchmark/pkg/worker/worker.go
/kind feature
/kind regression
**What this PR does / why we need it:**
This review is one of the changeset done as part of the enhancement/feature (Reference #1498)
This changeset has worker-pod implementation.
=> Adding network performance measurement testcases. (util-image changes)

clusterloader2/pkg/measurement/common/scheduler_latency.go, clusterloader2/pkg/prometheus/manifests/master-ip/master-endpoints.yaml, clusterloader2/pkg/prometheus/manifests/master-ip/master-service.yaml, clusterloader2/pkg/prometheus/manifests/master-ip/master-serviceMonitor.yaml, clusterloader2/pkg/provider/util.go
/kind cleanup
/kind deprecation
Now both [controller-manager](https://github.com/kubernetes/kubernetes/pull/96216) and [scheduler](https://github.com/kubernetes/kubernetes/pull/96345) are migrating off the insecure port, and the progress is being blocked by the job `pull-kubernetes-e2e-gce-100-performance`, because `clusterloader2` in this job would fetch metrics from the insecure port of scheduler.
This PR picks up @ingvagabund 's great work #1562, and make `clusterloader2` no longer depend on the insecure port of controller-manager and scheduler.
Fixes #
```release-note
clusterloader2: grab metrics …
```
=> clusterloader2: completely switch to secure port

clusterloader2/testing/load/deployment.yaml
"ClusterFirst" is the default dns option. "Default" inherits the node config.
https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy
We could put this in an if block in case Default dnsPolicy is needed in other testcases.
For the dns tests, we want ClusterFirst to be used in order to test cluster DNS solution.
Fixes #
```release-note
NONE
```
```docs
```
=> Use ClusterFirst dnsPolicy in workloads.

golang/build-kubernetes.sh
Context: https://github.com/kubernetes/kubernetes/pull/95494 (this is what we miss in the k8s version used in Golang jobs). Two most recent job runs suffered from the lack of this PR:
* https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-golang-tip-k8s-1-18/1349312930264387584,
* https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-golang-tip-k8s-1-18/1349252286177611776.
/assign @mm4tt
=> [Golang] Fix hollow node pods busybox image pulls issue

dns/py/data_test.py, dns/py/ingest.py, dns/py/params.py, dns/py/params_test.py, dns/py/runner.py
Hardening measure to prevent [issues] with parsing crafted yaml:
https://pyyaml.org/wiki/PyYAMLDocumentation#loading-yaml
`safe_load()` will become the default in [version 6.0]:
/kind cleanup
[issues]: https://nvd.nist.gov/vuln/search/results?form_type=Basic&results_type=overview&query=pyyaml&search_type=all
[version 6.0]: https://github.com/yaml/pyyaml/issues/420#issuecomment-696752389
=> Change yaml.load() to safe_load()

clusterloader2/pkg/prometheus/manifests/exporters/node-exporter.yaml
Updates node-exporter to 1.0.1 and mounts "/" of host instead of only proc and sys (this is what is done in reference config for 1.0.1 version here: https://github.com/prometheus-operator/kube-prometheus/blob/master/manifests/node-exporter-daemonset.yaml) 
The goal is to include cpu schedstat which may be useful for debugging https://github.com/kubernetes/kubernetes/issues/97801
/assign @mm4tt
=> Update node-exporter to 1.0.1

clusterloader2/pkg/prometheus/manifests/prometheus-prometheus.yaml
Upgrade Prometheus to v2.24.0 to enable support for watch bookmarks
/cc @jkaniuk
=> Upgrade Prometheus to v2.24.0

run-e2e.sh
Current implementation prints out the history of `k8s.io/kubernetes` repo instead of the intended `k8s.io/perf-tests` (this is because kubetest is run in the directory containing the former repo).
/assign @mm4tt
=> Fix printing k8s.io/perf-tests repo history

clusterloader2/testing/load/config.yaml
Backport of https://github.com/kubernetes/perf-tests/pull/1670.
/assign @mm4tt
=> [release-1.17] Custom thresholds param to APIResponsivenessSimple measurement

clusterloader2/testing/load/config.yaml
Backport of https://github.com/kubernetes/perf-tests/pull/1670.
/assign @mm4tt
=> [release-1.18] Custom thresholds param to APIResponsivenessSimple measurement

clusterloader2/testing/load/modules/services.yaml
It should use name 'name', not 'actionName': https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/testing/load/config.yaml#L181
/assign @mm4tt
=> Set name in services module

clusterloader2/testing/load/config.yaml
Backport of https://github.com/kubernetes/perf-tests/pull/1670.
/assign @mm4tt
=> [release-1.20] Custom thresholds param to APIResponsivenessSimple measurement

clusterloader2/testing/load/config.yaml
Backport of https://github.com/kubernetes/perf-tests/pull/1670.
/assign @mm4tt
=> [release-1.19] Custom thresholds param to APIResponsivenessSimple measurement

adhoc/log/distributed-provisioning.md
This was the first usage of the new ad-hoc testing facility. It's
worthwhile to capture the results here because it includes also some
lessons learned about the setup.
```release-note
NONE
```
=> distributed-provisioning.md: report with test setup and results

clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/metadata/metadata.go, clusterloader2/pkg/provider/aks.go, clusterloader2/pkg/provider/aws.go, clusterloader2/pkg/provider/eks.go, clusterloader2/pkg/provider/gce.go, clusterloader2/pkg/provider/gke.go, clusterloader2/pkg/provider/kubemark.go, clusterloader2/pkg/provider/local.go, clusterloader2/pkg/provider/provider.go, clusterloader2/pkg/provider/skeleton.go, clusterloader2/pkg/provider/vsphere.go
Idea:
If we start dumping instanceIDs for master nodes in gce tests and write it to 'finished.json' this information will be then available in `k8s-gubernator.build.all` and can be used for programmatically analyzing runs.
Usage: this PR writes 'cl2-metadata.json' file. If we include this file in --metadata-sources, it should be merged into finished.json which is what we need.
=> Dump instanceIDs for master nodes in clusterloader

clusterloader2/pkg/measurement/common/api_availability_measurement.go, clusterloader2/pkg/measurement/common/api_availability_metrics.go, clusterloader2/testing/load/config.yaml
This builds on https://github.com/kubernetes/perf-tests/pull/1162 where the measurement was introduced.
Changes in regard to the measurement:
* measuring master-level availability:
* relies on `/readyz` instead of deprecated `/healthz`,
* doesn't SSH to master - instead, it leverages the [exec service](https://github.com/kubernetes/perf-tests/tree/master/clusterloader2/pkg/execservice) to ping master's internal IPs,
* added optional `pause` and `unpause` actions to temporarily prevent the measurement from probing,
* code cleanup.
Tested the measurement manually.
=> Revamp API availability measurement

clusterloader2/README.md
Signed-off-by: timyinshi <shiguangyin@inspur.com>
/kind bug
/sig docs
modify the error url of override
the error url is : https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/testing/density/5000_nodes/override.yaml
the right url is : https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/testing/density/scheduler/pod-affinity/overrides.yaml
=> modify the error url of override

clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/measurement/common/api_availability_measurement.go, clusterloader2/pkg/measurement/common/api_availability_metrics.go, clusterloader2/testing/load/config.yaml
Backport https://github.com/kubernetes/perf-tests/pull/1679 and https://github.com/kubernetes/perf-tests/pull/1660 to release-1.20 branch.
/assign @mm4tt
=> API availability measurement revamp - backport to release-1.20

clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/measurement/common/api_availability_measurement.go, clusterloader2/pkg/measurement/common/api_availability_metrics.go, clusterloader2/testing/load/config.yaml
Backport https://github.com/kubernetes/perf-tests/pull/1162, https://github.com/kubernetes/perf-tests/pull/1679 and https://github.com/kubernetes/perf-tests/pull/1660 to release-1.19 branch.
/assign @mm4tt
=> API availability measurement revamp - backport to release-1.19

clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/measurement/common/api_availability_measurement.go, clusterloader2/pkg/measurement/common/api_availability_metrics.go, clusterloader2/testing/load/config.yaml
Backport https://github.com/kubernetes/perf-tests/pull/1162, https://github.com/kubernetes/perf-tests/pull/1679 and https://github.com/kubernetes/perf-tests/pull/1660 to release-1.18 branch.
/assign @mm4tt
=> API availability measurement revamp - backport to release-1.18

perfdash/deployment.yaml
perfdash is getting continuously OOMKilled with 8GiB memory limit.
Let's increase this to 10GiB (I can't set higher values as we use n1-standard-4 machine, see https://github.com/kubernetes/k8s.io/pull/1604), but this values seems to help.
=> Bump cpu and memory requests in perfdash

clusterloader2/pkg/measurement/common/probes/probes.go
Changing defaultCheckProbesReadyTimeout to 15m as this is a minimum value that avoids breaking test in case of single node failure when probes are starting (this can delay starting probe up to 15 minutes, see https://github.com/kubernetes/perf-tests/pull/353 for similar change for waiting for deployments).
In the next PR I will remove known overrides in our tests which set this to 10m (still too low value to handel that case).
/assign @mm4tt
=> Change defaultCheckProbesReadyTimeout to 15m

clusterloader2/testing/density/config.yaml, clusterloader2/testing/load/config.yaml
To match https://github.com/kubernetes/perf-tests/pull/1704
I'm wondering if there is a way avoid copying that value in configs to use value hardcoded in golang.
/assign @mm4tt
=> Change default PROBE_MEASUREMENTS_CHECK_PROBES_READY_TIMEOUT to 15m

clusterloader2/pkg/tuningset/randomized_time_limited.go, clusterloader2/testing/density/config.yaml, clusterloader2/testing/density/high-density-config.yaml, clusterloader2/testing/experimental/storage/pod-startup/config.yaml, clusterloader2/testing/load/config.yaml
/kind bug
Details: https://github.com/kubernetes/perf-tests/issues/887
Fixes https://github.com/kubernetes/perf-tests/issues/887
The type [conversion](https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/pkg/config/template_functions.go#L133) was rounding fractions to 0. Hence when `.Nodes` passed in is less than `NODES_PER_NAMESPACE (defaults to 100)`, `namespaces = DivideInt .Nodes  NODES_PER_NAMESPACE = 0`. thereafter `namespace` is used as the denominator for several computations eg. https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/testing/load/config.yaml#L7 …
=> Make Cl2 tests to work in <100 node clusters

util-images/scratch/Dockerfile, util-images/scratch/Makefile, util-images/scratch/README.md
/kind feature
Adds a script to generate scratch images with different image IDs. These images can then be preloaded onto the kubemark nodes. Details in https://github.com/kubernetes/kubernetes/issues/90833.
Part of https://github.com/kubernetes/kubernetes/issues/90833
Build and push to gcr after merging.
```release-note
NONE
```
```docs
```
=> Scratch image generation

clusterloader2/pkg/prometheus/manifests/master-ip/master-serviceMonitor.yaml
In a case a performance test overloades kube-apiserver, we might want to scrape data with higher timeout.
This is inspired by ref. #1325
=> Add CL2_PROMETHEUS_SLOW_APISERVER

clusterloader2/pkg/measurement/util/ssh.go
/kind bug
Original keyFile assignment is incorrect, it create a new variable under case scope and doesn't change keyFile defined earlier. 
This results in error reading SSH key even `AWS_SSH_KEY ` env is set.
Fixes https://github.com/kubernetes/perf-tests/issues/1717
I will cherry-pick to previous version. release-1.19 and earlier branches are affected. 
```release-note
NONE
```
```docs
```
=> Fix keyFile assignment for AWS provider

util-images/network/netperfbenchmark/go.mod, util-images/network/netperfbenchmark/pkg/worker/util.go, util-images/network/netperfbenchmark/pkg/worker/worker.go
/kind feature
In the current implementation of network performance measurement, controller and worker communicates with each other using http, this change is for making the controller and worker communicate using custom resources. This PR contains the changes for worker portion.
Fixes #1631
```release-note
NONE
```
```docs
```
=> Network performance measurement: Implementing worker using CRD

clusterloader2/testing/load/config.yaml, clusterloader2/testing/load/modules/pod-startup-latency.yaml
Latency pod measurements moved from config.yaml to a separate module in pod-startup-latency.yaml
/kind cleanup
/hold
Part of #1659
=> Load test - latency pod measurements moved to pod-startup-latency.yaml

clusterloader2/pkg/util/cluster.go, clusterloader2/pkg/util/cluster_test.go
/kind bug
Seems `LegacyIsMasterNode` can not correctly infer master node and ip in my environment. 
Could someone help verify your env? in my env, master only have `node-role.kubernetes.io/master=` (value is empty). I think node label key is enough to determinate a node is master. 
Fixes https://github.com/kubernetes/perf-tests/issues/1716
```release-note
NONE
```
```docs
```
=> Fix: only check label key in LegacyIsMasterNode

clusterloader2/README.md
Backport https://github.com/kubernetes/perf-tests/pull/1710 to release-1.20.
/assign @mm4tt
=> Add a README entry about the APIAvailabilityMeasurement - release-1.20

clusterloader2/testing/load/config.yaml, clusterloader2/testing/load/simple-deployment.yaml
Backport https://github.com/kubernetes/perf-tests/pull/1681 to release-1.19.
=> Add huge services to load test - release-1.19

clusterloader2/testing/windows-tests/config.yaml
/kind cleanup
As part of the efforts described in this Issue: https://github.com/kubernetes/k8s.io/issues/1525 we are trying to move away from `gcp project gke-release`
Also the pause image was release with windows support as we can see in the merged or in k/k https://github.com/kubernetes/kubernetes/pull/98205
/assign @spiffxp @wojtek-t
Fixes #
```release-note
NONE
```
```docs
```
=> test: update pause-win image to the new one k8s.gcr.io/pause:3.4.1

clusterloader2/testing/load/config.yaml, clusterloader2/testing/load/simple-deployment.yaml
Backport https://github.com/kubernetes/perf-tests/pull/1681 to release-1.20.
=> Add huge services to load test - release-1.20

clusterloader2/api/types.go, clusterloader2/api/validation.go, clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/config/cluster.go, clusterloader2/pkg/config/template_provider.go, clusterloader2/pkg/config/template_provider_test.go, clusterloader2/pkg/imagepreload/imagepreload.go, clusterloader2/pkg/prometheus/prometheus.go, clusterloader2/pkg/test/interface.go, clusterloader2/pkg/test/simple_context.go, clusterloader2/pkg/test/simple_test_executor.go, clusterloader2/pkg/test/test.go
/kind cleanup
This PR reverts #1711 and applies the changes introduced in #1680. On top of that, a fix has been made to bring back TestSuite overrides while keeping the global overrides within ClusterLoaderConfig.
```release-note
NONE
```
```docs
```
=> Revert #1711 and fix test suite overrides

clusterloader2/pkg/measurement/util/ssh.go
Cherry pick of #1718 on release-1.18.
#1718: Fix keyFile assignment for AWS provider
For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.
=> Automated cherry pick of #1718: Fix keyFile assignment for AWS provider

clusterloader2/pkg/util/cluster.go, clusterloader2/pkg/util/cluster_test.go
Cherry pick of #1725 on release-1.20.
#1725: Fix: only check label key in LegacyIsMasterNode
For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.
=> Automated cherry pick of #1725: Fix: only check label key in LegacyIsMasterNode

clusterloader2/api/default.go, clusterloader2/api/types.go, clusterloader2/api/validation.go, clusterloader2/api/validation_test.go, clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/config/cluster.go, clusterloader2/pkg/test/test.go
/kind feature
Refinement of https://github.com/kubernetes/perf-tests/pull/142. Validates more aspects of the CL2 config. 
Steps validation will automatically apply to modules once compilation is moved before test execution in https://github.com/kubernetes/perf-tests/pull/1680.
Fixes https://github.com/kubernetes/perf-tests/issues/1636
Copy pasted the logic from https://github.com/kubernetes/perf-tests/pull/142 but placed it in the existing api/validation.go file. Had to do a conversion back to CL2 error types.
```release-note
Added CL2 config validation for namespaces, tuning sets and steps.
``` …
=> CL2 config validation

clusterloader2/api/validation.go
When I was trying to run clusterloader from my laptop using a command like this:
```
./clusterloader \
--alsologtostderr \
--kubeconfig /home/ec2-user/.kube/config \
--testconfig /home/ec2-user/perf-tests/clusterloader2/testing/load/config.yaml \
--testoverrides /home/ec2-user/perf-tests/clusterloader2/build/overrides.yaml 
...
```
It failed with errors like these:
```
F0218 09:30:18.245345   64780 clusterloader.go:334] Test compliation failed: [steps[1].phases[0].objectBundle[0].objectTemplatePath: Invalid value: "service.yaml": file must exist
steps[1].phases[1].objectBundle[0].objectTemplatePath: Invalid value: "service.yaml": file must exist
steps[1].phases[2].objectBundle[0].objectTemplatePath: Invalid value: "service.yaml": file must exist …
```
=> Check for absolute path also while validating object files

clusterloader2/pkg/measurement/common/kube_state_metrics_measurement.go, clusterloader2/pkg/measurement/common/scheduler_latency.go, clusterloader2/pkg/measurement/summary.go
Hello, as discussed and asked on the SIG scalability [mailing list](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/kubernetes-sig-scale/UHx_ISEHT24/TEeAyVn7CAAJ), we need a performance test for kube-state-metrics. I followed the suggestions there, and hopefully, this is correct!
/kind feature
This is needed as the last step of https://github.com/kubernetes/kube-state-metrics 2.0 release. As mentioned in the mailing list, we want to run performance and scale tests to ensure we can run on a certain amount of nodes, but also to give our users some expectations on the number of resources needed, but also the latency they can expect.
kube-state-metrics has two /metrics endpoints, one /metrics that …
=> Add kube-state-metrics latency measurement 

perfdash/github-configs-fetcher.go
/kind cleanup
If there're Github failures,  `github-configs-fetcher.go` only shows `yaml: unmarshal errors:
line 1: cannot unmarshal !!map into []main.githubDirContent` which is not descriptive. 
This PR print github response if there's an unmarshal error. 
Example;
```
./perfdash \
--www
--address=0.0.0.0:8080
--builds=20
--force-builds
--githubConfigDir=https://api.github.com/repos/kubernetes/test-infra/contents/config/jobs/kubernetes/sig-sca_invalid
```
> Note: githubConfigDir is an invalid link
Logs
```
I0212 10:51:48.123168   31660 perfdash.go:73] Starting perfdash...
I0212 10:51:48.125962   31660 perfdash.go:136] Starting server...
I0212 10:51:48.126053   31660 perfdash.go:124] Fetching new data...
I0212 …
```
=> Add more descriptive error for github downloading issues

clusterloader2/pkg/config/cluster.go, clusterloader2/pkg/prometheus/manifests/0ssd-storage-class.yaml, clusterloader2/pkg/prometheus/prometheus.go
Introduce new arguments/envs PROMETHEUS_STORAGE_CLASS_PROVISIONER and PROMETHEUS_STORAGE_CLASS_VOLUME_TYPE that users can use to override prometheus storage class setting.
Signed-off-by: Jiaxin Shan <seedjeffwan@gmail.com>
Usage: 
1. env
```
PROMETHEUS_STORAGE_CLASS_PROVISIONER=kubernetes.io/aws-ebs PROMETHEUS_STORAGE_CLASS_VOLUME_TYPE=gp3 go run cmd/clusterloader.go
```
2. arg
```
--prometheus-storage-class-provisioner=kubernetes.io/aws-ebs --prometheus-storage-class-volume-type=gp3
```
/kind feature
Make storage_class manifest generic and all providers can customize the storage based on their needs. 
Fixes #1723 
**Does this PR introduce a …
=> Support prometheus stacks deployment for different providers

clusterloader2/testing/load/config.yaml
/kind bug
On small clusters, tuning set will fail validation because parallelismLimit = 0. This PR omits the offending tuning set on small clusters, similar to how it is done for the scheduler throughput steps.
Fixes https://github.com/kubernetes/perf-tests/issues/1752
```release-note
NONE
```
```docs
```
=> Remove scheduler throughput tuning set on small clusters

clusterloader2/pkg/measurement/util/wait_for_pods.go
/kind feature
We are not logging whole PodComponentsStatus information. This might be useful to understand what is teh status of failed pods.
/cc @wojtek-t 
=> Log all status information about broken waiter

run-e2e.sh
Until now, we relied on a hardcoded `/go/src/k8s.io/perf-tests` path and pod-utils-based jobs clone repos to `/home/prow/go/src` directory instead.
This change makes it work for both versions of the configs.
=> Fix printing git log in run-e2e.sh

golang/Makefile, golang/build-go.sh, golang/build-kubernetes.sh, golang/push.sh
Perform a major revamp of the scripts inside `golang` directory so that the migration to pod-utils is feasible.
=> Adapt golang subdirectory to pod-utils migration

clusterloader2/pkg/measurement/common/api_availability_measurement.go, clusterloader2/pkg/measurement/common/api_availability_metrics.go, clusterloader2/testing/load/config.yaml
Add a configurable threshold parameter that would serve as an SLO for the measurement.
=> Add SLO parameter to API availability measurement

clusterloader2/pkg/measurement/common/kube_state_metrics_measurement.go, clusterloader2/pkg/prometheus/manifests/exporters/kube-state-metrics/deployment.yaml, clusterloader2/pkg/prometheus/prometheus.go, clusterloader2/pkg/provider/gce.go, clusterloader2/pkg/provider/provider.go
Enable kube-state-metrics to be run in the presubmit load tests.
/hold
=> clusterloader2/testing/load: Adjust kube-state-metrics latency tests

clusterloader2/pkg/imagepreload/imagepreload.go, clusterloader2/pkg/measurement/common/service_creation_latency.go, clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go, clusterloader2/pkg/measurement/util/informer/informer.go, clusterloader2/pkg/measurement/util/selector.go
Migrate informer.NewInformer to cache.ListerWatcher to:
* provide compile-time validation of resources (e.g. typo in resource name will be detected in compilation time)
* make it testable:
* previous code uses on RESTClient which isn't implemented by kubernetes' fake.NewSimpleClientset()
* this code uses a standard way of creating informers which is properly handled by fake.NewSimpleClientset()
I still let informer.NewInformer exists as it has convenient addEventHandler call.
=> Migrate NewInformer to cache.ListerWatcher

clusterloader2/pkg/execservice/exec_service.go, clusterloader2/pkg/imagepreload/imagepreload.go, clusterloader2/pkg/measurement/common/network/network_performance_measurement.go, clusterloader2/pkg/measurement/common/wait_for_controlled_pods.go, clusterloader2/pkg/measurement/common/wait_for_pods.go, clusterloader2/pkg/measurement/util/runtimeobjects/replicaswatcher.go, clusterloader2/pkg/measurement/util/runtimeobjects/runtimeobjects.go, clusterloader2/pkg/measurement/util/runtimeobjects/runtimeobjects_test.go, clusterloader2/pkg/measurement/util/wait_for_pods.go
Problem: waitForControlledPodsRunning for daemonsets calculates a number of expected replicas based on the number of nodes that are schedule. That number can vary over time (e.g. node becoming notready/ready).
We are seeing a tests runs where e.g. node X was unhealthy for a short period of time for whatever reason (physical machine failure). During that time, we calculated a number of replicas. Then node becomes healthy and daemonset controller creates more replicas than we expect making the test fail.
This code introduces a watch for node objects to track accurate number of expected replicas over time
=> Implement watch-based daemonset replica counter.

perfdash/deployment.yaml
Version 2.33 requires more than 10GB of memory and we cannot bump the mem limit without https://github.com/kubernetes/k8s.io/pull/1604
=> Downgrade perf-dash to 2.32

clusterloader2/pkg/measurement/util/wait_for_pods.go
Do not wait for inactive pods during scale down.
Inactive pods happen especially with volatile nodes, e.g. preemptibles.
/kind bug
```release-note
NONE
```
/cc @mborsz
=> Do not wait for inactive pods during scale down

clusterloader2/testing/load/config.yaml
Run the exec command after we additionally load the cluster with the scheduler throughput pods.
=> Delay the exec command step in the load test config

clusterloader2/testing/load/config.yaml
In large clusters we create 2x more latency pods than #nodes. We don't think it's needed, so let's try to remove that.
I will run 5k test to see what happens in that scale.
Presubmit should validate 100 nodes scale.
/hold
=> Reduce $totalSchedulerThroughputPods in large clusters

clusterloader2/pkg/prometheus/manifests/0prometheus-operator-deployment.yaml
Prometheus-operator watches all secrets in the system as part of alertmanager. It also uses json for serialization/deserialization which is CPU/memory consuming.
It happens that when secrets watch is being interrupted, the secrets LIST result is not able to fit in the memory (in large clusters), causing OOMs.
Our tests usually create quite a few secrets, but we don't use any prometheus alert.
Let's use --secret-field-selector option to reduce set of secrets to only the ones that matches field selector type=prometheus-alert (none currently).
=> Make prometheus-operator watch only limited set of secrets

perfdash/deployment.yaml
NAP is already enabled in 'aaa' cluster, we have larger node pools.
Fixes https://github.com/kubernetes/perf-tests/issues/1792
=> Upgrade perfdash to 2.33

perfdash/deployment.yaml
Reverts kubernetes/perf-tests#1796
Even 32GiB of memory isn't sufficient.
/assign @mm4tt
=> Revert "Upgrade perfdash to 2.33"

clusterloader2/testing/overrides/kubemark_5000_nodes.yaml
This is to turn off alerting on slow patches of node statuses for Kubemark 5k CI job.
=> Add custom thresholds override for 5k Kubemark job

clusterloader2/testing/l4ilb/config.yaml
This PR makes the number of ILB services in the scale test to be configurable.
Fixes #
```release-note
NONE
```
```docs
```
=> Make ILB count configurable and increase default to 2.

clusterloader2/testing/l4ilb/config.yaml
`qpsLoad` does not have a `averageQps` field - this should be renamed to `qps`.
Also lowering the QPS to 20.
=> Fix tuning set for the ILB test

clusterloader2/pkg/measurement/common/network/manifests/worker-deployment.yaml, util-images/network/netperfbenchmark/cmd/main.go
/kind feature
Currently the worker pod logs cannot be accessed, this change is for making worker pods to write logs directly to /var/log on host.
Fixes #
NONE
```release-note
```
```docs
```
=> Network Performance tc's: changes for fetching worker pod logs

clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go
/kind bug
See this comment: https://github.com/kubernetes/perf-tests/issues/1096#issuecomment-842099659
N/A
See issue: https://github.com/kubernetes/perf-tests/issues/1096
See PR: https://github.com/kubernetes/test-infra/pull/21694
```release-note
NONE
```
```docs
```
=> Ignore exec subresource in APIResponsivenessPrometheus

clusterloader2/testing/load/config.yaml, clusterloader2/testing/load/job.yaml, clusterloader2/testing/load/modules/reconcile-objects.yaml
Change to 'Parallel Jobs with a work queue' to 'Parallel Jobs with a fixed completion count'
Setting `.spec.completions` to double of possible replicas to make test more resilient for node restart.
https://kubernetes.io/docs/concepts/workloads/controllers/job/#parallel-jobs
=> Change load test job to be more resilient

util-images/probes/OWNERS
The current set of OWNERS in that directory doesn't provide a good overage (technically only wojtek-t is able to do reviews).
Add me to avoid sending all PRs there to wojtek-t.
=> Add mborsz to util-images/probes/OWNERS

OWNERS
Adds mborsz to top-level OWNERS as suggested by @wojtek-t in https://github.com/kubernetes/perf-tests/pull/1819#pullrequestreview-672742974.
/cc @gmarek @mm4tt @shyamjvs @timothysc @wojtek-t
=> Add mborsz to OWNERS

clusterloader2/testing/l4lb/config.yaml
Minor fix to avoid timing out on LB creation when large number of LBs are configured.
=> share timeout config on LB creation and nodesync steps

clusterloader2/testing/load/config.yaml, clusterloader2/testing/load/modules/configmaps-secrets.yaml, clusterloader2/testing/load/modules/reconcile-objects.yaml
Mitigates https://github.com/kubernetes/kubernetes/issues/96635 in load test.
Currently if the following scenario happens:
* We delete deployment X
* We delete configmap used by deployment X
* Any node restarts (which is possible in 5k scale)
* The node will not be able to delete pod in deployment X due to https://github.com/kubernetes/kubernetes/issues/96635
With this mitigation, we delete configmaps/secrets only when we already know that all pod using that pod have been deleted.
Ref https://github.com/kubernetes/perf-tests/issues/1575
=> Mitigate https://github.com/kubernetes/kubernetes/issues/96635 in load test

clusterloader2/testing/load/config.yaml
Bug in https://github.com/kubernetes/perf-tests/pull/1822, the step that is supposed to delete configmaps and secrets in fact no-op patches them.
=> Actually delete configmaps and secrets

clusterloader2/testing/experiments/ignore_known_gce_container_restarts.yaml
We are already ignoring node components. Add 'konnectivity-agent' to the list
=> Ignore few restarts on konnectivity-agent

perfdash/Makefile, perfdash/deployment.yaml, perfdash/metrics-downloader.go, perfdash/perfdash.go
/kind feature
This PR is for unblocking the perfdash upgrade.
Fixes #1792 
NONE
```release-note
```
```docs
```
=> Unblock perfdash upgrade

clusterloader2/testing/load/config.yaml, clusterloader2/testing/load/modules/huge-services.yaml, clusterloader2/testing/load/modules/scheduler-throughput.yaml
/kind bug
Currently, in load test we have 5k pods in huge service. Unfortunately this is too big and causes flakiness of our tests. We would like to find appropriate size of huge service so we can include it in our scalability documentation. The idea is to split huge service to several smaller deployments, and document max service size equal to the size of single deployment.
N/A
N/A
```release-note
N/A
```
```docs
N/A
```
=> Parallelize scheduler-throughput pod creation

clusterloader2/api/validation.go, clusterloader2/api/validation_test.go
/kind feature
Part of #1746 
Logic Implemented :
```
loop through Steps.Phases.tuningSet 
loop through tuningSets
check if Steps.Phases.tuningSet is present
```
```release-note
NONE
```
```docs
```
=> tuning set referenced in a phase must be declared

clusterloader2/pkg/measurement/common/network/network_performance_measurement.go, clusterloader2/pkg/measurement/common/network/performance-measurement-helper.go, clusterloader2/pkg/measurement/common/network/types.go
a) Loss of packet in percentage added
b) Percentile calculation corrected
=> Adding additional metric for UDP Protocol

clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.dashboard.py, clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.json
What type of PR is this?
/kind cleanup
What this PR does / why we need it:
Currently most of "API call latency" panels has the same title: "Read-only API call latency".
This PR make titles more descriptive.
=> Make API call latency panels title more meaningful

clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.dashboard.py, clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.json
/kind cleanup
In APIResponsivenessPrometheus, we are not taking into account long running requests like exec or proxy: https://github.com/kubernetes/perf-tests/blob/7a618c70f992f9718a156106f42e56ab78eecbe6/clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go#L48
This PR removes these two calls from grafana latency panels as well. 
```release-note
```
```docs
```
=> Remove exec and proxy subresources from graphs

clusterloader2/pkg/measurement/common/nodelocaldns_latency_prometheus.go
/kind cleanup
Use `ToPerfData` when returning nodelocaldns metric summary. It converts the latency values to ms and is more verbose.
N/A
/assign @prameshj
/cc @jkaniuk
```release-note
NONE
```
```docs
NONE
```
=> Dump to PerfData when gathering nodelocaldns metric

clusterloader2/pkg/measurement/util/pods.go, clusterloader2/pkg/measurement/util/wait_for_pods.go
This is a first PR of WaitForPods refactor.
The goal is to make the logging in case of timeout more readable:
* not printing all "good state" pods
* making sure that all states in the logs matches actual statuses used in conditions
This PR addresses mostly first part.
I'm afraid to change the WaitForPods logic on Friday afternoon, so will do that in the next PR.
=> Refactor logging in WaitForPods

clusterloader2/pkg/prometheus/README.md, clusterloader2/pkg/prometheus/manifests/exporters/metrics-server/resourceConsumer.yaml, clusterloader2/pkg/prometheus/manifests/exporters/metrics-server/resourceConsumerHpa.yaml
Signed-off-by: JunYang <yang.jun22@zte.com.cn>
/kind feature
implement of issue:  [#710](https://github.com/kubernetes-sigs/metrics-server/issues/710)
Deploy some dummy HPAs to put load on MS and use resource-consumer image maintained as part of test-infra, and will not affect other tests.
Fixes #
part of issue:  [#710](https://github.com/kubernetes-sigs/metrics-server/issues/710)
```release-note
```
```docs
```
=> Automate testing scalability of Metrics Server

clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/prometheus/experimental.go, clusterloader2/pkg/prometheus/prometheus.go
/kind bug
Currently, [kubetest sends SIGINT](https://github.com/kubernetes/test-infra/blob/master/kubetest/process/process.go#L202) in case of test timeout. This is handled by ClusterLoader2 by exiting immediately.
After this changes, SIGINT will be cached and ClusterLoader2 will try to snapshot disk image.
Test timeouts can indicate problems with unresponsive kube-apiserver, so there is no communication attempt to kube-apiserver. Potentially partial data will be lost, but it's a better situation that missing a whole snapshot.
=> Add SIGINT handler to handle Prometheus snapshot

clusterloader2/testing/experimental/storage/pod-startup/config.yaml, clusterloader2/testing/experimental/storage/pod-startup/volume-types/genericephemeralinline/deployment_with_inline.yaml, clusterloader2/testing/experimental/storage/pod-startup/volume-types/genericephemeralinline/override.yaml
/kind feature
This can be used to create pods with a varying number of generic ephemeral
inline volumes.
Example for usage with the "distributed" deployment of csi-driver-host-path:
```
$ cat test.yaml
PODS_PER_NODE: 5
VOLUMES_PER_POD: 3
VOL_SIZE: 1Gi
STORAGE_CLASS: csi-hostpath-fast
$ go run cmd/clusterloader.go -v=3 --kubeconfig=$KUBECONFIG --provider=local --nodes=1 \
--testconfig=testing/experimental/storage/pod-startup/config.yaml \
--testoverrides=testing/experimental/storage/pod-startup/volume-types/genericephemeralinline/override.yaml \
--testoverrides=test.yaml
```
Related-to: https://github.com/kubernetes/enhancements/issues/1698
**Does this PR introduce a user-facing …
=> pod startup: pre-define generic ephemeral volume type

perfdash/Makefile, perfdash/deployment.yaml, perfdash/www/script.js
On OSX, Command key is reported as evt.metaKey and not evt.ctrKey: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/metaKey
It makes it hard to use the scale trimming feature. This PR makes perf-dash trim scale on "Cmd + click"
/assign @jprzychodzen
=> perf-dash: Also cap scale on Command on mac.

clusterloader2/pkg/imagepreload/manifests/daemonset.yaml
Our 1.19 tests are using containerd [1], but the clusterloader tries to use docker pull to fetch images. It fails. The test is not failing only because some other container is using pause:3.1 container.
This backports https://github.com/kubernetes/perf-tests/pull/1654 to make it work
[1] https://github.com/kubernetes/test-infra/blob/7562f6f1ca5e73357264ad194accf5373404c2b0/config/jobs/kubernetes/sig-release/release-branch-jobs/1.19.yaml#L330
=> [backport 1.19] Use containerd in image preloader

clusterloader2/pkg/imagepreload/manifests/daemonset.yaml
Our 1.20 tests are using containerd [1], but the clusterloader tries to use docker pull to fetch images. It fails.
This backports https://github.com/kubernetes/perf-tests/pull/1654 to make it work
[1] https://github.com/kubernetes/test-infra/blob/7562f6f1ca5e73357264ad194accf5373404c2b0/config/jobs/kubernetes/sig-release/release-branch-jobs/1.20.yaml#L330-L335
=> [backport 1.20] Use containerd in image preloader

perfdash/Dockerfile, perfdash/Makefile, perfdash/deployment.yaml
Without explicitly setting permissions for www/ static dir, `docker build` output depends on the chmod on the build workstation. This can lead to setting incorrect file permissions and rendering static file index instead of perfdash.
Let's explicitly request 0644 permissions.
/assign @mm4tt
=> Set www/ permissions in perfdash.

clusterloader2/testing/load/modules/pod-startup-latency.yaml
Make it possible to adjust number of latency pods, by setting CL2_LATENCY_POD_COUNT.
The context is that 500 pods seems to be sufficient in 100 node scale to get stable result.
Most likely, in 5000 similar number of pods will be sufficient, so adding an option to be able to play with it.
=> Add CL2_LATENCY_POD_COUNT

clusterloader2/pkg/imagepreload/imagepreload.go
5m isn't sufficient in very large clusters.
=> Increase image preload timeout to 15m

clusterloader2/testing/load/config.yaml
/kind feature
Rename the existing `HUGE_SERVICES_SIZE` flag to `HUGE_SERVICES_PODS_PER_DEPLOYMENT` which better reflects on it's functionality and reintroduce flag of the same name (`HUGE_SERVICES_SIZE`) that specifies the number of pods that the huge service should consist of.
N/A
This PR is split into two commits. It should make it a bit easier to track the changes as the end result might be a bit confusing.
```release-note
N/A
```
```docs
N/A
```
=> Allow customisation of number of endpoints for huge service

golang/build-kubernetes.sh
We are going to bump the version of K8s for the Golang job, so these cherry picks are no longer needed.
=> Remove old hacky cherry-picks from golang

clusterloader2/pkg/config/template_provider.go
E.g.
```
F0929 10:57:13.881474 4136660 clusterloader.go:305] Error while preloading images: [mapping merging error: merge conflict for key 'CL2_DELETE_TEST_THROUGHPUT': old value=14 (float64), new value=14 (int64)]
```
Without this, it's quite hard to tell why the validation fails in some cases.
=> Print type when there is a merge value conflict.

clusterloader2/pkg/provider/autopilot.go
/kind bug
Autopilot does not support image preloading.
Fixes #
```release-note
```
```docs
```
=> Turn off image preloading for Autopilot

clusterloader2/pkg/measurement/util/histogram.go, clusterloader2/pkg/measurement/util/histogram_test.go
It incorrectly sets count as a value instead of cumulative count.
In "prod", the histogram is generated using https://github.com/kubernetes/perf-tests/blob/d4c896470c6246838edde817dd41af04a181bd73/clusterloader2/pkg/measurement/util/histogram.go#L100-L110 which is using `model.BucketLabel` (value: "le") to populate, which is cumulative already.
=> Fix TestHistogramQuantile test

clusterloader2/drivers/gcp-csi-driver-stable.yaml, clusterloader2/run-e2e.sh
- updated pdcsi installation manifest
- install a default storage class when needed
/kind bug
Fixes #
linked to kubernetes/kubernetes#104722
/assign @mattcary
```release-note
NONE
```
```docs
```
=> Install pdcsi driver in gke scalability test

clusterloader2/pkg/config/cluster.go, clusterloader2/pkg/flags/flags.go, clusterloader2/pkg/flags/types.go, clusterloader2/pkg/prometheus/prometheus.go
Adds a possibility to configure how long ClusterLoader2 should wait for healthy Prometheus stack.
/kind feature
It's useful in case of:
1. Setting lower timeout for a well defined scenarios that should work.
2. Increasing timeout for exporters that need much time to start.
=> Add configurable timeout for Prometheus stack

clusterloader2/testing/load/daemonset.yaml
Allows overriding DaemonSet's maxUnavailable parameter.
=> Add CL2_DS_SURGE

clusterloader2/pkg/measurement/common/metrics_server_prometheus.go, clusterloader2/pkg/measurement/common/nodelocaldns_latency_prometheus.go, clusterloader2/pkg/measurement/common/prometheus_measurement.go, clusterloader2/pkg/measurement/common/scheduling_throughput_prometheus.go, clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go, clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus_test.go, clusterloader2/pkg/measurement/common/slos/network_programming.go, clusterloader2/pkg/measurement/common/slos/network_programming_test.go, clusterloader2/pkg/measurement/common/slos/windows_node_resource_usage.go
/kind feature
This PR adds endTime to Gatherer interface. It is necessary for me to introduce new executor to be used in unit tests in next pull request. This new executor will use prometheus query engine with lazy loader backend, allowing users to load time series from file. Thanks to that we will be able to write unit tests for measurements which will run queries against executor that can parse and execute queries in the same manner as prometheus does. Therefore, we will be able to detect issues with our queries in measurement. Currently in unit tests, we use fakeExecutors which always return the same results for test case even after the query in measurement is changed.
Fixes # …
=> Add endTime to Gatherer interface

clusterloader2/testing/load/configmap.yaml, clusterloader2/testing/load/deployment.yaml, clusterloader2/testing/load/secret.yaml
Reverts kubernetes/perf-tests#1692, since immutable ephemeral volumes are GA since 1.19+ and we do not test older minors anymore.
Fixes https://github.com/kubernetes/perf-tests/issues/1706.
/kind cleanup
/assign @wojtek-t @mborsz
=> Revert "Customize enabling of immutable secrets and configmaps in CL2"

perfdash/perfdash-service.yaml
Ref: https://github.com/kubernetes/k8s.io/issues/2488.
Switch to ClusterIP for the service.
Signed-off-by: Arnaud Meukam <ameukam@gmail.com>
/kind cleanup
/sig k8s-infra
=> perfdash: use NEG for kubernetes service

clusterloader2/testing/huge-service/config.yaml, clusterloader2/testing/huge-service/modules/measurements.yaml, clusterloader2/testing/huge-service/modules/service.yaml, clusterloader2/testing/huge-service/service.yaml, clusterloader2/testing/huge-service/simple-deployment.yaml
/kind feature
We want to decouple scheduler throughput from huge service test. In order to do so, a separate test needs to be implemented. Since we do not test for huge services everywhere, it is done in a separate file.
The default number of endpoints for the new huge service test is 1000 instead of the number of nodes.
There are two modules extracted from the existing `testing/load` configuration:
- `testing/load/modules/measurements.yaml` -> `testing/huge-service/modules/measurements.yaml`
- `testing/load/modules/huge-services.yaml` + `testing/load/modules/scheduler-throughput.yaml` -> `testing/huge-service/modules/service.yaml`
The config has been tested and passes our CI.
N/A …
=> Add separate huge service test config

clusterloader2/examples/generic_query_example.yaml, clusterloader2/pkg/measurement/common/generic_query_measurement.go, clusterloader2/pkg/measurement/common/metrics_server_prometheus.go, clusterloader2/pkg/measurement/common/nodelocaldns_latency_prometheus.go, clusterloader2/pkg/measurement/common/prometheus_measurement.go, clusterloader2/pkg/measurement/common/scheduling_throughput_prometheus.go, clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go, clusterloader2/pkg/measurement/common/slos/network_programming.go, clusterloader2/pkg/measurement/common/slos/windows_node_resource_usage.go
Basic version of a measurement allowing user to pass a custom Prometheus query via config, with the following limitations:
- only latency metrics are supported,
- the query must be parametrized by test duration,
- no checks/assertions available at this point.
Unit tests and documentation update pending.
=> Add generic Prometheus query measurement

clusterloader2/pkg/measurement/common/generic_query_measurement.go
Replace measurement name with metric name in summary.
=> Use metric name in summary

dns/dnsperfgo/Dockerfile
/kind bug
This PR adds bind-tools to dnsperfgo client. Without this, each DNS lookup results in PTR queries for the response IP.  We want the client to primarily test searchpath expansion and include external names. These PTR lookups cause more load(especially if the response has more than 1 IP), which results in regressions from the previous client.  This blocks submission of https://github.com/kubernetes/perf-tests/pull/1962
Fixes #
```release-note
NONE
```
```docs
```
=> Install bind-tools in dnsperfgo image.

clusterloader2/testing/huge-service/modules/service.yaml
/king bug
Add `CL2_CHECK_IF_PODS_ARE_UPDATED` support to the huge-service config.
N/A
This should mimic scheduler-throughput behaviour.
```release-note
N/A
```
```docs
N/A
```
=> Add CL2_CHECK_IF_PODS_ARE_UPDATED support to the huge-service config

clusterloader2/pkg/measurement/common/exec.go, clusterloader2/pkg/util/util.go
Using an integer as a value in Exec measurement command throws a type assertion error.
Let's parse values as strings, as expected.
GetStringArray is only used in Exec measurement, so I feel confident with changing behavior of this function.
=> Add support for integers in Exec measurement

clusterloader2/testing/huge-service/modules/measurements.yaml
/kind bug
/kind regression
After enabling the new huge-service test configuration, there were multiple failures related to slow pod lists per namespace. Investigation showed that there are on average 1-2 slow requests each time the cluster is drastically scaled up or down.
In the load test this was not visible as the test for a larger number of nodes lasts long enough for the p99 to get below 5s threshold. The huge-service test lasts at most a few minutes which is not enough for the same thing to happen.
Therefore a new parameter is introduced for the huge-service test that allows to ignore those few regularly appearing slow calls.
N/A
This change is …
=> Allow additional slow calls in huge-service test

clusterloader2/pkg/measurement/common/wait_for_jobs.go, clusterloader2/pkg/measurement/util/informer/informer.go, clusterloader2/testing/batch/config.yaml, clusterloader2/testing/batch/job.yaml
/kind feature
Adds a WaitForCompletedJobs measurement and a placeholder test.
Part of #799
kubernetes/enhancements#2214 and kubernetes/enhancements#2879
```release-note
Add measurement WaitForCompletedJobs that waits until Jobs complete or fail
```
=> Add WaitForFinishedJobs measurement

clusterloader2/examples/generic_query_example.yaml, clusterloader2/pkg/measurement/common/generic_query_measurement.go, clusterloader2/pkg/measurement/common/generic_query_measurement_test.go, clusterloader2/pkg/util/util.go
Follow-up to #1957. Changes:
- metric is no longer treated as latency,
- multiple queries can be defined for the same measurement instance,
- user can set threshold - all samples are expected to be lesser or equal to it.
@jprzychodzen - can you PTAL and see if the basic metric summary (avg, min, max) is what you meant? I'm not entirely sure what is the use case here (it obviously doesn't do anything for queries with top-level histogram_quantile()). If we're mostly supporting queries returning a single sample, perhaps we could instead return DataItem with names of queries as keys and results as values?
=> Add multiple queries and checks to generic query measurement

util-images/sleep/Dockerfile, util-images/sleep/Makefile, util-images/sleep/README.md, util-images/sleep/main.go
/kind feature
Adds an image with a program that sleeps for a given duration. This will be useful to test Jobs, which run to completion, as opposed to run forever.
Part of #799
```release-note
NONE
```
=> Add image for sleep command

util-images/sleep/main.go
Signed-off-by: Andrew Sy Kim <andrewsy@google.com>
/kind feature
In KEP-1672 we introduced the "terminating" condition for the EndpointSlice API. One of the criteria for graduating this feature to GA is that it has gone through some extensive performance testing to ensure we are not regressing endpointslice performance. This PR adds the option for the sleep image to optionally handle SIGTERM which will be useful for performance testing KEP-1672 later in the v1.24 release cycle.
N/A
```release-note
update sleep image to optionally handle SIGTERM with a --termination-grace-period flag
```
**Additional …
=> update sleep image to optionally handle SIGTERM

clusterloader2/pkg/prometheus/manifests/prometheus-prometheus.yaml
Adding the option to increase Prometheus memory limits to be able to scrape all Cilium metrics in scale tests.
/kind feature
=> Add a CL2 parameter for modifying the Prometheus memory limit

clusterloader2/pkg/config/cluster.go, clusterloader2/pkg/prometheus/manifests/master-ip/master-serviceMonitor.yaml, clusterloader2/pkg/prometheus/prometheus.go
Add PROMETHEUS_SCRAPE_MASTER_KUBELETS override that can be used to scrape only master kubelets, without scraping node kubelets.
Cases:
* PROMETHEUS_SCRAPE_MASTER_KUBELETS is not set, we will fallback to the current behaviour (which is to scrape only if we scrape kubelets on nodes)
* PROMETHEUS_SCRAPE_MASTER_KUBELETS is set, we will ignore PROMETHEUS_SCRAPE_KUBELETS
=> Add PROMETHEUS_SCRAPE_MASTER_KUBELETS

util-images/sleep/Dockerfile, util-images/sleep/Makefile
Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>
This patch adds the `sleep` bin from sleep image to PATH to prevent unwanted confusion when calling the image with explicit command arguments 
```bash
Warning  Failed     8s                 kubelet            Error: container create failed: time="2022-02-23T21:08:56Z" level=error msg="container_linux.go:380: starting container process ca
used: exec: \"sleep\": executable file not found in $PATH" 
```
This error is due the bin is under `/` , and this is not in `"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"`
=> Add sleep bin to PATH

clusterloader2/testing/load/configmap.yaml, clusterloader2/testing/load/deployment.yaml
Use the new DNS client that pushes up metrics and lookups names using GO net.LookupHost.
/kind feature
Fixes #
```release-note
NONE
```
```docs
```
=> Use the new dnsclient in scale tests.

clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go
=> Add TODO about fixing pod-startup-time phases

clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go, clusterloader2/testing/density/scheduler/custom-scheduler-metrics/config-custom-schd-sample.yaml, clusterloader2/testing/density/scheduler/custom-scheduler-metrics/deployment-custom-schd-sample.yaml
This PR adds a new parameter to the configuration called schedulerName. This new parameter will be used by gather action to get metrics for a target custom scheduler.
This is a feature enhancement PR to gather scheduling metrics from custom schedulers.
/kind feature
Fixes  https://github.com/kubernetes/perf-tests/issues/1944
- schedulerName param is now needed in the execute method to gather scheduling metrics. If the value to the param is not supplied then it defaults to the default-scheduler. Please refer to sample yamls present in folder clusterloader2/testing/custom-scheduler-metrics
- This PR was already reviewed here: https://github.com/kubernetes/perf-tests/pull/1945 , closed due to …
=> provides mechanism to gather custom scheduler metrics 

clusterloader2/pkg/measurement/common/generic_query_measurement.go, clusterloader2/pkg/measurement/common/generic_query_measurement_test.go, clusterloader2/pkg/util/util.go
Small change to GenericQueryMeasurement: instead of doing util.GetString and manually parse the config into struct, let's use some automation do to so!
Also changes tests to actually validate this change.
The goal is to make extensions easier.
This is a pilot of the new approach. We may want to migrate all measurements in to this pattern.
/assign @jprzychodzen 
/cc @aleksandra-malinowska
=> GenericQueryMeasurement: tiny refactoring of config parsing

dns/dnsperfgo/Makefile
Bump dnsperfgo to 1.3.0 version to include https://github.com/kubernetes/perf-tests/pull/1981
This should be merged after https://github.com/kubernetes/perf-tests/pull/1981
=> Bump dnsperfgo to 1.3.0 version

clusterloader2/pkg/measurement/common/wait_for_jobs.go, clusterloader2/testing/batch/config.yaml, clusterloader2/testing/batch/job.yaml, clusterloader2/testing/batch/overrides.yaml
/kind feature
Fixes #799
It was not trivial to gather metrics from kcm, so I'm leaving that as a follow up.
Because of this, I increased the resolution of WaitForJobsToFinish gather interval.
```release-note
Add a load test for the Job controller
```
=> Add job load test: create multiple jobs based on the number of nodes

network/benchmarks/netperf/launch.go
/kind cleanup
This PR cleansup/adds followings to `network/benchmarks/netperf`
* set default value to `kubeconfig` flag
* provided [example](https://github.com/kubernetes/perf-tests/blob/master/network/benchmarks/netperf/README.md#test-modes-and-pluggable-cni-modules) and the [make runtests](https://github.com/kubernetes/perf-tests/blob/master/network/benchmarks/netperf/Makefile#L41-L46) didn't specify this value and produce the below error
```bash
make runtests
...
Launching network performance tests
./launch
Network Performance Test
Parameters :
Iterations      :  1
Host Networking :  false
Test Namespace  :  netperf
Docker image    :  sirot/netperf-latest
------------------------------------------------------------ …
```
=> patch netperf cmd flag

clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/config/cluster.go
/kind feature
We want to be able to skip cluster verification for clusters that start with zero nodes.
Fixes #
```release-note
NONE
```
```docs
```
=> Add flag to skip cluster verification

clusterloader2/testing/batch/job.yaml
/kind feature
This is a more realistic scenario. The job controller might do extra syncs before the job actually finishes.
Fixes #
`30s` seems appropriate as it is the time it takes for all the jobs to be created in 100 nodes, using the default flags.
```release-note
NONE
```
```docs
```
=> Make job pods run for some time

clusterloader2/clean-up-old-snapshots-boskos.sh, clusterloader2/clean-up-old-snapshots.sh
/kind feature
This script is intended to be used together with `clean-up-old-snapshots.sh`. It solves an issue of updating projects that are bound to a specific boskos pool.
Example usage (assuming [test-infra](https://github.com/kubernetes/test-infra/tree/fae5b9d844fc61966f2f69bfa57afb9cd27e4a88)):
``` sh
$ ./clean-up-old-snapshots-boskos.sh list ci-kubernetes-e2e-gci-gce-scalability 30 \
scalability-project .../test-infra/config/prow/cluster/build/boskos-resources/boskos-resources.yaml
```
N/A
/assign @jprzychodzen
```release-note
Added a script that removes snapshots for given boskos resources.
``` …
=> Add snapshot clean-up script for boskos resources

clusterloader2/testing/density/deployment.yaml, clusterloader2/testing/density/scheduler/custom-scheduler-metrics/deployment-custom-schd-sample.yaml, clusterloader2/testing/density/scheduler/pod-affinity/deployment.yaml, clusterloader2/testing/density/scheduler/pod-anti-affinity/deployment.yaml, clusterloader2/testing/density/scheduler/pod-topology-spread/deployment.yaml, clusterloader2/testing/load/config.yaml, clusterloader2/testing/node-throughput/config.yaml
Related:
- https://github.com/kubernetes/k8s.io/issues/3411
/kind feature
Switch the scalability jobs to the new proxy for Kubernetes container images.
=>  k8s-infra: Switch to registry.k8s.io

clusterloader2/testing/density/deployment.yaml, clusterloader2/testing/density/scheduler/custom-scheduler-metrics/deployment-custom-schd-sample.yaml, clusterloader2/testing/density/scheduler/pod-affinity/deployment.yaml, clusterloader2/testing/density/scheduler/pod-anti-affinity/deployment.yaml, clusterloader2/testing/density/scheduler/pod-topology-spread/deployment.yaml, clusterloader2/testing/load/config.yaml, clusterloader2/testing/node-throughput/config.yaml
Reverts kubernetes/perf-tests#2024
This breaks internal GKE tests. Let's rollback and figure out why.
=> Revert " k8s-infra: Switch to registry.k8s.io"

clusterloader2/pkg/measurement/measurement_executor.go, clusterloader2/pkg/test/simple_reporter.go, clusterloader2/pkg/test/simple_test_executor.go, clusterloader2/pkg/test/step_summary.go
Two goals:
* improving printability of the ErrorList, as *ErrorList as String() defined.
Now it prints something like:
```
W0408 20:12:39.992612   15124 simple_test_executor.go:174] Got errors during step execution: {{0 0} [0xc062068a90]}
```
Not very helpful.
* improving safety -- while we copy that struct here and there, each copy has a separate lock, but keep using the same slice's underlying array. If we modify append concurrently we can have a race (two goroutines writing to the same underlying array). Even if this happens serially, one goroutine may override results of the second one, as both will share the same memory.
=> Use *errors.ErrorList everywhere

clusterloader2/drivers/gcp-csi-driver-stable.yaml
found while investigating the 100 test on https://github.com/kubernetes/kubernetes/pull/108797 
Not sure if it's a root cause of the failures or not.  I am interested in where I'd find logs in the job that would show this failure.  https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/108797/pull-kubernetes-e2e-gce-100-performance/1522188489787969536 being an example job.
=> stop using PSP API which is removed in 1.25

clusterloader2/pkg/provider/aks.go
/kind feature
/sig-windows
Enables Prometheus server for AKS provider
part of https://github.com/kubernetes/perf-tests/issues/2035
Since #2041 and #2043 have been merged we can enable --enable-prometheus-server flag for AKS provider
```release-note
--enable-prometheus-server flag available for AKS provider
```
```docs
```
=> Enable Prometehus server for AKS provider

clusterloader2/testing/chaosmonkey/ignore_node_killer_container_restarts_100.yaml
Fix node killer test.
Ref. kubernetes/kubernetes#109915
Sample failure from TestGrid (https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability-node-killer/1526128802835468288)
```
{ Failure :0 [measurement call TestMetrics - TestMetrics error: [action gather failed for SystemPodMetrics measurement: restart counts violation: RestartCount(konnectivity-agent-w549l, konnectivity-agent)=1, want <= 0; RestartCount(konnectivity-agent-plt4b, konnectivity-agent)=1, want <= 0]] :0}
```
=> Add konnectivity-agent to ignored restarts for node killer test

clusterloader2/pkg/prometheus/manifests/prometheus-prometheus.yaml
The annotation prevents cluster autoscaler from evicting the pod, reducing potential for disruption to measurements.
=> Add 'do not evict' annotation to Prometheus

clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/config/cluster.go, clusterloader2/pkg/execservice/exec_service.go, clusterloader2/pkg/measurement/common/api_availability_measurement.go, clusterloader2/pkg/measurement/common/service_creation_latency.go, clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus_test.go
/kind feature
Allows setting custom path to `exec_deployment.yaml`. Necessary if clusterloader is ran from another directory than `perf-tests/clusterloader2`.
N/A
This does not introduce a breaking change.
```release-note
NONE
```
```docs
```
=> Make exec_deployment.yaml path configurable

clusterloader2/pkg/prometheus/manifests/0prometheus-operator-deployment.yaml, clusterloader2/pkg/prometheus/manifests/prometheus-prometheus.yaml
Allow custom nodeSelector labels to harden Prometheus Pods
I need to do manual tests to confirm that everything behaves as expected
/hold
=> Add custom nodeSelector for Prometheus

clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go, clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus_test.go, clusterloader2/pkg/measurement/common/slos/testdata/get_slo_failure.yaml, clusterloader2/pkg/measurement/common/slos/testdata/mutating_slo_failure.yaml, clusterloader2/pkg/measurement/common/slos/testdata/namespace_list_slo_failure.yaml
/kind cleanup
1. Update thresholds to reflect updated api_call_latency SLO definition: https://github.com/kubernetes/community/blob/master/sig-scalability/slos/api_call_latency.md#definition
2. Fix/Simplify the getSLOThreshold() logic - before, it would not work for DELETECOLLETION (`verb:DELETE` `scope:namespace`).
Fixes #1908
Change tests classification criteria.
=> Update CL2 APIResponsivenessPrometheus threasholds

clusterloader2/pkg/prometheus/manifests/prometheus-prometheus.yaml
/kind feature
It allows scaling resource requests for Prometheus (as opposed to just memory limits).
N/A
This is a somewhat breaking change but `CL2_PROMETHEUS_MEMORY_LIMIT_FACTOR` is kept for compatibility.
```release-note
```
```docs
```
=> Allow scaling Prometheus resource requests & limits

clusterloader2/pkg/measurement/util/prometheus.go
/kind bug
We are seeing that in some cases, the stateful pod (like prometheus) can be rescheduled and it can take even ~7m to start again due to volume remounting/6m force disk detach timeout.
Let's increase timeout to avoid failing test when this happens.
```release-note
NONE
```
```docs
```
=> Increase prometheus timeout

clusterloader2/pkg/framework/framework.go
/kind bug
delete namespace sometimes fail
Fixes https://github.com/kubernetes/perf-tests/issues/2081
=> fix issue-2081 delete namespace sometimes error

clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/measurement/common/dns/dns_performance-k8s-hostnames.go, clusterloader2/pkg/measurement/common/dns/manifests/clusterrole.yaml, clusterloader2/pkg/measurement/common/dns/manifests/clusterrolebinding.yaml, clusterloader2/pkg/measurement/common/dns/manifests/dns-client.yaml, clusterloader2/pkg/measurement/common/dns/manifests/serviceaccount.yaml
Add a measurement that uses dnsperfgo (https://github.com/kubernetes/perf-tests/tree/master/dns/dnsperfgo) pods to query in-cluster K8s hostnames (based on Services and Endpoints), and report DNS performance metrics.
/kind feature
=> Add measurement for dnsperfgo K8s hostnames test

clusterloader2/cmd/clusterloader.go
Pprof for clusterloader.
It can be used e.g. to understand memory usage in https://github.com/kubernetes/perf-tests/pull/2056.
/assign @jupblb
=> Implement profiling in clusterloader

clusterloader2/go.mod, clusterloader2/pkg/measurement/common/probes/probes.go, clusterloader2/pkg/measurement/common/prometheus_measurement.go, clusterloader2/pkg/measurement/util/prometheus.go, clusterloader2/pkg/prometheus/clients/gcp_managed.go, clusterloader2/pkg/prometheus/clients/in_cluster.go, clusterloader2/pkg/prometheus/clients/interface.go, clusterloader2/pkg/provider/aks.go, clusterloader2/pkg/provider/autopilot.go, clusterloader2/pkg/provider/aws.go, clusterloader2/pkg/provider/eks.go, clusterloader2/pkg/provider/gce.go, clusterloader2/pkg/provider/gke.go, clusterloader2/pkg/provider/gke_kubemark.go, clusterloader2/pkg/provider/kcp.go, clusterloader2/pkg/provider/kind.go, clusterloader2/pkg/provider/kubemark.go, clusterloader2/pkg/provider/local.go, clusterloader2/pkg/provider/provider.go, clusterloader2/pkg/provider/skeleton.go, clusterloader2/pkg/provider/util.go, clusterloader2/pkg/provider/vsphere.go, clusterloader2/testing/load/modules/measurements.yaml
This change adds a GCE-related API quotas usage measurement to the `load` test.
Underneath, we extend the CL2's capabilities to use the [Google Cloud Managed Service for Prometheus](https://cloud.google.com/stackdriver/docs/managed-prometheus) as a backend instead of the in-cluster Prometheus instance. This backend be enabled through `prometheusClient: managed` parameter in the Prometheus-based measurements' params in the test scenario config and works only for a limited number of providers.
=> Add GCP Compute API quotas usage measurement

clusterloader2/testing/load/modules/measurements.yaml
The tests should fail when the DNS latency or error thresholds are exceeded.
/kind feature
=> Enable violations for the advanced DNS test

clusterloader2/pkg/framework/client/objects.go, clusterloader2/pkg/framework/client/objects_test.go
We rarely see "http2: client connection lost" error which means that ping for a given connection has timed out. Based on what we see it is usually transient issue and further calls seems to work fine.
Let's not fail the test on this error.
=> Retry transient http2 errors

clusterloader2/pkg/test/interface.go, clusterloader2/pkg/test/simple_reporter.go, clusterloader2/pkg/test/step_summary.go
We copy the StepResult in multiple places which doesn't make sense as we have a lock inside, which cannot be copied.
=> Pass StepResult only as pointer as it contains lock which cannot be copied

clusterloader2/pkg/execservice/exec_service.go, clusterloader2/pkg/measurement/common/network/network_performance_measurement.go, clusterloader2/pkg/measurement/common/wait_for_controlled_pods.go, clusterloader2/pkg/measurement/common/wait_for_pods.go, clusterloader2/pkg/measurement/util/object_store.go, clusterloader2/pkg/measurement/util/runtimeobjects/runtimeobjects.go, clusterloader2/pkg/measurement/util/runtimeobjects/runtimeobjects_test.go, clusterloader2/pkg/measurement/util/wait_for_pods.go
Few changes:
* Rename WaitForPodsWithLister to WaitForPods
* Remove Selector from WaitForPodOptions (as in the current state it doesn't need to match podStore, which may be misleading), as it's used only for providing human readable identifier of pods (this is being moved to PodLister interface).
* Remove GetSelectorFromRuntimeObject which is no longer used anywhere
=> Cleanup of WaitForPods

clusterloader2/testing/load/job.yaml
/kind bug
The default limit is 6 which does not play well with our `big-job` deployment.
N/A
```release-note
NONE
```
```docs
```
=> Set backoff limit for load test job

clusterloader2/testing/l4lb/config.yaml
/kind bug
Add sleep to wait for LB resources to be cleaned up, before deleting 
In the current state, cluster gets deleted, and 10 minutes (default wait to clean up resources) is not enough to remove all LBs and Deployments, that is why tests are failing
=> Add sleep after deleting LBs in l4lb test

perfdash/Makefile, perfdash/deployment.yaml, perfdash/gcs_metrics_bucket.go, perfdash/perfdash.go
Public Perfdash uses buckets that are not compatible with Application Default Credentials:
Thrown error:
```
<?xml version='1.0' encoding='UTF-8'?><Error><Code>PreconditionFailed</Code><Message>The operation requires that Uniform Bucket Level Access be enabled.</Message><Details>The type of authentication token used for this request requires that Uniform Bucket Level Access be enabled.</Details></Error>
```
=> Hide  ADC mode behind a flag

clusterloader2/pkg/execservice/exec_service.go, clusterloader2/pkg/measurement/common/network/network_performance_measurement.go, clusterloader2/pkg/measurement/common/wait_for_controlled_pods.go, clusterloader2/pkg/measurement/common/wait_for_pods.go, clusterloader2/pkg/measurement/util/runtimeobjects/replicaswatcher.go, clusterloader2/pkg/measurement/util/wait_for_pods.go
This PR refactors WaitForControlledPodsRunning measurement to:
* cleanup tidy terminate logic (which e.g. never closes stopCh on happy path) and is spread between two pieces of code
* use context as a termination signal -- this will be needed in the next PRs
I'm going to extend WaitForControlledPodsRunning to handle different timeout pattern (waiting on timeout defined in gather) and it will be easier this way.
=> Refactor WaitForControlledPodsRunning to use context

clusterloader2/pkg/measurement/util/controlled_pods_indexer.go, clusterloader2/pkg/measurement/util/controlled_pods_indexer_test.go
After submission of https://github.com/kubernetes/perf-tests/pull/2103 we handle "wait for deployment deletion" case incorrectly.
Once the ReplicaSet objects get deleted, we lose track of pods associated with the deployment so currently all pods are "deleted" when in fact that deployment's ReplicaSets are deleted, not the pods themselves.
=> Fix WaitForControlledPodsRunning for deletion of deployments

clusterloader2/pkg/execservice/exec_service.go, clusterloader2/pkg/measurement/common/loadbalancer_nodesync_latency.go, clusterloader2/pkg/measurement/common/network/network_performance_measurement.go, clusterloader2/pkg/measurement/common/ooms_tracker.go, clusterloader2/pkg/measurement/common/scheduling_throughput.go, clusterloader2/pkg/measurement/common/service_creation_latency.go, clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go, clusterloader2/pkg/measurement/common/wait_for_controlled_pods.go, clusterloader2/pkg/measurement/common/wait_for_jobs.go, clusterloader2/pkg/measurement/common/wait_for_nodes.go, clusterloader2/pkg/measurement/common/wait_for_pods.go, clusterloader2/pkg/measurement/common/wait_for_pvcs.go, clusterloader2/pkg/measurement/common/wait_for_pvs.go, clusterloader2/pkg/measurement/util/informer/informer.go, clusterloader2/pkg/measurement/util/object_store.go, clusterloader2/pkg/measurement/util/wait_for_nodes.go, clusterloader2/pkg/measurement/util/wait_for_pvcs.go, clusterloader2/pkg/measurement/util/wait_for_pvs.go, clusterloader2/pkg/util/selector.go, clusterloader2/pkg/util/util.go, clusterloader2/pkg/util/util_test.go
In two steps:
* Moves ObjectSelector to util to prevent import cycle
* Add tests to show:
* Defaulting behavior
* Ability to deserialize complex datatypes as ObjectSelector.
=> Add unit tests to util.ToStruct

clusterloader2/pkg/measurement/util/wait_for_pods.go
Won't harm in any case and may be useful if we make the timeout logic more complex than 15m.
=> Print timeout in WaitForPods

clusterloader2/pkg/config/template_functions.go, clusterloader2/testing/load/modules/pod-startup-latency.yaml
This PR tries to shorten pod startup latency phase in large clusters.
Reasoning:
* Given that we artificially slow down pod creation introducing delay between each, we can think about them as independent random variables
* In 100 node tests, we see that sample size of 500 is enough to reduce variance of the result
* In 5k it should be also case, as we don't expect the variance to grow with cluster size, as the latency is dominated by "schedule_to_run" phase which happens on each independent kubelet.
In this attempt we try to reduce this to 500 in any scale.
The preliminary result suggests that it's sufficient. I will try to start few more runs before merging.
/hold for manual runs
=> Shorten pod startup latency

clusterloader2/pkg/measurement/common/wait_for_controlled_pods.go, clusterloader2/testing/load/config.yaml, clusterloader2/testing/load/modules/reconcile-objects.yaml
Right now, the test tries to spread load to generate expected load on the control plane. It has been introduced when master was able to handle max 10 pods per second and was overloading with higher throughput.
Now we are in a state when it is able to handle 100 pods per second throughput (we have at least few manual runs with this PR, the metrics look comparable to regular runs).
Let's remove the artificial throttling to:
* make the test harder (it also validates property of k8s master that prevents overload)
* to make the test faster in happy case
The feature is controlled by CL2_RATE_LIMIT_POD_CREATION (default true) to keep default behavior.
We will gradually swap all tests to false and then remove the env var.
=> Remove artificial pod creation/update/delete rate limiting

clusterloader2/testing/load/config.yaml, clusterloader2/testing/load/modules/scheduler-throughput.yaml
Few steps:
* Removes SCHEDULER_THROUGHPUT_SIZE as it's not set anywhere
* Assume we always create a single replica per namespace
* In clusters <= 1000 nodes use single deployment with 1000 pods
* In clusters > 1000 nodes, use single deployment with .Nodes pods
* We still allow to customize SCHEDULER_THROUGHPUT_PODS_PER_DEPLOYMENT as we use that in some tests
* Changes tuningsets to remove custom logic 
/assign @jupblb
=> Simplify scheduler throughput module

clusterloader2/pkg/measurement/common/wait_for_controlled_pods.go, clusterloader2/testing/load/config.yaml, clusterloader2/testing/load/modules/reconcile-objects.yaml
Reverts kubernetes/perf-tests#2128
For some reason change guarding doesn't work. Even without changing flag we change tuningset to 100qps in 100 node tests.
=> Revert "Remove artificial pod creation/update/delete rate limiting"

clusterloader2/pkg/measurement/common/wait_for_controlled_pods.go, clusterloader2/testing/load/config.yaml, clusterloader2/testing/load/modules/reconcile-objects.yaml, clusterloader2/testing/load/modules/scheduler-throughput.yaml
Roll forward https://github.com/kubernetes/perf-tests/pull/2128, this time with fixed change guarding.
/hold for me to check generatedConfig this time.
=> Remove artificial pod creation/update/delete rate limiting #2

clusterloader2/testing/huge-service/modules/service.yaml
In some environments, upgrade process takes even 17m. Let's increase timeout to have some slack.
/assign @jupblb
=> Increase operationTimeout to 30m in huge-service test

clusterloader2/docs/create-new-test.md
This PR adds information about adding a new test to [test-infra](https://github.com/kubernetes/test-infra/tree/master/config/jobs/kubernetes/sig-scalability) that uses clusterloader2.
N/A
/assign @jprzychodzen
```release-note
NONE
```
```docs
```
=> Add documentation about adding a new clusterloader2 test

clusterloader2/pkg/measurement/common/generic_query_measurement.go, clusterloader2/pkg/measurement/common/generic_query_measurement_test.go, clusterloader2/testing/load/modules/measurements.yaml
Changes:
1. Modify generic_query_measurement to support PromQL queries that have multiple duration placeholders `[%v]`.
2. Add DNS lookup error percentage query to the advanced DNS test measurement in load test config, and move the threshold from DNS lookup error count to the DNS lookup error percentage query, with 0.1% threshold, meaning that there must be at least 99.9% of successful DNS lookups.
/kind feature
=> Add DNS lookup error percentage threshold instead of error count

network/OWNERS
Adds dlapcevic as approver for dns and networking directories.
```release-note
NONE
```
```docs
```
=> Add dlapcevic as owner for networking directories

clusterloader2/examples/generic_query_example.yaml, clusterloader2/pkg/measurement/common/generic_query_measurement.go, clusterloader2/pkg/measurement/common/generic_query_measurement_test.go
Add support for `requireSamples` field to GenericQueryMeasurement. Setting it true will cause the test to fail in case no samples are found for the query.
=> Add requireSamples field to GenericQueryMeasurement

clusterloader2/testing/huge-service/config.yaml, clusterloader2/testing/huge-service/modules/service.yaml, clusterloader2/testing/huge-service/modules/statefulset.yaml, clusterloader2/testing/huge-service/statefulset.yaml, clusterloader2/testing/huge-service/statefulset_service.yaml
Expand DNS test coverage in the huge-service test to verify that DNS lookups work for all in-cluster hostnames.
Statefulset pods automatically have hostnames assigned to them. Pods with hostnames behind headless services get their own DNS records.
/kind feature
=> Add statefulset behind a headless service to huge-service test

network/benchmarks/netperf/Dockerfile, network/benchmarks/netperf/launch.go, network/benchmarks/netperf/nptest/nptest.go, network/benchmarks/netperf/nptest/nptest_test.go
/kind feature
Currently netperf only supports `iperf`. 
`iperf` measures throughput only. 
`qperf` allows measuring both throughput and latency. It will also allow comparing numbers across the tools. 
Fixes #
```release-note
NONE
```
```docs
NONE
```
=> Add qperf support to netperf for network benchmarking

.golangci.yml, perfdash/parser.go
/kind cleanup
`golangci-lint` suggests replacing `golint` with `revive`:
```
level=warning msg="[runner] The linter 'golint' is deprecated (since v1.41.0) due to: The repository of the linter has been archived by the owner.  Replaced by revive."
```
Example: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/perf-tests/2156/pull-perf-tests-verify-lint/1580176208107147264
N/A
=> Replace golint with revive

util-images/request-benchmark/Makefile, util-images/request-benchmark/main.go
/kind feature
If benchmark's URI is invalid then the process will continue nonetheless. Added a loop of `10` iterations that ensures the tool can reach desired URI. This is useful because in case of failure the pod will restart and a CL2 scenario using this tool will stop in pod deployment phase.
N/A
=> Add a health check to request benchmark

clusterloader2/testing/request-benchmark/config.yaml, clusterloader2/testing/request-benchmark/modules/measurements.yaml
/kind bug
We noticed that variance of different indicators is higher at the beginning of the test so this PR adds 1m before the CPU measurement starts so that we are sure this does not influence results.
N/A
=> Extend benchmark duration

clusterloader2/testing/request-benchmark/deployment.yaml
/kind bug
Benchmark may reach something like 800 QPS easily for a single inflight so it's better to ensure it has enough processing throughput on the client side.
N/A
=> Bump benchmark requests

clusterloader2/testing/request-benchmark/deployment.yaml
/kind cleanup
A single inflight is generated by a single go routine. Additionally, there is one main go routine. Therefore instead of requesting `2 * Inflight` CPUs we can have `Inflight + 1` instead.
N/A
=> Reduce benchmark requests

clusterloader2/pkg/measurement/common/api_availability_metrics.go
Fixes https://github.com/kubernetes/perf-tests/issues/2092
=> Fix consecutive failed probes counting in API availability measurement

clusterloader2/pkg/measurement/common/bundle/test_metrics.go
/kind cleanup
I noticed that `apiServerCPUProfile` was used for memory profile execution (during gather), this PR fixes that
Fixes #
=> bundle: Use apiServerMemoryProfile for memory profile

clusterloader2/pkg/test/modules.go
/kind cleanup
Error message now (example):
```
F1019 12:19:24.281334   28900 clusterloader.go:379] Test compilation failed: [error flattening module steps: erorr while processing module api.Module{Steps:[]*api.Step(nil)}: decoding failed: error converting YAML to JSON: yaml: line 15: mapping values are not allowed in this context]
```
Error message after this PR (example):
```
F1019 12:21:40.998204   29714 clusterloader.go:379] Test compilation failed: [error flattening module steps: error while processing module modules/benchmark-deployment.yaml: decoding failed: error converting YAML to JSON: yaml: line 15: mapping values are not allowed in this context]
```
N/A
**Special notes for …
=> Improve error message on module parsing

clusterloader2/pkg/measurement/common/resource_usage.go, clusterloader2/pkg/provider/aks.go, clusterloader2/pkg/provider/aws.go, clusterloader2/pkg/provider/eks.go, clusterloader2/pkg/provider/gce.go, clusterloader2/pkg/provider/gke.go, clusterloader2/pkg/provider/gke_kubemark.go, clusterloader2/pkg/provider/kcp.go, clusterloader2/pkg/provider/kind.go, clusterloader2/pkg/provider/kubemark.go, clusterloader2/pkg/provider/local.go, clusterloader2/pkg/provider/provider.go, clusterloader2/pkg/provider/skeleton.go, clusterloader2/pkg/provider/vsphere.go
Currently, to get the resource usage of containers, the resource usage measurement queries `nodes/proxy` subresource underneath to access the `/stats/summary` endpoint of kubelets. Autopilot provider doesn't permit the user to access that subresource at all.
=> Disable resource usage measurement for Autopilot provider

clusterloader2/pkg/config/cluster.go, clusterloader2/pkg/prometheus/manifests/prometheus-prometheus.yaml, clusterloader2/pkg/prometheus/prometheus.go
/kind feature
This PR allows overriding the storage class used for prometheus pvc.
When working with kind, we need to use the already installed storage class (`standard`).
=> feat: allow overriding the storage class used for prometheus pvc

clusterloader2/pkg/measurement/common/job_lifecycle_latency.go, clusterloader2/testing/batch/config.yaml, clusterloader2/testing/batch/job.yaml
Created Job Startup Latency Measurement to measure how fast Kubernetes Jobs transition from `Created` to `Started` state. It also measures the transition latency from `Started` to `Completed` states. 
The measurement uses the existing Phase Latency utility to calculate the latency and it's heavily influenced by the Pod Startup Latency measurement.
The initial motivation to introduce this feature was to support performance and scalability testing of [Kueue](https://github.com/kubernetes-sigs/kueue) operator, but the measurement is not Kueue specific and can be used with any Kubernetes Jobs
cc @alculquicondor
=> Job Startup Latency Measurement

clusterloader2/testing/load/modules/measurements.yaml
/kind feature
This PR adds a new Prometheus-based measurement that counts the closed watchers.
Linked with https://github.com/kubernetes/perf-tests/issues/2054 
/assign @marseel @wojtek-t
=> Add terminated watches metrics

clusterloader2/pkg/prometheus/manifests/master-ip/master-serviceMonitor.yaml
/kind bug
This PR fixes master kubelets service monitor in CL2.
The service monitor lacks `bearerTokenFile` leading to 401 when scraping master kubelets.
=> fix: master kubelets service monitor in CL2

clusterloader2/pkg/config/cluster.go, clusterloader2/pkg/prometheus/manifests/prometheus-prometheus.yaml, clusterloader2/pkg/prometheus/prometheus.go
/kind feature
This PR allows overriding prometheus memory request.
It currently is hardcoded to `10Gi` when scraping kubelets.
When running CL2 on small clusters this request can too high, this PR allows one the configure the memory request used by the prometheus pod.
=> feat: allow overriding prometheus memory request

clusterloader2/testing/experimental/storage/pod-startup/config.yaml
Ref https://github.com/kubernetes/kubernetes/issues/109915
Before the failure are understood, let's simply disable the non-critical metrics in this test to turn it back to green.
```release-note
NONE
```
/kind bug
/assign @mborsz @marseel
=> Turn storage scalability tests to green

clusterloader2/pkg/config/cluster.go, clusterloader2/pkg/prometheus/prometheus.go
/kind feature
Enables Prometheus manifests that scrape Master to use public ips, instead of internal ones.
=> [ClusterLoader2] Enable usage of public IPs for master scraping

clusterloader2/testing/load/modules/measurements.yaml
kube-proxy implemented a new feature to do only partial restore of iptables rules to improve its performance.
The feature adds a new metrics that signals the operator if something goes wrong during the partial resttore. If this metrics is different than zero it most probably a bug in the code.
/kind feature
Ref: https://github.com/kubernetes/enhancements/pull/3454/files#r979617744
=> kube-proxy iptables partial restore failures

clusterloader2/pkg/config/cluster.go, clusterloader2/pkg/config/template_provider.go, clusterloader2/pkg/execservice/exec_service.go, clusterloader2/pkg/framework/framework.go, clusterloader2/pkg/test/simple_context.go
/kind cleanup
Clusterloader now reads a lot from $GOPATH which is problematic (e.g. when is executed from a different path or when binary has been built with different version than is now available in $GOPATH).
This is a first PR that aims to break this dependency in favour of embed.FS: we will embed necessary files (such as manifests which are considered a part of measurements). The test config files (such as load/config.yaml) will be still stored externally as they are not part of the testing framework.
This PR implements necessary interface and migrates the first that reads data in runtime: exec measurement as POC.
See https://github.com/kubernetes/perf-tests/pull/2199 for ~goal where are we going.
/assign @jupblb 
Fixes #
=> CL2: Use embed FS instead of relying on $GOPATH.

clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/config/cluster.go, clusterloader2/pkg/config/template_functions.go, clusterloader2/pkg/config/template_provider.go, clusterloader2/pkg/prometheus/manifests/grafana-dashboardDefinitions.yaml, clusterloader2/pkg/prometheus/prometheus.go
/kind cleanup
This is a follow up to https://github.com/kubernetes/perf-tests/pull/2200
This PR migrates the most manifest-heavy part of CL2: prometheus.
It includes https://github.com/kubernetes/perf-tests/pull/2200, please review the second commit only.
/assign @jupblb
=> Migrate prometheus manifests to embed FS

clusterloader2/pkg/imagepreload/imagepreload.go, clusterloader2/pkg/measurement/common/dns/dns_performance-k8s-hostnames.go, clusterloader2/pkg/measurement/common/network/network_performance_measurement.go, clusterloader2/pkg/measurement/common/probes/probes.go
/kind cleanup
Follow up to https://github.com/kubernetes/perf-tests/pull/2200.
This PR migrates remaining part of manifests to embed FS.
The goal is to reduce runtime dependency on $GOPATH.
Fixes #
=> Migrate remaining manifests to embed

clusterloader2/pkg/measurement/common/service_creation_latency.go
This is adding support for Dual Stack Kubernetes services
/kind feature
When checking if service is reachable we were checking only first Service IP
This PR adds checking all IPs, this adds support for DualStack services, which can have 2 IPs
=> Add checking all IPs in Service reachibility verification

clusterloader2/pkg/test/simple_test_executor.go
/kind bug
Observed in https://github.com/kubernetes/perf-tests/pull/2208
if objectBundle is empty, the CL2 fails.
/hold to see if the presubmit in https://github.com/kubernetes/perf-tests/pull/2208 passes
=> Fix case when there are no replicas

clusterloader2/pkg/provider/gke.go
I am running performance tests on GKE clusters and would like to measure several metrics provided by the `kube-state-metrics` scrapper (such as `kube_pod_info`).
I tested the change locally and verified that the scraper was successfully deployed if the `prometheus-scrape-kube-state-metrics` flag was enabled and I also could query the metrics in Prometheus.
Is there any particular reason why it's an option only for GCE for now?
=> Allow to optionally deploy kube-state-metrics scrapper on GKE clusters

clusterloader2/pkg/prometheus/manifests/0prometheus-priorityclass.yaml, clusterloader2/pkg/prometheus/manifests/grafana-deployment.yaml, clusterloader2/pkg/prometheus/manifests/prometheus-prometheus.yaml
The goal is to prevent eviction of prometheus when some pods with higher priority are created as part of the test.
/hold (for me to ensure in manual run that the goal is achieved)
=> Set priorityclass in prometheus

clusterloader2/pkg/measurement/common/api_availability_measurement.go
The goal is to make simpler debugging error cases by printing why it failed.
=> Improve error logging in exec service

clusterloader2/pkg/measurement/common/wait_for_controlled_pods.go
/kind bug
One of the test runs has failed with
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x17b1e9a]
goroutine 79903 [running]:
k8s.io/perf-tests/clusterloader2/pkg/measurement/common.(*objectChecker).Stop(0x1aa49a0)
/home/prow/go/src/k8s.io/perf-tests/clusterloader2/pkg/measurement/common/wait_for_controlled_pods.go:713 +0x7a
k8s.io/perf-tests/clusterloader2/pkg/measurement/util/checker.Map.Add(...)
/home/prow/go/src/k8s.io/perf-tests/clusterloader2/pkg/measurement/util/checker/checker_map.go:43
k8s.io/perf-tests/clusterloader2/pkg/measurement/common.(*waitForControlledPodsRunningMeasurement).handleObjectLocked(0xc03c6c9ba0, {0x0, 0x0}, {0x20edda0, 0xc081055010}) …
```
=> Avoid race in subsequent changes to the same controller

clusterloader2/pkg/execservice/exec_service.go, clusterloader2/pkg/measurement/common/api_availability_measurement.go, clusterloader2/pkg/measurement/common/service_creation_latency.go
/kind feature
With the current approach the whole operation of polling single master health via exec command can get stuck for a latency of respective POST call, which in case of overloaded cluster can take O(minutes) .
Fixes #
=> Add timeout to exec command used for polling single master health

clusterloader2/pkg/measurement/common/wait_for_controlled_pods.go, clusterloader2/pkg/measurement/util/wait_for_pods.go
e.g. now it happens that if we update controller (e.g. job, deployment) we wait on, we see time out error as new observed revision of the controller cancels context used by WaitForPods to start a new one, for new revision.
While it doesn't break anything, it is quite misleading.
=> WaitForPods: print timeout debugging data only if we are really seeing timeout.

network/benchmarks/netperf/Dockerfile
- Update netperf container base from `debian:jessie` to `debian:bullseye`
- Add `CFLAGS=-fcommon` to build of netperf binary
- The default image `sirot/netperf-latest` used by the netperf test crashes when given the `-testFrom` and `-testTo` parameters. These parameters cannot be turned off, but are implicitly set when omitted by user; introduced by kubernetes/perf-tests#2144.
- `debian:jessie` container on docker hub is ~2 years old: apt repo keys are expired, thus preventing dependency installation and container build
- After upgrade to `debian:bullseye`, with a newer compiler, netperf needs `-fcommon` flag for building (as workaround); see HewlettPackard/netperf#46
Updating the container is necessary to run the tests at all, fixing a regression introduced by the additionally passed …
=> Fix netperf docker image build failure

network/tools/network-policy-enforcement-latency/pkg/metrics/metrics.go, network/tools/network-policy-enforcement-latency/pkg/utils/utils.go, network/tools/network-policy-enforcement-latency/pod-creation-reachability-latency/test-client/client.go, network/tools/network-policy-enforcement-latency/policy-creation-enforcement-latency/test-client/client.go
Two fixes for the metrics:
1. The metrics server was being prematurely shutdown, and it was impossible to scrape the metrics. The metrics server shutdown call was moved from `initialize` to `run`.
2. Registering multiple metrics in the pod creation reachability test is fixed, by using the `prometheus.Collector`.
/kind bug
=> Fix metrics server to run until the app is shut down and register multiple metrics correctly

util-images/request-benchmark/main.go
Useful for testing other requests than GETs
/assign @jprzychodzen
=> Allow specifying verb in request-benchmark

clusterloader2/api/default.go, clusterloader2/api/types.go, clusterloader2/pkg/execservice/exec_service.go, clusterloader2/pkg/framework/client/objects.go, clusterloader2/pkg/framework/framework.go, clusterloader2/pkg/imagepreload/imagepreload.go, clusterloader2/pkg/measurement/common/network/network_performance_measurement.go, clusterloader2/pkg/measurement/common/probes/probes.go, clusterloader2/pkg/prometheus/prometheus.go, clusterloader2/pkg/test/simple_test_executor.go, clusterloader2/testing/huge-service/config.yaml
/kind feature
This PR makes it possible to customize namespace deletion timeout, as it's not possible that all tests everywhere can fit in 10m.
This PR also uses the possibility to customize it in huge service which in some cases takes more than 10m to cleanup (it's short and creates tons of events).
Fixes #
/assign @Argh4k
=> Add a way to customize namespace deletion timeout

golang/build-kubernetes.sh
/kind bug
ci-build-and-push-k8s-at-golang-tip job is currently broken because it is using debian stretch and it was moved to archive.debian.org (https://lists.debian.org/debian-devel-announce/2023/03/msg00006.html).
Fixes #
=> use new debian image in build_kube_cross for golang job

clusterloader2/examples/generic_query_example.yaml, clusterloader2/pkg/framework/framework.go, clusterloader2/pkg/measurement/common/metrics_server_prometheus.go, clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go, clusterloader2/pkg/measurement/common/testdata/api_responsiveness_prometheus/above_slow_count_failure.yaml, clusterloader2/pkg/measurement/common/testdata/api_responsiveness_prometheus/below_slow_count_pass.yaml, clusterloader2/pkg/measurement/common/testdata/api_responsiveness_prometheus/cluster_list_slo_failure.yaml, clusterloader2/pkg/measurement/common/testdata/api_responsiveness_prometheus/get_slo_failure.yaml, clusterloader2/pkg/measurement/common/testdata/api_responsiveness_prometheus/mutating_slo_failure.yaml, clusterloader2/pkg/measurement/common/testdata/api_responsiveness_prometheus/namespace_list_slo_failure.yaml, clusterloader2/pkg/measurement/common/testdata/api_responsiveness_prometheus/rules.yml, clusterloader2/pkg/measurement/common/testdata/api_responsiveness_prometheus/slo_pass.yaml, clusterloader2/pkg/measurement/interface.go, clusterloader2/pkg/measurement/manager.go, clusterloader2/pkg/measurement/util/metrics.go, clusterloader2/pkg/prometheus/manifests/prometheus-rules.yaml
/kind cleanup
In Kubernetes 1.23.0 a new request latency metric more suitable for SLOs since it doesn't account for webhooks latency was introduced. Since this new metric is better suited to clusterloader2 than the general-purpose one, it would make sense to update the existing Prometheus rules.
Note that this implies moving from a STABLE metric to an ALPHA one, but considering that the new metric has been around for already 3 releases and that it has a real-life scenario attached to it, the metric is very unlikely to be removed in the future.
This metric has been renamed in Kubernetes 1.26 (https://github.com/kubernetes/kubernetes/pull/112679) which means that the queries will only work on clusters from 1.26 onward. Would that be problematic for the support policy of clusterloader2?
This …
=> clusterloader2: use new apiserver latency SLI

clusterloader2/run-e2e.sh
Fix https://github.com/kubernetes/kubernetes/issues/104809
This effectively moved clusterloader calls to `workload-low` PriorityLevel (matched by service-accounts FlowSchema)
=> Don't use default kubeconfig for clusterloader

clusterloader2/pkg/provider/aws.go
/kind bug
Scrape k8s apiserver only metrics for AWS provider (added `ShouldPrometheusScrapeApiserverOnly : true` + sorted other options)
CL2 was unable to scrape kcm metrics:
```
4/8 targets are ready, example not ready target: {map[endpoint:kube-controller-manager instance:192.168.149.39:10257 job:master namespace:monitoring service:master] down}
```
=> Scrape k8s apiserver only for aws provider

perfdash/config.go
/kind bug
/kind failing-test
This is required because an empty name is no longer supported: the perf-dashboard is run with --allow-parsers-matching-all-tests=false which causes perfdash to skip current configuration for BenchmarkPerfResults as it does not have name set (https://github.com/kubernetes/perf-tests/blob/4674704f45e5d9785741b0399426cbfced37a648/perfdash/metrics-downloader.go#L165-L167).
The corresponding change for writing that file with "benchmark" is in https://github.com/kubernetes/kubernetes/pull/118164.
=> perf-dash: add "benchmark" as name also for BenchmarkPerfScheduling

perfdash/Makefile, perfdash/config.go, perfdash/deployment.yaml
/kind bug
We need that to display BenchmarkPerfResults on perfdash
=> Fix BenchmarkPerfResults name. Release perfdash 2.46

perfdash/config.go
a separate job type will allow to display metrics
collected during watchlist per tests like
https://perf-dash.k8s.io/#/?jobname=gce-100Nodes-master&metriccategoryname=E2E&metricname=LoadResources&PodName=kube-apiserver-e2e-big-master%2Fkube-apiserver&Resource=memory
Fixes #
=> watch-list: define a job type for the perf-dashboard

clusterloader2/testing/watch-list/config.yaml
/kind feature
Running more than one instance of the watch-list perf test we will put more load on the api-server.
An increased load on the server will allows us for better comparison/understanding scaling characteristic of the streaming API feature.
A single instance (`job`) of the performance test requires `6 CPUs, 16 RAM`. The test runs on an `e2-standard-16` machine with `16 CPU, 64 GB`. 
Fixes #
=> watch-list/job: run two replicas per namespace

dns/dnsperfgo/Makefile
Release dnsperfgo `1.4.0` to include the change to use EndpointSlices instead of Endpoints https://github.com/kubernetes/perf-tests/pull/2284
=> Bump dnsperfgo to 1.4.0

clusterloader2/testing/load/deployment.yaml
New dnsperfgo image is released `1.4.0` to use EndpointSlices instead of Endpoints, effectively supporting over 1k endpoints behind a single service https://github.com/kubernetes/perf-tests/pull/2285
=> CL2 load test bump dnsperfgo image to 1.4.0

clusterloader2/cmd/clusterloader.go, clusterloader2/pkg/measurement/common/network-policy/manifests/clusterrole.yaml, clusterloader2/pkg/measurement/common/network-policy/manifests/clusterrolebinding.yaml, clusterloader2/pkg/measurement/common/network-policy/manifests/dep-test-client-pod-creation.yaml, clusterloader2/pkg/measurement/common/network-policy/manifests/dep-test-client-policy-creation.yaml, clusterloader2/pkg/measurement/common/network-policy/manifests/policy-egress-allow-apiserver.yaml, clusterloader2/pkg/measurement/common/network-policy/manifests/policy-egress-allow-target-pods.yaml, clusterloader2/pkg/measurement/common/network-policy/manifests/policy-load.yaml, clusterloader2/pkg/measurement/common/network-policy/manifests/serviceaccount.yaml, clusterloader2/pkg/measurement/common/network-policy/network-policy-enforcement-latency.go
**Description**
A new measurement that utilizes network policy enforcement latency test clients.
https://github.com/kubernetes/perf-tests/tree/master/network/tools/network-policy-enforcement-latency 
This measurement is intended to be used in the ClusterLoader2 load test.
https://github.com/kubernetes/perf-tests/tree/master/clusterloader2/testing/load
Network policy enforcement latency is the required time for any change to pods or network policies to be reflected in the system. It's measured by simulating a real scenario with workloads that are connecting to each other, and measuring the time it takes for the network policies to be honored for new pods or network policy changes. The relevant scalability and performance dimensions are pod and policy churn rate (create, update, delete). …
=> Add network policy enforcement latency measurement

dns/dnsperfgo/main.go
/kind cleanup
"io/ioutil" has been deprecated since Go 1.19: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific function documentation for details.  (SA1019)
Fixes #
=> chore: remove refs to deprecated io/ioutil

clusterloader2/pkg/measurement/common/scheduler_latency.go, clusterloader2/pkg/measurement/util/gatherers/container_resource_gatherer.go, clusterloader2/pkg/prometheus/prometheus.go, clusterloader2/pkg/provider/gce.go, clusterloader2/pkg/util/cluster.go, clusterloader2/pkg/util/cluster_test.go
/kind bug
Adds check control plane instance in clusterloader with label key as `node-role.kubernetes.io/control-plane`
Fixes #
https://github.com/kubernetes/test-infra/issues/29139
Test failing as part of this PR-
https://github.com/kubernetes/kops/pull/15538
=> Include control plane node role when checking for control plane node

clusterloader2/pkg/measurement/common/generic_query_measurement_test.go, clusterloader2/pkg/measurement/util/prometheus.go
This makes sure that we take a look at the full interval which we are supposed to measure some Prometheus-based SLI rather than truncating it to full minutes.
/kind bug
=> Take full duration into account in Prometheus-based measurements

clusterloader2/pkg/measurement/common/generic_query_measurement.go, clusterloader2/pkg/measurement/common/generic_query_measurement_test.go
This was possible before by just prepending the relevant query with a minus character but I think handling this on the API level would give a better UX :).
/kind feature
=> Enable treating threshold as a lower bound in generic measurement

golang/Makefile
/kind bug
After https://go.googlesource.com/go/+/82ee946d7acd93cad27f748efb9c3131ae69668e it is required to use at least 1.20 to build golang from source.
https://testgrid.k8s.io/sig-scalability-golang#build-and-push-k8s-at-golang-tip
=> Update golang compiler for golang tip job

clusterloader2/testing/watch-list/job.yaml
After https://github.com/kubernetes/perf-tests/pull/2303 the latency dropped. 
If our theory hold then with ~8/12 informers we should start seeing increased latency (egress is 2 GB/s).
This PR updates the # of informers to `8`.
Fixes #
=> issue:2287: slightly increase the number of informers to see impact on latency

clusterloader2/testing/watch-list/job.yaml
After https://github.com/kubernetes/perf-tests/pull/2305 the latency increased to `30s`. 
With https://github.com/kubernetes/perf-tests/pull/2303 it was around `1s`.
Between `1s` and `30s` the CPU usage didn't significantly increase.
Everything indicates that the egress is being throttled.
According to my calculations we should be below the egress limit (2 GB/s) with `6` or `5` informers.
This PR set the value of the informers to `6`.
Once we find our sweet spot I'm going to add a metric that will measure the latency for streaming.
Then we update the value of informers to initial value of `16` and compare the latencies one more time.
xref: https://github.com/kubernetes/perf-tests/issues/2287
Fixes #
=> issue:2287: find maximum number of informers that doesn't impact latency.

clusterloader2/pkg/measurement/common/service_creation_latency.go
=> service_creation_latency: limit number of calls, exit on success

perfdash/config.go
/kind feature
The current node-throughput test export Prometheus Simple metrics, but perfdash is ignoring them: https://github.com/kubernetes/perf-tests/blob/b4bc889e1e6537cba3d83025b3d85274790fa7ba/clusterloader2/testing/node-throughput/config.yaml#L21
This PR adds support to perfdash to display Prometheus Simple metrics.
=> Add Responsiveness and RequestCount to node-throughput tests in perfdash

clusterloader2/README.md, clusterloader2/pkg/measurement/common/pod_command.go, clusterloader2/pkg/util/util.go, clusterloader2/pkg/util/util_test.go
/kind feature
This commit adds a new measurement named PodPeriodicCommand, which allows users to run commands within pods on a periodic basis, saving the output for later use. For instance, this can be used to scrape pprofs from a select set of pods. Here is an example configuration:
```yaml
name: testppc
namespace:
number: 1
steps:
- name: Start PodPeriodicCommand
measurements:
- identifier: PodPeriodicCommand
method: PodPeriodicCommand
params:
action: start
labelSelector: k8s-app=cilium
interval: 30s
container: cilium-agent
limit: 1
failOnError: true
commands:
- name: AllocsProfile
command:
- curl
- -s
- -k
- http://localhost:6060/debug/pprof/allocs?seconds=30
timeout: 35s
- name: Example Timeout
command:
- sleep
- 10
timeout: 1s
- name: Sleep for two minutes
measurements:
- Identifier: …
```
=> Add new measurement PodPeriodicCommand

golang/Makefile
/kind bug
Fix https://testgrid.k8s.io/sig-scalability-golang#build-and-push-k8s-at-golang-tip
=> Bump golang used to compile Go tip to 1.21.3

clusterloader2/api/types.go, clusterloader2/api/validation.go, clusterloader2/api/validation_test.go, clusterloader2/pkg/test/simple_test_executor.go
/kind feature
This PR allows users to specify a list of pre-existing namespaces rather than using the generated ones. It is important in scenarios where certain resources are restricted to only be deployed in specific namespaces. 
Fixes #2392
=> feat: Add support for specifying a list of existing namespaces

clusterloader2/pkg/prometheus/manifests/0prometheus-operator-deployment.yaml, clusterloader2/pkg/prometheus/manifests/prometheus-prometheus.yaml
Adding StructuralData as some data parsing was broken, only visible when PROMETHEUS_NODE_SELECTOR env was set
/kind bug
Using CL2_PROMETHEUS_NODE_SELECTOR no longer breaks Prometheus.
Fix #2464
Follow up to #2421 to cover use case of CL2_PROMETHEUS_NODE_SELECTOR
FYI @hakuna-matatah
=> [CL2] Follow up to safetext migration

slo-monitor/Makefile
/kind cleanup
To fix CVE-2023-45285 and CVE-2023-39326
Fixes #
=> Bump slo-monitor to 0.15.7

clusterloader2/testing/load/config.yaml
/kind feature
This PR allows to inject additional measurements via CL2_ADDITIONAL_MEASURMENT_MODULES to load/config.yaml.
Fixes #
=> Add an option to inject additional measurements to load config

clusterloader2/pkg/measurement/common/probes/manifests/dnsLookup/dns-prober-deployment.yaml, clusterloader2/pkg/measurement/common/probes/manifests/ping-client-deployment.yaml, clusterloader2/pkg/measurement/common/probes/manifests/ping-server-deployment.yaml, clusterloader2/pkg/measurement/common/probes/manifests/probes-serviceaccount.yaml
For being able to launch probes before a default SA is created.
=> Add a dedicated SA for probes

golang/Makefile
This is to (at least partially) fix https://testgrid.k8s.io/sig-scalability-golang#build-and-push-k8s-at-golang-tip.
https://github.com/kubernetes/test-infra/issues/31889 blocks the complete fix, however.
=> Bump go compiler version to 1.22.0

clusterloader2/testing/load/config.yaml
/kind feature
This PR allows to inject additional objects via CL2_ADDITIONAL_OBJECTS_MODULES to load/config.yaml.
=> Add an option to inject additional objects to load config

clusterloader2/testing/experiments/ignore_known_gce_container_restarts.yaml
https://testgrid.k8s.io/sig-release-master-informing#gce-master-scale-performance
Fixes https://github.com/kubernetes/kubernetes/issues/123328
https://perf-dash.k8s.io/#/?jobname=gce-5000Nodes&metriccategoryname=SystemPodMetrics&metricname=Load_SystemPodMetrics&RestartCount=RestartCount
Node Problem Detector restarted in recent runs. 
https://github.com/kubernetes/perf-tests/blob/ac4b33e7c3afe23b571be5c569fb968c8b88db7c/clusterloader2/testing/experiments/ignore_known_gce_container_restarts.yaml#L5-L16
It is not clear why the pod restart sometimes. Node Problem Detector is a daemonset and only 1 restarted may not indicts a big problem.
=> allow node problem detector restart 2 times

dns/run
Similar with https://github.com/kubernetes/test-infra/pull/30695
Fixes https://github.com/kubernetes/perf-tests/issues/2597
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-benchmark-nodelocal-dns-master/1762446829783355392/build-log.txt
```
2024/02/27 12:06:40 process.go:153: Running: /home/prow/go/src/k8s.io/perf-tests/run-e2e.sh node-local-dns /logs/artifacts/out /logs/artifacts 169.254.20.10
TOOL_NAME: node-local-dns
error: externally-managed-environment
× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
python3-xyz, where xyz is the package you are trying to
install.
If you wish to install a non-Debian-packaged Python package,
create a virtual environment using python3 -m venv path/to/venv.
Then use path/to/venv/bin/python …
```
=> add --break-system-packages for pip install

clusterloader2/testing/list/config.yaml
This is a small change to the list load test.
It changes the duration from 5m to 15m to give it a bit more time to exercise and allow more time to see potential memory usage increase.
=> increase the duration to 15m

clusterloader2/go.mod, clusterloader2/go.sum, clusterloader2/pkg/measurement/common/probes/manifests/dnsPropagation/dns-propagation-prober-deployment.yaml, clusterloader2/pkg/measurement/common/probes/manifests/dnsPropagation/dns-propagation-prober-rbac.yaml, clusterloader2/pkg/measurement/common/probes/manifests/dnsPropagation/dns-propagation-prober-service.yaml, clusterloader2/pkg/measurement/common/probes/manifests/dnsPropagation/dns-propagation-prober-serviceMonitor.yaml, clusterloader2/pkg/measurement/common/probes/probes.go, clusterloader2/pkg/measurement/common/probes/propagation_metric.go, clusterloader2/pkg/prometheus/manifests/prometheus-rules.yaml
Implementation of a DNS propagation measurement in CL2, using the DNS propagation prober.
Follow up on #2643
/kind feature
=> DNS propagation measurement in CL2

clusterloader2/testing/scheduler-throughput/config.yaml, clusterloader2/testing/scheduler-throughput/pod-default.yaml
/kind feature
Today our load test only tests scheduler-throughput at a a very small scale i.e max-pods to 5k and also its limited to KCM throughput as current test-suite depends on deployment/replicaset controller throughput in creating pods. That would limit us from knowing the actual scheduler throughput that we can achieve out of scheduler today.  More details https://github.com/kubernetes/perf-tests/issues/2681
Fixes #
https://github.com/kubernetes/perf-tests/issues/2681
=> Add direct scheduler throughput test suite

clusterloader2/pkg/prometheus/manifests/default/prometheus-podMonitorKubeNetworkPolicies.yaml
I've found the scalability jobs were not running https://testgrid.k8s.io/sig-scalability-experiments#kube-network-policies
```
F0612 10:46:47.152411   17893 clusterloader.go:330] Error while setting up prometheus stack: error while applying (default/prometheus-podMonitorKubeNetworkPolicies.yaml): PodMonitor.monitoring.coreos.com "kube-network-policies-pods" is invalid: spec.podMetricsEndpoints[0].port: Invalid value: "integer": spec.podMetricsEndpoints[0].port in body must be of type string: "integer"
2024/06/12 10:46:47 process.go:155: Step '/home/prow/go/src/k8s.io/perf-tests/run-e2e.sh cluster-loader2 --experimental-gcp-snapshot-prometheus-disk=true --experimental-prometheus-disk-snapshot-name=ci-kubernetes-e2e-gci-gce-scalability-np-1800838655078567936 …
```
=> use targetPort for monitoring network policies metrics

clusterloader2/pkg/config/cluster.go, clusterloader2/pkg/prometheus/prometheus.go
/kind feature
In the past, we added all service/pod monitors directly into manifests directory within cl2/prometheus. This is not really scalable solution if one wants to test other components. Let's add option to allow to specify additional monitors from different path.
Example use-case: https://github.com/marseel/perf-tests/commit/11075f78427c079801fb7b6ed53041dbad05a763
Example command:
```
CL2_PROMETHEUS_PVC_ENABLED=false go run ./cmd/clusterloader.go             -v=4             --testconfig=./testing/dns/config.yaml             --provider=kind             --enable-prometheus-server             --tear-down-prometheus-server=false             --nodes=2             --report-dir=./report                     --kubeconfig=$HOME/.kube/config …
```
=> prometheus: add optional path with additional manifests

clusterloader2/go.mod, clusterloader2/go.sum, clusterloader2/pkg/framework/client/objects.go, clusterloader2/pkg/framework/client/objects_test.go
/kind bug
Fixes a bug where tests using resources that are not properly pluralizes as described in https://github.com/kubernetes/client-go/issues/1082 systematically fail.
For example, any test creating a `Gateway` object will fail (as it's turned into 'gatewaies').
=> Fix Kind pluralization.

clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go, clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus_test.go
/kind feature
`WatchList` latency is gathered for 50th, 90th and 99th duration quantiles for watch list requests broken down by group, resource, scope.
The new metric (https://github.com/kubernetes/kubernetes/pull/120490) allows for comparing watch-list requests with standard list requests and measuring performance of the new requests in general.
Fixes #
=> adds WatchList Latency to APIResponsivenessPrometheus

clusterloader2/pkg/prometheus/manifests/0prometheus-priorityclass.yaml, clusterloader2/pkg/prometheus/manifests/grafana-deployment.yaml, clusterloader2/pkg/prometheus/manifests/prometheus-prometheus.yaml, clusterloader2/pkg/prometheus/manifests/prometheus-resourceQuota.yaml
/kind bug
Bumping the priorityclass of prometheus to prevent eviction caused by any potential higher priority pods.
=> Bump priorityclass of prometheus

.golangci.yml
/kind cleanup
Updates the golangci-lint configuration to silence an errcheck linter warning.
Fixes #2801
See golangci/golangci-lint#4733
=> Add workaround for errcheck linter warning

clusterloader2/testing/huge-service/config.yaml, clusterloader2/testing/huge-service/modules/measurements.yaml
Enabling DNS propagation measurement in huge-service test.
Measures the DNS propagation of the statefulset created in huge-service.
Required new env variable:
- `CL2_ENABLE_DNS_PROPAGATION_MEASUREMENT` should be set to true to enable the measurement
Optional new env variable:
- `CL2_DNS_PROPAGATION_THRESHOLD` time threshold for DNS propagation, defaults to 10s.
In addition, this measurement assumes huge-service is run with large statefulset enabled, hence the following existing vars will be needed as well 
- `CL2_ENABLE_LARGE_STATEFULSET` should be set to true to enable adding large statefulset
- `CL2_STATEFULSET_ENDPOINTS` indicates the size of the statefulset
/kind feature
=> Enable DNS propagation measurement for huge-service test

clusterloader2/testing/load/deployment.yaml, clusterloader2/testing/load/job.yaml, clusterloader2/testing/load/statefulset.yaml
/kind bug
A previous change https://github.com/kubernetes/perf-tests/pull/2803 introduced a variable parametrizing the image with fallback to a default value, but instead used the variable that does not have a fallback. This can cause the tests to fail.
None that I know of
=> Fix image parametrization in load config

golang/Makefile
This should fix https://testgrid.k8s.io/sig-scalability-golang#build-and-push-k8s-at-golang-tip .
Example failure: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-build-and-push-k8s-at-golang-tip/1833601955637760000
(FTR: the PR is based on https://github.com/kubernetes/perf-tests/pull/2542 )
=> Bump version of go compiler that bootstraps golang tip test to 1.23.0

clusterloader2/pkg/measurement/common/wait_for_nodes.go, clusterloader2/pkg/measurement/common/wait_for_pods.go
/kind feature
This PR introduces a new param called `refreshInterval` to `WaitForNodes` and `WaitForRunningPods` measurements. The current value of refresh interval in both measurements are currently fixed. However, for test that includes a small number of nodes, 30 seconds for refreshing is too long, which can lead to inaccurate result (5 nodes that usually take 10 - 15 seconds to get ready almost always end up being reported as taking 30 seconds due to the fixed interval). At the same time, for test that includes a large number of pods and numbers, 5 seconds for pod's refresh interval might be too frequent.
Fixes #
=> CL2: Add refreshInterval param to WaitForNodes and WaitForRunningPods measurements

.github/dependabot.yml
/kind cleanup
Updates the configuration so any PRs opened by dependabot have the `ok-to-test` and `kind/cleanup` labels by default. This has saved maintainers some time in Cluster API projects, maybe it would be useful here too.
N/A
Sorry for all the repetition. As best I can tell, there isn't a way to set labels globally in [dependabot.yml](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#labels).
=> Label dependabot PRs as ok-to-test by default

clusterloader2/pkg/prometheus/manifests/exporters/kube-state-metrics/clusterRole.yaml, clusterloader2/pkg/prometheus/manifests/exporters/kube-state-metrics/clusterRoleBinding.yaml, clusterloader2/pkg/prometheus/manifests/exporters/kube-state-metrics/deployment.yaml, clusterloader2/pkg/prometheus/manifests/exporters/kube-state-metrics/service.yaml, clusterloader2/pkg/prometheus/manifests/exporters/kube-state-metrics/serviceAccount.yaml, clusterloader2/pkg/prometheus/manifests/exporters/kube-state-metrics/serviceMonitor.yaml
A PR was submitted to kube-state-metrics that should greatly improve performances and I'd like to update our perf tests to check it out.
Most of the manifests changes are copied from https://github.com/kubernetes/kube-state-metrics/tree/main/examples/standard
=> Update kube-state-metrics manifests to the latest release

clusterloader2/pkg/errors/error_list.go, clusterloader2/pkg/errors/fatal_error.go, clusterloader2/pkg/measurement/common/wait_for_pods.go, clusterloader2/pkg/measurement/measurement_executor.go, clusterloader2/pkg/test/simple_test_executor.go
/kind feature
This PR introduces a set of commits that enable measurements to fail during their `Execute` method. Errors that are returned during a measurement's `Execute` method are passed up the stack to the simple test executor, which then passes them through a function called `isErrsCritical`. This function can control if the entire test should bail, based on the criticalness of the errors passed to it. Right now, it's a no-op:
https://github.com/kubernetes/perf-tests/blob/e7bdd15c9122e55d7dc267768190addc8fdf7b9e/clusterloader2/pkg/test/simple_test_executor.go#L386-L389
This PR modifies the function to check if any of the errors in the given list are fatal. A measurement can mark an error as fatal if it returns an error wrapped by a newly added `FatalError` type.
This PR also modifies …
=> CL2: Add isFatal param to WaitForPods and enable failing measurements

.gitignore, perfdash/.gitignore, perfdash/Makefile, perfdash/local_metrics_dir.go, perfdash/metrics-downloader.go, perfdash/perfdash.go
/kind feature
This adds an additional metrics bucket type called `local` which allows users to load perf dash metrics from a local directory, specifically the output from running `clusterloader2` with the `--reportdir` flag set. This is primarily used for development purposes so perf dash is usable with job data that is not hosted on prow.
Fixes #
=> Add option to load perf dash metrics from local artifacts directory

clusterloader2/pkg/config/cluster.go, clusterloader2/pkg/execservice/exec_service.go, clusterloader2/pkg/execservice/manifest/exec_deployment.yaml
/kind feature
Some clusters may not be able to reach the upstream Kubernetes image repos, like registry.k8s.io, but can reach some internal mirror of these. This will allow to set a custom image repo for the exec_service that cluster loader uses to create the exec pods. You can supply the image repo via a clusterloader2 CLI flag `--registry-k8s-repo`
Fixes # https://github.com/kubernetes/perf-tests/issues/2704
=> allows for the exec_service pod image to be pulled from a custom repo

clusterloader2/pkg/measurement/common/probes/manifests/dnsPropagation/dns-propagation-prober-deployment.yaml, clusterloader2/pkg/measurement/common/probes/propagation_metric.go
Adding flags for setting custom values for CPU and memory resources for DNS propagation prober.
/kind feature
/kind api-change
=> Add flags for resources of DNS propagation prober

perfdash/config.go, perfdash/perfdash.go
/kind bug
Perf-dash should use `kubernetes-ci-logs` logs bucket, because perf jobs are not running in `kubernetes-jenkins` anymore. 
https://github.com/kubernetes/test-infra/issues/33381
=> Change perf-dash logs bucket to kubernetes-ci-logs

clusterloader2/testing/watch-list/config.yaml, clusterloader2/testing/watch-list/job.yaml
`watchlist-off` [perf test](https://perf-dash.k8s.io/#/?jobname=watch-list-off&metriccategoryname=APIServer&metricname=LoadResponsiveness_PrometheusSimple&Resource=secrets&Scope=namespace&Subresource=&Verb=LIST) reports unexpectedly high LIST latency.
It looks like the main suspect is egress throughput. This PR reduces the amount of informers, which, in turn, reduces the amount of downloaded data, resulting in improved latency.
=> watchlist: decrease the number of informers to 6 to confirm no impact on latency

clusterloader2/pkg/chaos/monkey.go, clusterloader2/pkg/measurement/common/chaos_monkey_measurement.go, clusterloader2/pkg/test/simple_test_executor.go
/kind bug
Not really a bug but I noticed that the waitgroup returned from chaosMonkey.Init() is always non-nil and therefore we always log and await the waitgroup, which can be confusing when chaosmonkey nodekiller is disabled. I also updated to avoid emitting an empty log statement when the summary is empty.
```
I1219 14:48:15.653932   23514 simple_test_executor.go:80] Waiting for the chaos monkey subroutine to end...
I1219 14:48:15.653947   23514 simple_test_executor.go:82] Chaos monkey ended.
I1219 14:48:15.657172   23514 simple_test_executor.go:102] 
```
None
None
=> clusterloader2: Avoid logging and awaiting waitgroup when chaosmonkey is disabled

clusterloader2/go.mod, clusterloader2/go.sum, clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus_test.go, clusterloader2/pkg/measurement/util/informer/informer.go, clusterloader2/pkg/prometheus/clients/aks_managed.go
Brings back part of https://github.com/kubernetes/perf-tests/pull/3050 that was reverted.
Verified that the error reported in https://github.com/kubernetes/perf-tests/pull/3075 was not caused by this part.
=> Cleanup klog in clusterloader

clusterloader2/run-e2e.sh
Populating a ServiceAccount's Secret with CA and JWT data is a legacy flow [replaced in 1.24+](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#urgent-upgrade-notes) with the `kube-root-ca.crt ConfigMap` and `token` resources.  Public documentation now encourages using `tokens` instead: https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#manual-secret-management-for-serviceaccounts
/kind bug
/kind deprecation
Clusters using GKE's [CPA](https://cloud.google.com/kubernetes-engine/docs/concepts/about-control-plane-authority) (and many other modern clusters) no longer populate a SA's secret with CA and token information.
=> Update ClusterLoader2's temp KubeConfig PKI for ServiceAccount

perfdash/Dockerfile, perfdash/deployment.yaml
/kind bug
It fixes version in deployment.yaml and bumps to a new golang version that is required to build.
/assign @serathius
=> Fix go version and deployment.yaml

clusterloader2/testing/list/config.yaml, clusterloader2/testing/list/deployment.yaml, clusterloader2/testing/list/modules/list-benchmark.yaml
Thanks to improvements in https://github.com/kubernetes/perf-tests/pull/3143 we can just use constant resources. Removing passing cpu and memory variables as they should no longer needed. Removing Inflights variable as clients are single threaded and cpu bound so there is no benefit of having multpile concurrent calls from single container.
Setting default benchmark pods to 1 to allow executing the test locally on a smaller machine.
/kind feature
=> Use constant resources for list benchmark deployment

clusterloader2/testing/list/kind.yaml
Forgot to add kind file to https://github.com/kubernetes/perf-tests/pull/3163
=> Add missing kind file with configuration to run tests locally

util-images/request-benchmark/Makefile
/kind feature
Fixes #
It is already pushed
```
➜  request-benchmark git:(d1c0bd772) ✗ make
docker build --pull -t gcr.io/k8s-testimages/perf-tests-util/request-benchmark:v0.0.8 .
Sending build context to Docker daemon  26.62kB
Step 1/12 : FROM golang:1.24 as builder
1.24: Pulling from library/golang
155ad54a8b28: Pull complete
8031108f3cda: Pull complete
1d281e50d3e4: Pull complete
9760da4e8f07: Pull complete
a2a60326dddc: Pull complete
8985a99e1ce3: Pull complete
4f4fb700ef54: Pull complete
Digest: sha256:3f7444391c51a11a039bf0359ee81cc64e663c17d787ad0e637a4de1a3f62a71
Status: Downloaded newer image for golang:1.24
---> 245780beb82f
Step 2/12 : ENV GOOS linux
---> Running in 1404c20247cb
Removing intermediate container 1404c20247cb
---> 016a0af68764
Step 3/12 : ENV CGO_ENABLED 0
---> …
```
=> Increase request-benchmark version to 0.0.8

clusterloader2/pkg/prometheus/manifests/default/prometheus-serviceMonitorCoreDNS.yaml, clusterloader2/pkg/prometheus/manifests/default/prometheus-serviceMonitorKubelet.yaml, clusterloader2/pkg/prometheus/manifests/default/prometheus-serviceMonitorLegacyKubeDNS.yaml, clusterloader2/pkg/prometheus/manifests/master-ip/master-serviceMonitor.yaml, clusterloader2/pkg/prometheus/prometheus.go
…p apiserver metrics
/kind bug
Binding any permissions to system:anonymous and system:unauthenticated is dangerous.
This PR removes usage of system:anonymous in CLusterROleBinding used to talk to apiserver. 
What is more, service account needs to be used when talking to apiserver.
Fixes #
=> Remove system anonymous from apis metrics v2

golang/Makefile
This should fix [build-and-push-k8s-at-golang-tip testgrid](https://testgrid.k8s.io/sig-scalability-golang#build-and-push-k8s-at-golang-tip).
(Example failure](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-build-and-push-k8s-at-golang-tip/1899076505376395264)
(FTR: the PR is based on https://github.com/kubernetes/perf-tests/pull/2542 )
=> Bump version of go compiler that bootstraps golang tip test to 1.24.0

clusterloader2/pkg/prometheus/manifests/prometheus-prometheus.yaml
/kind feature
This bumps the version of Prometheus used in CL2's Prometheus Operator deployment to [2.40.0](https://github.com/prometheus/prometheus/releases/tag/v2.40.0).
That version contains a change that makes Prometheus talk to the K8s API using protobuf instead of JSON when doing service discovery: https://github.com/prometheus/prometheus/pull/11353.
=> Bump prometheus version to 2.40.0 in prometheus operator

golang/build-kubernetes.sh, golang/push.sh
/kind bug
https://github.com/kubernetes/test-infra/pull/33436 bumped the K8s version used in the `ci-build-and-push-k8s-at-golang-tip` job after which it stopped using the locally built golang version - instead, it started to rely on and download the version specified in k/k's `.go-version` file.
To address this, we pass the `GOTOOLCHAIN=local` env var to the build scripts to make it use the locally built version of golang.
1) This PR makes sure that kube-build picks up the manually built version of golang.
2) This also fixes https://github.com/kubernetes/perf-tests/issues/3146.
=> Update golang scripts

golang/Makefile, golang/build-go.sh
Remove previous go instalation in build-go.sh and bump go compiler to 1.24.2
/kind bug
This fixes recent failures of ci-build-and-push-k8s-at-golang-tip.  Currently the job fails at install_go_compiler step, as kubekins was updated to use 1.24.2 golang in https://github.com/kubernetes/test-infra/commit/5ad67f09e073e03c704e488cb8c02b426bdee66b (note that variants are linked from kubekins directory). In 1.24.2 the `go/src/debug/buildinfo/testdata/go117` and `go/src/debug/buildinfo/testdata/notgo` are directories, meanwhile in 1.24.0 those are files. That's why tar fails.
Also according to https://go.dev/doc/install we should clean up the old golang installation anyway, per:
```
Do not untar the archive into an existing /usr/local/go tree. This is known to produce broken Go installations. …
```
=> Remove previous go instalation in build-go.sh, bump go compiler to 1.24.2

clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go, clusterloader2/pkg/measurement/common/slos/slo_measurement_test.go, clusterloader2/pkg/measurement/util/latency_metric.go
/kind feature
Intorducing threshold by percentile 50, 90 and 99 for the PodStartupLatency only. The default values of the new thresholds are the "threshold" value. So this change should be no-op unless the params are used in the test configuration.
Fixes #
=> Adding threshold by percentile for podStartupLatency

clusterloader2/docs/GETTING_STARTED.md
Updates versions of go and cluster to work with modern environments (tested 6/3/2025 on an Ubuntu 24.04.2 LTS install)
Fixes #
Previous versions (go1.15.21 and cluster v1.21.1) were failing for various steps (installing kind for go 1.15.21, and kind create cluster was failing for cluster v1.21.1)
=> Clusterloader2 docs update

clusterloader2/pkg/tuningset/time_limited.go
When creating a scale test that scales with number of nodes, it's possible that for small scale clusters some of the objects are not created, resulting in number of actions equal to zero for specific phase. For TimeLimitedLoad it caused panic due to division by zero.
/kind bug
=> tuningSet: fix TimeLimitedLoad for zero actions

clusterloader2/testing/dra-baseline/README.md, clusterloader2/testing/dra-baseline/config.yaml, clusterloader2/testing/dra-baseline/job.yaml, clusterloader2/testing/dra-baseline/long-running-job.yaml
/kind feature
This PR adds test such that 90% of available CPU in the cluster is first saturated and then 10% remaining CPU is used by pods that are churned for 10 times. 
This creates a baseline test to compare how cluster performs with and without DRA
Fixes #
=> add dra-baseline tests with workloads without resourceclaims

clusterloader2/pkg/imagepreload/imagepreload.go
/kind feature
To be able to pull and cache AI/ML images, we would need configurable timeout beyond default timeout 15mins.
Fixes #
=> Make image preload timeout configurable

clusterloader2/testing/list/OWNERS
Multiple PRs are stuck in review, while the current owners are busy. As the author of the list benchmark I would be happy to help review it.
=> Add serathius to owners of list benchmark

perfdash/Makefile, perfdash/config.go, perfdash/deployment.yaml
/kind feature
This PR adds a new option to parse the etcd-benchmark related data, which is done as a part of defining a performance suite for etcd. Ref: https://github.com/etcd-io/etcd/issues/16467.
This is one of the many etcd API/Operations that will be supported on the perf-dash.
None
=> Add parser for etcd API benchmarks
